unit Unit2;

interface
uses classes;


const


{
CREATE DATABASE /*!32312 IF NOT EXISTS*/ `MyNutWin` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `MyNutWin`;
create user NUTRICAO identified  by password '*C4FA1D6B9185FD0DCD13B990F5489735252CC210';


GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON MyNutWin.* TO NUTRICAO WITH GRANT OPTION;

DROP TABLE IF EXISTS `adeq`;
}


CREATE_DATABASE_STMT = 'CREATE DATABASE /*!32312 IF NOT EXISTS*/ `%s` /*!40100 DEFAULT CHARACTER SET latin1 */';
CREATE_USER_STMT = 'create user `%s` identified  by password ''%s'' ';
CREATE_GRANT_STMT = 'GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON `%s`.* TO %s WITH GRANT OPTION';
DROP_TABLE_STMT = 'DROP TABLE IF EXISTS `%s`';


CREATE_ADEQ_STMT =
'CREATE TABLE `adeq` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(20) DEFAULT NULL,'+
'  KEY `ADEQ0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_aliconv_STMT =
'CREATE TABLE `aliconv` ('+
'  `NDB_NO` varchar(5) DEFAULT NULL,'+
'  `GUID` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  UNIQUE KEY `ALICONV0` (`NDB_NO`,`GUID`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_alifreq_STMT =
'CREATE TABLE `alifreq` ('+
'  `IDALI` varchar(50) DEFAULT NULL,'+
'  `USERNAME` varchar(50) DEFAULT NULL,'+
'  `FREQUSO` int(11) DEFAULT NULL,'+
'  UNIQUE KEY `ALIFREQ0` (`IDALI`,`USERNAME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_aligcal_STMT =
'CREATE TABLE `aligcal` ('+
'  `IDALI` varchar(50) DEFAULT NULL,'+
'  `IDGRUCAL` varchar(50) DEFAULT NULL,'+
'  `IDMEDCAS` varchar(50) DEFAULT NULL,'+
'  `QTDE` varchar(9) DEFAULT NULL,'+
'  `MEDGR` varchar(9) DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `ALIGCAL0` (`IDALI`),'+
'  KEY `IDXGRUCAL` (`IDGRUCAL`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_aligprot_STMT =
'CREATE TABLE `aligprot` ('+
'  `IDALI` varchar(50) DEFAULT NULL,'+
'  `IDGRUPROT` varchar(50) DEFAULT NULL,'+
'  `IDMEDCAS` varchar(50) DEFAULT NULL,'+
'  `QTDE` varchar(9) DEFAULT NULL,'+
'  `MEDGR` varchar(9) DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `ALIGPROT0` (`IDALI`),'+
'  KEY `IDXGRUPROT` (`IDGRUPROT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_alimento_STMT =
'CREATE TABLE `alimento` ('+
'  `IDALI` varchar(50) DEFAULT NULL,'+
'  `NOME` varchar(60) DEFAULT NULL,'+
'  `NOMESIMP` varchar(30) DEFAULT NULL,'+
'  `IDORIG` varchar(50) DEFAULT NULL,'+
'  `IDGRUALI` varchar(50) DEFAULT NULL,'+
'  `TIPOALI` varchar(4) DEFAULT NULL,'+
'  `PREP` varchar(1) DEFAULT NULL,'+
'  `OBSALI` varchar(240) DEFAULT NULL,'+
'  UNIQUE KEY `ALIMENTO0` (`IDALI`),'+
'  KEY `IDNOMEALI` (`NOME`),'+
'  KEY `IDNOMESIMP` (`NOMESIMP`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_alinut_STMT =
'CREATE TABLE `alinut` ('+
'  `IDALI` varchar(50) DEFAULT NULL,'+
'  `IDNUT` varchar(50) DEFAULT NULL,'+
'  `VALOR` double DEFAULT NULL,'+
'  UNIQUE KEY `ALINUT0` (`IDALI`,`IDNUT`),'+
'  KEY `NUT` (`IDNUT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_aliorg_STMT =
'CREATE TABLE `aliorg` ('+
'  `IDORIG` varchar(50) DEFAULT NULL,'+
'  `DESCRICAO` varchar(60) DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `ALIORG0` (`IDORIG`),'+
'  UNIQUE KEY `ALIORGDESC` (`DESCRICAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_alipreco_STMT =
'CREATE TABLE `alipreco` ('+
'  `IDALI` varchar(50) DEFAULT NULL,'+
'  `IDMEDCAS` varchar(50) DEFAULT NULL,'+
'  `QTDE` double DEFAULT NULL,'+
'  `PRECO` double DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `MEDGR` varchar(9) DEFAULT NULL,'+
'  UNIQUE KEY `ALIPRECO0` (`IDALI`),'+
'  KEY `IDALIPREC` (`IDALI`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_anamnese_STMT =
'CREATE TABLE `anamnese` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `ANAM` longtext,'+
'  UNIQUE KEY `ANAMNESE0` (`IDPESSOA`,`DATA`),'+
'  UNIQUE KEY `IDDATADECR` (`IDPESSOA`,`DATA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_antrops_STMT =
'CREATE TABLE `antrops` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `ANTROP` longtext,'+
'  `DESCRICAO` varchar(60) DEFAULT NULL,'+
'  UNIQUE KEY `ANTROPS0` (`IDPESSOA`,`DATA`),'+
'  UNIQUE KEY `IDANTROPDECR` (`IDPESSOA`,`DATA`),'+
'  KEY `IDANTNOME` (`DESCRICAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_areaclic_STMT =
'CREATE TABLE `areaclic` ('+
'  `OVAREA` varchar(25) DEFAULT NULL,'+
'  `DESCRICAO` varchar(50) DEFAULT NULL,'+
'  `OVCURSOR` varchar(25) DEFAULT NULL,'+
'  `AVI` longblob,'+
'  `INSTRUCOES` longtext,'+
'  `IDAREA` int(11) DEFAULT NULL,'+
'  UNIQUE KEY `AREACLIC0` (`OVAREA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_areavist_STMT =
'CREATE TABLE `areavist` ('+
'  `OBJETO` varchar(25) DEFAULT NULL,'+
'  `OVORDEM` double DEFAULT NULL,'+
'  `OVAREA` varchar(25) DEFAULT NULL,'+
'  `OVTOP` double DEFAULT NULL,'+
'  `OVLEFT` double DEFAULT NULL,'+
'  `OVHEIGHT` double DEFAULT NULL,'+
'  `OVWIDTH` double DEFAULT NULL,'+
'  `OVCAPTION` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `AREAVIST0` (`OBJETO`,`OVORDEM`,`OVAREA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_ativfis_STMT =
'CREATE TABLE `ativfis` ('+
'  `GUID` varchar(50) DEFAULT NULL,'+
'  `TEMPO` double DEFAULT NULL,'+
'  UNIQUE KEY `ATIVFIS0` (`GUID`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_cachedic_STMT =
'CREATE TABLE `cachedic` ('+
'  `IDCACHE` varchar(50) DEFAULT NULL,'+
'  `CODPROC` varchar(50) DEFAULT NULL,'+
'  `COMPPROC` varchar(50) DEFAULT NULL,'+
'  `MEDIDA` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `CACHEDIC0` (`IDCACHE`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_cadpastas_STMT =
'CREATE TABLE `cadpastas` ('+
'  `IDPASTA` varchar(50) DEFAULT NULL,'+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `DATACAD` DATETIME DEFAULT NULL,'+
'  UNIQUE KEY `CADPASTAS0` (`IDPASTA`,`IDPESSOA`),'+
'  KEY `IDPASTAS` (`IDPASTA`),'+
'  KEY `INDPESS` (`IDPESSOA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_calcali_STMT =
'CREATE TABLE `calcali` ('+
'  `GUID` varchar(50) DEFAULT NULL,'+
'  `ID_CALCALI` varchar(50) DEFAULT NULL,'+
'  `NOME_CALC` varchar(30) DEFAULT NULL,'+
'  `DATA_CRIACAO` DATETIME DEFAULT NULL,'+
'  `OBSERVACOES` longblob,'+
'  UNIQUE KEY `CALCALI0` (`GUID`),'+
'  KEY `IDCALCALI` (`ID_CALCALI`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_ccsisdic_STMT =
'CREATE TABLE `ccsisdic` ('+
'  `SIGLA` varchar(15) DEFAULT NULL,'+
'  `TIPO` varchar(15) DEFAULT NULL,'+
'  `NOME` varchar(40) DEFAULT NULL,'+
'  `DATA_ALTERACAO` DATETIME DEFAULT NULL,'+
'  `DATA_CRIACAO` DATETIME DEFAULT NULL,'+
'  `FONTE` varchar(30) DEFAULT NULL,'+
'  `VERSAO` varchar(6) DEFAULT NULL,'+
'  `MAX_FILHOS` smallint(6) DEFAULT NULL,'+
'  `NUM_NIVEIS` smallint(6) DEFAULT NULL,'+
'  `CAMPO_CODIGO` varchar(15) DEFAULT NULL,'+
'  `CODIGO_TAMANHO` int(11) DEFAULT NULL,'+
'  `CAMPO_DESCR` varchar(15) DEFAULT NULL,'+
'  `DESCR_TAMANHO` int(11) DEFAULT NULL,'+
'  `LIVRO_IMAGEM` longblob,'+
'  UNIQUE KEY `CCSISDIC0` (`SIGLA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_cidade_STMT =
'CREATE TABLE `cidade` ('+
'  `DESCRCID` varchar(40) DEFAULT NULL,'+
'  `UF` varchar(2) DEFAULT NULL,'+
'  `IDCID` varchar(50) DEFAULT NULL,'+
'  `CEPCID` varchar(10) DEFAULT NULL,'+
'  `DDD` varchar(5) DEFAULT NULL,'+
'  `CIDUF` varchar(40) DEFAULT NULL,'+
'  KEY `IDCIDUF` (`CIDUF`),'+
'  KEY `IDDESCRCID` (`DESCRCID`,`UF`),'+
'  KEY `IDESTADO` (`UF`),'+
'  KEY `CIDADE0` (`DESCRCID`,`UF`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_classetariageral_STMT =
'CREATE TABLE `classetariageral` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(20) DEFAULT NULL,'+
'  UNIQUE KEY `CLASSETARIAGERAL0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_cnut_STMT =
'CREATE TABLE `cnut` ('+
'  `COD_CNUT` varchar(50) DEFAULT NULL,'+
'  `DESCR_CNUT` varchar(150) DEFAULT NULL,'+
'  `NIVEL` varchar(20) DEFAULT NULL,'+
'  `TIPO` varchar(20) DEFAULT NULL,'+
'  `CLASSE` varchar(30) DEFAULT NULL,'+
'  UNIQUE KEY `CNUT0` (`COD_CNUT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_cnut_pf_STMT =
'CREATE TABLE `cnut_pf` ('+
'  `CODPAI_CNUT` varchar(50) DEFAULT NULL,'+
'  `CODFILHO_CNUT` varchar(50) DEFAULT NULL,'+
'  `ORDEM_CNUT` int(11) DEFAULT NULL,'+
'  `MEDIDA_CNUT` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `CNUT_PF0` (`CODPAI_CNUT`,`CODFILHO_CNUT`),'+
'  KEY `CNUT_PF1` (`CODPAI_CNUT`,`ORDEM_CNUT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_conversaobd_STMT =
'CREATE TABLE `conversaobd` ('+
'  `ORDEM` int(11) DEFAULT NULL,'+
'  `TABORIGEM` varchar(30) DEFAULT NULL,'+
'  `TABDESTINO` varchar(30) DEFAULT NULL,'+
'  `COPIADO` char(1) DEFAULT NULL,'+
'  `LIMPAR` char(1) DEFAULT NULL,'+
'  KEY `CONVERSAOBD0` (`ORDEM`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_cor_STMT =
'CREATE TABLE `cor` ('+
'  `CODCOR` varchar(50) DEFAULT NULL,'+
'  `DESCCOR` varchar(15) DEFAULT NULL,'+
'  UNIQUE KEY `COR0` (`CODCOR`),'+
'  UNIQUE KEY `INCOR` (`DESCCOR`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_cursores_STMT =
'CREATE TABLE `cursores` ('+
'  `OVCURSOR` varchar(25) DEFAULT NULL,'+
'  `DESCRICAO` varchar(50) DEFAULT NULL,'+
'  `NCURSOR` int(11) DEFAULT NULL,'+
'  UNIQUE KEY `CURSORES0` (`OVCURSOR`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_descranges_STMT =
'CREATE TABLE `descranges` ('+
'  `TABELA` varchar(60) DEFAULT NULL,'+
'  `BEGINPOINTDESC` varchar(60) DEFAULT NULL,'+
'  `BEGINUNIT` varchar(30) DEFAULT NULL,'+
'  `ENDPOINTNDESC` varchar(60) DEFAULT NULL,'+
'  `ENDUNIT` varchar(30) DEFAULT NULL,'+
'  `CAPTIONDESC` varchar(60) DEFAULT NULL,'+
'  `CAPTIONUNIT` varchar(30) DEFAULT NULL,'+
'  `MEDIDA` varchar(30) DEFAULT NULL,'+
'  `MEDIDADIAG` varchar(30) DEFAULT NULL,'+
'  `FILTRO` varchar(60) DEFAULT NULL,'+
'  `ATIVO` varchar(1) DEFAULT NULL,'+
'  KEY `DESCRANGES0` (`TABELA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_dicas_STMT =
'CREATE TABLE `dicas` ('+
'  `CODDICA` varchar(50) DEFAULT NULL,'+
'  `PALPORT` varchar(40) DEFAULT NULL,'+
'  `DICAPORT` longtext,'+
'  `PALINGL` varchar(40) DEFAULT NULL,'+
'  `DICAINGL` longtext,'+
'  `DATACAD` DATETIME DEFAULT NULL,'+
'  UNIQUE KEY `DICAS0` (`CODDICA`),'+
'  KEY `INPALING` (`PALINGL`),'+
'  KEY `INPALPORT` (`PALPORT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_dietas_STMT =
'CREATE TABLE `dietas` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `DIETA` longtext,'+
'  `DESCRICAO` varchar(60) DEFAULT NULL,'+
'  UNIQUE KEY `DIETAS0` (`IDPESSOA`,`DATA`),'+
'  UNIQUE KEY `IDDIETADECR` (`IDPESSOA`,`DATA`),'+
'  KEY `IDDIENOME` (`DESCRICAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_dscrfnt_STMT =
'CREATE TABLE `dscrfnt` ('+
'  `FONTE` varchar(50) DEFAULT NULL,'+
'  `DESCRICAO` varchar(255) DEFAULT NULL,'+
'  UNIQUE KEY `DSCRFNT0` (`FONTE`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_dscrnumval_STMT =
'CREATE TABLE `dscrnumval` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `DSCRLD` varchar(50) DEFAULT NULL,'+
'  `INTERVALBEGIN` double DEFAULT NULL,'+
'  `INTERVALEND` double DEFAULT NULL,'+
'  `NORMAL` double DEFAULT NULL,'+
'  `MEAN` double DEFAULT NULL,'+
'  `STDDEV` double DEFAULT NULL,'+
'  UNIQUE KEY `DSCRNUMVAL0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_dscrparm_STMT =
'CREATE TABLE `dscrparm` ('+
'  `CODDSCR` varchar(50) DEFAULT NULL,'+
'  `CODQTYPARM` varchar(50) DEFAULT NULL,'+
'  `UNIDADE` varchar(50) DEFAULT NULL,'+
'  `VALOR` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `DSCRPARM0` (`CODDSCR`,`CODQTYPARM`),'+
'  KEY `DSCRPRM` (`CODDSCR`),'+
'  KEY `QTYPRM` (`CODQTYPARM`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_dscrqntv_STMT =
'CREATE TABLE `dscrqntv` ('+
'  `CODDSCR` varchar(50) DEFAULT NULL,'+
'  `VALORDEPENDENTE` varchar(50) DEFAULT NULL,'+
'  `UNIDADEVDEP` varchar(50) DEFAULT NULL,'+
'  `VARINDEPENDENTE` varchar(50) DEFAULT NULL,'+
'  `UNIDADEVINDEP` varchar(50) DEFAULT NULL,'+
'  `MINVINDEP` varchar(50) DEFAULT NULL,'+
'  `MAXVINDEP` varchar(50) DEFAULT NULL,'+
'  `TIPOINTERVALO` varchar(20) DEFAULT NULL,'+
'  `DELTA` double DEFAULT NULL,'+
'  UNIQUE KEY `DSCRQNTV0` (`CODDSCR`,`VALORDEPENDENTE`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_dscrtrs_STMT =
'CREATE TABLE `dscrtrs` ('+
'  `CODIGO` varchar(50) DEFAULT NULL,'+
'  `DESCRICAO` varchar(255) DEFAULT NULL,'+
'  `RESPONSAVEL` varchar(50) DEFAULT NULL,'+
'  `DATACRIACAO` DATETIME DEFAULT NULL,'+
'  `ULTIMAALTERACAO` DATETIME DEFAULT NULL,'+
'  `FONTE` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `DSCRTRS0` (`CODIGO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_dscrvalues_STMT =
'CREATE TABLE `dscrvalues` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `DSCRID` varchar(50) DEFAULT NULL,'+
'  `INTERVALBEGIN` varchar(50) DEFAULT NULL,'+
'  `INTERVALEND` varchar(50) DEFAULT NULL,'+
'  `NORMAL` varchar(50) DEFAULT NULL,'+
'  `MEAN` varchar(50) DEFAULT NULL,'+
'  `STDDEV` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `DSCRVALUES0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_endereco_STMT =
'CREATE TABLE `endereco` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `NOMELOGRAD` varchar(60) DEFAULT NULL,'+
'  `NUMLOGRAD` varchar(8) DEFAULT NULL,'+
'  `COMPLEM` varchar(15) DEFAULT NULL,'+
'  `BAIRRO` varchar(50) DEFAULT NULL,'+
'  `CIDADE` varchar(50) DEFAULT NULL,'+
'  `CEP` varchar(10) DEFAULT NULL,'+
'  `UF` varchar(2) DEFAULT NULL,'+
'  `EMAIL` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `ENDERECO0` (`IDPESSOA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_estado_STMT =
'CREATE TABLE `estado` ('+
'  `IDESTADO` varchar(50) DEFAULT NULL,'+
'  `ABREVESTADO` varchar(2) DEFAULT NULL,'+
'  `NOMEESTADO` varchar(20) DEFAULT NULL,'+
'  UNIQUE KEY `ESTADO0` (`IDESTADO`),'+
'  UNIQUE KEY `INABREVEST` (`ABREVESTADO`),'+
'  UNIQUE KEY `INESTADO` (`NOMEESTADO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_exapess_STMT =
'CREATE TABLE `exapess` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `EXAMES` longtext,'+
'  UNIQUE KEY `EXAPESS0` (`IDPESSOA`,`DATA`),'+
'  UNIQUE KEY `EXAPESS_IDDATADECR` (`IDPESSOA`,`DATA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_faixaetaria_STMT =
'CREATE TABLE `faixaetaria` ('+
'  `NOMESLOT` varchar(50) DEFAULT NULL,'+
'  `LIMMINIMO` double DEFAULT NULL,'+
'  `LIMMAXIMO` double DEFAULT NULL,'+
'  `TIPOLIMITEMIN` varchar(50) DEFAULT NULL,'+
'  `TIPOLIMITEMAX` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `FAIXAETARIA0` (`NOMESLOT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_galical_STMT =
'CREATE TABLE `galical` ('+
'  `IDGRUALI` varchar(50) DEFAULT NULL,'+
'  `IDGRUCAL` varchar(50) DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `GALICAL0` (`IDGRUALI`,`IDGRUCAL`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_galiprot_STMT =
'CREATE TABLE `galiprot` ('+
'  `IDGRUALI` varchar(50) DEFAULT NULL,'+
'  `IDGRUPROT` varchar(50) DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `GALIPROT0` (`IDGRUALI`,`IDGRUPROT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_gruali_STMT =
'CREATE TABLE `gruali` ('+
'  `IDGRUALI` varchar(50) DEFAULT NULL,'+
'  `NOMEGRU` varchar(30) DEFAULT NULL,'+
'  `PROTAVB` varchar(1) DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `GRUALI0` (`IDGRUALI`),'+
'  UNIQUE KEY `IDNOMEGRU` (`NOMEGRU`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_grucal_STMT =
'CREATE TABLE `grucal` ('+
'  `IDGRUCAL` varchar(50) DEFAULT NULL,'+
'  `NOME` varchar(30) DEFAULT NULL,'+
'  `CALORIAS` double DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `GRUCAL0` (`IDGRUCAL`),'+
'  UNIQUE KEY `IDGCALNOME` (`NOME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_gruprot_STMT =
'CREATE TABLE `gruprot` ('+
'  `IDGRUPROT` varchar(50) DEFAULT NULL,'+
'  `NOME` varchar(30) DEFAULT NULL,'+
'  `PROTEINAS` double DEFAULT NULL,'+
'  `CALORIAS` double DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `GRUPROT0` (`IDGRUPROT`),'+
'  UNIQUE KEY `IDGPROTNOME` (`NOME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_help_STMT =
'CREATE TABLE `help` ('+
'  `TOPICID` char(50) DEFAULT NULL,'+
'  `MAP` int(11) DEFAULT NULL,'+
'  `FILEID` int(11) DEFAULT NULL,'+
'  `TOPICNAME` char(100) DEFAULT NULL,'+
'  KEY `IDXTOPICID` (`TOPICID`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_helpfiles_STMT =
'CREATE TABLE `helpfiles` ('+
'  `FILEID` int(11) DEFAULT NULL,'+
'  `FILENAME` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `IDXFILEID` (`FILEID`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

 
CREATE_inqaf_STMT =
'CREATE TABLE `inqaf` ('+
'  `GUIDATIVFIS` varchar(50) DEFAULT NULL,'+
'  `TEMPO` double DEFAULT NULL,'+
'  UNIQUE KEY `INQAF0` (`GUIDATIVFIS`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_inqueritos_STMT =
'CREATE TABLE `inqueritos` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `INQUERITO` longtext,'+
'  `DESCRICAO` varchar(60) DEFAULT NULL,'+
'  UNIQUE KEY `IDINQDECR` (`IDPESSOA`,`DATA`),'+
'  UNIQUE KEY `INQUERITOS0` (`IDPESSOA`,`DATA`),'+
'  KEY `IDINQNOME` (`DESCRICAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

 
CREATE_instrucao_STMT =
'CREATE TABLE `instrucao` ('+
'  `CODINSTRUC` varchar(50) DEFAULT NULL,'+
'  `DESCINST` varchar(45) DEFAULT NULL,'+
'  `ORDEM` int(11) DEFAULT NULL,'+
'  UNIQUE KEY `INSTRUCAO0` (`CODINSTRUC`),'+
'  KEY `DESCINSTRUCAO` (`DESCINST`),'+
'  KEY `ININSTRUCAO` (`ORDEM`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_itensali_STMT =
'CREATE TABLE `itensali` ('+
'  `GUID` varchar(50) DEFAULT NULL,'+
'  `ID_CALCALI` varchar(50) DEFAULT NULL,'+
'  `ID_REFEICAO` varchar(50) DEFAULT NULL,'+
'  `ID_ALI` varchar(50) DEFAULT NULL,'+
'  `ID_MEDIDA` varchar(50) DEFAULT NULL,'+
'  `QUANT` double DEFAULT NULL,'+
'  `PESO` double DEFAULT NULL,'+
'  `FREQDIA` double DEFAULT NULL,'+
'  `IDGRUALI` varchar(50) DEFAULT NULL,'+
'  `NUT_PROT` double DEFAULT NULL,'+
'  `NUT_PROTAVB` double DEFAULT NULL,'+
'  `NUT_ENERGIA` double DEFAULT NULL,'+
'  `NUT_CALCIO` double DEFAULT NULL,'+
'  `NUT_FOSFORO` double DEFAULT NULL,'+
'  `NUT_AGSAT` double DEFAULT NULL,'+
'  `NUT_AGPOL` double DEFAULT NULL,'+
'  `NUT_AGMON` double DEFAULT NULL,'+
'  `NUT_CARBO` double DEFAULT NULL,'+
'  `NUT_ALCOOL` double DEFAULT NULL,'+
'  `NUT_TEMP` double DEFAULT NULL,'+
'  `ITEM` int(11) DEFAULT NULL,'+
'  UNIQUE KEY `ITENSALI0` (`GUID`),'+
'  KEY `IDALIIX` (`ID_ALI`),'+
'  KEY `ORDITEM` (`ID_CALCALI`,`ID_REFEICAO`,`GUID`),'+
'  KEY `ORDITEM2` (`ID_CALCALI`,`ID_REFEICAO`,`ITEM`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_listarefeicao_STMT =
'CREATE TABLE `listarefeicao` ('+
'  `ID_REFEICAO` varchar(50) DEFAULT NULL,'+
'  `ID_MODREF` varchar(50) DEFAULT NULL,'+
'  `HORARIO` DATETIME DEFAULT NULL,'+
'  UNIQUE KEY `LISTAREFEICAO0` (`ID_REFEICAO`,`ID_MODREF`),'+
'  KEY `IDXHORARIO` (`HORARIO`),'+
'  KEY `IDXMODREF` (`ID_MODREF`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_macronut_STMT =
'CREATE TABLE `macronut` ('+
'  `IDMACRONUT` varchar(50) DEFAULT NULL,'+
'  `ORDPADRAO` double DEFAULT NULL,'+
'  `DESCRICAO` varchar(30) DEFAULT NULL,'+
'  `UNIDADE` varchar(10) DEFAULT NULL,'+
'  `FATORENERGIA` double DEFAULT NULL,'+
'  UNIQUE KEY `MACRONUT0` (`IDMACRONUT`),'+
'  KEY `ORDEMPADRAO` (`ORDPADRAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 

CREATE_medcorpo_STMT =
'CREATE TABLE `medcorpo` ('+
'  `CORPO` varchar(50) DEFAULT NULL,'+
'  `PSENSIVEL` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `MEDCORPO0` (`CORPO`,`PSENSIVEL`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_meddesc_STMT =
'CREATE TABLE `meddesc` ('+
'  `GRANDEZA` varchar(50) DEFAULT NULL,'+
'  `DESCRITOR` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `MEDDESC0` (`GRANDEZA`,`DESCRITOR`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 

CREATE_medidacaseira_STMT =
'CREATE TABLE `medidacaseira` ('+
'  `IDALI` varchar(50) DEFAULT NULL,'+
'  `IDMEDCAS` varchar(50) DEFAULT NULL,'+
'  `VALOR` double DEFAULT NULL,'+
'  `ORDPADRAO` double DEFAULT NULL,'+
'  `PORCAOPAD` varchar(1) DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `MEDIDACASEIRA0` (`IDALI`,`IDMEDCAS`),'+
'  KEY `IDMEDCAS` (`IDMEDCAS`),'+
'  KEY `IDXALI` (`IDALI`),'+
'  KEY `IDXORDPAD` (`IDALI`,`ORDPADRAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_medidas_STMT =
'CREATE TABLE `medidas` ('+
'  `IDMEDCAS` varchar(50) DEFAULT NULL,'+
'  `MEDIDA` varchar(20) DEFAULT NULL,'+
'  `READONLY` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `IDMEDIDA` (`MEDIDA`),'+
'  UNIQUE KEY `MEDIDAS0` (`IDMEDCAS`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

 
CREATE_medparte_STMT =
'CREATE TABLE `medparte` ('+
'  `MEDIDA` varchar(50) DEFAULT NULL,'+
'  `PARTECORPO` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `MEDPARTE0` (`MEDIDA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_metas_STMT =
'CREATE TABLE `metas` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `META` longtext,'+
'  UNIQUE KEY `IDMETADECR` (`IDPESSOA`,`DATA`),'+
'  UNIQUE KEY `METAS0` (`IDPESSOA`,`DATA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_modrefeicao_STMT =
'CREATE TABLE `modrefeicao` ('+
'  `ID_MODREF` varchar(50) DEFAULT NULL,'+
'  `NOME` varchar(30) DEFAULT NULL,'+
'  UNIQUE KEY `IDXNOME` (`NOME`),'+
'  UNIQUE KEY `MODREFEICAO0` (`ID_MODREF`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_nacionalidade_STMT =
'CREATE TABLE `nacionalidade` ('+
'  `NACIONALIDADE` varchar(40) DEFAULT NULL,'+
'  `SIGLA` varchar(2) DEFAULT NULL,'+
'  `IDNAC` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `INNACIONALIDADE` (`SIGLA`),'+
'  UNIQUE KEY `NACIONALIDADE0` (`NACIONALIDADE`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_nt3_ei_STMT =
'CREATE TABLE `nt3_ei` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `COMPESTAT` varchar(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  UNIQUE KEY `NT3_EI0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_nt3_pe_STMT =
'CREATE TABLE `nt3_pe` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `COMPESTAT` varchar(11) DEFAULT NULL,'+
'  `ESTATURAMIN` double DEFAULT NULL,'+
'  `ESTATURAMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  UNIQUE KEY `NT3_PE0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_nt3_pi_STMT =
'CREATE TABLE `nt3_pi` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `COMPESTAT` varchar(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  UNIQUE KEY `NT3_PI0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_nut_STMT =
'CREATE TABLE `nut` ('+
'  `IDNUT` varchar(50) DEFAULT NULL,'+
'  `ABREV` varchar(4) DEFAULT NULL,'+
'  `NOMENUT` varchar(30) DEFAULT NULL,'+
'  `UNIDADE` varchar(6) DEFAULT NULL,'+
'  `ORDPADRAO` double DEFAULT NULL,'+
'  `VISIVEL` varchar(1) DEFAULT NULL,'+
'  `IDORIG` varchar(50) DEFAULT NULL,'+
'  `ORDUSDA` double DEFAULT NULL,'+
'  UNIQUE KEY `IDNOMENUT` (`NOMENUT`),'+
'  UNIQUE KEY `NUT0` (`IDNUT`),'+
'  KEY `IDXORDUSDA` (`ORDUSDA`),'+
'  KEY `IDXORDPADRAO` (`ORDPADRAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_nutconv_STMT =
'CREATE TABLE `nutconv` ('+
'  `NUTR_NO` varchar(3) DEFAULT NULL,'+
'  `GUID` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  UNIQUE KEY `NUTCONV0` (`NUTR_NO`,`GUID`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_nutord_STMT =
'CREATE TABLE `nutord` ('+
'  `IDNUT` varchar(50) DEFAULT NULL,'+
'  `USERNAME` varchar(50) DEFAULT NULL,'+
'  `ORDUSER` int(11) DEFAULT NULL,'+
'  UNIQUE KEY `NUTORD0` (`IDNUT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_objvis_STMT =
'CREATE TABLE `objvis` ('+
'  `OBJETO` varchar(25) DEFAULT NULL,'+
'  `VISTAINICIAL` double DEFAULT NULL,'+
'  `TOTALVISTAS` double DEFAULT NULL,'+
'  UNIQUE KEY `OBJVIS0` (`OBJETO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_opcoes_STMT =
'CREATE TABLE `opcoes` ('+
'  `IDOPCOES` varchar(50) DEFAULT NULL,'+
'  `NATURALIDADE` varchar(50) DEFAULT NULL,'+
'  `NACIONALIDADE` varchar(50) DEFAULT NULL,'+
'  `SEXO` varchar(1) DEFAULT NULL,'+
'  `COR` varchar(50) DEFAULT NULL,'+
'  `CIDADE` varchar(50) DEFAULT NULL,'+
'  `RCABEC1` varchar(50) DEFAULT NULL,'+
'  `RCABEC2` varchar(100) DEFAULT NULL,'+
'  `RCABEC3` varchar(100) DEFAULT NULL,'+
'  `RCABEC4` varchar(100) DEFAULT NULL,'+
'  `RRODAP1` varchar(100) DEFAULT NULL,'+
'  `RLOGO` longblob,'+
'  `ESTADO` varchar(2) DEFAULT NULL,'+
'  UNIQUE KEY `OPCOES0` (`IDOPCOES`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_ovcursor_STMT =
'CREATE TABLE `ovcursor` ('+
'  `OVCURSOR` varchar(25) DEFAULT NULL,'+
'  `DESCRICAO` varchar(50) DEFAULT NULL,'+
'  `NCURSOR` int(11) DEFAULT NULL,'+
'  UNIQUE KEY `OVCURSOR0` (`OVCURSOR`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_pastas_STMT =
'CREATE TABLE `pastas` ('+
'  `IDPASTA` varchar(50) DEFAULT NULL,'+
'  `NOMEPASTA` varchar(20) DEFAULT NULL,'+
'  `ICON` int(11) DEFAULT NULL,'+
'  UNIQUE KEY `IDNOMEPASTA` (`NOMEPASTA`),'+
'  UNIQUE KEY `PASTAS0` (`IDPASTA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_pesqtemp_STMT =
'CREATE TABLE `pesqtemp` ('+
'  `CODIGO` varchar(50) DEFAULT NULL,'+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `DATANASC` DATETIME DEFAULT NULL,'+
'  `CODSEXO` varchar(1) DEFAULT NULL,'+
'  `DATACAD` DATETIME DEFAULT NULL,'+
'  `SOBRPESS` varchar(18) DEFAULT NULL,'+
'  `NOMEPESS` varchar(30) DEFAULT NULL,'+
'  UNIQUE KEY `PESQTEMP0` (`CODIGO`,`IDPESSOA`),'+
'  KEY `IDCODIGO` (`CODIGO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_pesscomp_STMT =
'CREATE TABLE `pesscomp` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `CODNATURAL` varchar(50) DEFAULT NULL,'+
'  `CODNACIONAL` varchar(50) DEFAULT NULL,'+
'  `CODESTCIVIL` varchar(6) DEFAULT NULL,'+
'  `CODCOR` varchar(50) DEFAULT NULL,'+
'  `CODPROFIS` varchar(50) DEFAULT NULL,'+
'  `OBS` longtext,'+
'  `CODINSTRUC` varchar(50) DEFAULT NULL,'+
'  `REGISTRO` varchar(6) DEFAULT NULL,'+
'  UNIQUE KEY `PESSCOMP0` (`IDPESSOA`),'+
'  KEY `IDREGISTRO` (`REGISTRO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_pessoa_STMT =
'CREATE TABLE `pessoa` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `SOBRPESS` varchar(18) DEFAULT NULL,'+
'  `NOMEPESS` varchar(30) DEFAULT NULL,'+
'  `DATANASC` DATETIME DEFAULT NULL,'+
'  `CODSEXO` varchar(1) DEFAULT NULL,'+
'  `SOBRRESP` varchar(18) DEFAULT NULL,'+
'  `NOMERESP` varchar(30) DEFAULT NULL,'+
'  `DATACAD` DATETIME DEFAULT NULL,'+
'  `FOTOPESS` longblob,'+
'  `FONETIZADO` varchar(28) DEFAULT NULL,'+
'  UNIQUE KEY `PESSOA0` (`IDPESSOA`),'+
'  KEY `IDFONETICO` (`FONETIZADO`),'+
'  KEY `IDNOMEPES` (`NOMEPESS`,`SOBRPESS`),'+
'  KEY `IDSOBRPES` (`SOBRPESS`,`NOMEPESS`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_preparac_STMT =
'CREATE TABLE `preparac` ('+
'  `IDALI` varchar(50) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `PREP` longtext,'+
'  UNIQUE KEY `PREPARAC0` (`IDALI`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_profissao_STMT =
'CREATE TABLE `profissao` ('+
'  `CODPROFIS` varchar(50) DEFAULT NULL,'+
'  `DESCPROF` varchar(60) DEFAULT NULL,'+
'  UNIQUE KEY `INPROFISSAO` (`DESCPROF`),'+
'  UNIQUE KEY `PROFISSAO0` (`CODPROFIS`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_pt3_ei_STMT =
'CREATE TABLE `pt3_ei` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `COMPESTAT` varchar(11) DEFAULT NULL,'+
'  `SEXO` varchar(9) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `BEGINCAPTION` double DEFAULT NULL,'+
'  `CAPTION` varchar(10) DEFAULT NULL,'+
'  `ENDCAPTION` double DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `PT3_EI0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_rda_STMT =
'CREATE TABLE `rda` ('+
'  `IDNUT` varchar(50) DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `NUTRIENTE` varchar(20) DEFAULT NULL,'+
'  `ORDEM` double DEFAULT NULL,'+
'  `UNIDADE` varchar(10) DEFAULT NULL,'+
'  `FAIXA1` double DEFAULT NULL,'+
'  `FAIXA2` double DEFAULT NULL,'+
'  `FAIXA3` double DEFAULT NULL,'+
'  `FAIXA4` double DEFAULT NULL,'+
'  `FAIXA5` double DEFAULT NULL,'+
'  `FAIXA6` double DEFAULT NULL,'+
'  `FAIXA7` double DEFAULT NULL,'+
'  `FAIXA8` double DEFAULT NULL,'+
'  `FAIXA9` double DEFAULT NULL,'+
'  `FAIXA10` double DEFAULT NULL,'+
'  UNIQUE KEY `RDA0` (`IDNUT`,`SEXO`),'+
'  KEY `IDXNOMENUTRDA` (`NUTRIENTE`),'+
'  KEY `IDXNUTORDEMRDA` (`ORDEM`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_rdafaixas_STMT =
'CREATE TABLE `rdafaixas` ('+
'  `TIPOFAIXA` varchar(1) DEFAULT NULL,'+
'  `NOMEFAIXA` varchar(20) DEFAULT NULL,'+
'  `MINF` double DEFAULT NULL,'+
'  `MAXF` double DEFAULT NULL,'+
'  `UNIDADE` varchar(10) DEFAULT NULL,'+
'  UNIQUE KEY `RDAFAIXAS0` (`TIPOFAIXA`,`NOMEFAIXA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_rdagn_STMT =
'CREATE TABLE `rdagn` ('+
'  `IDNUT` varchar(50) DEFAULT NULL,'+
'  `NUTRIENTE` varchar(20) DEFAULT NULL,'+
'  `UNIDADE` varchar(10) DEFAULT NULL,'+
'  `OP` varchar(1) DEFAULT NULL,'+
'  `GESTANTE1` double DEFAULT NULL,'+
'  `GESTANTE2` double DEFAULT NULL,'+
'  `NUTRIZ1` double DEFAULT NULL,'+
'  `NUTRIZ2` double DEFAULT NULL,'+
'  UNIQUE KEY `RDAGN0` (`IDNUT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_refcalcali_STMT =
'CREATE TABLE `refcalcali` ('+
'  `GUID` varchar(50) DEFAULT NULL,'+
'  `ID_CALCALI` varchar(50) DEFAULT NULL,'+
'  `ID_REFEICAO` varchar(50) DEFAULT NULL,'+
'  `DISTRIBUICAO` double DEFAULT NULL,'+
'  UNIQUE KEY `REFCALCALI0` (`GUID`),'+
'  KEY `REFCALCALI` (`ID_CALCALI`,`ID_REFEICAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
 
CREATE_refeicao_STMT =
'CREATE TABLE `refeicao` ('+
'  `ID_REFEICAO` varchar(50) DEFAULT NULL,'+
'  `NOME` varchar(30) DEFAULT NULL,'+
'  `HORARIO` DATETIME DEFAULT NULL,'+
'  `EXCLUSIVE` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `IDXNOMEREF` (`NOME`),'+
'  UNIQUE KEY `REFEICAO0` (`ID_REFEICAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_semaforo_STMT =
'CREATE TABLE `semaforo` ('+
'  `RECURSO` varchar(50) NOT NULL,'+
'  `USERNAME` varchar(50) NOT NULL,'+
'  `APPID` varchar(50) NOT NULL,'+
'  `DSC_RECURSO` varchar(50) NOT NULL,'+
'  `DT_TRAVAMENTO` DATETIME NOT NULL,'+
'  UNIQUE KEY `RDB_PRIMARY1` (`RECURSO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_sexo_STMT =
'CREATE TABLE `sexo` ('+
'  `CODSEXO` varchar(1) DEFAULT NULL,'+
'  `DESCSEXO` varchar(10) DEFAULT NULL,'+
'  UNIQUE KEY `SEXO0` (`CODSEXO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_sxagebdy_STMT =
'CREATE TABLE `sxagebdy` ('+
'  `SEXO` varchar(50) DEFAULT NULL,'+
'  `ESTADO` varchar(50) DEFAULT NULL,'+
'  `FAIXAETARIA` varchar(50) DEFAULT NULL,'+
'  `CORPO` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `SXAGEBDY0` (`SEXO`,`ESTADO`,`FAIXAETARIA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';


CREATE_t1_STMT =
'CREATE TABLE `t1` ('+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `C` double DEFAULT NULL,'+
'  `M` double DEFAULT NULL,'+
'  UNIQUE KEY `T10` (`IDADEMIN`,`IDADEMAX`,`SEXO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t10_STMT =
'CREATE TABLE `t10` ('+
'  `COMPLEICAO` varchar(10) DEFAULT NULL,'+
'  `FATOR` double DEFAULT NULL,'+
'  UNIQUE KEY `T100` (`COMPLEICAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t11_STMT =
'CREATE TABLE `t11` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(45) DEFAULT NULL,'+
'  UNIQUE KEY `T110` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t12_STMT =
'CREATE TABLE `t12` ('+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `FGER` varchar(15) DEFAULT NULL,'+
'  `B` double DEFAULT NULL,'+
'  `C` double DEFAULT NULL,'+
'  UNIQUE KEY `T120` (`SEXO`,`IDADEMIN`,`IDADEMAX`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t13_STMT =
'CREATE TABLE `t13` ('+
'  `ATIVFIS` varchar(10) DEFAULT NULL,'+
'  `FATOR` double DEFAULT NULL,'+
'  `DESCRICAO` varchar(200) DEFAULT NULL,'+
'  UNIQUE KEY `T130` (`ATIVFIS`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t14_STMT =
'CREATE TABLE `t14` ('+
'  `ATIVINT` varchar(16) DEFAULT NULL,'+
'  `FATOR` double DEFAULT NULL,'+
'  UNIQUE KEY `T140` (`ATIVINT`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t15_STMT =
'CREATE TABLE `t15` ('+
'  `LESAO` varchar(25) DEFAULT NULL,'+
'  `FATOR` double DEFAULT NULL,'+
'  UNIQUE KEY `T150` (`LESAO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t16_STMT =
'CREATE TABLE `t16` ('+
'  `TEMPCORP` varchar(6) DEFAULT NULL,'+
'  `FATOR` double DEFAULT NULL,'+
'  UNIQUE KEY `T160` (`TEMPCORP`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t17_STMT =
'CREATE TABLE `t17` ('+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `KCALKG` double DEFAULT NULL,'+
'  UNIQUE KEY `T170` (`SEXO`,`IDADEMIN`,`IDADEMAX`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t18_STMT =
'CREATE TABLE `t18` ('+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `ATIVFIS` varchar(12) DEFAULT NULL,'+
'  `FATOR` double DEFAULT NULL,'+
'  UNIQUE KEY `T180` (`SEXO`,`ATIVFIS`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t19_STMT =
'CREATE TABLE `t19` ('+
'  `DESCATIVFI` varchar(40) DEFAULT NULL,'+
'  `GUID` varchar(50) DEFAULT NULL,'+
'  `COEFA` double DEFAULT NULL,'+
'  `COEFB` double DEFAULT NULL,'+
'  UNIQUE KEY `T190` (`DESCATIVFI`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t2_STMT =
'CREATE TABLE `t2` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(20) DEFAULT NULL,'+
'  UNIQUE KEY `T20` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t20_STMT =
'CREATE TABLE `t20` ('+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `ESTATURA` double DEFAULT NULL,'+
'  `CI` double DEFAULT NULL,'+
'  UNIQUE KEY `T200` (`SEXO`,`IDADEMIN`,`IDADEMAX`,`ESTATURA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t22_STMT =
'CREATE TABLE `t22` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  UNIQUE KEY `T220` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t23_STMT =
'CREATE TABLE `t23` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  UNIQUE KEY `T230` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t24_STMT =
'CREATE TABLE `t24` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(70) DEFAULT NULL,'+
'  UNIQUE KEY `T240` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t25_STMT =
'CREATE TABLE `t25` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  UNIQUE KEY `T250` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t26_STMT =
'CREATE TABLE `t26` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  UNIQUE KEY `T260` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t27_STMT =
'CREATE TABLE `t27` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  UNIQUE KEY `T270` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t28_STMT =
'CREATE TABLE `t28` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `PERCENTIL` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(40) DEFAULT NULL,'+
'  `CAPTION2` varchar(20) DEFAULT NULL,'+
'  UNIQUE KEY `T280` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t29_STMT =
'CREATE TABLE `t29` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `PORCMIN` double DEFAULT NULL,'+
'  `PORCMAX` double DEFAULT NULL,'+
'  `DIAG` varchar(11) DEFAULT NULL,'+
'  UNIQUE KEY `T290` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t31_STMT =
'CREATE TABLE `t31` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `T310` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t32_STMT =
'CREATE TABLE `t32` ('+
'  `ICEMIN` double DEFAULT NULL,'+
'  `ICEMAX` double DEFAULT NULL,'+
'  `DIAG` varchar(15) DEFAULT NULL,'+
'  UNIQUE KEY `T320` (`ICEMIN`,`ICEMAX`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t33_STMT =
'CREATE TABLE `t33` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(20) DEFAULT NULL,'+
'  UNIQUE KEY `T330` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t33a_STMT =
'CREATE TABLE `t33a` ('+
'  `DIAGIMCGEST` varchar(10) DEFAULT NULL,'+
'  `POSMENARCA2A` varchar(3) DEFAULT NULL,'+
'  `TIPOESTATURA` varchar(10) DEFAULT NULL,'+
'  `DIAGGANHOPESO` varchar(15) DEFAULT NULL,'+
'  KEY `T33A0` (`DIAGIMCGEST`,`POSMENARCA2A`,`TIPOESTATURA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t3_ei_STMT =
'CREATE TABLE `t3_ei` ('+
'  `COMPESTAT` varchar(11) DEFAULT NULL,'+
'  `SEXO` varchar(9) DEFAULT NULL,'+
'  `IDADE` double DEFAULT NULL,'+
'  `P3` double DEFAULT NULL,'+
'  `P5` double DEFAULT NULL,'+
'  `P10` double DEFAULT NULL,'+
'  `P20` double DEFAULT NULL,'+
'  `P30` double DEFAULT NULL,'+
'  `P40` double DEFAULT NULL,'+
'  `P50` double DEFAULT NULL,'+
'  `P60` double DEFAULT NULL,'+
'  `P70` double DEFAULT NULL,'+
'  `P80` double DEFAULT NULL,'+
'  `P90` double DEFAULT NULL,'+
'  `P95` double DEFAULT NULL,'+
'  `P97` double DEFAULT NULL,'+
'  `ZN3DE` double DEFAULT NULL,'+
'  `ZN2DE` double DEFAULT NULL,'+
'  `ZN1DE` double DEFAULT NULL,'+
'  `ZMED` double DEFAULT NULL,'+
'  `Z1DE` double DEFAULT NULL,'+
'  `Z2DE` double DEFAULT NULL,'+
'  `Z3DE` double DEFAULT NULL,'+
'  UNIQUE KEY `T3_EI0` (`COMPESTAT`,`SEXO`,`IDADE`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t3_pe_STMT =
'CREATE TABLE `t3_pe` ('+
'  `COMPESTAT` varchar(11) DEFAULT NULL,'+
'  `SEXO` varchar(9) DEFAULT NULL,'+
'  `ESTATURA` double DEFAULT NULL,'+
'  `P3` double DEFAULT NULL,'+
'  `P5` double DEFAULT NULL,'+
'  `P10` double DEFAULT NULL,'+
'  `P20` double DEFAULT NULL,'+
'  `P30` double DEFAULT NULL,'+
'  `P40` double DEFAULT NULL,'+
'  `P50` double DEFAULT NULL,'+
'  `P60` double DEFAULT NULL,'+
'  `P70` double DEFAULT NULL,'+
'  `P80` double DEFAULT NULL,'+
'  `P90` double DEFAULT NULL,'+
'  `P95` double DEFAULT NULL,'+
'  `P97` double DEFAULT NULL,'+
'  `ZN3DE` double DEFAULT NULL,'+
'  `ZN2DE` double DEFAULT NULL,'+
'  `ZN1DE` double DEFAULT NULL,'+
'  `ZMED` double DEFAULT NULL,'+
'  `Z1DE` double DEFAULT NULL,'+
'  `Z2DE` double DEFAULT NULL,'+
'  `Z3DE` double DEFAULT NULL,'+
'  UNIQUE KEY `T3_PE0` (`COMPESTAT`,`SEXO`,`ESTATURA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t3_pi_STMT =
'CREATE TABLE `t3_pi` ('+
'  `COMPESTAT` varchar(11) DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `IDADE` double DEFAULT NULL,'+
'  `P3` double DEFAULT NULL,'+
'  `P5` double DEFAULT NULL,'+
'  `P10` double DEFAULT NULL,'+
'  `P20` double DEFAULT NULL,'+
'  `P30` double DEFAULT NULL,'+
'  `P40` double DEFAULT NULL,'+
'  `P50` double DEFAULT NULL,'+
'  `P60` double DEFAULT NULL,'+
'  `P70` double DEFAULT NULL,'+
'  `P80` double DEFAULT NULL,'+
'  `P90` double DEFAULT NULL,'+
'  `P95` double DEFAULT NULL,'+
'  `P97` double DEFAULT NULL,'+
'  `ZN3DE` double DEFAULT NULL,'+
'  `ZN2DE` double DEFAULT NULL,'+
'  `ZN1DE` double DEFAULT NULL,'+
'  `ZMED` double DEFAULT NULL,'+
'  `Z1DE` double DEFAULT NULL,'+
'  `Z2DE` double DEFAULT NULL,'+
'  `Z3DE` double DEFAULT NULL,'+
'  UNIQUE KEY `T3_PI0` (`COMPESTAT`,`SEXO`,`IDADE`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t4_STMT =
'CREATE TABLE `t4` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `IDADEMIN` double DEFAULT NULL,'+
'  `IDADEMAX` double DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(45) DEFAULT NULL,'+
'  UNIQUE KEY `T40` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t5_STMT =
'CREATE TABLE `t5` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `EIMIN` double DEFAULT NULL,'+
'  `EIMAX` double DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(100) DEFAULT NULL'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t6_STMT =
'CREATE TABLE `t6` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(20) DEFAULT NULL,'+
'  UNIQUE KEY `T60` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t7_STMT =
'CREATE TABLE `t7` ('+
'  `SEXO` varchar(9) DEFAULT NULL,'+
'  `ESTATURA` double DEFAULT NULL,'+
'  `PEQUENA` double DEFAULT NULL,'+
'  `MEDIA` double DEFAULT NULL,'+
'  `GRANDE` double DEFAULT NULL,'+
'  UNIQUE KEY `T70` (`SEXO`,`ESTATURA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t7a_STMT =
'CREATE TABLE `t7a` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `COMPLEICAO` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` double DEFAULT NULL,'+
'  UNIQUE KEY `T7A0` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t8_STMT =
'CREATE TABLE `t8` ('+
'  `INTERVALO` int(11) DEFAULT NULL,'+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `BEGINPOINT` double DEFAULT NULL,'+
'  `BEGINEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `BEGINOPENED` varchar(1) DEFAULT NULL,'+
'  `ENDPOINT` double DEFAULT NULL,'+
'  `ENDEXCLUDED` varchar(1) DEFAULT NULL,'+
'  `ENDOPENED` varchar(1) DEFAULT NULL,'+
'  `CAPTION` varchar(20) DEFAULT NULL,'+
'  UNIQUE KEY `T80` (`INTERVALO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_t9_STMT =
'CREATE TABLE `t9` ('+
'  `DEFICIENCIA` varchar(20) DEFAULT NULL,'+
'  `FATOR` double DEFAULT NULL,'+
'  UNIQUE KEY `T90` (`DEFICIENCIA`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_tambso_STMT =
'CREATE TABLE `tambso` ('+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `F1` double DEFAULT NULL,'+
'  UNIQUE KEY `TAMBSO0` (`SEXO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_tcondica_STMT =
'CREATE TABLE `tcondica` ('+
'  `NAME` varchar(50) DEFAULT NULL,'+
'  `DATABASENAME` varchar(50) DEFAULT NULL,'+
'  `NOMECONDICAO` varchar(50) DEFAULT NULL,'+
'  `VERDADEIRO` varchar(50) DEFAULT NULL,'+
'  `FALSO` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `TCONDICA0` (`NAME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_tdescritor_STMT =
'CREATE TABLE `tdescritor` ('+
'  `NAME` varchar(50) DEFAULT NULL,'+
'  `DESCRICAO` varchar(50) DEFAULT NULL,'+
'  `NOMEPROCEDIMENTO` varchar(50) DEFAULT NULL,'+
'  `MEDIDAVALNAME` varchar(50) DEFAULT NULL,'+
'  `GRANDEZANAME` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `TDESCRITOR0` (`NAME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_teccp_STMT =
'CREATE TABLE `teccp` ('+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `F1` double DEFAULT NULL,'+
'  `F2` double DEFAULT NULL,'+
'  `F3` double DEFAULT NULL,'+
'  `F4` double DEFAULT NULL,'+
'  `F5` double DEFAULT NULL,'+
'  `F6` double DEFAULT NULL,'+
'  UNIQUE KEY `TECCP0` (`SEXO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_telefone_STMT =
'CREATE TABLE `telefone` ('+
'  `IDPESSOA` varchar(50) DEFAULT NULL,'+
'  `TIPO` varchar(15) DEFAULT NULL,'+
'  `DDD` varchar(5) DEFAULT NULL,'+
'  `NUMTEL` varchar(9) DEFAULT NULL,'+
'  `RAMAL` varchar(10) DEFAULT NULL,'+
'  UNIQUE KEY `TELEFONE0` (`IDPESSOA`,`TIPO`,`NUMTEL`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_tfuncao_STMT =
'CREATE TABLE `tfuncao` ('+
'  `NAME` varchar(50) DEFAULT NULL,'+
'  `TIPO` varchar(30) DEFAULT NULL,'+
'  `EXPRESSAO` varchar(100) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `DESCRICAO` varchar(255) DEFAULT NULL,'+
'  `ACEITAPARAMINVALIDO` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `TFUNCAO0` (`NAME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_tgebhb_STMT =
'CREATE TABLE `tgebhb` ('+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `F1` double DEFAULT NULL,'+
'  `F2` double DEFAULT NULL,'+
'  `F3` double DEFAULT NULL,'+
'  `F4` double DEFAULT NULL,'+
'  UNIQUE KEY `TGEBHB0` (`SEXO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_tipoanam_STMT =
'CREATE TABLE `tipoanam` ('+
'  `TIPO` varchar(20) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `DESCR` longtext,'+
'  UNIQUE KEY `TIPOANAM0` (`TIPO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_tipoexa_STMT =
'CREATE TABLE `tipoexa` ('+
'  `TIPO` varchar(20) DEFAULT NULL,'+
'  `DATA` DATETIME DEFAULT NULL,'+
'  `DESCR` longtext,'+
'  UNIQUE KEY `TIPOEXA0` (`TIPO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_tmedida_STMT =
'CREATE TABLE `tmedida` ('+
'  `NAME` varchar(50) DEFAULT NULL,'+
'  `DESCRICAO` varchar(50) DEFAULT NULL,'+
'  `UNIDADEDEFAULT` varchar(50) DEFAULT NULL,'+
'  `VALORDEFAULT` varchar(50) DEFAULT NULL,'+
'  `LISTANUMEROS` varchar(250) DEFAULT NULL,'+
'  `LISTAUNIDADES` varchar(250) DEFAULT NULL,'+
'  `PRECISAO` double DEFAULT NULL,'+
'  `DESCRIPTORNAME` varchar(50) DEFAULT NULL,'+
'  `VALID` varchar(1) DEFAULT NULL,'+
'  UNIQUE KEY `TMEDIDA0` (`NAME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_tpdcs_STMT =
'CREATE TABLE `tpdcs` ('+
'  `SEXO` varchar(10) DEFAULT NULL,'+
'  `F1` double DEFAULT NULL,'+
'  `F2` double DEFAULT NULL,'+
'  UNIQUE KEY `TPDCS0` (`SEXO`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_ttabela_STMT =
'CREATE TABLE `ttabela` ('+
'  `NAME` varchar(50) DEFAULT NULL,'+
'  `DATABASENAME` varchar(50) DEFAULT NULL,'+
'  `NOMETABELA` varchar(50) DEFAULT NULL,'+
'  `CAMPORESULT` varchar(50) DEFAULT NULL,'+
'  `MODOPESQUISA` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `TTABELA0` (`NAME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_usda_food_des_STMT =
'CREATE TABLE `usda_food_des` ('+
'  `NDB_NO` varchar(5) DEFAULT NULL,'+
'  `FDGP_CD` varchar(4) DEFAULT NULL,'+
'  `DESC_` varchar(200) DEFAULT NULL,'+
'  `SHRT_DESC` varchar(60) DEFAULT NULL,'+
'  `REF_DESC` varchar(45) DEFAULT NULL,'+
'  `REFUSE` double DEFAULT NULL,'+
'  `SCINAME` varchar(60) DEFAULT NULL,'+
'  `N_FACTOR` double DEFAULT NULL,'+
'  `PRO_FACTOR` double DEFAULT NULL,'+
'  `FAT_FACTOR` double DEFAULT NULL,'+
'  `CHO_FACTOR` double DEFAULT NULL,'+
'  `BLANK_1` double DEFAULT NULL,'+
'  `BLANK_2` double DEFAULT NULL,'+
'  `BLANK_3` double DEFAULT NULL,'+
'  `BLANK_4` double DEFAULT NULL,'+
'  `DATATRADUCAO` DATETIME DEFAULT NULL'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_usda_nutr_def_STMT =
'CREATE TABLE `usda_nutr_def` ('+
'  `NUTR_NO` varchar(3) DEFAULT NULL,'+
'  `UNITS` varchar(6) DEFAULT NULL,'+
'  `TAGNAME` varchar(20) DEFAULT NULL,'+
'  `NUTRDESC` varchar(60) DEFAULT NULL,'+
'  `IFDA_NO` varchar(3) DEFAULT NULL,'+
'  `BLANK_1` double DEFAULT NULL,'+
'  `DATATRADUCAO` DATETIME DEFAULT NULL'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_usuarios_STMT =
'CREATE TABLE `usuarios` ('+
'  `USERNAME` varchar(50) DEFAULT NULL,'+
'  `SENHA` varchar(30) DEFAULT NULL,'+
'  `FUNDO_TELA` int(11) DEFAULT NULL,'+
'  `MOSTRA_DICA` int(11) DEFAULT NULL,'+
'  `CABEC_LINHA` int(11) DEFAULT NULL,'+
'  `CABEC_TEXTO` varchar(60) DEFAULT NULL,'+
'  UNIQUE KEY `IDXUSERSENHA` (`USERNAME`,`SENHA`),'+
'  UNIQUE KEY `USUARIOS0` (`USERNAME`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';
 
CREATE_validade_STMT =
'CREATE TABLE `validade` ('+
'  `DESENVOLVIMENTO` varchar(1) DEFAULT NULL,'+
'  `VERSAO_AVALIACAO` varchar(1) DEFAULT NULL,'+
'  `DATA_INSTALACAO` DATETIME DEFAULT NULL,'+
'  `DATA_ULTIMO_ACESSO` DATETIME DEFAULT NULL,'+
'  `RETROCESSO` varchar(1) DEFAULT NULL,'+
'  `CONTADOR` int(11) DEFAULT NULL,'+
'  `VALIDADE` int(11) DEFAULT NULL,'+
'  `SERIAL` varchar(16) DEFAULT NULL,'+
'  `LICENCAS` int(11) DEFAULT NULL'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_viewer_STMT =
'CREATE TABLE `viewer` ('+
'  `CALCULO` varchar(10) DEFAULT NULL,'+
'  `TIPO` varchar(10) DEFAULT NULL,'+
'  `ORDEM` int(11) DEFAULT NULL,'+
'  `MEDIDA` varchar(50) DEFAULT NULL,'+
'  UNIQUE KEY `VIEWER0` (`CALCULO`,`TIPO`,`ORDEM`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_vista_STMT =
'CREATE TABLE `vista` ('+
'  `OBJETO` varchar(25) DEFAULT NULL,'+
'  `OVORDEM` double DEFAULT NULL,'+
'  `OVPICTURE` longblob,'+
'  UNIQUE KEY `VISTA0` (`OBJETO`,`OVORDEM`)'+
') ENGINE=MYISAM DEFAULT CHARSET=latin1;';

CREATE_STMT_LIST : ARRAY[0..134] of String= (
CREATE_ADEQ_STMT,
CREATE_aliconv_STMT,
CREATE_alifreq_STMT,
CREATE_aligcal_STMT,
CREATE_aligprot_STMT,
CREATE_alimento_STMT,
CREATE_alinut_STMT,
CREATE_aliorg_STMT,
CREATE_alipreco_STMT,
CREATE_anamnese_STMT,
CREATE_antrops_STMT,
CREATE_areaclic_STMT,
CREATE_areavist_STMT,
CREATE_ativfis_STMT,
CREATE_cachedic_STMT,
CREATE_cadpastas_STMT,
CREATE_calcali_STMT,
CREATE_ccsisdic_STMT,
CREATE_cidade_STMT,
CREATE_classetariageral_STMT,
CREATE_cnut_STMT,
CREATE_cnut_pf_STMT,
CREATE_conversaobd_STMT,
CREATE_cor_STMT,
CREATE_cursores_STMT,
CREATE_descranges_STMT,
CREATE_dicas_STMT,
CREATE_dietas_STMT,
CREATE_dscrfnt_STMT,
CREATE_dscrnumval_STMT,
CREATE_dscrparm_STMT,
CREATE_dscrqntv_STMT,
CREATE_dscrtrs_STMT,
CREATE_dscrvalues_STMT,
CREATE_endereco_STMT,
CREATE_estado_STMT,
CREATE_exapess_STMT,
CREATE_faixaetaria_STMT,
CREATE_galical_STMT,
CREATE_galiprot_STMT,
CREATE_gruali_STMT,
CREATE_grucal_STMT,
CREATE_gruprot_STMT,
CREATE_help_STMT,
CREATE_helpfiles_STMT,
CREATE_inqaf_STMT,
CREATE_inqueritos_STMT,
CREATE_instrucao_STMT,
CREATE_itensali_STMT,
CREATE_listarefeicao_STMT,
CREATE_macronut_STMT,
CREATE_medcorpo_STMT,
CREATE_meddesc_STMT,
CREATE_medidacaseira_STMT,
CREATE_medidas_STMT,
CREATE_medparte_STMT,
CREATE_metas_STMT,
CREATE_modrefeicao_STMT,
CREATE_nacionalidade_STMT,
CREATE_nt3_ei_STMT,
CREATE_nt3_pe_STMT,
CREATE_nt3_pi_STMT,
CREATE_nut_STMT,
CREATE_nutconv_STMT,
CREATE_nutord_STMT,
CREATE_objvis_STMT,
CREATE_opcoes_STMT,
CREATE_ovcursor_STMT,
CREATE_pastas_STMT,
CREATE_pesqtemp_STMT,
CREATE_pesscomp_STMT,
CREATE_pessoa_STMT,
CREATE_preparac_STMT,
CREATE_profissao_STMT,
CREATE_pt3_ei_STMT,
CREATE_rda_STMT,
CREATE_rdafaixas_STMT,
CREATE_rdagn_STMT,
CREATE_refcalcali_STMT,
CREATE_refeicao_STMT,
CREATE_semaforo_STMT,
CREATE_sexo_STMT,
CREATE_sxagebdy_STMT,
CREATE_t1_STMT,
CREATE_t10_STMT,
CREATE_t11_STMT,
CREATE_t12_STMT,
CREATE_t13_STMT,
CREATE_t14_STMT,
CREATE_t15_STMT,
CREATE_t16_STMT,
CREATE_t17_STMT,
CREATE_t18_STMT,
CREATE_t19_STMT,
CREATE_t2_STMT,
CREATE_t20_STMT,
CREATE_t22_STMT,
CREATE_t23_STMT,
CREATE_t24_STMT,
CREATE_t25_STMT,
CREATE_t26_STMT,
CREATE_t27_STMT,
CREATE_t28_STMT,
CREATE_t29_STMT,
CREATE_t31_STMT,
CREATE_t32_STMT,
CREATE_t33_STMT,
CREATE_t3_ei_STMT,
CREATE_t3_pe_STMT,
CREATE_t3_pi_STMT,
CREATE_t4_STMT,
CREATE_t5_STMT,
CREATE_t6_STMT,
CREATE_t7_STMT,
CREATE_t7a_STMT,
CREATE_t8_STMT,
CREATE_t9_STMT,
CREATE_tambso_STMT,
CREATE_tcondica_STMT,
CREATE_tdescritor_STMT,
CREATE_teccp_STMT,
CREATE_telefone_STMT,
CREATE_tfuncao_STMT,
CREATE_tgebhb_STMT,
CREATE_tipoanam_STMT,
CREATE_tipoexa_STMT,
CREATE_tmedida_STMT,
CREATE_tpdcs_STMT,
CREATE_ttabela_STMT,
CREATE_usda_food_des_STMT,
CREATE_usda_nutr_def_STMT,
CREATE_usuarios_STMT,
CREATE_validade_STMT,
CREATE_viewer_STMT,
CREATE_vista_STMT);


CREATE_STMT_MAP : ARRAY[0..134, 0..1] of String= (
('adeq',CREATE_ADEQ_STMT),
('aliconv',CREATE_aliconv_STMT),
('alifreq',CREATE_alifreq_STMT),
('aligcal',CREATE_aligcal_STMT),
('aligprot',CREATE_aligprot_STMT),
('alimento',CREATE_alimento_STMT),
('alinut',CREATE_alinut_STMT),
('aliorg',CREATE_aliorg_STMT),
('alipreco',CREATE_alipreco_STMT),
('anamnese',CREATE_anamnese_STMT),
('antrops',CREATE_antrops_STMT),
('areaclic',CREATE_areaclic_STMT),
('areavist',CREATE_areavist_STMT),
('ativfis',CREATE_ativfis_STMT),
('cachedic',CREATE_cachedic_STMT),
('cadpastas',CREATE_cadpastas_STMT),
('calcali',CREATE_calcali_STMT),
('ccsisdic',CREATE_ccsisdic_STMT),
('cidade',CREATE_cidade_STMT),
('classetariageral',CREATE_classetariageral_STMT),
('cnut',CREATE_cnut_STMT),
('cnut_pf',CREATE_cnut_pf_STMT),
('conversaobd',CREATE_conversaobd_STMT),
('cor',CREATE_cor_STMT),
('cursores',CREATE_cursores_STMT),
('descranges',CREATE_descranges_STMT),
('dicas',CREATE_dicas_STMT),
('dietas',CREATE_dietas_STMT),
('dscrfnt',CREATE_dscrfnt_STMT),
('dscrnumval',CREATE_dscrnumval_STMT),
('dscrparm',CREATE_dscrparm_STMT),
('dscrqntv',CREATE_dscrqntv_STMT),
('dscrtrs',CREATE_dscrtrs_STMT),
('dscrvalues',CREATE_dscrvalues_STMT),
('endereco',CREATE_endereco_STMT),
('estado',CREATE_estado_STMT),
('exapess',CREATE_exapess_STMT),
('faixaetaria',CREATE_faixaetaria_STMT),
('galical',CREATE_galical_STMT),
('galiprot',CREATE_galiprot_STMT),
('gruali',CREATE_gruali_STMT),
('grucal',CREATE_grucal_STMT),
('gruprot',CREATE_gruprot_STMT),
('help',CREATE_help_STMT),
('helpfiles',CREATE_helpfiles_STMT),
('inqaf',CREATE_inqaf_STMT),
('inqueritos',CREATE_inqueritos_STMT),
('instrucao',CREATE_instrucao_STMT),
('itensali',CREATE_itensali_STMT),
('listarefeicao',CREATE_listarefeicao_STMT),
('macronut',CREATE_macronut_STMT),
('medcorpo',CREATE_medcorpo_STMT),
('meddesc',CREATE_meddesc_STMT),
('medidacaseira',CREATE_medidacaseira_STMT),
('medidas',CREATE_medidas_STMT),
('medparte',CREATE_medparte_STMT),
('metas',CREATE_metas_STMT),
('modrefeicao',CREATE_modrefeicao_STMT),
('nacionalidade',CREATE_nacionalidade_STMT),
('nt3_ei',CREATE_nt3_ei_STMT),
('nt3_pe',CREATE_nt3_pe_STMT),
('nt3_pi',CREATE_nt3_pi_STMT),
('nut',CREATE_nut_STMT),
('nutconv',CREATE_nutconv_STMT),
('nutord',CREATE_nutord_STMT),
('objvis',CREATE_objvis_STMT),
('opcoes',CREATE_opcoes_STMT),
('ovcursor',CREATE_ovcursor_STMT),
('pastas',CREATE_pastas_STMT),
('pesqtemp',CREATE_pesqtemp_STMT),
('pesscomp',CREATE_pesscomp_STMT),
('pessoa',CREATE_pessoa_STMT),
('preparac',CREATE_preparac_STMT),
('profissao',CREATE_profissao_STMT),
('pt3_ei',CREATE_pt3_ei_STMT),
('rda',CREATE_rda_STMT),
('rdafaixas',CREATE_rdafaixas_STMT),
('rdagn',CREATE_rdagn_STMT),
('refcalcali',CREATE_refcalcali_STMT),
('refeicao',CREATE_refeicao_STMT),
('semaforo',CREATE_semaforo_STMT),
('sexo',CREATE_sexo_STMT),
('sxagebdy',CREATE_sxagebdy_STMT),
('t1',CREATE_t1_STMT),
('t10',CREATE_t10_STMT),
('t11',CREATE_t11_STMT),
('t12',CREATE_t12_STMT),
('t13',CREATE_t13_STMT),
('t14',CREATE_t14_STMT),
('t15',CREATE_t15_STMT),
('t16',CREATE_t16_STMT),
('t17',CREATE_t17_STMT),
('t18',CREATE_t18_STMT),
('t19',CREATE_t19_STMT),
('t2',CREATE_t2_STMT),
('t20',CREATE_t20_STMT),
('t22',CREATE_t22_STMT),
('t23',CREATE_t23_STMT),
('t24',CREATE_t24_STMT),
('t25',CREATE_t25_STMT),
('t26',CREATE_t26_STMT),
('t27',CREATE_t27_STMT),
('t28',CREATE_t28_STMT),
('t29',CREATE_t29_STMT),
('t31',CREATE_t31_STMT),
('t32',CREATE_t32_STMT),
('t33',CREATE_t33_STMT),
('t3_ei',CREATE_t3_ei_STMT),
('t3_pe',CREATE_t3_pe_STMT),
('t3_pi',CREATE_t3_pi_STMT),
('t4',CREATE_t4_STMT),
('t5',CREATE_t5_STMT),
('t6',CREATE_t6_STMT),
('t7',CREATE_t7_STMT),
('t7a',CREATE_t7a_STMT),
('t8',CREATE_t8_STMT),
('t9',CREATE_t9_STMT),
('tambso',CREATE_tambso_STMT),
('tcondica',CREATE_tcondica_STMT),
('tdescritor',CREATE_tdescritor_STMT),
('teccp',CREATE_teccp_STMT),
('telefone',CREATE_telefone_STMT),
('tfuncao',CREATE_tfuncao_STMT),
('tgebhb',CREATE_tgebhb_STMT),
('tipoanam',CREATE_tipoanam_STMT),
('tipoexa',CREATE_tipoexa_STMT),
('tmedida',CREATE_tmedida_STMT),
('tpdcs',CREATE_tpdcs_STMT),
('ttabela',CREATE_ttabela_STMT),
('usda_food_des',CREATE_usda_food_des_STMT),
('usda_nutr_def',CREATE_usda_nutr_def_STMT),
('usuarios',CREATE_usuarios_STMT),
('validade',CREATE_validade_STMT),
('viewer',CREATE_viewer_STMT),
('vista_STMT)',CREATE_vista_STMT));

implementation
end.
