// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TNewDic                                         }
{                                                                    }
{   Dicionario pra nutricao                                          }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file                                       }
{    d:\delp20\delphi 2.0\ocx\ocxdcn\dicnut.cd                       }
{   on 26 Aug 1997 at 13:11                                          }
{                                                                    }
{   Copyright © 1997 by ...                                          }
{                                                                    }
{ ****************************************************************** }

unit DicNut;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls,
     Forms, Graphics, OCXDCNLib_TLB, dbtables,Dialogs,db;

type
  TListaTipoDic = ( ltCode, ltDescription );

  TNewDic = class(TDicionario)
    private
      { Private fields of TNewDic }
      { Private methods of TNewDic }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;

    protected
      { Protected fields of TNewDic }
        DeepList : TStringList;
        MaximoNiveis: integer;
      { Protected methods of TNewDic }
        procedure Loaded; override;

    public
      { Public fields and properties of TNewDic }

      { Public methods of TNewDic }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function CollectListInstances (Code : string; var ListaFilhos: TStringList; ListaTipo: TListaTipoDic = ltDescription): boolean; virtual;
        function CollectAllInstances (Code : string; var Instancias: TStringList): boolean;
        function FindROOTPath (code:string; var ROOTPath: TStringList) : boolean; virtual;
        function GetLowestAncestor ( FirstCode, SecondCode: string; var CommonAncestor : string) : integer; virtual;
        function GetFarParents (FirstCode, SecondCode: string; var Parent1, Parent2: string) : integer; virtual;
        function ListAll( Code : String; var AllInstances: TStringList ) : boolean;
        procedure ClearDeepList;
    published
      { Published properties of the component }
  end;

  TAttributedDic = class(TNewDic)
    private
      { Private fields of TNewDic }

    protected
      { Protected fields of TNewDic }
        AuxTab : TTable;
    public
      { Public fields and properties of TNewDic }
        function GetAttributeByCode (Code : WideString; AttributeName: string; var Attribute : string) : boolean;
      { Public methods of TNewDic }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
  end;

  TCacheDic = class(TAttributedDic)
    private
      { Private fields of TNewDic }
      FCached : Boolean;
      FActiveCache : Boolean;

    protected
      { Protected fields of TNewDic }
        Cache1Tab : TTable;
        Cache2Tab : TTable;

        procedure SetActiveCache( Value : Boolean );
    public
      { Public fields and properties of TNewDic }
        property Cached : Boolean read FCached;
      { Public methods of TNewDic }
        function ListAll( Code : String; var AllInstances: TStringList ) : boolean;
        function CollectAllInstances (Code : string; var Instancias: TStringList): boolean;
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
    published
       property ActiveCache : Boolean read FActiveCache write SetActiveCache;
  end;


procedure Register;

implementation

procedure Register;
begin
     { Register TNewDic with Samples as its
       default page on the Delphi component palette }
     RegisterComponents('Dicionario', [TNewDic]);
     RegisterComponents('Dicionario', [TAttributedDic]);
     RegisterComponents('Dicionario', [TCacheDic]);
end;

{ Method to set variable and property values and create objects }
procedure TNewDic.AutoInitialize;
begin
DeepList:=TStringList.Create;
end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TNewDic.AutoDestroy;
begin
DeepList.Free;
end; { of AutoDestroy }

constructor TNewDic.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TNewDic.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TNewDic.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;


//Pesquisa e constroi uma lista sem repetições de todas as instancias (folhas)
//da árvore embaixo do galho pasado como código
//Esta rotina é recursiva e verifica que não pase duas vezes pelo mesmo código
//Isto é para prevenir travamentos por causa de listas mal construidas
//A pesquisa é por profundidade
function TNewDic.CollectAllInstances (Code : string; var Instancias: TStringList): boolean;
var
ListaFilhos: TStringList;
SonCount: smallint;
Codigo, Descricao: WideString;
Index : integer;
begin

{********************** Desativando, pois estava dando problemas
//Esta lista mantam os codigos navegados em profundidade
//Se pasamos duas vezes pelo mesmo codigo (tem repetição)
//quer dizer que a tabela esta furada
if DeepList.Find (Code,Index) then
   begin
   //Estamos com problemas. Já pasamos por este código antes.
   //Limpa a lista
   DeepList.clear;
   //Sai com erro
   Result:=False;
   exit;
   end
else
***************************************************************}
    //Ok. Adicione o codigo
    DeepList.Add (Code);

//Verifica a quantidade máxima de níveis
if DeepList.Count > MaximoNiveis then MaximoNiveis:=DeepList.Count;

//Lista auxiliar
ListaFilhos:=TStringList.Create;

Codigo := Code;
//Expande o codigo recebido
if (ExpandCode (Codigo, SonCount)) then
    begin
    //Monta a lista auxiliar de todos os filhos que tem este código
    GetFirstSon( Codigo, Descricao);
    ListaFilhos.Insert(0, Codigo);
    while (GetNextBrother(Codigo, Descricao)) do
          ListaFilhos.Insert(0, Codigo);

    //Depois de construir a lista de filhos, percorre ele um
    //por um, coletando as instancias deles.
    while SonCount <>0 do
          begin
          //Se um filho tem netos, colecta as instancias dele (recursão)
          if HasChilds(ListaFilhos [SonCount-1]) then
             begin
             if not CollectAllInstances ( ListaFilhos [SonCount-1],Instancias) then
                begin
                //Libera a lista auxiliar
                ListaFilhos.Free;
                Result:=False;
                exit
                end;
             end
          else
             begin
             //Senão, é uma folha (instancia). Adiciona ela na lista.
             if Instancias.IndexOf ( ListaFilhos[SonCount-1])=-1 then
                Instancias.Add (ListaFilhos[SonCount-1]);
             end;
          SonCount:=SonCount-1;
          end;
    end;
//Libera a lista auxiliar
ListaFilhos.Free;
Result:=True;
//Apaga o codigo da lista de profundidade
if DeepList.Find (Code,Index) then DeepList.Delete (Index);
end;

//Constroi uma lista de codigos que representa o cminho ate o ROOT
//O promeiro elemento do array ([0]), é o ROOT e o último ([n]), é o codigo
//pasado para pesquisa
function TNewDic.FindROOTPath (code:string;var ROOTPath: TStringList) : boolean;

var
 Index: integer;
 DADsCount: SmallInt;
 SonCode, FirstFatherCode: WideString;
begin
SonCode:=code;

//Limpa a lista
ROOTPath.clear;

//Insere o proprio como ultimo elemento da lista
ROOTPath.Insert (0,SonCode);

//Procura o primeiro pai
DADsCount:=FindParents(SonCode,FirstFatherCode);

 while (DADsCount > 0) do
       begin
       //Verifica que a arvore nao tem heranca multipla.
       //Este metodo nao funciona em codigos que tem mais de um pai.
       if DADsCount > 1 then
          begin
          Result:=False;
          exit;
          end;

       //Verifica que a tabela de pais e filhos nao tem erros
       //Quer dizer, checa se nao esta pasando de novo pelo mesmo lugar
       if (ROOTPath.Find (FirstFatherCode,Index)) then
          begin
          Result:=False;
          exit;
          end
       else
          ROOTPath.Insert (0,FirstFatherCode);
       SonCode:=FirstFatherCode;

       //Procura o proximo pai
       DADsCount:=FindParents(SonCode,FirstFatherCode);

       end;

Result:=True;
end;

//Obtem o ancestro comum entre dosi codigos
function TNewDic.GetLowestAncestor (FirstCode, SecondCode: string; var CommonAncestor: string) : integer;
var
FirstPath,SecondPath : TStringList;
MinIndex, Index: integer;
begin
//Listas que armazenam a rota ate o ROOT
FirstPath:=TStringList.Create;
SecondPath:=TStringList.Create;

//Pega a rota ate o ROOT
FindROOTPath (FirstCode, FirstPath);
FindROOTPath (SecondCode, SecondPath);


// find the shortest path
if (FirstPath.Count < SecondPath.Count) then
   MinIndex := FirstPath.Count - 1
else
    MinIndex := SecondPath.Count - 1;

Index:=0;

//* find the LCA node */
while (Index <= MinIndex) do
      begin
      if (FirstPath[Index] = SecondPath[Index]) then
         begin
         //O ancestro em comum
         CommonAncestor:= FirstPath[Index];
         Index:=Index+1
         end

      else
         break;
      end;

//Se o index é um, quer dizer que sao filhos de deus, por isso sao irmaos
//mais pertencem a familias diferentes
if Index=1 then
   Result:=-1
else
    //A relacao de parentesco
    Result:=(FirstPath.Count - Index) * (SecondPath.Count - Index);

end;

//Procura o ancestro em comum e retorna os dois primeiros filhos dele (irmãos )
//que correspondem a linha direta dos códigos pasados
function TNewDic.GetFarParents (FirstCode, SecondCode: string; var Parent1, Parent2: string) : integer;
var
FirstPath,SecondPath : TStringList;
MinIndex, Index: integer;
begin
//Listas que armazenam a rota ate o ROOT
FirstPath:=TStringList.Create;
SecondPath:=TStringList.Create;

//Pega a rota ate o ROOT
FindROOTPath (FirstCode, FirstPath);
FindROOTPath (SecondCode, SecondPath);


// find the shortest path
if (FirstPath.Count < SecondPath.Count) then
   MinIndex := FirstPath.Count - 1
else
    MinIndex := SecondPath.Count - 1;

Index:=0;

//* find the LCA node */
while (Index <= MinIndex) do
      begin
      //Os dois primeiros irmaos
      Parent1:= FirstPath[Index];
      Parent2:= SecondPath [Index];
      if (FirstPath[Index] = SecondPath[Index]) then
         begin
         Index:=Index+1
         end

      else
         break;
      end;

//Se o index é um, quer dizer que sao filhos de deus, porisso sao irmaos
//mais pertencem a familias diferentes
if Index=1 then
   Result:=-1
else
    //A relacao de parentesco
    Result:=(FirstPath.Count - Index) * (SecondPath.Count - Index);

end;

//Pesquisa e constroi uma lista de todos os pais e filhos, na ordem de navegação
// da direita para esquerda e de cima pra baixo,
//da árvore embaixo do galho pasado como código
//Esta rotina é recursiva e verifica que não pase duas vezes pelo mesmo código
//Isto é para prevenir travamentos por causa de listas mal construidas
//A pesquisa é por profundidade
function TNewDic.ListAll( Code : String; var AllInstances: TStringList ) : boolean;
var
   ListaFilhos: TStringList;
   SonCount: smallint;
   Codigo, Descricao: WideString;
   Index : integer;
begin

{*************************** Desativando, pois estava dando problemas
   //Esta lista mantam os codigos navegados em profundidade
   //Se pasamos duas vezes pelo mesmo codigo (tem repetição)
   //quer dizer que a tabela esta furada
   if DeepList.Find (Code,Index) then
      begin
         //Estamos com problemas. Já pasamos por este código antes.
         //Limpa a lista
         DeepList.clear;
         //Sai com erro
         Result:=False;
         exit;
      end
   else
**********************************************************************}
      //Ok. Adicione o codigo
      DeepList.Add (Code);

   //Verifica a quantidade máxima de níveis
   if DeepList.Count > MaximoNiveis then MaximoNiveis:=DeepList.Count;

   //Lista auxiliar
   ListaFilhos:=TStringList.Create;

   //Expande o codigo recebido
   Codigo := Code;
   if (ExpandCode (Codigo, SonCount)) then
      begin
          //Monta a lista auxiliar de todos os filhos que tem este código
          GetFirstSon( Codigo, Descricao);
          ListaFilhos.Insert(0, Codigo);
          while (GetNextBrother(Codigo, Descricao)) do
                ListaFilhos.Insert(0, Codigo);

          //Depois de construir a lista de filhos, percorre ele um
          //por um, coletando as instancias deles.
          while SonCount <>0 do
             begin
                //Se um filho tem netos, colecta as instancias dele (recursão)
                if HasChilds(ListaFilhos [SonCount-1]) then
                   begin
                     // Pega primeira instancia da lista.
                     AllInstances.Add(ListaFilhos [SonCount-1]);
                     if not ListAll(ListaFilhos [SonCount-1], AllInstances) then
                        begin
                           //Libera a lista auxiliar
                           ListaFilhos.Free;
                           Result:=False;
                           exit
                        end;
                   end
                else
                   begin
                      //Senão, é uma folha (instancia).
                      AllInstances.Add(ListaFilhos [SonCount-1]);
                   end;
                SonCount:=SonCount-1;
             end;
      end;

   //Libera a lista auxiliar
   ListaFilhos.Free;
   Result:=True;
   //Apaga o codigo da lista de profundidade
   if DeepList.Find (Code,Index) then DeepList.Delete (Index);
end;

function TNewDic.CollectListInstances (Code : string; var ListaFilhos: TStringList; ListaTipo: TListaTipoDic = ltDescription): boolean;
var
   Codigo, Descricao: WideString;
   SonCount : smallint;
begin
   Result := True;

   //Lista auxiliar
//   ListaFilhos:=TStringList.Create;

   //Expande o codigo recebido
   Codigo := Code;
   if (ExpandCode (Codigo, SonCount)) then
      begin
          //Monta a lista auxiliar de todos os filhos que tem este código
          GetFirstSon( Codigo, Descricao);
          if ListaTipo = ltDescription then
             ListaFilhos.Insert(0, Descricao)
          else
             ListaFilhos.Insert(0, Codigo);
          while (GetNextBrother(Codigo, Descricao)) do
              if ListaTipo = ltDescription then
                ListaFilhos.Insert(0, Descricao)
              else
                ListaFilhos.Insert(0, Codigo);
      end
   else
      Result:=False;
end;

procedure TNewDic.ClearDeepList;
begin
   DeepList.Clear;
end;

{ TAttributedDic }

constructor TAttributedDic.Create(AOwner: TComponent);
begin
inherited;
AuxTab := TTable.Create (self);
end;

destructor TAttributedDic.Destroy;
begin
AuxTab.Free;
inherited;
end;

function TAttributedDic.GetAttributeByCode(Code: WideString;
  AttributeName: string; var Attribute: string): boolean;
begin

with AuxTab do
  begin
    if not Active then
    try
    { First try to use an alias }
      if DataSourceName <> '' then
         begin
         DatabaseName := DataSourceName;
         TableName := SiglaDicionario;
         Active := True;
         end;
    except
      on E:EDatabaseError do
      { If that fails, try to use the drive and directory }
      ShowMessage ('Erro 2114: ' + E.Message  + DataSourceName + ' - ' +SiglaDicionario);
    end;

    if Locate ('cod_'+SiglaDicionario,Code,[])then
       begin
       Attribute:=FieldByName(AttributeName).AsString;
       Result:=True;
       end
    else
       begin
       Attribute:='';
       Result:=False;
       end;

  end;
end;

{ TCacheDic }

constructor TCacheDic.Create(AOwner: TComponent);
begin
inherited;
Cache1Tab := TTable.Create (self);
Cache2Tab := TTable.Create (self);
ActiveCache := False;
end;

destructor TCacheDic.Destroy;
begin
Cache1Tab.Free;
Cache2Tab.Free;
inherited;
end;

// Coleta as instancias de TMedidas
function TCacheDic.ListAll( Code : String; var AllInstances: TStringList ) : boolean;
begin

with Cache1Tab do
  begin
    if not Active then
    try
    { First try to use an alias }
      if DataSourceName <> '' then
         begin
         DatabaseName := DataSourceName;
         TableName := SiglaDicionario + '_PF';
         IndexName := SiglaDicionario + '_PF1';
         ReadOnly := True;
         Active := True;
         end;
    except
      on E: EDatabaseError do
      { If that fails, try to use the drive and directory }
      ShowMessage ('Erro 2115: ' + E.Message  + DataSourceName );
    end;
    Filter := 'CODPAI_' + SiglaDicionario + ' = ''' + Code + ''' AND MEDIDA_' + SiglaDicionario + ' = ''T'' ';;
    Filtered := True;
    if IsEmpty or not ActiveCache then
      begin
       Result:=inherited ListAll(Code, AllInstances);
       FCached := False;
      end
    else
       begin
          while not EOF do
             begin
                AllInstances.Add( FieldByName( 'CODFILHO_' + SiglaDicionario ).AsString );
                Next;
             end;
          Result:=True;
          FCached := True;
       end;
  end;

end;

function TCacheDic.CollectAllInstances (Code : string; var Instancias: TStringList): boolean;
begin

with Cache2Tab do
  begin
    if not Active then
    try
    { First try to use an alias }
      if DataSourceName <> '' then
         begin
         DatabaseName := DataSourceName;
         TableName := SiglaDicionario + '_PF';
         IndexName := SiglaDicionario + '_PF1';
         ReadOnly := True;
         Active := True;
         end;
    except
      on E:EDatabaseError do
      { If that fails, try to use the drive and directory }
      ShowMessage ('Erro 2116: ' + E.Message  + DataSourceName );
    end;
    Close;
    Filter := 'CODPAI_' + SiglaDicionario + ' = ''' + Code + ''' AND MEDIDA_' + SiglaDicionario + ' = ''T'' ';
    Filtered := True;
    Open;
    if IsEmpty or not ActiveCache then
       begin
       ClearDeepList;
       Result:=inherited CollectAllInstances(Code, Instancias);
       FCached := False;
       end
    else
       begin
          while not EOF do
             begin
                Instancias.Add( FieldByName( 'CODFILHO_' + SiglaDicionario ).AsString );
                Next;
             end;
          Result:=True;
          FCached := True;
       end;
  end;

end;

procedure TCacheDic.SetActiveCache(Value: Boolean);
begin
   FActiveCache := Value;
   FCached := Value;
end;

end.
