;; NutWin - Programa de Apoio a Nutrição(R)
;; Copyright (C) 2002-2010 Departamento de Informática em Saúde
;; Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
;;
;; This file is part of NutWin.
;;
;; NutWin is free software:  you  can  redistribute  it  and/or
;; modify it under the terms of the GNU General Public  License
;; as published by the Free Software Foundation, either version
;; 3 of the License, or (at your option) any later version.
;;
;; Nutwin is distributed in the hope that it  will  be  useful,
;; but WITHOUT ANY WARRANTY; without even the implied  warranty
;; of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
;; the GNU General Public License for more details.
;;
;; You should have received a copy of the  GNU  General  Public
;; License along with Foobar.
;; If not, see <http://www.gnu.org/licenses/>.

; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MySQL Connector/ODBC"
#define MyAppVerName "MySQL Connector/ODBC 3.51"
#define MyAppPublisher "MySQL AB"
#define MyAppURL "http://www.mysql.com"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{90E878AD-A263-468C-A51E-4996283369A7}
AppName={#MyAppName}
AppVerName={#MyAppVerName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: english; MessagesFile: compiler:Default.isl
Name: brazilianportuguese; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

[Files]
Source: C:\SVNRepository\sourceforge\installer\ScriptFiles\MyODBCConnector\mysql-connector-odbc-noinstall-5.1.6-win32\*; DestDir: {win}; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


Source: SourceFiles\components\MySQL\*; DestDir: {tmp}; Flags: deleteafterinstall


[Run]
Filename: msiexec.exe; Parameters: "/qb /i  ""{tmp}\mysql-connector-odbc-3.51.27-win32.msi"""; WorkingDir: {tmp}; StatusMsg: Instalando MySQL Connector/ODBC 3.51; Flags: waituntilterminated


[Registry]
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\ODBC Data Sources; ValueType: string; ValueName: My_NutWin-1.6; ValueData: MySQL ODBC 3.51 Driver; Flags: createvalueifdoesntexist uninsdeletevalue
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6; Flags: uninsdeletekey createvalueifdoesntexist
Root: HKLM; SubKey: Software\ODBC\ODBC.INI\My_NutWin-1.6; ValueType: string; ValueName: Driver; ValueData: C:\WINDOWS\system32\myodbc3.dll; Flags: createvalueifdoesntexist uninsdeletevalue
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6; ValueType: string; ValueName: DATABASE; ValueData: MyNutWin; Flags: createvalueifdoesntexist uninsdeletevalue
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6; ValueType: string; ValueName: DESCRIPTION; ValueData: NutWin ODBC Data Source; Flags: createvalueifdoesntexist uninsdeletevalue
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6; ValueType: string; ValueName: PWD; ValueData: masterkey; Flags: createvalueifdoesntexist uninsdeletevalue
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6; ValueType: string; ValueName: SERVER; ValueData: localhost; Flags: createvalueifdoesntexist uninsdeletevalue
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6; ValueType: string; ValueName: UID; ValueData: root; Flags: createvalueifdoesntexist uninsdeletevalue
