// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TFormula                                        }
{                                                                    }
{   Descreve formulas                                                }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file c:\projeto\nutwin\temp\uformula.cd    }
{   on 15 July 1997 at 9:16                                          }
{                                                                    }
{   Copyright © 1997 by Equipe de Nutrição - DIS-EPM/UNIFESP         }
{                                                                    }
{ ****************************************************************** }

unit Formula;

interface

uses Classes, Measurement, Parser10;

type

   TFormula = class(TComponent)
   private
      FDescricao : String;
      FSimbolo : String;
      FData : String;
      FFormula : String;
      FA : TMedida;
      FB : TMedida;
      FC : TMedida;
      FD : TMedida;
      FE : TMedida;
      Ft : TMedida;
      FX : TMedida;
      FY : TMedida;
      FResultado : TMedida;
    FAceitaParametrosInvalidos: Boolean;
      function GetDescricao : String;
      procedure SetDescricao(Value : String);
      function GetSimbolo : String;
      procedure SetSimbolo(Value : String);
      function GetData : String;
      procedure SetData(Value : String);
      function GeTFormula : String;
      procedure SeTFormula(Value : String);
      function GetA : TMedida;
      procedure SetA(Value : TMedida);
      function GetB : TMedida;
      procedure SetB(Value : TMedida);
      function GetC : TMedida;
      procedure SetC(Value : TMedida);
      function GetD : TMedida;
      procedure SetD(Value : TMedida);
      function GetE : TMedida;
      procedure SetE(Value : TMedida);
      function Gett : TMedida;
      procedure Sett(Value : TMedida);
      function GetX : TMedida;
      procedure SetX(Value : TMedida);
      function GetY : TMedida;
      procedure SetY(Value : TMedida);
      function GetResultado : TMedida;
      procedure SetResultado(Value : TMedida);
    procedure SetAceitaParametrosInvalidos(const Value: Boolean);
   protected
      procedure Loaded; override;
   public
      procedure LimparParametros;
      procedure Notification(AComponent : TComponent; Operation : TOperation); override;
      constructor Create(AOwner: TComponent); override;
      destructor Destroy; override;
      function Execute : Boolean;
   published
      property Descricao : String read GetDescricao write SetDescricao;
      property Simbolo : String read GetSimbolo write SetSimbolo;
      property Data : String read GetData write SetData;
      property A : TMedida read GetA write SetA;
      property B : TMedida read GetB write SetB;
      property C : TMedida read GetC write SetC;
      property D : TMedida read GetD write SetD;
      property E : TMedida read GetE write SetE;
      property t : TMedida read Gett write Sett;
      property X : TMedida read GetX write SetX;
      property Y : TMedida read GetY write SetY;
      property Formula : String read GeTFormula write SeTFormula;
      property Resultado : TMedida read GetResultado write SetResultado;
      property AceitaParametrosInvalidos : Boolean read FAceitaParametrosInvalidos write SetAceitaParametrosInvalidos;
   end;

procedure Register;

implementation

procedure Register;
begin
   RegisterComponents('Calculadora', [TFormula]);
end;

function TFormula.GetDescricao : String;
begin
   Result := FDescricao
end;

procedure TFormula.SetDescricao(Value : String);
begin
   FDescricao := Value;
end;

function TFormula.GetSimbolo : String;
begin
   Result := FSimbolo
end;

procedure TFormula.SetSimbolo(Value : String);
begin
   FSimbolo := Value;
end;

function TFormula.GetData : String;
begin
   Result := FData
end;

procedure TFormula.SetData(Value : String);
begin
   FData := Value;
end;

function TFormula.GeTFormula : String;
begin
   Result := FFormula
end;

procedure TFormula.SeTFormula(Value : String);
begin
   FFormula := Value;
end;

function TFormula.GetA : TMedida;
begin
   Result := FA;
end;

procedure TFormula.SetA(Value : TMedida);
begin
   FA := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TFormula.GetB : TMedida;
begin
   Result := FB;
end;

procedure TFormula.SetB(Value : TMedida);
begin
   FB := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TFormula.GetC : TMedida;
begin
   Result := FC;
end;

procedure TFormula.SetC(Value : TMedida);
begin
   FC := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TFormula.GetD : TMedida;
begin
   Result := FD;
end;

procedure TFormula.SetD(Value : TMedida);
begin
   FD := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TFormula.GetE : TMedida;
begin
   Result := FE;
end;

procedure TFormula.SetE(Value : TMedida);
begin
   FE := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TFormula.Gett : TMedida;
begin
   Result := Ft;
end;

procedure TFormula.Sett(Value : TMedida);
begin
   Ft := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TFormula.GetX : TMedida;
begin
   Result := FX;
end;

procedure TFormula.SetX(Value : TMedida);
begin
   FX := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TFormula.GetY : TMedida;
begin
   Result := FY;
end;

procedure TFormula.SetY(Value : TMedida);
begin
   FY := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TFormula.GetResultado : TMedida;
begin
   Result := FResultado
end;

procedure TFormula.SetResultado(Value : TMedida);
begin
   FResultado := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

constructor TFormula.Create(AOwner: TComponent);
begin
   inherited Create(AOwner);
end;

destructor TFormula.Destroy;
begin
  inherited Destroy;
end;

procedure TFormula.Loaded;
begin
   inherited Loaded;
end;

function TFormula.Execute : Boolean;
var
   psFmla : TParser;
begin
// Cria parser para calculo
psFmla := TParser.Create(self);
try
   Result := True; // define que o calculo é possivel e deu certo
   // Atribui os parâmetros se existirem e se forem válidos
   if ( FA <> nil ) then
   begin
      if FA.Valid or FAceitaParametrosInvalidos then
         psFmla.A := FA.AsFloat
      else
         Result := False;
   end;
   if ( FB <> nil ) then
   begin
      if FB.Valid or FAceitaParametrosInvalidos then
         psFmla.B := FB.AsFloat
      else
         Result := False;
   end;
   if ( FC <> nil ) then
   begin
      if FC.Valid or FAceitaParametrosInvalidos then
         psFmla.C := FC.AsFloat
      else
         Result := False;
   end;
   if ( FD <> nil ) then
   begin
      if FD.Valid or FAceitaParametrosInvalidos then
         psFmla.D := FD.AsFloat
      else
         Result := False;
   end;
   if ( FE <> nil ) then
   begin
      if FE.Valid or FAceitaParametrosInvalidos then
         psFmla.E := FE.AsFloat
      else
         Result := False;
   end;
   if ( Ft <> nil ) then
   begin
      if Ft.Valid or FAceitaParametrosInvalidos then
         psFmla.t := Ft.AsFloat
      else
         Result := False;
   end;
   if ( FX <> nil ) then
   begin
      if FX.Valid or FAceitaParametrosInvalidos then
         psFmla.X := FX.AsFloat
      else
         Result := True;
   end;
   if ( FY <> nil ) then
   begin
      if FY.Valid or FAceitaParametrosInvalidos then
         psFmla.Y := FY.AsFloat
      else
         Result := True;
   end;
   // Todos os parâmetro são válidos?
   if Result then
   begin
      // Calcula!
      psFmla.Expression := Formula;
      // Se existe uma variável para o resultado
      if ( Resultado <> nil ) then
         begin
           Resultado.AsFloat :=  psFmla.Value;
           Resultado.Valid := True;
           Result := True;
        end
     else
        Result := False; // Esqueceram de passar uma variável de resultado
  end
  else // algum parâmetro é invalido (já está Result := Tru)
  begin
     // seta que o resultado (se existir) é inválido (MUITO IMPORTANTE)
     if Resultado <> nil then
        Resultado.Valid := False;
  end;
finally
  psFmla.Free;
end;
end;

procedure TFormula.LimparParametros;
begin
   A := nil;
   B := nil;
   C := nil;
   D := nil;
   E := nil;
   t := nil;
   X := nil;
   Y := nil;
end;

procedure TFormula.Notification(AComponent: TComponent;
  Operation: TOperation);
begin
   inherited Notification(AComponent, Operation);
   if Operation <> opRemove then
      Exit;
   if AComponent = FA then
      FA := nil
   else if AComponent = FB then
      FB := nil
   else if AComponent = FC then
      FC := nil
   else if AComponent = FD then
      FD := nil
   else if AComponent = FE then
      FE := nil
   else if AComponent = Ft then
      Ft := nil
   else if AComponent = FX then
      FX := nil
   else if AComponent = FY then
      FY := nil;
end;

procedure TFormula.SetAceitaParametrosInvalidos(const Value: Boolean);
begin
  FAceitaParametrosInvalidos := Value;
end;

end.
