// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TDataIdade                                      }
{                                                                    }
{   Gera a partir de duas datas, a idade.                            }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from untitled component definition                     }
{   on 25 July 1997 at 11:09                                         }
{                                                                    }
{   Copyright © 1997 by Nutrição - CIS-EPM...                                          }
{                                                                    }
{ ****************************************************************** }

unit UDIdade;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls, 
     Forms, Graphics, StdCtrls, Dialogs;

type
  TDataIdade = class(TComponent)
    private
      { Private fields of TDataIdade }
        { Storage for property Dia }
        FDia : TCustomEdit;
        { Storage for property DataInicio }
        FDataInicio : TCustomEdit;
        { Storage for property DataFinal }
        FDataFinal : TCustomEdit;
        { Storage for property Mes }
        FMes : TCustomEdit;
        { Storage for property Ano }
        FAno : TCustomEdit;

      { Private methods of TDataIdade }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        { Read method for property Dia }
        function GetDia : TCustomEdit;
        { Write method for property Dia }
        procedure SetDia(Value : TCustomEdit);
        { Read method for property DataInicio }
        function GetDataInicio : TCustomEdit;
        { Write method for property DataInicio }
        procedure SetDataInicio(Value : TCustomEdit);
        { Read method for property DataFinal }
        function GetDataFinal : TCustomEdit;
        { Write method for property DataFinal }
        procedure SetDataFinal(Value : TCustomEdit);
        { Read method for property Mes }
        function GetMes : TCustomEdit;
        { Write method for property Mes }
        procedure SetMes(Value : TCustomEdit);
        { Read method for property Ano }
        function GetAno : TCustomEdit;
        { Write method for property Ano }
        procedure SetAno(Value : TCustomEdit);

    protected
      { Protected fields of TDataIdade }

      { Protected methods of TDataIdade }
        { Resets prop of component type if referenced component deleted }
        procedure Notification(AComponent : TComponent; Operation : TOperation); override;
        procedure Loaded; override;

    public
      { Public fields and properties of TDataIdade }

      { Public methods of TDataIdade }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function Execute : Boolean;
        { Gera dia, mes e ano. }
        function GDataCompleta : TCustomEdit;
        { Gera a data de inicio. }
        function GDataInicio : TCustomEdit;
        function GIdade : String;

    published
      { Published properties of the component }
        { Dia }
        property Dia : TCustomEdit read GetDia write SetDia;
        { Retorna a data inicial }
        property DataInicio : TCustomEdit read GetDataInicio write SetDataInicio;
        { Retorna a Data Final }
        property DataFinal : TCustomEdit read GetDataFinal write SetDataFinal;
        { Mes }
        property Mes : TCustomEdit read GetMes write SetMes;
        { Ano }
        property Ano : TCustomEdit read GetAno write SetAno;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TDataIdade with Lixo as its
       default page on the Delphi component palette }
     RegisterComponents('Miscelanea', [TDataIdade]);
end;

{ Method to set variable and property values and create objects }
procedure TDataIdade.AutoInitialize;
begin
     FDia := nil;
     FDataInicio := nil;
     FDataFinal := nil;
     FMes := nil;
     FAno := nil;
end; { of AutoInitialize }

{ Resets prop of component type if referenced component deleted }
procedure TDataIdade.Notification(AComponent : TComponent; Operation : TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of
       this component been deleted?  If so, update
       the property. }
     if AComponent = FDia then
        FDia := nil;
     if AComponent = FDataInicio then
        FDataInicio := nil;
     if AComponent = FDataFinal then
        FDataFinal := nil;
     if AComponent = FMes then
        FMes := nil;
     if AComponent = FAno then
        FAno := nil;
end;

{ Method to free any objects created by AutoInitialize }
procedure TDataIdade.AutoDestroy;
begin
     { No objects from AutoInitialize to free }
end; { of AutoDestroy }

{ Read method for property Dia }
function TDataIdade.GetDia : TCustomEdit;
begin
     Result := FDia
end;

{ Write method for property Dia }
procedure TDataIdade.SetDia(Value : TCustomEdit);

var
mi_Dia : integer;

begin
     { Use Assign method because TCustomEdit is an object type }
  If Value.Text = '' then
     Value.Text := '0';

  try
    mi_Dia := StrToInt( Value.Text );
    If (mi_Dia < 0)  or  (mi_Dia > 30) then
       MessageDlg('Valor dos dias está fora dos limites.', mtInformation,
       [mbOk], 0);
    except
    MessageDlg('Valor da Data não válido.', mtInformation,
      [mbOk], 0);
  end;

    FDia := Value;
end;

{ Read method for property DataInicio }
function TDataIdade.GetDataInicio : TCustomEdit;
begin
     Result := FDataInicio
end;

{ Write method for property DataInicio }
procedure TDataIdade.SetDataInicio(Value : TCustomEdit);

begin

If Value.Text = '' then
   Value.Text := DateToStr( Date );
     { Use Assign method because TCustomEdit is an object type }
     FDataInicio := Value;
end;

{ Read method for property DataFinal }
function TDataIdade.GetDataFinal : TCustomEdit;
begin
     Result := FDataFinal
end;

{ Write method for property DataFinal }
procedure TDataIdade.SetDataFinal(Value : TCustomEdit);

begin
  If Value.Text = '' then
     Value.Text := DateToStr( Date );
{ Use Assign method because TCustomEdit is an object type }
     FDataFinal := Value;
end;

{ Read method for property Mes }
function TDataIdade.GetMes : TCustomEdit;
begin
     Result := FMes
end;

{ Write method for property Mes }
procedure TDataIdade.SetMes(Value : TCustomEdit);

var
mi_Mes : integer;

begin
     { Use Assign method because TCustomEdit is an object type }
  If Value.Text = '' then
     Value.Text := '0';

  try
    mi_Mes := StrToInt( Value.Text );
    If (mi_Mes < 0)  or  (mi_Mes > 11) then
       MessageDlg('Valor dos Meses está fora dos limites.', mtInformation,
      [mbOk], 0);
   except
    MessageDlg('Valor da Data não válido.', mtInformation,
      [mbOk], 0);
  end;
     { Use Assign method because TCustomEdit is an object type }
     FMes := Value;
end;

{ Read method for property Ano }
function TDataIdade.GetAno : TCustomEdit;
begin
     Result := FAno
end;

{ Write method for property Ano }
procedure TDataIdade.SetAno(Value : TCustomEdit);

var
mi_Ano : integer;

begin
     { Use Assign method because TCustomEdit is an object type }
  If Value.Text = '' then
     Value.Text := '0';

  try
    mi_Ano := StrToInt( Value.Text );
    If (mi_Ano < 0)  or  (mi_Ano > 130) then
       MessageDlg('Valor dos Anos está fora dos limites.', mtInformation,
      [mbOk], 0);
   except
    MessageDlg('Valor da Data não válido.', mtInformation,
      [mbOk], 0);
  end;
     { Use Assign method because TCustomEdit is an object type }
     FAno := Value;
end;

constructor TDataIdade.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TDataIdade.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TDataIdade.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;

function TDataIdade.Execute : Boolean;
begin
     { Perform the component operation }

     { Return True if the operation was successful, False otherwise }
     Result := True
end;

{ Gera dia, mes e ano. }
function TDataIdade.GDataCompleta : TCustomEdit;
     { Internal declarations for method }
     { type }
     { . . . }
var

 mi_Anos, mi_Meses, mi_Dias : integer;
 mw_AnoI, mw_MesI, mw_DiaI, mw_AnoF, mw_MesF, mw_DiaF, mw_AnoFM, mw_MesFM, mw_DiaFM : word;
 md_DataInicio, md_DataFinal, md_FinalMes : TDateTime;

begin
 Result := nil;

 mi_Anos := 0 ;
 mi_Meses:= 0 ;
 mi_Dias := 0 ;
 md_DataInicio := StrtoDate(FDataInicio.Text);
 md_DataFinal  := StrtoDate(FDataFinal.Text);

 If  md_DataInicio <= md_DataFinal then
    Begin
     DecodeDate( md_DataInicio, mw_AnoI, mw_MesI, mw_DiaI);
     DecodeDate( md_DataFinal,  mw_AnoF, mw_MesF, mw_DiaF);
     mi_Anos  := mw_AnoF - mw_AnoI;
     mi_Meses := mw_MesF - mw_MesI;
     mi_Dias  := mw_DiaF - mw_DiaI;
     If mi_Dias < 0 then
      Begin
       md_FinalMes := md_DataFinal - mw_DiaF;
       DecodeDate( md_FinalMes, mw_AnoFM, mw_MesFM, mw_DiaFM);
       Inc( mi_Dias, mw_DiaFM );
       Dec( mi_Meses );
      End;
     If mi_Meses < 0 then
       Begin
        Inc( mi_Meses, 12 );
        Dec( mi_Anos );
       End;
    End
  else
    Begin
     MessageDlg('Data inicial maior que Data final.', mtInformation,
      [mbOk], 0);

    End;

 (FDia as TCustomEdit).Text := IntToStr(mi_Dias);
 (FMes as TCustomEdit).Text := IntToStr(mi_Meses);
 (FAno as TCustomEdit).Text := IntToStr(mi_Anos);

 End;

{ Gera a data de inicio. }
function TDataIdade.GDataInicio : TCustomEdit;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
  var

  mi_Anos, mi_Meses, mi_Dias : integer;
//  mw_AnoI, mw_MesI, mw_DiaI,
  mw_AnoF, mw_MesF, mw_DiaF, mw_AnoFM, mw_MesFM, mw_DiaFM : word;
  md_DataInicio, md_DataFinal, md_FinalMes : TDateTime;

begin
 Result := nil;

 mi_Anos := StrtoInt(FAno.Text) ;
 mi_Meses:= StrtoInt(FMes.Text) ;
 mi_Dias := StrtoInt(FDia.Text) ;
 md_DataFinal  := StrtoDate(FDataFinal.Text);

 DecodeDate( md_DataFinal,  mw_AnoF, mw_MesF, mw_DiaF);
 mi_Anos  := mw_AnoF - mi_Anos ;
 mi_Meses := mw_MesF - mi_Meses;
 mi_Dias  := mw_DiaF - mi_Dias;

 If mi_Dias <= 0 then
    Begin
     md_FinalMes := md_DataFinal - mw_DiaF;
     DecodeDate( md_FinalMes, mw_AnoFM, mw_MesFM, mw_DiaFM);
     Inc( mi_Dias, mw_DiaFM );
     Dec( mi_Meses );
    End;

If mi_Meses <= 0 then
   Begin
    Inc( mi_Meses, 12 );
    Dec( mi_Anos );
   End;

  Try
    md_DataInicio := StrToDate(IntToStr(mi_Dias)+ '/'+ IntToStr(mi_Meses)+ '/' +
                    IntToStr(mi_Anos));
   (FDataInicio as TCustomEdit).Text := DateToStr( md_DataInicio );

  Except
   (FDataInicio as TCustomEdit).Text := DateToStr(Date);

  End;

End;


function TDataIdade.GIdade : String;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }

 var

 Fidade : String ;

begin

  GDataCompleta ;

  FIdade := FMes.Text;
  If StrToInt( FIdade ) < 10 then Insert( '0', FIdade,1);
  GIdade := Concat( FAno.Text,',', FIdade) ;

end;


end.
