// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TListDic                                        }
{                                                                    }
{   ListView for Dictionary                                          }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file                                       }
{   d:\dados\projetos\componentes delphi\listdic\listdic.cd          }
{   on 6 June 1997 at 20:57                                          }
{                                                                    }
{   Copyright © 1997 by Eng. Pablo J. Madril - SIH HSP               }
{                                                                    }
{ ****************************************************************** }

unit ListDic;

interface
//Forms, Graphics,WinTypes, WinProcs,Messages,WinTypes,
uses   SysUtils,Classes, StdCtrls, Controls,Comctrls,DsgnIntf, OCXDCNLib_TLB,
       TreeDic;

type
  // Definição da procedure para o handler do novo evento click que ja recebe
  //o Codigo e a Descrição do item clicado: ver Nota 6
  TClickDicEvent = procedure (Sender: TObject; Code: String; Description: String) of object;
  TListDic = class(TCustomListView)
    private
      // Private fields of TListDic
        m_Xpos: integer;
        m_Ypos: integer;
        m_DescricaoPai: WideString;
        m_ModoProcura: Boolean;
        m_ContadorPalavras : integer;
        // Storage for property Dicionario
        FDicionario : TDicionario;
        // Storage for property Code: ver Nota 2
        FCode : WideString;
        // Storage for property Description: ver Nota 2
        FDescription : WideString;
        // Storage for property Active
        FActive : Boolean;
        //Usuario e Password: ver Nota 4
        FUser : String;
        FPassword : String;
        // Storage for property BotaoProcura
        FBotaoProcura : TButton;
        // Storage for property PalavraPesquisada
        FPalavraPesquisada : TEdit;
        // Storage for property TreeDic
        FTreeDic : TTreeDic;
        // Storage for property LblFrase
        FLblFrase : TLabel;
        {Evento do novo click: ver Nota 6}
        FOnClickDic : TClickDicEvent;


      // Private methods of TListDic
        // Method to set variable and property values and create objects
        procedure AutoInitialize;
        // Method to free any objects created by AutoInitialize
        procedure AutoDestroy;
        // Write method for property Dicionario
        procedure SetDicionario(Value : TDicionario);
        // Write method for property Active
        procedure SetActive(Value : Boolean);
        // Write method for property BotaoProcura
        procedure SetBotaoProcura(Value : TButton);
        // Write method for property PalavraPesquisada
        procedure SetPalavraPesquisada(Value : TEdit);
        // Write method for property TreeDic
        procedure SetTreeDic(Value : TTreeDic);
        // Write method for property LblFrase
        procedure SetLblFrase(Value : TLabel);
        //Write method for property User;
        procedure SetUser(NewUser: string);
        //Write method for property Password;
        procedure SetPassword(NewPassword: string);

    protected
      // Protected fields of TListDic

      // Protected methods of TListDic
        procedure BeforeOpen;
        procedure AfterClose;
        // Resets prop of component type if referenced component deleted
        procedure Notification(AComponent : TComponent; Operation : TOperation); override;
        // Adiciona Code e Description
        procedure Click; override;
        procedure DblClick; override;
        procedure Loaded; override;
        procedure PreencheListView;
        procedure MontaFrasePreencheList;
        procedure MouseDown(Button: TMouseButton;
                  Shift: TShiftState; X, Y: Integer); override;
        property ReadOnly default True;

    public
      { Public fields and properties of TListDic }
        { Codigo do Item selecionado }
        property Code : WideString read FCode;
        { Descrição do item selecionado }
        property Description : WideString read FDescription;
        procedure BotaoProcuraClick(Sender: TObject);
        procedure ClickOnTreeDic(Sender: TObject; Code, Description: string);

      { Public methods of TListDic }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;

    published
      { Published properties of the component }
        { Dicionário usado pelo List View }
        property Dicionario : TDicionario read FDicionario write SetDicionario;
        { Define o estado da comnexão com o Dicionário }
        property Active : Boolean read FActive write SetActive default False;
        {User e Password}
        property User: string read FUser write SetUser;        //: Ver nota 4
        property Password: string read FPassword write SetPassword;
        { Botão que ativa a pesquisa }
        property BotaoProcura : TButton
             read FBotaoProcura write SetBotaoProcura;
        { TEdit que tem a palavra para pesquisar }
        property PalavraPesquisada : TEdit
             read FPalavraPesquisada write SetPalavraPesquisada;
        { TreeDic associado }
        property TreeDic : TTreeDic read FTreeDic write SetTreeDic;
        property LblFraseCompleta: TLabel
             read FLblFrase write SetLblFrase;
         { Adiciona Code e Description }
        property OnClick: TClickDicEvent read FOnClickDic write FOnClickDic;
        //
        property Align;
        property BorderStyle;
        property Color;
        property ColumnClick;
        property Columns;
        property Ctl3D;
        property DragMode;
        property Font;
        property HideSelection;
        property IconOptions;
        property Items;
        property AllocBy;
        property MultiSelect;
        property OnChange;
        property OnChanging;
        property OnColumnClick;
        property OnCompare;
        property OnDeletion;
        property OnEdited;
        property OnEditing;
        property OnEnter;
        property OnExit;
        property OnInsert;
        property OnDragDrop;
        property OnDragOver;
        property DragCursor;
        property OnStartDrag;
        property OnEndDrag;
        property OnMouseDown;
        property OnMouseMove;
        property OnMouseUp;
        property ParentShowHint;
        property ShowHint;
        property PopupMenu;
        property ShowColumnHeaders;
        property SortType;
        property TabOrder;
        property TabStop default True;
        property ViewStyle;
        property Visible;
        property OnKeyDown;
        property OnKeyPress;
        property OnKeyUp;
        property LargeImages;
        property SmallImages;
        property StateImages;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TListDic with Win95 as its
       default page on the Delphi component palette }
     RegisterComponents('Dicionario', [TListDic]);

end;

{ Method to set variable and property values and create objects }
procedure TListDic.AutoInitialize;
begin
     FActive := False;
     FBotaoProcura := nil;
     FPalavraPesquisada := nil;
     FTreeDic:=nil;
     FLblFrase:=nil;
     //Set default values: ver Nota 4
     FUser:='';
     FPassword:='';

end; { of AutoInitialize }

{ Resets prop of component type if referenced component deleted }
procedure TListDic.Notification(AComponent : TComponent; Operation : TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of
       this component been deleted?  If so, update
       the property. }
     if AComponent = FBotaoProcura then
        FBotaoProcura := nil;
     if AComponent = FPalavraPesquisada then
        FPalavraPesquisada := nil;
     if AComponent = FTreeDic then
        begin
        FTreeDic := nil;
        FPassword:='';
        FUser:='';
        FDicionario:=nil;
        SetActive(False); //: ver Nota 3
        end;
     if AComponent = FLblFrase then
        FLblFrase := nil;
     if AComponent = FDicionario then
        begin
        FTreeDic := nil;
        FPassword:='';
        FUser:='';
        FDicionario := nil;
        SetActive(False); //: ver Nota 3
        end;
end;

{ Method to free any objects created by AutoInitialize }
procedure TListDic.AutoDestroy;
begin
     { No objects from AutoInitialize to free }
end; { of AutoDestroy }

{ Write method for property Dicionario }
procedure TListDic.SetDicionario(Value : TDicionario);
{********************************************************
SetDicionario:
Atualiza o valor da referencia para o Dicionario
Ver Nota 1
**********************************************************}
begin
  //: ver Nota 3
  if not(csLoading in ComponentState) then
     begin
     SetActive (False);
     if Assigned (TreeDic) then
        begin
        TreeDic.OnClick:=nil;
        TreeDic:=nil;
        FUser:='';
        FPassword:='';
        end;
     end;

  FDicionario:=Value;
  if Value <> nil then Value.FreeNotification(Self);
 end;

procedure TListDic.SetActive(Value : Boolean);
begin
  if not(csLoading in ComponentState) then
    begin
    if Assigned (FDicionario) and FActive <> Value then
     begin
      if Value then
       begin
       if (FDicionario.Connected) then
          //Dicionario previamente conectado
          begin
          BeforeOpen;
          FActive := True;
          end
       else
          if (FDicionario.ConnectDictionary(FUser,FPassword)) then
          //Dicionario conectado
          begin
          BeforeOpen;
          FActive := True;
          end;

       end
      else
       begin
       AfterClose;
       FActive := False;
       end;
     end;
    end else FActive := Value;
end;

{ Write method for property BotaoProcura }
procedure TListDic.SetBotaoProcura(Value : TButton);
begin
  //: ver Nota 3
  FBotaoProcura:=Value;
  if Value <> nil then
   begin
   Value.FreeNotification(Self);
   Value.OnClick :=BotaoProcuraClick;
   end;
end;

{ Write method for property PalavraPesquisada }
procedure TListDic.SetPalavraPesquisada(Value : TEdit);
begin
     { Use Assign method because TEdit is an object type }
  FPalavraPesquisada:=Value;
  if Value <> nil then
   Value.FreeNotification(Self)
  else if Assigned(FBotaoProcura) then
    begin;
    FBotaoProcura.OnClick:=nil;
    FBotaoProcura:=nil;
    end;
end;

{ Write method for property TreeDic }
procedure TListDic.SetTreeDic(Value : TTreeDic);
begin
  if not(csLoading in ComponentState) then SetActive (False);
  FTreeDic:=Value;
  if Value <> nil  then //and Value.Dicionario <> nil
   begin;
   Value.FreeNotification(Self);
   Value.OnClick:=ClickOnTreeDic;
   FPassword:=Value.Password;
   FUser:=Value.User;
  FDicionario:=Value.Dicionario;
  if Value <> nil then Value.Dicionario.FreeNotification(Self);
   end;
end;

//Write method for property User;
procedure TListDic.SetUser(NewUser: string);
begin;
if not Assigned(FTreeDic) then FUser:=NewUser;
end;
//Write method for property Password;
procedure TListDic.SetPassword(NewPassword: string);
begin;
if not Assigned(FTreeDic) then FPassword:=NewPassword;
end;
{ Write method for property Active }

procedure TListDic.SetLblFrase(Value : TLabel);
begin
  FLblFrase:=Value;
  if Value <> nil then Value.FreeNotification(Self);
end;

constructor TListDic.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TListDic.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TListDic.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }
if  Assigned (FDicionario) and FActive  then
       begin
       if (FDicionario.Connected) then
          //Dicionario previamente conectado
          begin
          BeforeOpen;
          FActive := True;
          end
       else
       if (FDicionario.ConnectDictionary(FUser,FPassword)) then
          //Dicionario conectado
          begin
          BeforeOpen;
          FActive := True;
          end else FActive := False;
       end;

end;
procedure TListDic.ClickOnTreeDic(Sender: TObject; Code, Description: string);
begin
if FCode = Code then Exit;

FCode:=Code;
FDescription:=Description;
MontaFrasePreencheList;
end;

{********************************************************
BeforeOpen:
Nesta rotina é inicializado o primeiro no do TreeView :o ROOT.
Como descrição vai a SiglaDicionario do dicionario. Pode ir o
NomeDicionario. Como Código vai 'ROOT'.
A rotina PreencheTree, completa os primeiros filhos do ROOT.
O resto da arvore e preenchido a medida que é solicitado (Ver DblClick).
**********************************************************}
procedure TListDic.BeforeOpen;
//var
//   ChildCount: Smallint;
//   SonCode: String;
//   SonDesc: String;
begin
FDicionario.GetCurrentParent (FCode,Fdescription);
MontaFrasePreencheList;
end;
{********************************************************
AfterClose:
Nesta rotina são reinicializados o TreeView e o StrList.
**********************************************************}
procedure TListDic.AfterClose;
begin
Items.Clear;
end;


procedure TListDic.MouseDown(Button: TMouseButton;
  Shift: TShiftState; X, Y: Integer);
begin
m_Xpos:=X;
m_Ypos:=Y;
end;

{ Adiciona Code e Description }
procedure TListDic.Click;
var
   NewItem : TListItem;
   DescAtual: WideString;
   CodePai : WideString;
begin
{ Code to execute before activating click
       behavior of component's parent class }
{ Activate click behavior of parent }
inherited Click;

{ Code to execute after click behavior
       of parent }

NewItem:=GetItemAt(m_Xpos, m_Ypos);

if NewItem <> NIL then
   begin
   if not m_ModoProcura then
      begin
      FDescription:=NewItem.SubItems[0];
      FCode:=NewItem.Caption;

      if (FDicionario.HasChilds (FCode) = FALSE)  then
        DescAtual := m_DescricaoPai + ' : '+ Trim (FDescription)
      else
        DescAtual := Trim (FDescription);

      if Assigned(FLblFrase) then
        FLblFrase.Caption := Trim (FCode) + ' - ' + DescAtual;
      end
   else
      if NewItem.Caption = '...' then
         BotaoProcuraClick(self)
      else
      begin
         m_ContadorPalavras :=0;
         FDescription:=NewItem.SubItems[0];
         FCode:=NewItem.Caption;
         FDicionario.FindParents(FCode,CodePai);
         FDicionario.GetFirstParent(CodePai,m_DescricaoPai);
         m_DescricaoPai:=Trim (m_DescricaoPai);
         MontaFrasePreencheList;
      end;
   end;


if Assigned (FOnClickDic) then
     FOnClickDic (Self,FCode,FDescription);


end;

procedure TListDic.DblClick;
//var
//   ChildCount: Smallint;
//   NewItem : TListItem;
begin

inherited DblClick;
MontaFrasePreencheList;

end;

procedure TListDic.MontaFrasePreencheList;
var
   ChildCount: Smallint;
   DescAtual: string;
begin

if Assigned (FDicionario) then
     begin
     if (FDicionario.HasChilds (FCode) = FALSE)  then
          DescAtual := m_DescricaoPai + ' : '+ Trim (FDescription)
     else
          DescAtual := Trim (FDescription);

     if Assigned(FLblFrase) then
          FLblFrase.Caption := Trim (FCode) + ' - ' + DescAtual;

     if (FDicionario.ExpandCode(FCode,ChildCount)) then
          begin
          m_DescricaoPai:=Trim (FDescription);
          PreencheListView;
          end;
     end;



end;

procedure TListDic.PreencheListView;
var
   NewItem : TListItem;
   Code : WideString;
   Description : WideString;

begin
//Limpo a lista
Items.Clear;

//Adiciono o item retorno da arvore
if Assigned(FDicionario) then
   begin
        with FDicionario do
        begin
        GetCurrentParent(Code,Description);
        while (Code <> 'ROOT') do
              begin
              NewItem:=Items.Insert(0);
              NewItem.Caption := Code;
              NewItem.SubItems.Add(Description);
              NewItem.ImageIndex:=2;
              FindParents(Code,Code);
              GetFirstParent (Code,Description);
              end;

        //Pega o Primeiro Filho do Novo Pai
        GetFirstSon(Code,Description);
        NewItem:=Items.Add;
        NewItem.Caption := Code;
        NewItem.SubItems.Add(Description);

        if HasChilds(Code) then
              NewItem.ImageIndex:=1
        else
              NewItem.ImageIndex:=0;

        //Pego os outros filhos
        while (GetNextBrother(Code,Description)) do
              begin
              NewItem:=Items.Add;
              NewItem.Caption := Code;
              NewItem.SubItems.Add(Description);
              if HasChilds(Code) then
                 NewItem.ImageIndex:=1
              else
                 NewItem.ImageIndex:=0;
              end;
        end;
   end;
end;


procedure TListDic.BotaoProcuraClick(Sender: TObject);
var
   NewItem : TListItem;
   Code : WideString;
   Description : WideString;
   MoreItems : Boolean;

begin
if Assigned (FDicionario) and Assigned (FPalavraPesquisada) then
with FDicionario do
     begin
     if not m_ModoProcura then
     begin
     Description := '%' + FPalavraPesquisada.Text + '%';
     if (FindCodeByDescription(Code,Description) > 0) then
        begin
        m_ModoProcura:=True;
        m_ContadorPalavras:=0;
        //Limpo a lista
        Items.Clear;

        //Pega o Primeiro da Lista
        GetFirstCodeByDesc(Code,Description);
        NewItem:=Items.Add;
        NewItem.Caption := Code;
        NewItem.SubItems.Add(Description);

        //m_CIDAtual := Trim (Code);

        if HasChilds(Code) then
           begin
           NewItem.ImageIndex:=1;
           end
        else
           begin
           NewItem.ImageIndex:=0;
           end;
        end;
     end
     else
     begin
     //Limpo o ultimo item que tem o '...' 'Mais items ...'
     Items.Delete (Items.Count -1);
     end;
     begin
        //Pego os outros filhos
        MoreItems:=GetNextCodeByDesc(Code,Description);
        while (MoreItems and (m_ContadorPalavras < 30)) do
           begin
           m_ContadorPalavras:=m_ContadorPalavras + 1;
           NewItem:=Items.Add;
           NewItem.Caption := Code;
           NewItem.SubItems.Add(Description);
           if HasChilds(Code) then
              NewItem.ImageIndex:=1
           else
              NewItem.ImageIndex:=0;
           MoreItems:=GetNextCodeByDesc(Code,Description);
           end;

        m_ContadorPalavras:=0;
        if MoreItems then
           begin
           NewItem:=Items.Add;
           NewItem.Caption := '...';
           NewItem.SubItems.Add('Mais items..');
           end
        else
           m_ModoProcura:= False;
        end;
     end;
end;


{

procedure TFPrincipal.PreencheListView;
var NewItem : TListItem;

begin

end;




procedure TFPrincipal.EdPesqCodChange(Sender: TObject);
begin

//Validar o Codigo digitado e achar a descricao correspondente

if (Dic.FindDescriptionByCode(EdPesqCod.Text,Description)) then
   begin
    MontaDiagnostico (EdPesqCod.Text,Description);
    m_bFlagChangeCID:=TRUE;
   end;

end;

procedure TFPrincipal.EdPesqCodEnter(Sender: TObject);
begin
     EdPesqDesc.Text := '';
end;

procedure TFPrincipal.EdPesqDescEnter(Sender: TObject);
begin
     EdPesqCod.Text := '';
end;


end;

}

end.


