// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TMedida                                        }
{                                                                    }
{   Representa as grandezas, seus valores numericos e suas unidades  }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file                                       }
{   d:\dados\projetos\componentes delphi\medida\quantity.cd          }
{   on 28 June 1997 at 6:35                                          }
{                                                                    }
{   Copyright © 1997 by DIS-EPM/UNIFESP                              }
{                                                                    }
{ ****************************************************************** }

unit Measurement;

interface

uses  Classes, SysUtils, DsgnIntf, Dialogs, Math, Forms;

const
   INVALID_VALUE = 'não foi possível determinar';
   EMPTY_VALUE   = '-';
   INVALID_UNIT = '';

type

   // Para engenar a referencia cruzada entre TMeasurementRanges e TMeasurementIntervals
   TMeasurementRanges = class;

   // Isto é para resolver a referencia cruzada em TMedida e TDescritorQuantitativo
   TDescritorQuantitativo = class;

   /////////////////////////////////////////////////////////////////////////
   //
   //                  Definição : WMedida
   //
   ////////////////////////////////////////////////////////////////////////

   EMeasurementError = class(Exception);

   TMedida = class(TComponent)
   private
    FInvalidDescr: String;
      procedure SetCodigoMedida(const Value: String);
      procedure SetMascaraNumeros(const Value: string);
      procedure SetPrecisao(const Value: Integer);
    procedure SetInvalidDescr(const Value: String);
    function GetInvalidDescr: String;
   protected
      FCodigoMedida : String;
      FValorNumerico : String;
      FDescricao : String;
      FPrecisao : Integer;
      FDescritor : TDescritorQuantitativo;
      FUnidade : string;
      FListaUnidades: TStrings;
      FListaValores: TStrings;
      FMascaraNumeros: String;
      FEmpty : Boolean;
      FValid: Boolean;
      FIdxUDefault: Integer;
      FIdxVDefault: Integer;
      InternalStgValue : string;
      InternalStgUnit : string;

      FEstimated: Boolean;
      FReadOnly: Boolean;
      FPrintable: Boolean;
      procedure SetReadOnly(const Value: Boolean);virtual;
      procedure SetDescricao(const Value: String);virtual;
      procedure SetPrintable(const Value: Boolean);virtual;
      procedure SetDescritor(const Value: TDescritorQuantitativo);virtual;

      procedure SetListaUnidades(Value: TStrings);virtual;
      procedure SetIdxUDefault(const Value: Integer);virtual;
      procedure SetListaValores(Value : TStrings);virtual;
      procedure SetIdxVDefault(const Value: Integer);  virtual;
      procedure SetValorNumerico(const Value: String);virtual;
      function GetValorNumerico: String;virtual;
      procedure SetUnidade(const Value: String);virtual;
      function GetAsFloat: Double;virtual;
      procedure SetAsFloat(const Value: Double);virtual;
      procedure SetEmpty(const Value: Boolean);virtual;
      procedure SetValid(const Value: Boolean);virtual;
      procedure SetEstimated(const Value: Boolean);virtual;
      function GetUnidadeApresentacao: String;virtual;
      function GetValorApresentacao : String;virtual;
      function DefineStorage:Boolean;virtual;
      function DefStorageInvalidDescr:Boolean;virtual;

      procedure Loaded; override;

      procedure DefineProperties(Filer: TFiler); override;
      procedure ReadValue(Reader: TReader);
      procedure ReadUnit(Reader: TReader);
      procedure WriteValue(Writer: TWriter);
      procedure WriteUnit(Writer: TWriter);
   public
      class procedure SetListaCnst(PLista:TStringList);
      property AsFloat: Double read GetAsFloat write SetAsFloat;
      constructor Create(AOwner: TComponent); overload;override;
      constructor Create(AOwner: TComponent;AMedida: TMedida);reintroduce;overload;virtual;
      destructor Destroy; override;
      procedure Notification(AComponent: TComponent; Operation: TOperation);override;
      procedure AssignTo(Dest : TPersistent);override;
      procedure Assign(Sou: TMedida);reintroduce;overload;
      function SetMedida(Valor,Unidade : string): Boolean; virtual;
      function ValorNumericoFormatado : String;  virtual;
      function UnidadeFormatada : String;  virtual;
      function ConvertToUnit(NewUnit: string): TMedida; virtual;
      function AsFloatUnit(NewUnit: string) : Double; virtual;
      procedure Clear;virtual;
      function GTE(AnOperand : TMedida) : Boolean;virtual;
      function GT(AnOperand : TMedida) : Boolean;virtual;
   published
      property Descricao : String read FDescricao write SetDescricao;
      property CodigoMedida : String read FCodigoMedida write SetCodigoMedida;
      property ValorNumerico : String read GetValorNumerico write SetValorNumerico stored DefineStorage;
      property Unidade : String read FUnidade write SetUnidade stored DefineStorage;
      property MascaraNumeros : string read FMascaraNumeros write SetMascaraNumeros;
      property ListaValores : TStrings read FListaValores write SetListaValores;
      property IdxVDefault:Integer read FIdxVDefault write SetIdxVDefault default 0;
      property ListaUnidades : TStrings read FListaUnidades write SetListaUnidades;
      property IdxUDefault:Integer read FIdxUDefault write SetIdxUDefault default 0;
      property Precisao : Integer read FPrecisao write SetPrecisao default 0;
      property Descritor : TDescritorQuantitativo read FDescritor write SetDescritor;
      property Empty : Boolean read FEmpty write SetEmpty;
      property InvalidDescr : String read GetInvalidDescr write SetInvalidDescr stored DefStorageInvalidDescr;
      property Valid : Boolean read FValid write SetValid;
      property Estimated: Boolean read FEstimated write SetEstimated default False;
      property ValorApresentacao : String read GetValorApresentacao;
      property UnidadeApresentacao : String read GetUnidadeApresentacao;
      property ReadOnly : Boolean read FReadOnly write SetReadOnly default False;
      property Printable : Boolean read FPrintable write SetPrintable default True;
   end;

   TMedidaClass = class of TMedida;

   /////////////////////////////////////////////////////////////////////////
   //
   //                  Definição : TMedidaOrdinal
   //
   /////////////////////////////////////////////////////////////////////////

   TMedidaOrdinal = class(TMedida)
   private
   protected
      procedure SetValorNumerico(const Value: String);override;
      function GetValorNumerico: String;override;
      procedure SetAsFloat(const Value: Double);override;
      function GetAsFloat: Double;override;
      function GetUnidadeApresentacao: String;override;
      function GetValorApresentacao : String;override;
   public
      constructor Create(Owner:TComponent);override;
   published
   end;

   /////////////////////////////////////////////////////////////////////////
   //
   //                  Definição : WIntervaloMedidas
   //
   /////////////////////////////////////////////////////////////////////////

   TMeasureLimit = class(TPersistent)
   private
      FExcluded: boolean;
      FOpened: boolean;
      FPoint: TMedida;
      FCaption: String;
      procedure SetExcluded(const Value: boolean);
      procedure SetOpened(const Value: boolean);
      procedure SetPoint(const Value: TMedida);
      procedure SetCaption(const Value: String);
   protected
      function CreatePoint(AOwner : TComponent; PName : string): TMedida;virtual;
   public
      constructor Create(AOwner : TComponent; PointName : string);
      destructor Destroy;override;
      procedure Assign(Source: TPersistent); override;
   published
      property Opened : boolean read FOpened write SetOpened default False;
      property Excluded : boolean read FExcluded write SetExcluded default False;
      property Point : TMedida read FPoint write SetPoint stored False;
      property Caption : String read FCaption write SetCaption;
   end;

   TMeasurementInterval = class(TCollectionItem)
   private
      FCaption: string;
      FEndPoint: TMeasureLimit;
      FBeginPoint: TMeasureLimit;
      FAutoName: Boolean;
      procedure SetOnChange(const Value: TNotifyEvent);
      procedure SetBeginPoint(const Value: TMeasureLimit);
      procedure SetCaption(const Value: string);
      procedure SetEndPoint(const Value: TMeasureLimit);
      procedure SetAutoName(const Value: Boolean);
   protected
      FOnChange: TNotifyEvent;
      FBeginPointCreated : Boolean;
      FEndPointCreated : Boolean;
      procedure Change;
   protected
      function GetDisplayName: string; override;
      function CreateLimit(AOwner : TComponent; LimitName : string) : TMeasureLimit;virtual;
   public
      constructor Create(Collection: TCollection); override;
      destructor Destroy; override;
      procedure Assign(Source: TPersistent); override;
      function Has(AMedida : TMedida) : boolean;overload;virtual;
      function Has(AMedida : TMedida; var ANearPoint : TMeasureLimit; var Percent : Double) : boolean;overload;
   published
      property Caption : string read FCaption write SetCaption;
      //Stored tem que ser False senao fica com ponteiro sem resolver (acha que aponta para outro form)
      property BeginPoint : TMeasureLimit read FBeginPoint write SetBeginPoint; // stored False;
      property EndPoint : TMeasureLimit read FEndPoint write SetEndPoint; // stored False;
      property OnChange : TNotifyEvent read FOnChange write SetOnChange;
      property AutoName : Boolean read FAutoName write SetAutoName;
   end;

   TMeasurementIntervals = class(TCollection)
   private
      FOwner: TMeasurementRanges;
      function GetItem(Index: Integer): TMeasurementInterval;
      procedure SetItem(Index: Integer; Value: TMeasurementInterval);
   protected
      function GetOwner: TPersistent; override;
      procedure Update(Item: TCollectionItem); override;
   public
      constructor Create(AOwner: TMeasurementRanges;ItemClass: TCollectionItemClass);
      function Add: TMeasurementInterval;
      procedure Clear;
      function Find(const DisplayName: string): TMeasurementInterval;
      function IndexOf(const DisplayName: string): Integer;
      property Items[Index: Integer]: TMeasurementInterval read GetItem write SetItem;default;
      property Owner: TMeasurementRanges read FOwner;
   end;

   TMeasurementRanges = class(TComponent)
   private
      FRanges: TMeasurementIntervals;
      FPointList: TStrings;
      procedure SetRanges(const Value: TMeasurementIntervals);
      procedure SetPointList(const Value: TStrings);
   protected
      function CreateRange(AOwner : TComponent) : TMeasurementIntervals;virtual;
      procedure SetName(const NewName : TComponentName);override;
      procedure AdjustPointNames;
   public
      constructor Create(AOwner : TComponent);override;
      destructor Destroy;override;
      procedure GetChildren(Proc: TGetChildProc; Root: TComponent); override;
      procedure UpdateInterval(ItemIndex : integer);
      procedure UpdateIntervals;
      procedure Notification(AComponent: TComponent; Operation: TOperation);override;
      procedure Loaded;override;
      procedure ValidateRename(AComponent: TComponent; const CurName, NewName: string);override;
   published
      property Ranges : TMeasurementIntervals read FRanges write SetRanges;
      property PointList : TStrings read FPointList write SetPointList;
   end;

   /////////////////////////////////////////////////////////////////////////
   //
   //                  Definição : WDescritorQuantitativo
   //
   /////////////////////////////////////////////////////////////////////////

   TNewValidateEvent = procedure(Sender: TObject; var Valid : Boolean) of object;

   TDescritorQuantitativo = class(TComponent)
   private
      FLimiteMinimo: String;
      FMedidaDeValidacao: String;
      FLimiteMaximo: String;
      FProcedimentoDeValidacao: String;
      FNewValidate: TNewValidateEvent;
      procedure SetLimiteMaximo(const Value: String);
      procedure SetLimiteMinimo(const Value: String);
      procedure SetMedidaDeValidacao(const Value: String);
      procedure SetNewValidate(const Value: TNewValidateEvent);
      procedure SetProcedimentoDeValidacao(const Value: String);
   protected
   public
      constructor Create(AOwner: TComponent); override;
      destructor Destroy; override;
      function Validate(ValorAVerificar: TMedida) : Boolean;
      procedure ShowAlert(ValorErrado: TMedida);
      procedure AssignTo(Dest: TPersistent);override;
      procedure Assign(Sou: TDescritorQuantitativo);reintroduce;overload;
   published
      property LimiteMaximo : String read FLimiteMaximo write SetLimiteMaximo;
      property LimiteMinimo : String read FLimiteMinimo write SetLimiteMinimo;
      property NewValidate : TNewValidateEvent read FNewValidate write SetNewValidate;
      property ProcedimentoDeValidacao : String read FProcedimentoDeValidacao write SetProcedimentoDeValidacao;
      property MedidaDeValidacao : String read FMedidaDeValidacao write SetMedidaDeValidacao;
   end;

procedure Register;

var
   ListaConstantes : TStringList;

implementation

uses Memoria;

procedure Register;
begin
   RegisterComponents('Medida', [TDescritorQuantitativo]);
   RegisterComponents('Medida', [TMedida]);
   RegisterComponents('Medida', [TMedidaOrdinal]);
   RegisterComponents('Medida', [TMeasurementRanges]);
   RegisterPropertyEditor(TypeInfo(TMedida), TMeasureLimit,'Point', TClassProperty);
end;

{ TDescritorQuantitativo }

procedure TDescritorQuantitativo.Assign(Sou: TDescritorQuantitativo);
begin
   if (Sou = nil) then
      exit;
   FLimiteMaximo := Sou.FLimiteMaximo;
   FLimiteMinimo := Sou.FLimiteMinimo;
   FNewValidate := Sou.FNewValidate;
   FProcedimentoDeValidacao := Sou.FProcedimentoDeValidacao;
   FMedidaDeValidacao := Sou.FMedidaDeValidacao;
   if Name = '' then
      Name := Sou.Name;
end;

procedure TDescritorQuantitativo.AssignTo(Dest: TPersistent);
begin
  if Dest is TDescritorQuantitativo then
     begin
        TDescritorQuantitativo(Dest).FLimiteMaximo := FLimiteMaximo;
        TDescritorQuantitativo(Dest).FLimiteMinimo := FLimiteMinimo;
        TDescritorQuantitativo(Dest).FNewValidate := FNewValidate;
        TDescritorQuantitativo(Dest).FProcedimentoDeValidacao := FProcedimentoDeValidacao;
        TDescritorQuantitativo(Dest).FMedidaDeValidacao := FMedidaDeValidacao;
        if TDescritorQuantitativo(Dest).Name = '' then
           TDescritorQuantitativo(Dest).Name := Name;
     end
  else
     inherited AssignTo(Dest);
end;

constructor TDescritorQuantitativo.Create(AOwner: TComponent);
begin
   inherited Create(AOwner);
end;

destructor TDescritorQuantitativo.Destroy;
begin
   inherited Destroy;
end;

procedure TDescritorQuantitativo.SetLimiteMaximo(const Value: String);
begin
  FLimiteMaximo := Value;
end;

procedure TDescritorQuantitativo.SetLimiteMinimo(const Value: String);
begin
  FLimiteMinimo := Value;
end;

procedure TDescritorQuantitativo.SetMedidaDeValidacao(const Value: String);
begin
  FMedidaDeValidacao := Value;
end;

procedure TDescritorQuantitativo.SetNewValidate(const Value: TNewValidateEvent);
begin
  FNewValidate := Value;
end;

procedure TDescritorQuantitativo.SetProcedimentoDeValidacao(const Value: String);
begin
  FProcedimentoDeValidacao := Value;
end;

procedure TDescritorQuantitativo.ShowAlert(ValorErrado: TMedida);
begin
   ShowMessage('Valor Invalido');
end;

function TDescritorQuantitativo.Validate(ValorAVerificar: TMedida): Boolean;
var
   Valid : Boolean;
begin
   Result := True;
   // Valida só pelo evento se ele existir
   if Assigned( FNewValidate ) then
      Begin
         Valid := True;
         FNewValidate( self, Valid );
         Result := Valid;
      end;
end;

{ TMedida }

procedure TMedida.Assign(Sou : TMedida);
begin
   if (Sou = nil) then
      exit;
   FListaUnidades.Assign(Sou.FListaUnidades);
   FListaValores.Assign(Sou.FListaValores);
   FDescritor := Sou.FDescritor;
   FEstimated := Sou.FEstimated;
   FCodigoMedida := Sou.FCodigoMedida;
   FDescricao := Sou.FDescricao;
   FEmpty := Sou.FEmpty;
   FIdxUDefault := Sou.FIdxUDefault;
   FIdxVDefault := Sou.FIdxVDefault;
   FMascaraNumeros := Sou.FMascaraNumeros;
   FPrecisao := Sou.FPrecisao;
   FUnidade := Sou.FUnidade;
   FValid := Sou.FValid;
   FInvalidDescr := Sou.FInvalidDescr;
   FReadOnly := Sou.FReadOnly;
   FValorNumerico := Sou.FValorNumerico;
   FPrintable := Sou.FPrintable;
   InternalStgUnit := Sou.InternalStgUnit;
   InternalStgValue := Sou.InternalStgValue;
   if Name = '' then
      Name := Sou.Name;
end;

procedure TMedida.AssignTo(Dest: TPersistent);
begin
   if Dest is TMedida then
      begin
         TMedida(Dest).FListaUnidades.Assign(FListaUnidades);
         TMedida(Dest).FListaValores.Assign(FListaValores);
         TMedida(Dest).FDescritor := FDescritor;
         TMedida(Dest).FEstimated := FEstimated;
         TMedida(Dest).FCodigoMedida := FCodigoMedida;
         TMedida(Dest).FDescricao := FDescricao;
         TMedida(Dest).FEmpty := FEmpty;
         TMedida(Dest).FIdxUDefault := FIdxUDefault;
         TMedida(Dest).FIdxVDefault := FIdxVDefault;
         TMedida(Dest).FMascaraNumeros := FMascaraNumeros;
         TMedida(Dest).FPrecisao := FPrecisao;
         TMedida(Dest).FUnidade := FUnidade;
         TMedida(Dest).FValid := FValid;
         TMedida(Dest).FInvalidDescr := FInvalidDescr;
         TMedida(Dest).FReadOnly := FReadOnly;
         TMedida(Dest).FValorNumerico := FValorNumerico;
         TMedida(Dest).FPrintable := FPrintable;
         TMedida(Dest).InternalStgUnit := InternalStgUnit;
         TMedida(Dest).InternalStgValue := InternalStgValue;
         if TMedida(Dest).Name = '' then
            TMedida(Dest).Name := Name;
     end
  else
     inherited AssignTo(Dest);
end;

procedure TMedida.Clear;
begin
   FValorNumerico := '';
   FUnidade := '';
   FEmpty := True;
   InternalStgValue := '';
   InternalStgUnit := '';
   Estimated := False;
   FValid := False;
   FIdxUDefault := 0;
   FIdxVDefault := 0;
end;

function TMedida.ConvertToUnit(NewUnit: string): TMedida;
begin
   Result := self;
end;

constructor TMedida.Create(AOwner: TComponent);
begin
   inherited Create(AOwner);
   FListaUnidades := TStringList.Create;
   FListaValores := TStringList.Create;
   FEmpty := True; // não tirar esta linha,  pois ela arruma o default False (por causa da persistencia)
   FValid := False; // não tirar esta linha, pois ela arruma o default True (por causa da persistencia)
   FReadOnly := False;
   Estimated := False;
   FCodigoMedida := '';
   FDescricao := '';
   FDescritor := nil;
   FIdxUDefault := 0;
   FIdxVDefault := 0;
   FMascaraNumeros := '';
   FPrecisao := 0;
   FUnidade := '';
   FValorNumerico := '';
   InternalStgUnit := '';
   InternalStgValue := '';
   FPrintable := True;
end;

constructor TMedida.Create(AOwner: TComponent; AMedida: TMedida);
begin
   Create(AOwner);
   if AMedida <> nil then
      Assign(AMedida);
end;

procedure TMedida.DefineProperties(Filer: TFiler);
begin
   inherited DefineProperties(Filer);
   Filer.DefineProperty('InternalValue', ReadValue, WriteValue, (InternalStgValue<>''));
   Filer.DefineProperty('InternalUnit', ReadUnit, WriteUnit, (InternalStgUnit<>''));
end;

function TMedida.DefineStorage: Boolean;
begin
   Result := True;
end;

destructor TMedida.Destroy;
begin
   FListaUnidades.Free;
   FListaValores.Free;
   inherited Destroy;
end;

function TMedida.GetAsFloat: Double;
begin
   if not Empty then
      Result := StrToFloat(ValorNumerico)
   else
      raise EInvalidArgument.CreateFmt('Medida vazia, a medida cod:%s descricao:%s não foi preenchida',[self.name,self.descricao]);
end;

function TMedida.GetUnidadeApresentacao: String;
begin
   if not FValid then
      Result := INVALID_UNIT
   else if FEmpty then
      Result := FUnidade
   else
      Result := FUnidade;
end;

function TMedida.GetValorApresentacao: String;
var
   FormatMask : String;
begin
   if not FValid then
      Result := InvalidDescr //INVALID_VALUE
   else if FEmpty then
      Result := EMPTY_VALUE
   else
      begin
         Result := FValorNumerico;
         if Pos('.', Result) > 0 then
         begin
            Result[Pos('.', Result)] := DecimalSeparator;
            if FPrecisao = 0 then
               FormatMask := '0'
            else
               FormatMask := '0.'+ stringOfChar( '0', FPrecisao );
            Result := FormatFloat(FormatMask, StrToFloat( Result ));
         end;
      end;
end;

function TMedida.GetValorNumerico: String;
begin
   //Troca . pelo DecimalSeparator
   Result := FValorNumerico;
   if Pos('.', Result) > 0 then
      Result[Pos('.', Result)] := DecimalSeparator;
end;

function TMedida.GT(AnOperand: TMedida): Boolean;
var
   AMedida : TMedida;
begin
   if FEmpty or AnOperand.FEmpty then
      begin
         Result := False;
         exit;
      end;
   AMedida := TMedida.Create(Owner, AnOperand);
   AMedida.ConvertToUnit(FUnidade);
   Result := (AsFloat > AMedida.AsFloat);
   AMedida.free;
end;

function TMedida.GTE(AnOperand: TMedida): Boolean;
var
   AMedida : TMedida;
begin
   if FEmpty or AnOperand.FEmpty then
      begin
         Result := False;
         exit;
      end;
   AMedida := TMedida.Create(Owner, AnOperand);
   AMedida.ConvertToUnit(FUnidade);
   Result := (AsFloat >= AMedida.AsFloat);
   AMedida.free;
end;

procedure TMedida.Loaded;
begin
   inherited Loaded;
   //Levar em conta InternalStgValue pois a idade usa ele (a medida nao)
   if (InternalStgValue = '') and (FValorNumerico = '') and (FListaValores.Count <> 0) then
      ValorNumerico := FListaValores[FIdxVDefault];
   //Levar em conta InternalStgUnit pois a idade usa ele (a medida nao)
   if (InternalStgUnit = '') and (FUnidade = '') and (FListaUnidades.Count <> 0) then
      FUnidade := FListaUnidades[FIdxUDefault];
end;

procedure TMedida.Notification(AComponent: TComponent; Operation: TOperation);
begin
   inherited Notification(AComponent, Operation);
   if Operation <> opRemove then
      Exit;
   if AComponent = FDescritor then
      FDescritor := nil;
end;

procedure TMedida.ReadUnit(Reader: TReader);
begin
   InternalStgUnit := Reader.ReadString;
end;

procedure TMedida.ReadValue(Reader: TReader);
begin
   InternalStgValue := Reader.ReadString;
end;

procedure TMedida.SetAsFloat(const Value: Double);
begin
   ValorNumerico := FloatToStr(Value);
   FEmpty := False;
end;

function TMedida.AsFloatUnit(NewUnit: string): Double;
begin
   with TMedida.Create(nil) do
     try
        Assign(self);
        ConvertToUnit(NewUnit);
        Result := AsFloat;
     finally
        Free;
     end;
end;

procedure TMedida.SetCodigoMedida(const Value: String);
begin
   FCodigoMedida := Value;
end;

procedure TMedida.SetDescricao(const Value: String);
begin
   FDescricao := Value;
end;

procedure TMedida.SetDescritor(const Value: TDescritorQuantitativo);
begin
   FDescritor := Value;
end;

procedure TMedida.SetEmpty(const Value: Boolean);
begin
   //Faz nada pra ser Read Only
end;

procedure TMedida.SetEstimated(const Value: Boolean);
begin
   FEstimated := Value;
end;

procedure TMedida.SetIdxUDefault(const Value: Integer);
begin
   FIdxUDefault := Value;
end;

procedure TMedida.SetIdxVDefault(const Value: Integer);
begin
   FIdxVDefault := Value;
end;

class procedure TMedida.SetListaCnst(PLista: TStringList);
begin
   if Assigned(PLista) then
      ListaConstantes := PLista;
end;

procedure TMedida.SetListaUnidades(Value: TStrings);
begin
   if ListaUnidades.Text <> Value.Text then
   begin
      ListaUnidades.BeginUpdate;
      try
         ListaUnidades.Assign(Value);
      finally
         ListaUnidades.EndUpdate;
      end;
   end;
end;

procedure TMedida.SetListaValores(Value: TStrings);
begin
   if FListaValores.Text <> Value.Text then
   begin
      FListaValores.BeginUpdate;
      try
         FListaValores.Assign(Value);
      finally
         FListaValores.EndUpdate;
      end;
   end;
end;

procedure TMedida.SetMascaraNumeros(const Value: string);
begin
  FMascaraNumeros := Value;
end;

function TMedida.SetMedida(Valor, Unidade: string): Boolean;
var
   FModifield : Boolean;
   OwnerNow : TComponent;
begin
   Result := False;
   if FReadOnly and not( csLoading in ComponentState ) then  // wgb
      raise EInvalidArgument.CreateFmt('Medida Somente para leitura, codigo: %s descricao: %s',[self.name,self.descricao])
   // Não mudou nada, portanto não precisa validar nem setar
   else if ( ValorNumerico = Valor ) and ( FUnidade = Unidade ) then  // www
      Result := True
   // Se tem um descritor, então vamos validar
   else if Assigned(FDescritor) then
      begin
         // medida vazia (com descritor) não precisa validar
         // isto deveria ser uma opcao do descritor (ValidarEmpty=True/False)
         if Trim(Valor) = '' then
         begin
            Result := True;
            exit;
         end;
         ValorNumerico := Valor;
         FUnidade := Unidade;
         FEmpty := False;
         FValid := False; // vai pra validar
         if (FDescritor.Validate(self)) then
            begin
               FValid := True;
               FModifield := ( ValorNumerico <> Valor ) or ( FUnidade <> Unidade );
               Result := True;
               // Só digo que modificou depois do assign acima
               // Esta variavel deveria ser public, mas fica pra outra versao
               if FModifield then
               begin
                  // Pra achar a memoria onde a medida está (se existir memoria)
                  OwnerNow := Owner;
                  while not ( OwnerNow is TMemoria ) and
                        not ( OwnerNow is TApplication ) do
                        OwnerNow := OwnerNow.Owner;
                  if OwnerNow is TMemoria then
                     TMemoria( OwnerNow ).AddModified;
               end;
            end
         else
            begin
               FValid := False;
            end;
      end
   else
      begin
         FModifield := ( ValorNumerico <> Valor ) or ( FUnidade <> Unidade );
         ValorNumerico := Valor;
         FUnidade := Unidade;
         FValid := True; // se não tem descritor, está válida???
         Result := True;
         // Só digo que modificou depois do assign acima
         // Esta variavel deveria ser public, mas fica pra outra versao
         if FModifield then
            begin
               // Pra achar a memoria onde a medida está (se existir memoria)
               OwnerNow := Owner;
               while not ( OwnerNow is TMemoria ) and
                     not ( OwnerNow is TApplication ) do
                     OwnerNow := OwnerNow.Owner;
               if OwnerNow is TMemoria then
                  TMemoria( OwnerNow ).AddModified;
            end;
      end;
end;

procedure TMedida.SetPrecisao(const Value: Integer);
begin
  FPrecisao := Value;
end;

procedure TMedida.SetPrintable(const Value: Boolean);
begin
   FPrintable := Value;
end;

procedure TMedida.SetReadOnly(const Value: Boolean);
begin
   FReadOnly := Value; 
end;

procedure TMedida.SetUnidade(const Value: String);
begin
   if FReadOnly and not( csLoading in ComponentState ) then  // wgb
      raise EInvalidArgument.CreateFmt('Medida Somente para leitura, codigo: %s descricao: %s',[self.name,self.descricao])
   else
      FUnidade := Value;
end;

procedure TMedida.SetValid(const Value: Boolean);
// Obs.: Sempre atribua aos atributos Valid e InvalidDesc na seguinte ordem:
// Valid := False;
// InvalidDescr := 'Erro na tabela X'
// ou
// Valid := True; // não se deve atribuir msg a InvalidDescr neste caso
begin
  FValid := Value;
  if not FValid then
     FInvalidDescr := INVALID_VALUE
  else
     FInvalidDescr := '';
end;

procedure TMedida.SetValorNumerico(const Value: String);
begin
   if FReadOnly and not( csLoading in ComponentState ) then
      raise EInvalidArgument.CreateFmt('Medida Somente para leitura, codigo: %s descricao: %s',[self.name,self.descricao])
   else
      begin
         if Value <> '' then
            FEmpty := False
         else
            FEmpty := True;
         FValorNumerico := Value;
         //Troca , por ponto
         if Pos(',', FValorNumerico) > 0 then
            FValorNumerico[Pos(',', FValorNumerico)] := '.';
      end;
end;

function TMedida.UnidadeFormatada: String;
begin
   Result := GetUnidadeApresentacao;
end;

function TMedida.ValorNumericoFormatado: String;
begin
   Result := GetValorApresentacao;
end;

procedure TMedida.WriteUnit(Writer: TWriter);
begin
   Writer.WriteString(InternalStgUnit);
end;

procedure TMedida.WriteValue(Writer: TWriter);
begin
   Writer.WriteString(InternalStgValue);
end;

procedure TMedida.SetInvalidDescr(const Value: String);
begin
  FInvalidDescr := Value;
end;

function TMedida.GetInvalidDescr: String;
begin
   if FInvalidDescr = '' then
      Result := INVALID_VALUE
   else
      Result := FInvalidDescr;
end;

function TMedida.DefStorageInvalidDescr: Boolean;
begin
   Result := not FValid;
end;

{ TMedidaOrdinal }

constructor TMedidaOrdinal.Create(Owner: TComponent);
begin
   inherited;
end;

function TMedidaOrdinal.GetAsFloat: Double;
begin
   if not Empty then
      if Assigned(ListaConstantes) then
         begin
            Result := ListaConstantes.IndexOf(FValorNumerico);
            if Result = -1 then
               raise EInvalidArgument.CreateFmt('Valor nao cadastrado na Lista Global codigo: %s descricao: %s',[self.name,self.descricao]);
         end
      else
         raise EInvalidArgument.CreateFmt('Ponteiro Vazio : ListaConstantes nao foi preenchido',[])
   else
      raise EInvalidArgument.CreateFmt('Medida vazia, a medida codigo: %s descricao: %s não foi preenchida',[self.name,self.descricao]);
end;

function TMedidaOrdinal.GetUnidadeApresentacao: String;
begin
   Result := FUnidade;
end;

function TMedidaOrdinal.GetValorApresentacao: String;
begin
   if not FValid then
      Result := InvalidDescr //INVALID_VALUE
   else if FEmpty then
      Result := EMPTY_VALUE
   else
      Result := FValorNumerico;
end;

function TMedidaOrdinal.GetValorNumerico: String;
begin
   Result := FValorNumerico;
end;

procedure TMedidaOrdinal.SetAsFloat(const Value: Double);
var
   Indice : integer;
begin
   if (Value > -1) and Assigned (ListaConstantes) and (ListaConstantes.Count > Value) then
      begin
         Indice := StrToInt(FloatToStrF(Value, ffFixed, 18, 0));
         ValorNumerico := ListaConstantes.Strings[Indice];
      end;
end;

procedure TMedidaOrdinal.SetValorNumerico(const Value: String);
begin
   if FReadOnly and not( csLoading in ComponentState ) then
      raise EInvalidArgument.CreateFmt('Medida Somente para leitura, codigo: %s descricao: %s',[self.name,self.descricao])
   else
      begin
         if Value <> '' then
            FEmpty := False
         else
            FEmpty := True;
         FValorNumerico := Value;
      end;
end;

{ TMeasureLimit }

procedure TMeasureLimit.Assign(Source: TPersistent);
var
   Limit : TMeasureLimit;
begin
   if Source is TMeasureLimit then
      begin
         Limit := TMeasureLimit(Source);
         Excluded := Limit.Excluded;
         Opened := Limit.Opened;
         Point := Limit.Point;
      end
   else
      inherited Assign(Source);
end;

constructor TMeasureLimit.Create(AOwner: TComponent; PointName: string);
begin
   inherited Create;
   if not(csLoading in AOwner.ComponentState) then
      Point := CreatePoint(AOwner, PointName);
end;

function TMeasureLimit.CreatePoint(AOwner: TComponent; PName: string): TMedida;
begin
   Result := TMedida.Create(AOwner);
   Result.name := PName;
end;

destructor TMeasureLimit.Destroy;
begin
   inherited;
end;

procedure TMeasureLimit.SetCaption(const Value: String);
begin
   FCaption := Value;
end;

procedure TMeasureLimit.SetExcluded(const Value: boolean);
begin
   FExcluded := Value;
end;

procedure TMeasureLimit.SetOpened(const Value: boolean);
begin
   FOpened := Value;
end;

procedure TMeasureLimit.SetPoint(const Value: TMedida);
begin
   FPoint := Value;
end;

{ TMeasurementInterval }

procedure TMeasurementInterval.Assign(Source: TPersistent);
var
   Interval : TMeasurementInterval;
begin
   if Source is TMeasurementInterval then
      begin
         Interval := TMeasurementInterval(Source);
         BeginPoint := Interval.BeginPoint;
         EndPoint := Interval.EndPoint;
         Caption := Interval.Caption;
         OnChange := Interval.OnChange;
      end
   else
      inherited Assign(Source);
end;

procedure TMeasurementInterval.Change;
begin
   if Assigned(FOnChange) then
      OnChange(self);
end;

constructor TMeasurementInterval.Create(Collection: TCollection);
var
   AuxOwner : TComponent;
begin
   inherited Create(Collection);
   AuxOwner := TMeasurementIntervals(Collection).Owner;
   BeginPoint := CreateLimit(AuxOwner, AuxOwner.Name + '_' + GetDisplayName + '_Begin');
   EndPoint := CreateLimit(AuxOwner,AuxOwner.Name + '_' + GetDisplayName + '_End');
end;

function TMeasurementInterval.CreateLimit(AOwner: TComponent;
  LimitName: string): TMeasureLimit;
begin
   Result := TMeasureLimit.Create(AOwner,LimitName);
end;

destructor TMeasurementInterval.Destroy;
begin
   if Assigned(BeginPoint) then
      begin
         if Assigned(BeginPoint.Point) then BeginPoint.Point.Free;
            BeginPoint.Free;
      end;
   if Assigned(EndPoint) then
      begin
         if Assigned(EndPoint.Point) then EndPoint.Point.Free;
            EndPoint.Free;
      end;
   //Forca o chamado de AdjustPointNames
   TMeasurementIntervals(Collection).Owner.Name := TMeasurementIntervals(Collection).Owner.Name;
   inherited;
end;

function TMeasurementInterval.GetDisplayName: string;
   function ChangeIdent(const Ident: string): string;
   const
      Alpha = ['A'..'Z', 'a'..'z', '_'];
      AlphaNumeric = Alpha + ['0'..'9'] + [' '];
   var
      I: Integer;
   begin
      Result := '';
      if (Length(Ident) = 0) then
         Result := Ident
      else
         for I := 1 to Length(Ident) do
      if (Ident[I] in AlphaNumeric) then
         Result := Result + Ident[I];
   end;
var
   I : integer;
begin
   Result := ChangeIdent( Caption );
   if ( Result = '' ) or FAutoName then
      begin
         Result := inherited GetDisplayName + inttostr(Index);
         Result := copy(Result,2,Length(Result));
      end;
   repeat
      I := Pos(' ', Result);
      if (I > 0) then
         Result [I] := '_';
   until I = 0;
end;

function TMeasurementInterval.Has(AMedida: TMedida;
  var ANearPoint: TMeasureLimit; var Percent: Double): boolean;
var
   NearBegin,
   Delta : Double;
begin
   // A medida está dentro da faixa
   if Has( AMedida ) then
   begin
      Result := True;
      // Não existe ponto próximo pois ambos são infinitos
      if FBeginPoint.FOpened and FEndPoint.FOpened then
      begin
         ANearPoint := nil;
         Percent := 0;
      end
      // O mais próximo é o EndPoint
      else if FBeginPoint.FOpened then
      begin
         ANearPoint := FEndPoint;
         Percent := 0;
      end
      // O mais próximo é o BeginPoint
      else if FEndPoint.FOpened then
      begin
         ANearPoint := FBeginPoint;
         Percent := 0;
      end
      else // calculando sobre uma faixa fechada
      begin
         Delta := FEndPoint.Point.AsFloat - FBeginPoint.Point.AsFloat;
         // Os pontos são iguais
         if Delta = 0 then
         begin
            // Por eliminação é o EndPoint
            if FBeginPoint.Excluded and not FEndPoint.Excluded then
            begin
               ANearPoint := FEndPoint;
               Percent := 100;
            end
            // Por eliminação é o BeginPoint
            else if EndPoint.Excluded and not FBeginPoint.Excluded then
            begin
               ANearPoint := FBeginPoint;
               Percent := 100;
            end
            // intervalo vazio {} Isto nunca acontecerá, mas fica como documentação
            else if EndPoint.Excluded and not FBeginPoint.Excluded then
            begin
               ANearPoint := nil;
               Percent := 0;
            end;
         end
         else
         begin
            // Quantos % a medida está do BeginPoint
            NearBegin := 100-((AMedida.AsFloat - FBeginPoint.Point.AsFloat)/Delta*100);
            // Corrigindo o valor do NearBegin quando alguma ponta for excluded
            if FBeginPoint.Excluded then
               NearBegin := NearBegin + 0.0001
            else if FEndPoint.Excluded then
               NearBegin := NearBegin - 0.0001;
            if NearBegin = 50 then // Bem no meio, não tem um próximo
            begin
               ANearPoint := nil;
               Percent := 50;
            end
            else if NearBegin > 50 then // Mais próximo do BeginPoint
            begin
               ANearPoint := FBeginPoint;
               Percent := NearBegin;
            end
            else // Mais próximo do EndPoint
            begin
               ANearPoint := FEndPoint;
               Percent := 100-NearBegin;
            end;
         end;
      end;
   end
   else
   // Não está dentro da faixa
   begin
      ANearPoint := nil;
      Percent := 0;
      Result := False;
   end;
end;

function TMeasurementInterval.Has(AMedida: TMedida): boolean;
begin
   Result := True;
   if not FBeginPoint.FOpened then
      begin
         if FBeginPoint.FExcluded then
            Result := ( Result and (AMedida.GT(FBeginPoint.Point)))
         else
            Result := ( Result and (AMedida.GTE(FBeginPoint.Point)));
      end;
   if not  FEndPoint.FOpened then
      begin
         if FEndPoint.FExcluded then
            Result := ( Result and FEndPoint.Point.GT(AMedida))
         else
            Result := ( Result and FEndPoint.Point.GTE(AMedida));
      end;
end;

procedure TMeasurementInterval.SetAutoName(const Value: Boolean);
begin
   FAutoName := Value;
end;

procedure TMeasurementInterval.SetBeginPoint(const Value: TMeasureLimit);
begin
   FBeginPoint := Value;
end;

procedure TMeasurementInterval.SetCaption(const Value: string);
begin
   FCaption := Value;
   //Forca o chamado de AdjustPointNames
   TMeasurementIntervals(Collection).Owner.Name := TMeasurementIntervals(Collection).Owner.Name;
end;

procedure TMeasurementInterval.SetEndPoint(const Value: TMeasureLimit);
begin
   FEndPoint := Value;
end;

procedure TMeasurementInterval.SetOnChange(const Value: TNotifyEvent);
begin
   FOnChange := Value;
end;

{ TMeasurementIntervals }

function TMeasurementIntervals.Add: TMeasurementInterval;
begin
   Result := TMeasurementInterval(inherited Add);
end;

procedure TMeasurementIntervals.Clear;
begin
   inherited Clear;
   Owner.DestroyComponents;
end;

constructor TMeasurementIntervals.Create(AOwner: TMeasurementRanges;
  ItemClass: TCollectionItemClass);
begin
   inherited Create(ItemClass);
   FOwner := AOwner;
end;

function TMeasurementIntervals.Find(const DisplayName: string): TMeasurementInterval;
var
   I: Integer;
begin
   I := IndexOf(DisplayName);
   if I < 0 then Result := nil else Result := TMeasurementInterval(Items[I]);
end;

function TMeasurementIntervals.GetItem(Index: Integer): TMeasurementInterval;
begin
   Result := TMeasurementInterval(inherited GetItem(Index));
end;

function TMeasurementIntervals.GetOwner: TPersistent;
begin
   Result := FOwner;
end;

function TMeasurementIntervals.IndexOf(const DisplayName: string): Integer;
begin
   for Result := 0 to Count - 1 do
      if AnsiCompareText(TMeasurementInterval(Items[Result]).DisplayName, DisplayName) = 0 then Exit;
   Result := -1;
end;

procedure TMeasurementIntervals.SetItem(Index: Integer; Value: TMeasurementInterval);
begin
   inherited SetItem(Index, Value);
end;

procedure TMeasurementIntervals.Update(Item: TCollectionItem);
begin
   if Item <> nil then
      Owner.UpdateInterval(Item.Index)
   else
      Owner.UpdateIntervals;
end;

{ TMeasurementRanges }

procedure TMeasurementRanges.AdjustPointNames;
var
   I : Integer;
   MedidaIndx : Integer;
begin
   MedidaIndx := 0;
   for I := 0 to ComponentCount-1 do
      if (Components[I] is TMedida) then
         begin
            if ((MedidaIndx mod 2)=0) then
               Components[MedidaIndx].name := Name + '_' + FRanges.Items[MedidaIndx div 2].GetDisplayName + '_Begin'
            else
               Components[MedidaIndx].name := Name + '_' + FRanges.Items[MedidaIndx div 2].GetDisplayName + '_End';
            Inc(MedidaIndx);
         end;
end;

constructor TMeasurementRanges.Create(AOwner: TComponent);
begin
   inherited;
   FPointList := TStringList.Create;
   FRanges := CreateRange(AOwner);
end;

function TMeasurementRanges.CreateRange(AOwner: TComponent): TMeasurementIntervals;
begin
   Result := TMeasurementIntervals.Create(self, TMeasurementInterval);
end;

destructor TMeasurementRanges.Destroy;
begin
   if Assigned(FRanges) then
      FRanges.Free;
   if Assigned(FPointList) then
      FPointList.Free;
   inherited;
end;

procedure TMeasurementRanges.GetChildren(Proc: TGetChildProc;Root: TComponent);
var
   I: Integer;
   OwnedComponent: TComponent;
begin
   inherited GetChildren(Proc, Root);
   for I := 0 to ComponentCount - 1 do
      begin
         OwnedComponent := Components[I];
         if not OwnedComponent.HasParent then
            Proc(OwnedComponent);
      end;
end;

procedure TMeasurementRanges.Loaded;
var
   I : Integer;
   Temp, Obj : TComponent;
begin
   if Assigned(Owner) then
      for I := 0 to FPointList.Count-1 do
         begin
            //Procura o componente no form
            Obj := Owner.FindComponent(FPointList.Strings[I]);
            Temp := Obj;
            if not Assigned(Temp) then
               continue;
            //Tira do form
            Obj.Owner.RemoveComponent(Temp);
            //Poe no componente
            InsertComponent(Temp);
            //Acerta os Points dos Limits
            if ((I mod 2)=0) then
               FRanges.Items[I div 2].BeginPoint.Point := TMedida(Temp)
            else
               FRanges.Items[I div 2].EndPoint.Point := TMedida(Temp);
         end;
   inherited;
   AdjustPointNames;
end;

procedure TMeasurementRanges.Notification(AComponent: TComponent; Operation: TOperation);
var
   I : integer;
begin
   inherited;
   if (not Assigned(AComponent)) or (AComponent=self) then
      Exit;
   if (Operation = opRemove) and (AComponent.Owner = self) then
       if FPointList.IndexOf(AComponent.Name) > 0 then
          begin
             I := FPointList.IndexOf(AComponent.Name);
             FPointList.Delete(I);
          end;
end;

procedure TMeasurementRanges.SetName(const NewName: TComponentName);
begin
   inherited;
   AdjustPointNames;
end;

procedure TMeasurementRanges.SetPointList(const Value: TStrings);
begin
//
end;

procedure TMeasurementRanges.SetRanges(const Value: TMeasurementIntervals);
begin
   FRanges.Assign(Value);
end;

procedure TMeasurementRanges.UpdateInterval(ItemIndex: integer);
begin
//
end;

procedure TMeasurementRanges.UpdateIntervals;
begin
//
end;

procedure TMeasurementRanges.ValidateRename(AComponent: TComponent;
  const CurName, NewName: string);
begin
   if Assigned(AComponent) then
      begin
         if FPointList.IndexOf(CurName) >= 0 then
            FPointList.Delete(FPointList.IndexOf(CurName));
         if (NewName <> '') and (FPointList.IndexOf(NewName) < 0) then
            begin
               FPointList.Add(NewName);
            end;
      end;
   inherited;
end;

end.
