// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TPainelMedida                                   }
{                                                                    }
{   Mostra medidas, seus valores numericos e suas unidades           }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file                                       }
{   d:\dados\projetos\componentes delphi\medida\quantity.cd          }
{   on 28 June 1997 at 6:35                                          }
{                                                                    }
{   Copyright © 1997 by DIS-EPM/UNIFESP                              }
{                                                                    }
{ ****************************************************************** }

unit PainelMedida;

interface

uses Classes, SysUtils, ExtCtrls, DsgnIntf, Controls, Dialogs, Mask, StdCtrls,
     Clipbrd, QRCTRLS, LblCmpnt, FnpNumericEdit, FnpNEditBlank, Measurement;

type

   TStateMode = (Edit, Convert);

   pStringRef = ^string;

   //Gambiarra para acessar o Checked private.
   TMyBtnControl = class(TButtonControl);
   TMyControl = class (TControl);
   TMyCustComboBox = class (TCustomComboBox);
   TMyCustListBox = class (TCustomListBox);
   TMyCustEdit = class (TCustomEdit);

   TPainelMedida = class(TPanel)
   private
      FNomeMedida : String;
      FSaidaDescricao : TControl;
      FEntradaNumerica : TControl;
      FEntradaDeUnidade : TControl;
      FBotaoReset : TButtonControl;
      FMedida : TMedida;
      FOnChangeValue : TNotifyEvent;
      FOnChangeUnit : TNotifyEvent;
//      FOnEditing : TNotifyEvent;
//      FOnConverting : TNotifyEvent;
      {Determina se a conversao automatica esta habilitada ou nao}
      FAutoConvert : Boolean;
      {Indica que o valor ou a unidade foi alterado}
      Modified : Boolean;
   protected
      Mode: TStateMode;
      procedure Notification(AComponent : TComponent; Operation : TOperation); override;
      procedure ChangeValue(Sender: TObject);
      procedure ChangeUnit(Sender: TObject);
      procedure Loaded; override;
      procedure SetSaidaDescricao(Value : TControl);
//      procedure SetBotaoReset(Value : TButtonControl);
      procedure SetEntradaNumerica(Value : TControl);
      procedure SetEntradaDeUnidade(Value : TControl);
      procedure SetMedida (Value : TMedida);
      procedure EndingConvertMode(Sender: TObject);
      procedure DoExit; override;
      procedure GetValores(Valor: TControl; Texto : pStringRef);
      procedure PrepareValores (DisplayValor: TControl; ListaValores: TStrings; Valor, ValorApresentacao: string;IdxDefault:Integer) ;
   public
      constructor Create(AOwner: TComponent); override;
      destructor Destroy; override;
      procedure Refresh;
      procedure Update; override;
   published
      { O valor numerico foi alterado }
      property OnChangeValue : TNotifyEvent read FOnChangeValue write FOnChangeValue;
      { A unidade foi alterada }
      property OnChangeUnit : TNotifyEvent read FOnChangeUnit write FOnChangeUnit;
      { Igual ao Name da Medida }
      property NomeMedida : String read FNomeMedida write FnomeMedida;
      { Entrou em modo edicao }
      property SaidaDescricao : TControl read FSaidaDescricao write SetSaidaDescricao;
      { Entrou em modo edicao }
      property EntradaNumerica : TControl read FEntradaNumerica write SetEntradaNumerica;
      { Campo para a seleção da Unidade }
      property EntradaDeUnidade : TControl read FEntradaDeUnidade write SetEntradaDeUnidade;
      { Campo para a seleção da Unidade }
      property Medida : TMedida read FMedida write SetMedida;
      { Botao para restaurar o default }
      property BotaoReset : TButtonControl read FBotaoReset write FBotaoReset; //SetBotaoReset;
      {Determina se a conversao automatica esta habilitada ou nao}
      property AutoConversion : Boolean read FAutoConvert write FAutoConvert default False;
   end;

   TGBoxMedida = class(TGroupBox)
   private
      FNomeMedida : String;
      FSaidaDescricao : TControl;
      FEntradaNumerica : TControl;
      FEntradaDeUnidade : TControl;
      FBotaoReset : TButtonControl;
      FMedida : TMedida;
      FOnChangeValue : TNotifyEvent;
      FOnChangeUnit : TNotifyEvent;
//      FOnEditing : TNotifyEvent;
//      FOnConverting : TNotifyEvent;
      {Determina se a conversao automatica esta habilitada ou nao}
      FAutoConvert : Boolean;
      {Indica que o valor ou a unidade foi alterado}
      Modified : Boolean;
      FCntlEstimatedTrue: TControl;
      FCntlEstimatedFalse: TControl;
      procedure SetCntlEstimatedFalse(const Value: TControl);
      procedure SetCntlEstimatedTrue(const Value: TControl);
   protected
      Mode: TStateMode;
      procedure Notification(AComponent : TComponent; Operation : TOperation); override;
      procedure ChangeValue(Sender: TObject);
      procedure ChangeUnit(Sender: TObject);
      procedure Loaded; override;
      procedure SetSaidaDescricao(Value : TControl);
//      procedure SetBotaoReset(Value : TButtonControl);
      procedure SetEntradaNumerica(Value : TControl);
      procedure SetEntradaDeUnidade(Value : TControl);
      procedure SetMedida (Value : TMedida);
      procedure EndingConvertMode(Sender: TObject);
      procedure DoExit; override;
      procedure GetValores(Valor: TControl; Texto : pStringRef);
      procedure PrepareValores (DisplayValor: TControl; ListaValores: TStrings; Valor, ValorApresentacao: string;IdxDefault:Integer) ;
   public
      constructor Create(AOwner: TComponent); override;
      destructor Destroy; override;
      procedure Refresh;
      procedure Update; override;
   published
      { O valor numerico foi alterado }
      property OnChangeValue : TNotifyEvent read FOnChangeValue write FOnChangeValue;
      { A unidade foi alterada }
      property OnChangeUnit : TNotifyEvent read FOnChangeUnit write FOnChangeUnit;
      { Igual ao Name da Medida }
      property NomeMedida : String read FNomeMedida write FnomeMedida;
      { Entrou em modo edicao }
      property SaidaDescricao : TControl read FSaidaDescricao write SetSaidaDescricao;
      { Entrou em modo edicao }
      property EntradaNumerica : TControl read FEntradaNumerica write SetEntradaNumerica;
      { Campo para a seleção da Unidade }
      property EntradaDeUnidade : TControl read FEntradaDeUnidade write SetEntradaDeUnidade;
      { Campo para a seleção da Unidade }
      property Medida : TMedida read FMedida write SetMedida;
      { Botao para restaurar o default }
      property BotaoReset : TButtonControl read FBotaoReset write FBotaoReset; // SetBotaoReset;
      {Determina se a conversao automatica esta habilitada ou nao}
      property AutoConversion : Boolean read FAutoConvert write FAutoConvert default False;
      property CntlEstimatedTrue: TControl read FCntlEstimatedTrue write SetCntlEstimatedTrue;
      property CntlEstimatedFalse: TControl read FCntlEstimatedFalse write SetCntlEstimatedFalse;
   end;

procedure DigitaValor (Display : TControl; Valor : string);

procedure Register;

implementation

procedure Register;
begin
   RegisterComponents('Medida', [TPainelMedida]);
   RegisterComponents('Medida', [TGBoxMedida]);
   RegisterPropertyEditor(TypeInfo(TControl), TPainelMedida,
                          'EntradaDeUnidade', TLabeledComponentsProperty);
   RegisterPropertyEditor(TypeInfo(TControl), TPainelMedida,
                          'EntradaNumerica', TLabeledComponentsProperty);
   RegisterPropertyEditor(TypeInfo(TControl), TGBoxMedida,
                          'EntradaDeUnidade', TLabeledComponentsProperty);
   RegisterPropertyEditor(TypeInfo(TControl), TGBoxMedida,
                          'EntradaNumerica', TLabeledComponentsProperty);
end;

{ TPainelMedida }

procedure TPainelMedida.DoExit;
begin
   if Mode = Convert then
      exit;
   Update;
   Mode := Convert;
   inherited DoExit;
end;

procedure TPainelMedida.EndingConvertMode(Sender: TObject);
begin
   Mode:= Edit;
end;

procedure TPainelMedida.Update;
var
   NewValue,NewUnit: string;
begin
   inherited Update;
   if (not assigned(FMedida)) or (not assigned(FEntradaNumerica)) or
      (not Modified) or (not assigned (FEntradaDeUnidade)) then exit;
      //Obtenha os valores
      GetValores(FEntradaNumerica, @NewValue);
      GetValores(FEntradaDeUnidade, @NewUnit);
      //Atualize
      if Mode = Edit then
      begin
         FMedida.SetMedida(NewValue, NewUnit);
      end
      else
         FMedida.ConvertToUnit(NewUnit);
      Modified:= False;
      Refresh;
end;

procedure TPainelMedida.Notification(AComponent : TComponent; Operation : TOperation);
begin
   inherited Notification(AComponent, Operation);
   if Operation <> opRemove then
      Exit;
   if AComponent = FSaidaDescricao then
      FSaidaDescricao := nil;
   if AComponent = FEntradaNumerica then
      FEntradaNumerica := nil;
   if AComponent = FEntradaDeUnidade then
      FEntradaDeUnidade := nil;
   if AComponent = FBotaoReset then
      FBotaoReset := nil;
   if AComponent = FMedida then
      FMedida := nil;
end;

procedure TPainelMedida.ChangeValue;
begin
   Modified := True;
   if Assigned(FOnChangeValue) then
      FOnChangeValue(Self)
end;

procedure TPainelMedida.ChangeUnit;
begin
   Modified := True;
   if Assigned(FOnChangeUnit) then
      FOnChangeUnit(Self);
   Update;
   Mode := Convert;
end;

constructor TPainelMedida.Create(AOwner: TComponent);
begin
   inherited Create(AOwner);
   FSaidaDescricao := nil;
   FEntradaNumerica := nil;
   FEntradaDeUnidade := nil;
   FBotaoReset := nil;
   FAutoConvert:=False;
   Mode:=Edit;
end;

destructor TPainelMedida.Destroy;
begin
   inherited Destroy;
end;

procedure TPainelMedida.Loaded;
begin
   inherited Loaded;
end;

procedure TPainelMedida.SetMedida (Value : TMedida);
begin
   if Value <> nil then
   begin
      Value.FreeNotification(Self);
      FMedida := Value;
      Refresh;
   end
   else
      FMedida := Value;
end;

procedure TPainelMedida.Refresh;
begin
   if not assigned (FMedida) then
      exit;
   if (assigned(FSaidaDescricao)) then
   begin
      //Prepare Valores Numericos - TMaskEdit
      if (FSaidaDescricao is TLabel) then
      begin
         (FSaidaDescricao as TLabel).Caption := FMedida.Descricao;
      end
      else if (FSaidaDescricao is TQRLabel) then
      begin
         (FSaidaDescricao as TQRLabel).Caption := FMedida.Descricao;
      end;
   end;
   if (assigned(FEntradaNumerica)) then
   begin
      //Prepare Valores Numericos - TMaskEdit
      if (FEntradaNumerica is TMaskEdit) then
      begin
         (FEntradaNumerica as TMaskEdit).EditMask := FMedida.MascaraNumeros;
         (FEntradaNumerica as TMaskEdit).Text := FMedida.ValorNumerico; // Apresentacao;
      end;
      //Prepare Valores Numericos - O resto
      PrepareValores (FEntradaNumerica, FMedida.ListaValores, FMedida.ValorNumerico, FMedida.ValorApresentacao,FMedida.IdxVDefault );
   end;
   if (assigned(FEntradaDeUnidade)) then
      //Prepare Unidades (nao usam mascara)
      if ( FEntradaNumerica is TLabel ) then // a unidade tem que ser de apresentação
         PrepareValores(FEntradaDeUnidade, FMedida.ListaUnidades, FMedida.Unidade, FMedida.UnidadeApresentacao,FMedida.IdxUDefault )
      else // a unidade não é de apresentação, pois senão daria unidade em branco (mais uma gamby)
         PrepareValores(FEntradaDeUnidade, FMedida.ListaUnidades, FMedida.Unidade, FMedida.Unidade,FMedida.IdxUDefault );

   Mode := Convert;
end;

// PrepareValores: Atualiza os controls segundo o seu tipo
procedure TPainelMedida.PrepareValores (DisplayValor: TControl; ListaValores: TStrings; Valor, ValorApresentacao: string;IdxDefault:Integer) ;
var
   YGambe : TMyCustComboBox;
   ZGambe : TMyCustListBox;
   WGambe : TMyCustEdit;
begin
   if (DisplayValor is TCustomListBox) then
   begin
      ZGambe := TMyCustListBox(DisplayValor);
      ZGambe.Items.BeginUpdate;
      try
         ZGambe.Items.Assign (ListaValores);
         if Valor <> '' then
            ZGambe.ItemIndex := ZGambe.Items.IndexOf(Valor)
         else
            ZGambe.ItemIndex := IdxDefault;
      finally
         ZGambe.Items.EndUpdate;
      end;
   end
   else if (DisplayValor is TCustomComboBox) then
      begin
         YGambe := TMyCustComboBox(DisplayValor);
         YGambe.Items.BeginUpdate;
         try
            if YGambe.Items.Count = 0 then
               YGambe.Items.Assign (ListaValores);
            YGambe.Style := csDropDownList;
            if Valor <> '' then
               YGambe.ItemIndex := YGambe.Items.IndexOf(Valor)
            else
               YGambe.ItemIndex := IdxDefault;
         finally
            YGambe.Items.EndUpdate;
         end;
      end
   else if (DisplayValor is TQRLabel) then
      (DisplayValor as TQRLabel).Caption := ValorApresentacao
   else if (DisplayValor is TFnpNumericEdit) then
      begin
         if (DisplayValor is TFnpNEditBlank) then
            try
               if  Valor <> '' then
               begin
                  (DisplayValor as TFnpNEditBlank).AsFloat := StrToFloat(Valor);
               end;
            except
               on EConvertError do ShowMessage('Valor inválido : ' + Valor);
            end
         else
            try
               (DisplayValor as TFnpNumericEdit).AsFloat := StrToFloat (Valor);
            except
               on EConvertError do ShowMessage ('Valor não numérico : '+Valor);
            end;
      end
   else
      begin
         WGambe := TMyCustEdit(DisplayValor);
         if ( DisplayValor is TLabel ) then
            WGambe.Text := ValorApresentacao
         else
            WGambe.Text := Valor;
      end;
end;

// GetValores: Le os controls segundo o seu tipo
procedure TPainelMedida.GetValores(Valor: TControl; Texto : pStringRef);
var
   XGambe : TMyControl;
begin
   XGambe := TMyControl(Valor);
   Texto^ := XGambe.Text;
   if (Valor is TQRLabel) then
      Texto^ := (Valor as TQRLabel).Caption;
end;

procedure TPainelMedida.SetSaidaDescricao(Value : TControl);
begin
   FSaidaDescricao := Value;
end;

procedure TPainelMedida.SetEntradaNumerica(Value : TControl);
var
   YGambe : TMyCustComboBox;
   ZGambe : TMyCustListBox;
   QGambe : TMyCustEdit;
begin
   if Value <> nil then
   begin
      if (Value is TCustomEdit) then
      begin
         QGambe := TMyCustEdit(Value);
         QGambe.OnEnter := EndingConvertMode;
         QGambe.OnChange := ChangeValue;
      end
   else if (Value is TCustomComboBox) then
      begin
         YGambe := TMyCustComboBox(Value);
         YGambe.OnEnter := EndingConvertMode;
         YGambe.OnChange := ChangeValue;
      end
   else if (Value is TCustomListBox) then
      begin
         ZGambe := TMyCustListBox(Value);
         ZGambe.OnEnter := EndingConvertMode;
         ZGambe.OnClick := ChangeValue;
      end
   else if not ( (Value is TLabel) or (Value is TQRLabel) ) then
         exit;
      Value.FreeNotification(Self);
   end;
   FEntradaNumerica:=Value;
end;

procedure TPainelMedida.SetEntradaDeUnidade(Value : TControl);
var
   YGambe : TMyCustComboBox;
   ZGambe : TMyCustListBox;
   QGambe : TMyCustEdit;
begin
   FEntradaDeUnidade := Value;
   if Value <> nil then
   begin
      if (Value is TCustomEdit) then
      begin
         QGambe := TMyCustEdit(Value);
         QGambe.OnChange := ChangeValue;
      end
   else if (Value is TCustomComboBox) then
      begin
         YGambe := TMyCustComboBox(Value);
         YGambe.OnChange := ChangeValue;
      end
   else if (Value is TCustomListBox) then
      begin
         ZGambe := TMyCustListBox(Value);
         ZGambe.OnClick := ChangeValue;
      end
   else if not ( (Value is TLabel) or (Value is TQRLabel) ) then
      exit;
   end;
end;

// Write method for property BotaoReset
{procedure TPainelMedida.SetBotaoReset(Value : TButtonControl);
begin

end;
}

{ TGBoxMedida }

procedure TGBoxMedida.DoExit;
begin
   if Mode = Convert then
      exit;
   Update;
   Mode := Convert;
   inherited DoExit;
end;

procedure TGBoxMedida.EndingConvertMode(Sender: TObject);
begin
   Mode:= Edit;
end;

procedure TGBoxMedida.Update;
var
   NewValue, NewUnit : string;
   Xgambe : TMyBtnControl;
begin
   inherited Update;
   if (not assigned (FMedida)) or (not assigned (FEntradaNumerica)) or
      (not Modified) or (not assigned (FEntradaDeUnidade)) then
      exit;
   //Obtenha os valores
   GetValores(FEntradaNumerica, @NewValue);
   GetValores (FEntradaDeUnidade, @NewUnit);
   //Atualize
   if Mode = Edit then
      FMedida.SetMedida(NewValue, NewUnit)
   else
      FMedida.ConvertToUnit(NewUnit);
   if (Assigned(FCntlEstimatedTrue))then
   begin
      if (FCntlEstimatedTrue is TButtonControl) then
      begin
         Xgambe := TMyBtnControl(FCntlEstimatedTrue);
         FMedida.Estimated := Xgambe.Checked;
      end
   else
      FMedida.Estimated := FCntlEstimatedTrue.Visible;
   end;
   Modified:= False;
   Refresh;
end;

procedure TGBoxMedida.Notification(AComponent : TComponent; Operation : TOperation);
begin
   inherited Notification(AComponent, Operation);
   if Operation <> opRemove then
      Exit;
   if AComponent = FSaidaDescricao then
      FSaidaDescricao := nil;
   if AComponent = FEntradaNumerica then
      FEntradaNumerica := nil;
   if AComponent = FEntradaDeUnidade then
      FEntradaDeUnidade := nil;
   if AComponent = FBotaoReset then
      FBotaoReset := nil;
   if AComponent = FMedida then
      FMedida := nil;
   if AComponent = FCntlEstimatedTrue then
      FCntlEstimatedTrue := nil;
   if AComponent = FCntlEstimatedFalse then
      FCntlEstimatedFalse := nil;
end;

procedure TGBoxMedida.ChangeValue;
begin
   Modified:= True;
   if Assigned(FOnChangeValue) then
      FOnChangeValue(Self)
end;

procedure TGBoxMedida.ChangeUnit;
begin
   Modified:= True;
   if Assigned(FOnChangeUnit) then
      FOnChangeUnit(Self);
   Update;
   Mode := Convert;
end;

constructor TGBoxMedida.Create(AOwner: TComponent);
begin
   inherited Create(AOwner);
   FSaidaDescricao := nil;
   FEntradaNumerica := nil;
   FEntradaDeUnidade := nil;
   FBotaoReset := nil;
   FAutoConvert:=False;
   Mode:=Edit;
end;

destructor TGBoxMedida.Destroy;
begin
   inherited Destroy;
end;

procedure TGBoxMedida.Loaded;
begin
   inherited Loaded;
end;

procedure TGBoxMedida.SetMedida (Value : TMedida);
begin
   if Value <> nil then
   begin
      Value.FreeNotification(Self);
      FMedida := Value;
      Refresh;
   end
   else
       FMedida := Value;
end;

// Refresh: Atualiza os controls com os valores da medida
procedure TGBoxMedida.Refresh;
var
   Xgambe : TMyBtnControl;
begin
   if not assigned (FMedida) then
      exit;
   if (assigned (FSaidaDescricao)) then
   begin
      //Prepare Valores Numericos - TMaskEdit
      if (FSaidaDescricao is TLabel) then
      begin
         (FSaidaDescricao as TLabel).Caption := FMedida.Descricao;
      end
      else if (FSaidaDescricao is TQRLabel) then
      begin
         (FSaidaDescricao as TQRLabel).Caption := FMedida.Descricao;
      end;
   end
   else
      Caption := FMedida.Descricao;
   if (Assigned(FCntlEstimatedTrue)) then
   begin
      if (FCntlEstimatedTrue is TButtonControl) then
      begin
         Xgambe := TMyBtnControl(FCntlEstimatedTrue);
         Xgambe.Checked := FMedida.Estimated;
      end
      else
         FCntlEstimatedTrue.Visible := FMedida.Estimated;
   end;
   if (Assigned(FCntlEstimatedFalse)) then
   begin
      if (FCntlEstimatedFalse is TButtonControl) then
      begin
         Xgambe := TMyBtnControl(FCntlEstimatedFalse);
         Xgambe.Checked := not FMedida.Estimated;
      end
      else
         FCntlEstimatedFalse.Visible := not FMedida.Estimated;
   end;
   if (assigned (FEntradaNumerica)) then
   begin
      //Prepare Valores Numericos - TMaskEdit
      if (FEntradaNumerica is TMaskEdit) then
      begin
         (FEntradaNumerica as TMaskEdit).EditMask := FMedida.MascaraNumeros;
         (FEntradaNumerica as TMaskEdit).Text := FMedida.ValorNumerico; // Apresentacao;
      end;
      //Prepare Valores Numericos - O resto
      PrepareValores(FEntradaNumerica, FMedida.ListaValores, FMedida.ValorNumerico, FMedida.ValorApresentacao,FMedida.IdxVDefault );
   end;
   if (assigned(FEntradaDeUnidade)) then
      //Prepare Unidades (nao usam mascara)
      PrepareValores(FEntradaDeUnidade, FMedida.ListaUnidades, FMedida.Unidade, FMedida.UnidadeApresentacao,FMedida.IdxUDefault );
   Mode := Convert;
end;
// PrepareValores: Atualiza os controls segundo o seu tipo
procedure TGBoxMedida.PrepareValores (DisplayValor: TControl; ListaValores: TStrings; Valor, ValorApresentacao: string;IdxDefault:Integer) ;
var
   YGambe : TMyCustComboBox;
   ZGambe : TMyCustListBox;
   WGambe : TMyCustEdit;
begin
   if (DisplayValor is TCustomListBox) then
   begin
      ZGambe:=TMyCustListBox (DisplayValor);
      ZGambe.Items.BeginUpdate;
      try
         ZGambe.Items.Assign (ListaValores);
         if Valor <> '' then
            ZGambe.ItemIndex := ZGambe.Items.IndexOf(Valor)
         else
            ZGambe.ItemIndex := IdxDefault;
      finally
         ZGambe.Items.EndUpdate;
      end;
   end
   else if (DisplayValor is TCustomComboBox) then
   begin
      YGambe := TMyCustComboBox(DisplayValor);
      YGambe.Items.BeginUpdate;
      try
         if YGambe.Items.Count = 0 then
            YGambe.Items.Assign (ListaValores);
         YGambe.Style := csDropDownList;
         if Valor <> '' then
            YGambe.ItemIndex :=YGambe.Items.IndexOf(Valor)
         else
            YGambe.ItemIndex := IdxDefault;
      finally
         YGambe.Items.EndUpdate;
      end;
   end
   else if (DisplayValor is TQRLabel) then
      (DisplayValor as TQRLabel).Caption := ValorApresentacao
   else if (DisplayValor is TFnpNumericEdit) then
   begin
      if (DisplayValor is TFnpNEditBlank) then
      try
         if  Valor <> '' then
         begin
            (DisplayValor as TFnpNEditBlank).AsFloat := StrToFloat (Valor);
         end;
      except
         on EConvertError do ShowMessage ('Valor inválido : '+ Valor);
      end
      else
         try
            (DisplayValor as TFnpNumericEdit).AsFloat := StrToFloat (Valor);
         except
            on EConvertError do ShowMessage ('Valor não numérico : '+ Valor);
         end;
   end
   else
   begin
      WGambe := TMyCustEdit(DisplayValor);
      WGambe.Text := Valor;
   end;
end;

// GetValores: Le os controls segundo o seu tipo
procedure TGBoxMedida.GetValores(Valor: TControl; Texto : pStringRef);
var
   XGambe : TMyControl;
begin
   XGambe := TMyControl(Valor);
   Texto^ := XGambe.Text;
   if (Valor is TQRLabel) then
      Texto^ := (Valor as TQRLabel).Caption;
end;

procedure TGBoxMedida.SetSaidaDescricao(Value : TControl);
begin
   FSaidaDescricao := Value;
end;

procedure TGBoxMedida.SetEntradaNumerica(Value : TControl);
var
   YGambe : TMyCustComboBox;
   ZGambe : TMyCustListBox;
   QGambe : TMyCustEdit;
begin
   if Value <> nil then
   begin
      if (Value is TCustomEdit) then
      begin
         QGambe := TMyCustEdit(Value);
         QGambe.OnEnter := EndingConvertMode;
         QGambe.OnChange := ChangeValue;
      end
      else if (Value is TCustomComboBox) then
      begin
         YGambe := TMyCustComboBox(Value);
         YGambe.OnEnter := EndingConvertMode;
         YGambe.OnChange := ChangeValue;
      end
      else if (Value is TCustomListBox) then
      begin
         ZGambe := TMyCustListBox(Value);
         ZGambe.OnEnter := EndingConvertMode;
         ZGambe.OnClick := ChangeValue;
      end
      else if not ( (Value is TLabel) or (Value is TQRLabel) ) then
         exit;
      Value.FreeNotification(Self);
   end;
   FEntradaNumerica:=Value;
end;

procedure TGBoxMedida.SetEntradaDeUnidade(Value : TControl);
var
   YGambe : TMyCustComboBox;
   ZGambe : TMyCustListBox;
   QGambe : TMyCustEdit;
begin
   FEntradaDeUnidade:=Value;
   if Value <> nil then
   begin
      if (Value is TCustomEdit) then
      begin
         QGambe := TMyCustEdit(Value);
         QGambe.OnChange := ChangeValue;
      end
      else if (Value is TCustomComboBox) then
      begin
         YGambe := TMyCustComboBox(Value);
         YGambe.OnChange := ChangeValue;
      end
      else if (Value is TCustomListBox) then
      begin
         ZGambe := TMyCustListBox(Value);
         ZGambe.OnClick := ChangeValue;
      end
      else if not ( (Value is TLabel) or (Value is TQRLabel) )then
         exit;
   end;
end;

procedure TGBoxMedida.SetCntlEstimatedFalse(const Value: TControl);
begin
   FCntlEstimatedFalse := Value;
end;

procedure TGBoxMedida.SetCntlEstimatedTrue(const Value: TControl);
begin
   FCntlEstimatedTrue := Value;
end;

procedure DigitaValor (Display : TControl; Valor : string);
var
   QGambe : TMyCustEdit;
   XGambe : TMyControl;
   MyClp : TClipboard;
begin
   MyClp:=Clipboard;
   if Display <> nil then
   begin
      if (Display is TCustomEdit) then
      begin
         QGambe := TMyCustEdit(Display);
         if QGambe.ReadOnly then
            QGambe.Text:= Valor
         else
         begin
            MyClp.AsText := Valor;
            QGambe.SelStart := 0;
            QGambe.SelLength := Length(QGambe.Text);
            QGambe.PasteFromClipboard;
         end;
      end
      else
      begin
         XGambe := TMyControl (Display);
         XGambe.Text := Valor;
      end;
   end;
end;

end.
