// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TCalculo                                        }
{                                                                    }
{                                                                    }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file                                       }
{                                                                    }
{   on 21 January 1998 at 08:57                                      }
{                                                                    }
{   Copyright © 1998 by DIS-EPM/UNIFESP                              }
{                                                                    }
{ ****************************************************************** }

unit Calculo;

interface

uses SysUtils, Classes, TypInfo, Forms, Dialogs, math, Procedimento,
     CCSDBListaLinks, CalcDM, Measurement, DicNut, Memoria,
     Formula, ROM, Parser10, DelayedOpIndicator;

type

   ECalcError = class(Exception);

   TTipoListaProc = (tpCode, tpDescription);

   TCalculo = class(TCCSDBListaLinks)
   private
      FDicionario : TCacheDic;
      FListaCalculo : TStringList;
      FListaMedida : TStringList;
      FListaParametro : TStringList;
      FDMCalc : TDMCalc;
      FNomeProc : WideString;
      FTemBackup : Boolean;
      FActiveLog: Boolean;
      FDelayedOpIndicator: TDelayedOpIndicator;
      FConfiguracao: TMemoria;
      FBackup: TMemoria;
      FMemoria: TMemoria;
      FProcedimentos: TStringList;
      FLog: TStringList;
      FConstantes: TStrings;
      FTipoListaProc: TTipoListaProc;
      function CalcProc : Boolean;
      function CriaMed (Categoria : string = '') : Boolean;
      function SetNomeProc( Value : wideString) : Boolean;
      procedure SetDicionario(Value : TNewDic);
      function GetDicionario: TNewDic;
      procedure AddLog(Value : TComponent);
      procedure NewValidate(Sender : TObject; var Valid : Boolean);
      function GetDescritor(const MedidaName : String) : TDescritorQuantitativo;
      procedure SetActiveLog(const Value: Boolean);
      procedure SetBackup(const Value: TMemoria);
      procedure SetConfiguracao(const Value: TMemoria);
      procedure SetConstantes(const Value: TStrings);
      procedure SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
      procedure SetLog(const Value: TStringList);
      procedure SetMemoria(const Value: TMemoria);
      procedure SetProcedimentos(const Value: TStringList);
      procedure SetTipoListaProc(const Value: TTipoListaProc);
   protected
      procedure Loaded; override;
      procedure TratErroFmla(fla : TFormula; E : Exception);
      procedure TratErroTbla(Tbla : TTabela; E : Exception);
      function ExecFuncaoPendente (bExecutar : byte): Boolean;
   public
      property ListaCalculo : TStringList read FListaCalculo;
      property ListaMedida : TStringList read FListaMedida;
      property ListaParametro : TStringList read FListaParametro;
      property Procedimentos : TStringList read FProcedimentos write SetProcedimentos;
      property Log : TStringList read FLog write SetLog;
      property ActiveLog : Boolean read FActiveLog write SetActiveLog;
      procedure AssignTo(Dest : TPersistent); override;
      procedure Assign(Sou : TCalculo); reintroduce; overload;
      constructor Create(AOwner: TComponent); override;
      destructor Destroy; override;
      procedure Notification(AComponent : TComponent; Operation : TOperation); override;
      function CriaMedidas : Integer;
      function ListaMedidasProcedimentos( var LstMedProc : TStringList ) : Integer;
      function Execute : Integer; overload; virtual;
      function Execute (CaixaProc : TCaixa): Integer; overload; virtual;
      function ConnectCalculo( User, Password : String ) : Boolean;
      procedure DisconnectCalculo;
      procedure ValidaCalculo(Calculo, Caixa : String);
      procedure FiltraCalculo(const MemoriaCfg : TMemoria; const NomeCaixa : String);
      function CriaListaProc(const Memoria : TMemoria; const NomeCaixa, NomeCalculo : String; const EstadoProcDefault: TProcState): Boolean;
      function EncheListas(Caixa : String; Procedimentos, Medidas, Resultados: TStringList): Boolean;
      function SetEstadoProc(const Memoria : TMemoria; const Caixa, Procedimento : String; const EstadoProc: TProcState): Boolean;
      procedure BackupMemoria;
      procedure RestoreMemoria;
   published
      property DelayedOpIndicator : TDelayedOpIndicator read FDelayedOpIndicator write SetDelayedOpIndicator;
      property Dicionario : TNewDic read GetDicionario write SetDicionario;
      property TipoListaProc : TTipoListaProc read FTipoListaProc write SetTipoListaProc default tpCode;
      property Memoria : TMemoria read FMemoria write SetMemoria;
      property Constantes : TStrings read FConstantes write SetConstantes;
      property Configuracao : TMemoria read FConfiguracao write SetConfiguracao;
      property Backup : TMemoria read FBackup write SetBackup;
  end;

procedure Register;

implementation

procedure Register;
begin
     RegisterComponents('Calculadora', [TCalculo]);
end;

{ TCalculo }

procedure TCalculo.AddLog(Value: TComponent);
begin
   if ActiveLog and Assigned( Value ) then
      if Value is TFormula then
      with TFormula( Value ), FLog do
      begin
         Add( 'Componente:  ' + Name );
         Add( 'Procedimento:' + FNomeProc );
         Add( 'Formula:     ' + Formula );
         if Assigned( Resultado ) then
            Add( 'Resultado=' + Resultado.ValorNumerico + ' ' + Resultado.Unidade + '(' + Resultado.Name + ')');
         if Assigned( A ) then
            Add( 'A=' + A.ValorNumerico + ' ' + A.Unidade  + '(' + A.Name + ')');
         if Assigned( B ) then
            Add( 'B=' + B.ValorNumerico + ' ' + B.Unidade + '(' + B.Name + ')');
         if Assigned( C ) then
            Add( 'C=' + C.ValorNumerico + ' ' + C.Unidade + '(' + C.Name + ')');
         if Assigned( D ) then
            Add( 'D=' + D.ValorNumerico + ' ' + D.Unidade + '(' + D.Name + ')');
         if Assigned( E ) then
            Add( 'E=' + E.ValorNumerico + ' ' + E.Unidade + '(' + E.Name + ')');
         if Assigned( t ) then
            Add( 't=' + t.ValorNumerico + ' ' + t.Unidade + '(' + t.Name + ')');
         if Assigned( X ) then
            Add( 'X=' + X.ValorNumerico + ' ' + X.Unidade + '(' + X.Name + ')');
         if Assigned( Y ) then
            Add( 'Y=' + Y.ValorNumerico + ' ' + Y.Unidade + '(' + Y.Name + ')');
         Add('-------------------------------------------');
      end
      else if Value is TTabela then
      with Ttabela( Value ), FLog do
      begin
         Add( 'Componente:  ' + Name );
         Add( 'DataBase:    ' + DataBaseName );
         Add( 'Tabela:      ' + NomeTabela );
         Add( 'Procedimento:' + FNomeProc );
         Add( 'Condição:    ' + Condicao );
         if Assigned( Resultado ) then
            Add( 'Resultado=' + Resultado.ValorNumerico + ' ' + Resultado.Unidade + '(' + Resultado.Name + ')');
         if Assigned( A ) then
            Add( 'A=' + A.ValorNumerico + ' ' + A.Unidade  + '(' + A.Name + ')');
         if Assigned( B ) then
            Add( 'B=' + B.ValorNumerico + ' ' + B.Unidade + '(' + B.Name + ')');
         if Assigned( C ) then
            Add( 'C=' + C.ValorNumerico + ' ' + C.Unidade + '(' + C.Name + ')');
         if Assigned( D ) then
            Add( 'D=' + D.ValorNumerico + ' ' + D.Unidade + '(' + D.Name + ')');
         if Assigned( E ) then
            Add( 'E=' + E.ValorNumerico + ' ' + E.Unidade + '(' + E.Name + ')');
         Add('-------------------------------------------');
      end;
end;

procedure TCalculo.Assign(Sou: TCalculo);
begin
   if (Sou = nil) then
      exit;
   FListaCalculo.Assign( Sou.FListaCalculo );
   FListaMedida.Assign( Sou.FListaMedida );
   FListaParametro.Assign(Sou.FListaParametro );
   FProcedimentos.Assign( Sou.FProcedimentos );
   FLog.Assign( Sou.FLog );
   FConstantes.Assign( Sou.FConstantes );
   FActiveLog := Sou.FActiveLog;
   FDelayedOpIndicator := Sou.FDelayedOpIndicator;
   FDicionario := Sou.FDicionario;
   FTipoListaProc := Sou.FTipoListaProc;
   FMemoria := Sou.FMemoria;
   FConfiguracao := Sou.FConfiguracao;
   FBackup := Sou.FBackup;
   if Name = '' then
      Name := Sou.Name;
end;

procedure TCalculo.AssignTo(Dest: TPersistent);
begin
  if Dest is TMedida then
   begin
     TCalculo(Dest).FListaCalculo.Assign( FListaCalculo );
     TCalculo(Dest).FListaMedida.Assign( FListaMedida );
     TCalculo(Dest).FListaParametro.Assign( FListaParametro );
     TCalculo(Dest).FProcedimentos.Assign( FProcedimentos );
     TCalculo(Dest).FLog.Assign( FLog );
     TCalculo(Dest).FConstantes.Assign( FConstantes );
     TCalculo(Dest).FActiveLog := FActiveLog;
     TCalculo(Dest).FDelayedOpIndicator := FDelayedOpIndicator;
     TCalculo(Dest).FDicionario := FDicionario;
     TCalculo(Dest).FTipoListaProc := FTipoListaProc;
     TCalculo(Dest).FMemoria := FMemoria;
     TCalculo(Dest).FConfiguracao := FConfiguracao;
     TCalculo(Dest).FBackup := FBackup;
     if TCalculo(Dest).Name = '' then
        TCalculo(Dest).Name := Name;
   end
  else
    inherited AssignTo(Dest);

end;

procedure TCalculo.BackupMemoria;
begin
   FMemoria.CopiaPara( FBackup );
   FTemBackup := True;
end;

{ Faz calculo do procedimento corrente (FNomeProv) }
function TCalculo.CalcProc: Boolean;
var
   I,
   iParamIndex : integer;
   bExecutar : byte;
   mdMed : TMedida;
begin
   FListaMedida.Clear;
   FDicionario.ClearDeepList;
   FListaCalculo.Clear;
   FDMCalc.flFormula.LimparParametros ;
   FDMCalc.tbTabela.LimparParametros;
   if not Fdicionario.ListAll( FNomeProc, FListaCalculo ) then
      begin
         Result := False;
         exit;
      end;
   bExecutar := 0;
   iParamIndex := 0;
   with  FDMCalc do
   begin
     { Perform the component operation }
     for I := 0 to FListaCalculo.Count - 1 do
     begin
        if quFmla.Locate( 'NAME', FListaCalculo[I], [] ) then
           begin
              // Executa Formula ou Tabela
              Result:=ExecFuncaoPendente (bExecutar);
              if not Result then
                 exit;
              flFormula.Formula := quFmla.FieldByName( 'Expressao' ).AsString;
              flFormula.AceitaParametrosInvalidos := ( quFmla.FieldByName( 'ACEITAPARAMINVALIDO' ).AsString = 'T' );
              bExecutar := 1;
              iParamIndex := 0;
           end
        else if quTab.Locate( 'NAME', FListaCalculo[I], [] ) then
           begin
              // Executa Formula ou Tabela
              Result:=ExecFuncaoPendente (bExecutar);
              if not Result then
                 exit;
              tbTabela.Condicao := quTab.FieldByName( 'Expressao' ).AsString;
              if quTab.FieldByName( 'DataBaseName' ).AsString = '' then
                 tbTabela.DataBaseName := self.Database.DatabaseName;
              tbTabela.NomeTabela := quTab.FieldByName( 'NomeTabela' ).AsString;
              tbTabela.CampoResult := quTab.FieldByName( 'CampoResult' ).AsString;
              tbTabela.AceitaParametrosInvalidos := (quFmla.FieldByName( 'ACEITAPARAMINVALIDO' ).AsString = 'T');
              tbTabela.ModoPesquisa := TModoPesquisa( GetEnumValue( TypeInfo( TModoPesquisa ), quTab.FieldByName( 'MODOPESQUISA' ).AsString ) );
              bExecutar := 2;
              iParamIndex := 0;
           end
        else if taMed.Locate( 'NAME', FListaCalculo[I], [] ) then
           begin
             if FMemoria.Acha(FListaCalculo[I], TObject( mdMed )) then
             begin
              if bExecutar = 1 then
                 Case iParamIndex of
                      0 : flFormula.Resultado := mdMed;
                      1 : flFormula.A := mdMed;
                      2 : flFormula.B := mdMed;
                      3 : flFormula.C := mdMed;
                      4 : flFormula.D := mdMed;
                      5 : flFormula.E := mdMed;
                      6 : flFormula.t := mdMed;
                      7 : flFormula.X := mdMed;
                      8 : flFormula.Y := mdMed;
                 end
              else
                 Case iParamIndex of
                      0 : tbTabela.Resultado := mdMed;
                      1 : tbTabela.A := mdMed;
                      2 : tbTabela.B := mdMed;
                      3 : tbTabela.C := mdMed;
                      4 : tbTabela.D := mdMed;
                      5 : tbTabela.E := mdMed;
                 end;
              Inc( iParamIndex );
             end;
           end;
     end;
     // Executa ultima Formula ou Tabela
     Result := ExecFuncaoPendente (bExecutar);
     if not Result then
        exit;
   end;
end;

{ Conecta o dicionario e as tabelas }
function TCalculo.ConnectCalculo(User, Password: String): Boolean;
begin
   Result := True;
   // Se ha' dicionario e Active mudou valor
   if Assigned (FDicionario) and not(FDicionario.Connected) then
      // Conecta dicionario e abre tabelas contendo os atributos das
      // instancias que o dicionario referencia
      if FDicionario.ConnectDictionary(User, Password) then
         with FDMCalc do
         begin
            taMed.Open;
            taDescritor.Open;
            quFmla.Open;
            quTab.Open;
            TMedida.SetListaCnst(TStringList(FConstantes));
            Result := (taMed.Active and quFmla.Active and quTab.Active and taDescritor.Active);
         end
      else
         Result := False;
end;

constructor TCalculo.Create(AOwner: TComponent);
begin
   inherited Create(AOwner);
   { Cria DataModule das Tabelas }
   FDMCalc := TDMCalc( Application.FindComponent( 'DMCalc' ) );
   if ( FDMCalc = nil ) then
      begin
         FDMCalc := TDMCalc.Create( Application );
         FDMCalc.FreeNotification(self);
      end;
   //Set default values
   FTipoListaProc := tpCode;
   // Cria Listas
   FProcedimentos := TStringList.Create;
   FListaCalculo := TStringList.Create;
   FListaMedida := TStringList.Create;
   FListaParametro := TStringList.Create;
   FConstantes := TStringList.Create;
   FLog := TStringList.Create;
end;

function TCalculo.CriaListaProc(const Memoria: TMemoria; const NomeCaixa,
  NomeCalculo: String; const EstadoProcDefault: TProcState): Boolean;
var
   ListaDescrProc : TStringList;
   AuxCx : TCaixa;
   prProc : TProcedimento;
   I : Integer;
   Code : WideString;
begin
   Result := False;
   // Conecta dicionario (ROM)
   if Assigned (FDicionario) and ConnectCalculo(FDicionario.IDUsuario, FDicionario.SenhaUsuario) then
   begin
      // Cria Procedimentos
      AuxCx := TCaixa.Create( Memoria );
      AuxCx.Name := NomeCaixa;
      AuxCx.Descricao := 'Lista de Procedimentos';
      ListaDescrProc := TStringList.Create;
      if (Assigned (FDicionario) and (FDicionario.CollectListInstances( NomeCalculo, ListaDescrProc ))) then
      begin
         For I := 0 to ListaDescrProc.Count - 1 do
         begin
             prProc := TProcedimento.Create(AuxCx);
             with prProc do
             begin
                FDicionario.FindCodeByDescription(Code,ListaDescrProc.Strings[I]);
                Name := Code;
                Descricao := ListaDescrProc.Strings[I];
                Estado := EstadoProcDefault;
             end;
         end;
         Result := True;
      end;
      ListaDescrProc.Free;
   end;
end;

{ Cria medidas do procedimento corrente (FNomeProc) }
function TCalculo.CriaMed(Categoria: string): Boolean;
var
   I : integer;
   mdMed : TMedida;
   ClasseMedida : string;
begin
   FListaMedida.Clear;
   FDicionario.ClearDeepList;
   if not FDicionario.CollectAllInstances( FNomeProc, FListaMedida ) then
      begin
         Result := False;
         ShowMessage( 'Erro na coleta das medidas! (TCalculo: 344)' );
         exit;
      end
   else
      begin
         Result := True;
      end;
   For I := 0 to FListaMedida.Count - 1 do
   begin
     if not FMemoria.Acha( FListaMedida.Strings[I], TObject( mdMed ) ) then
     begin
        TAttributedDic(FDicionario).GetAttributeByCode(FListaMedida.Strings[I], 'CLASSE', ClasseMedida);
        //Default : TMedida
        if ClasseMedida = '' then
           ClasseMedida := TMedida.ClassName;
        try
           mdMed := TMedidaClass(GetClass(ClasseMedida)).Create(nil);
        except
           on E : Exception do ShowMessage(E.Message);
        end;
        mdMed.Name := FListaMedida.Strings[I];
        //So pra depuracao
        ClasseMedida := mdMed.ClassName;
        with FDMCalc do
        begin
           if taMed.Locate( 'NAME', FListaMedida[I], [] ) then
              begin
                 mdMed.Descricao := taMed.FieldByName( 'DESCRICAO').AsString;
                 mdMed.ValorNumerico := taMed.FieldByName( 'VALORDEFAULT').AsString;
                 mdMed.Unidade := taMed.FieldByName( 'UNIDADEDEFAULT').AsString;
                 mdMed.Precisao := taMed.FieldByName( 'PRECISAO').AsInteger;
                 mdMed.Valid := (taMed.FieldByName( 'VALID' ).AsString = 'T');
              end
           else
              begin
                 mdMed.Unidade := '';
              end;
        end;
        // Seta a propriedade do descritor se a medida for criada ou já existir
        mdMed.Descritor := GetDescritor( mdMed.Name );
        // Atenção!!! quando adiciono, faz-se uma cópia de mdMed para a memoria
        // mdMed pode ser destruida.
        FMemoria.Adiciona( mdMed.Name, TObject( mdMed ), 'cx' + Categoria );
        if mdMed <> nil then
           mdMed.Free;
     end;
   end;
   for I := 0 to FListaMedida.Count - 1 do
       if FMemoria.Acha( FListaMedida.Strings[I], TObject( mdMed ) ) then
          begin
             if FListaParametro.IndexOf (FListaMedida.Strings[I]) = -1 then
                FListaParametro.AddObject( FListaMedida.Strings[I], TObject( mdMed ) );
          end
       else
          ShowMessage( 'Erro, medida nao foi criada! (TCalculo: 379)' );
end;

function TCalculo.ListaMedidasProcedimentos( var LstMedProc: TStringList): Integer;
var
   I : Integer;
begin
   LstMedProc.Clear;
   if not Assigned( LstMedProc ) then
   begin
      Result := -1;
      exit;
   end;
   if not ( FDicionario.Connected ) or ( FMemoria = nil ) then
      begin
         Result := -2;
         exit;
      end;
   for I := 0 To FProcedimentos.Count - 1 do
   begin
      if SetNomeProc( FProcedimentos[I] ) then
      begin
         FDicionario.ClearDeepList;
         if not FDicionario.CollectAllInstances( FNomeProc, LstMedProc ) then
         begin
            Result := -3;
            LstMedProc.Clear;
            exit;
         end;
      end;
   end;
   Result := FProcedimentos.Count;
end;

{ Cria os TMedidas necessarios para executar a lista de Procedimentos,
  se nao conseguir retorna da mesma forma que Execute }
function TCalculo.CriaMedidas: Integer;
var
   I : Integer;
   AuxCx : TCaixa;
   Code, Description : WideString;
begin
   FListaParametro.Clear;
   if not ( FDicionario.Connected ) or ( FMemoria = nil ) then
      begin
         Result := -1;
         exit;
      end;
   for I := 0 To FProcedimentos.Count - 1 do
   begin
      if SetNomeProc( FProcedimentos[I] ) then
         begin
            if not CriaMed(FNomeProc) then
               begin
                  Result := I;
                  exit;
               end;
            // Provavelmente, CriaMed criou a caixa do calculo. Então eu coloco a descricao
            Code := FNomeProc;
            if FDicionario.FindDescriptionByCode( Code, Description ) then
               if FMemoria.Acha('cx' + FNomeProc,TObject(AuxCx)) and ( AuxCx.Descricao = '' ) then
                  AuxCx.Descricao := Description;
         end;
   end;
   Result := FProcedimentos.Count;
end;

destructor TCalculo.Destroy;
begin
   FProcedimentos.Free;
   FListaCalculo.Free;
   FListaMedida.Free;
   FListaParametro.Free;
   FConstantes.Free;
   FLog.Free;
   { Destroi DataModule}
   if Assigned(FDMCalc) then
      FDMCalc.Free;
   inherited Destroy;
end;

{ desconecta o dicionario e as tabelas }
procedure TCalculo.DisconnectCalculo;
begin
   // Se ha' dicionario e Active mudou valor
   if Assigned (FDicionario) and (FDicionario.Connected) then
      begin
         // Desconecta dicionario e abre tabelas contendo os atributos das
         // instancias que o dicionario referencia
         FDicionario.DisconnectDictionary;
         with FDMCalc do
         begin
            taMed.Close;
            taDescritor.Close;
            quFmla.Close;
            quTab.Close;
         end;
      end;
end;

function TCalculo.EncheListas(Caixa: String; Procedimentos, Medidas, Resultados: TStringList): Boolean;
var
   AuxCx,
   AuxPr : TComponent;
   I : Integer;
   Temp : TStringList;
   TipoMed : String;
   mdMedTemp : TMedida;
   DescrProcAtual : String;
begin
   Procedimentos.Clear;
   Medidas.Clear;
   Medidas.Sorted := True;
   Medidas.Duplicates := dupIgnore	;
   Resultados.Clear;
   Resultados.Sorted := True;
   Resultados.Duplicates := dupIgnore	;
   Temp := TStringList.Create;
   Result := False;
   AuxCx := nil;
   if Assigned(FMemoria) then
      AuxCx := FMemoria.FindComponent( Caixa );
   if Assigned( AuxCx ) then
    if ( AuxCx is TCaixa ) then
     with (AuxCx as TCaixa ) do
     begin
        For I := 0 to AuxCx.ComponentCount - 1 do
        begin
           AuxPr := AuxCx.Components[I];
           if ( AuxPr is TProcedimento ) then
           with (AuxPr as TProcedimento ) do
           begin
              if Estado = psChecked then
                begin
                 Procedimentos.AddObject( Descricao, AuxPr );
                 Temp.AddObject( Descricao, AuxPr );
                 if Assigned (FDicionario) then
                    TCacheDic( FDicionario ).CollectAllInstances( Name, Temp );
                end;
              Result := True;
           end;
        end;
     end;
     For I := 0 to Temp.Count - 1 do
     begin
        if Temp.Objects[I] is TProcedimento then
          begin
             DescrProcAtual := Temp.Strings[I];
          end
        else if Assigned (FDicionario) and TAttributedDic( FDicionario ).GetAttributeByCode (Temp.Strings[I], 'TIPO', TipoMed) then
          begin
           if Assigned (FMemoria) and FMemoria.Acha( Temp.Strings[I], TObject( mdMedTemp ) ) then
             begin
              if TipoMed = 'MEDIDA' then
                 Medidas.AddObject( mdMedTemp.Descricao, mdMedTemp )
              else if TipoMed = 'RESULTADO' then
                 Resultados.AddObject( mdMedTemp.Descricao, mdMedTemp )
              else if TipoMed = 'PARAMETRO' then
                 mdMedTemp.Printable := False;
             end;
          end;
     end;
     Temp.Free;
end;

function TCalculo.ExecFuncaoPendente(bExecutar: byte): Boolean;
begin
  Result := True;
  with FDMCalc do
  begin
   if bExecutar = 1 then
      begin
         try
            AddLog( flFormula );
            flFormula.Execute
         except
            on E: Exception do
               begin
                  TratErroFmla(FDMCalc.flFormula, E);
                  Result := False;
                  flFormula.LimparParametros;
                  exit;
               end;
         end;
         flFormula.LimparParametros;
      end
   else if bExecutar = 2 then
      begin
         try
            AddLog( tbTabela );
            tbTabela.Execute;
         except
            on E: Exception do
               begin
                  TratErroTbla(FDMCalc.tbTabela, E);
                  Result := False;
                  tbTabela.LimparParametros;
                  exit;
               end;
         end;
         tbTabela.LimparParametros;
      end;
   end;
end;

{ Executa a Lista de Procedimentos encontrada em Procedimentos,
  retornando: o tamanho da lista se todos os procedimentos foram
  calculados com sucesso ou o número de procedimentos clculados. }
// &&& A pedido do Meide não abortar cálculos se um der errado, em 12/04/2001
function TCalculo.Execute(CaixaProc: TCaixa): Integer;
var
   I : Integer;
   ProcComErro : TProcedimento;
begin
   Result := 0;
   if not (FDicionario.Connected) or (FMemoria = nil) then
      begin
         Result := -1;
         exit;
      end;
   for I := 0 To CaixaProc.ComponentCount - 1 do
   begin
      FNomeProc:= CaixaProc.Components[I].Name;
      if CalcProc then
         Inc( Result )
      else
         begin
            if Assigned(FMemoria) then
               begin
                  if FMemoria.Acha(FNomeProc,TObject(ProcComErro)) then
                     FLog.Add( 'Erro no procedimento :' + ProcComErro.Descricao)
                  else
                     FLog.Add( 'Erro em procedimento indeterminado') ;
                  end;
         end;
   end;
   // Limpa "registradores" para o proximo calculo não dar problema
   Fprocedimentos.Clear;
end;

function TCalculo.Execute: Integer;
var
   I : Integer;
   ProcComErro : TProcedimento;
begin
   Result := 0;
   if not ( FDicionario.Connected ) or ( FMemoria = nil ) then
      begin
         Result := -1;
         exit;
      end;
   for I := 0 To FProcedimentos.Count - 1 do
     begin
       if SetNomeProc( FProcedimentos[I] ) then
       begin
          if CalcProc then
             Inc( Result )
          else
            begin
               if Assigned(FMemoria) then
                  begin
                     if FMemoria.Acha(FProcedimentos[I], TObject(ProcComErro)) then
                        FLog.Add( 'Erro no procedimento :' + ProcComErro.Descricao)
                     else
                        FLog.Add( 'Erro em procedimento indeterminado') ;
                  end;
            end;
       end;
     end;
   // Limpa "registradores" para o proximo calculo não dar problema
   Fprocedimentos.Clear;
end;

procedure TCalculo.FiltraCalculo(const MemoriaCfg: TMemoria; const NomeCaixa: String);
var
   AuxCxMem,
   AuxPrMem,
   AuxCxCfg,
   AuxPrCfg : TComponent;
   I : Integer;
begin
   AuxCxMem := FMemoria.FindComponent( NomeCaixa );
   AuxCxCfg := MemoriaCfg.FindComponent( NomeCaixa );
   if Assigned( AuxCxMem ) and Assigned( AuxCxCfg ) then
     if ( AuxCxMem is TCaixa ) and ( AuxCxCfg is TCaixa )then
        For I := 0 to AuxCxMem.ComponentCount - 1 do
        begin
           AuxPrMem := AuxCxMem.Components[I];
           if Assigned( AuxPrMem ) then
              if ( AuxPrMem is TProcedimento ) then
              begin
                 AuxPrCfg := AuxCxCfg.FindComponent( TProcedimento( AuxPrMem ).Name );
                 if Assigned( AuxPrCfg ) then
                    if ( AuxPrCfg is TProcedimento ) then
                        if ( TProcedimento( AuxPrCfg ).Estado = psInvisible ) and
                           ( TProcedimento( AuxPrMem ).Estado <> psChecked ) then
                           TProcedimento( AuxPrMem ).Estado := psInvisible;
              end;
        end;
end;

function TCalculo.GetDescritor(const MedidaName: String): TDescritorQuantitativo;
var
   dqDescritor : TDescritorQuantitativo;
   cxDescritores : TCaixa;
begin
   Result := nil;
   with FDMCalc do
   if taMed.Locate( 'NAME', MedidaName, [] ) then
     begin
       // Aqui eu transformo o nome do descritor pelo ponteiro
       if taDescritor.Locate( 'NAME', taMed.FieldByName( 'DESCRIPTORNAME' ).AsString, [] ) then
          begin
             if not FMemoria.Acha( taMed.FieldByName( 'DESCRIPTORNAME' ).AsString, TObject(dqDescritor) ) then
                begin
                   if not FMemoria.Acha( 'cxDescritores', TObject( cxDescritores ) ) then
                     begin
                         cxDescritores := TCaixa.Create( FMemoria );
                         cxDescritores.Name := 'cxDescritores';
                         cxDescritores.Descricao := 'Descritores das Medidas';
                      end;
                   dqDescritor := TDescritorQuantitativo.Create(cxDescritores);
                   dqDescritor.Name := taDescritor.FieldByName( 'NAME' ).AsString;
                   dqDescritor.ProcedimentoDeValidacao := taDescritor.FieldByName( 'NOMEPROCEDIMENTO' ).AsString;
                   dqDescritor.MedidaDeValidacao := taDescritor.FieldByName( 'MEDIDAVALNAME' ).AsString;
                   dqDescritor.NewValidate := NewValidate;
                end;
             // Caso tenha perdido na persistencia
             if not Assigned( dqDescritor.NewValidate ) then
                dqDescritor.NewValidate := NewValidate;
             Result := dqDescritor;
          end;
     end;
end;

function TCalculo.GetDicionario: TNewDic;
begin
   Result := TNewDic(FDicionario);
end;

procedure TCalculo.Loaded;
begin
   inherited Loaded;
   // Atualiza o DM do pai
   DM := FDMCalc;
end;

procedure TCalculo.NewValidate(Sender: TObject; var Valid: Boolean);
var
   AuxProc : TStringList;
   mdValid : TMedida;
begin
   // Considera que a medida é valida
   Valid := True;
    // Backup dos procedimentos atuais
   AuxProc := TStringList.Create;
   AuxProc.Assign( FProcedimentos );
   FProcedimentos.Clear;
   // Executa validação
   FProcedimentos.Add( TDescritorQuantitativo( Sender ).ProcedimentoDeValidacao );
   CriaMedidas;
   Execute;
   // Restore do procedimentos atuais
   FProcedimentos.Assign( AuxProc );
   AuxProc.Free;
   // Pega rsultado da validação
   if FMemoria.Acha( TDescritorQuantitativo( Sender ).MedidaDeValidacao, TObject( mdValid ) ) then
      begin
          Valid := ( mdValid.AsFloat <> 0 );
          if not Valid then
             ShowMessage( 'Medida inválida' );
      end;    
end;

procedure TCalculo.Notification(AComponent: TComponent; Operation: TOperation);
begin
   inherited Notification(AComponent, Operation);
   if Operation <> opRemove then
      Exit;
   if AComponent = FDicionario then
      FDicionario := nil
   else if AComponent = FMemoria then
      FMemoria := nil
   else if AComponent = FConfiguracao then
      FConfiguracao := nil
   else if AComponent = FDMCalc then
      FDMCalc := nil
   else if AComponent = FDelayedOpIndicator then
      FDelayedOpIndicator := nil
   else if AComponent = FBackup then
      FBackup := nil;
end;

procedure TCalculo.RestoreMemoria;
begin
   if FTemBackup then
   begin
      FBackup.CopiaPara( FMemoria );
      if Assigned(FMemoria.OnModified) then
         FMemoria.OnModified(FMemoria);
      FTemBackup := False;
   end;
end;

procedure TCalculo.SetActiveLog(const Value: Boolean);
begin
  FActiveLog := Value;
end;

procedure TCalculo.SetBackup(const Value: TMemoria);
begin
  FBackup := Value;
  if Value <> nil then
     Value.FreeNotification(Self);
end;

procedure TCalculo.SetConfiguracao(const Value: TMemoria);
begin
  FConfiguracao := Value;
  if Value <> nil then
     Value.FreeNotification(Self);
end;

procedure TCalculo.SetConstantes(const Value: TStrings);
begin
  if Assigned(Value) then
     FConstantes.Assign(Value)
  else
     FConstantes.Clear;
  TMedida.SetListaCnst(TStringList(FConstantes));
end;

procedure TCalculo.SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
begin
  FDelayedOpIndicator := Value;
  if Value <> nil then
     Value.FreeNotification(Self);
  if Assigned( FDMCalc ) then
     FDMCalc.tbTabela.DelayedOpIndicator := FDelayedOpIndicator;
end;

procedure TCalculo.SetDicionario(Value: TNewDic);
begin
   FDicionario := TCacheDic(Value);
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TCalculo.SetEstadoProc(const Memoria: TMemoria; const Caixa,
  Procedimento: String; const EstadoProc: TProcState): Boolean;
var
   AuxCx,
   AuxPr : TComponent;
begin
  Result := False;
  AuxCx := nil;
  if Assigned (Memoria) then
     AuxCx := Memoria.FindComponent( Caixa );
  if Assigned( AuxCx ) then
    if ( AuxCx is TCaixa ) then
     with (AuxCx as TCaixa ) do
     begin
       AuxPr := FindComponent( Procedimento );
       if Assigned( AuxPr ) then
         if ( AuxPr is TProcedimento ) then
           with (AuxPr as TProcedimento ) do
           begin
              Estado := EstadoProc;
              Result := True;
           end;
     end;
end;

procedure TCalculo.SetLog(const Value: TStringList);
begin
  if Assigned(Value) then
     FLog.Assign( Value )
  else
     FLog.Clear;
end;

procedure TCalculo.SetMemoria(const Value: TMemoria);
begin
  FMemoria := Value;
  if Value <> nil then
     Value.FreeNotification(Self);
end;

function TCalculo.SetNomeProc(Value: wideString): Boolean;
var
   Code,
   Description : WideString;
begin
   // Tipo de Lista de Procedimentos for de Descricoes
   if FTipoListaProc = tpDescription then
      begin
         Description := Value;
         if FDicionario.FindCodeByDescription( Code, Description ) = 1 then
            begin
               FNomeProc := Code;
               Result := True;
            end
         else
            Result := False;
      end
   else
      begin
         FNomeProc := Value;
         Result := True;
      end;
end;

procedure TCalculo.SetProcedimentos(const Value: TStringList);
begin
   if Assigned( Value ) then
      FProcedimentos.Assign( Value )
   else
      FProcedimentos.Clear;
end;

procedure TCalculo.SetTipoListaProc(const Value: TTipoListaProc);
begin
  FTipoListaProc := Value;
end;

procedure TCalculo.TratErroFmla(fla: TFormula; E: Exception);
begin
   if ((E.ClassType = EInvalidArgument) or
      (E.ClassType =  EExpressionHasBlanks) or
      (E.ClassType =  EParserInternalError)) then
      begin
         ShowMessage ('Erro na execução da formula : ' + fla.Descricao + #13#10 +
                      'Alguma das medidas do indivíduo está fora dos' + #13#10 +
                      'valores aceitos por este programa para efetuar calculos.' + #13#10 +
                      'Você já deve ter sido advertido anteriormente desta situação.' + #13#10 +
                      'A mensagem enviada pelo parser foi : ' + E.Message + #13#10);
         exit;
      end;
end;

procedure TCalculo.TratErroTbla(Tbla: TTabela; E: Exception);
begin
   if ((E.ClassType = EInvalidArgument) or
       (E.ClassType = ETabelaVazia)) then
      begin
         ShowMessage ('Erro na execução da tabela : ' + Tbla.NomeTabela  + #13#10 +
                      'Alguma das medidas do indivíduo está fora dos' + #13#10 +
                      'valores aceitos por este programa para efetuar calculos.' + #13#10 +
                      'Você já deve ter sido advertido anteriormente desta situação.' + #13#10 +
                      E.Message + #13#10);
         exit;
      end;
end;

procedure TCalculo.ValidaCalculo(Calculo, Caixa: String);
var
   AuxCx,
   AuxPr : TComponent;
   mdMed : TMedida;
   I, J : Integer;
   Temp, Temp2 : TStringList;
begin
   Procedimentos.Clear;
   Temp := TStringList.Create;
   Temp2 := TStringList.Create;
   Dicionario.CollectListInstances( Calculo, Temp, ltCode);
   Procedimentos.Assign(Temp);
   CriaMedidas;
   Execute;
   AuxCx := FMemoria.FindComponent( Caixa );
   if Assigned( AuxCx ) then
    if ( AuxCx is TCaixa ) then
     with (AuxCx as TCaixa ) do
     begin
        For I := 0 to AuxCx.ComponentCount - 1 do
        begin
           AuxPr := AuxCx.Components[I];
           if ( AuxPr is TProcedimento ) then
           with (AuxPr as TProcedimento ) do
           begin
              if ( Estado = psInvisible ) or ( Estado = psHidden ) then
                 // nao precisa validar aqui
              else if FMemoria.Acha( NomeMedidaValidacao, TObject( mdMed ) ) then
                 begin
                    if mdMed.AsFloat <> 0 then
                       Estado := psNone
                    else
                       Estado := psDisabled;
                    // Pega descrição das fórmulas ou tabelas de validação onde está o escopo
                    Temp2.Clear;
                    Escopo := '';
                    Dicionario.CollectListInstances( 'vl' + AuxPr.Name, Temp2, ltCode);
                    For J := Temp2.Count - 1 downto 0 do
                    with  FDMCalc do
                      begin
                       if quFmla.Locate( 'NAME',Temp2.Strings[J], [] ) then
                          Escopo := quFmla.FieldByName( 'DESCRICAO' ).AsString + '. ' + Escopo
                       else if quTab.Locate( 'NAME', Temp2.Strings[J], [] ) then
                          Escopo := quTab.FieldByName( 'DESCRICAO' ).AsString + '. ' + Escopo;
                      end;
                 end
              else
                 Estado := psInvisible;
           end;
        end;
     end;
   // Limpando da memoria os calculos de validacao
   For I := 0 to Temp.Count - 1 do
      begin
         AuxCx := FMemoria.FindComponent( 'cx' + Temp.Strings[I] );
         if ( AuxCx <> nil ) and ( AuxCx is TCaixa ) then
            AuxCx.Free;
      end;
   Temp.Free;
   Temp2.Free;
end;

end.

