// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




unit Escopo;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  // Escopo
  Idade, Procedimento, NovoInd, Memoria, Measurement,
  Calculo, DescriptorManager, ObjVis;
  
type
  TEscopo = class(TComponent)
  private
    FCalculo: TCalculo;
    FIndicadores: TDescriptorManager;
    FConfiguracao: TMemoria;
    FCorpoHumano: TCorpoHumano;
    { Private declarations }
    { Method to set variable and property values and create objects }
    procedure AutoInitialize;
    { Method to free any objects created by AutoInitialize }
    procedure AutoDestroy;
    procedure SetCalculo(const Value: TCalculo);
    procedure SetConfiguracao(const Value: TMemoria);
    procedure SetIndicadores(const Value: TDescriptorManager);
    procedure SetCorpoHumano(const Value: TCorpoHumano);
  protected
    { Protected declarations }
  public
    { Public declarations }
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
    procedure Notification(AComponent : TComponent; Operation : TOperation); override;
    procedure Loaded; override;

    procedure PreparaCorpoHumano;
    function Pegar( ModoOrg : Boolean = False) : Boolean;
  published
    { Published declarations }
    property Calculo : TCalculo read FCalculo write SetCalculo;
    property Indicadores : TDescriptorManager read FIndicadores write SetIndicadores;
    property Configuracao : TMemoria read FConfiguracao write SetConfiguracao;
    property CorpoHumano : TCorpoHumano read FCorpoHumano write SetCorpoHumano;
  end;

procedure Register;

implementation

procedure Register;
begin
  RegisterComponents('Calculadora', [TEscopo]);
end;


// Pede o escopo para calculos com limitacoes
procedure TEscopo.AutoDestroy;
begin

end;

procedure TEscopo.AutoInitialize;
begin

end;

constructor TEscopo.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }
end;

destructor TEscopo.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TEscopo.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }
end;

procedure TEscopo.Notification(AComponent: TComponent;
  Operation: TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of
       this component been deleted?  If so, update
       the property. }
     if AComponent = FCalculo then
        FCalculo := nil;
     if AComponent = FIndicadores then
        FIndicadores := nil;
     if AComponent = FConfiguracao then
        FConfiguracao := nil;
     if AComponent = FCorpoHumano then
        FCorpoHumano := nil;
end;

function TEscopo.Pegar( ModoOrg : Boolean = False ): Boolean;
var
   fmNovoInd : TfmNovoIndividuo;
   mdMed,
   mdEscopoOk : TMedida;
begin

   Result := False;

   if (not Assigned( FCalculo )) or (not Assigned( FIndicadores )) or
      (not Assigned( FConfiguracao)) or (not Assigned( FCorpoHumano ))then
      exit;

   // Se o escopo já foi criado
   if FCalculo.Memoria.Acha( 'mdEscopoCriado', TObject( mdEscopoOk )) then
      begin
         // O escopo já foi criado
         if ( mdEscopoOk.ValorNumerico <> '0' ) then
         begin
            PreparaCorpoHumano;
            Result := True;
            exit;
         end;
      end
   else
      begin
         ShowMessage( 'Erro na criação do Escopo' );
         exit; // raise
      end;

   // Cria janela modal pedindo os dados de escopo
   fmNovoInd := TfmNovoIndividuo.Create(self);
   fmNovoInd.ModoOrganizador:= ModoOrg;
   fmNovoInd.Calculo := FCalculo;
   fmNovoInd.Indicadores := FIndicadores;
   fmNovoInd.Configuracao := FConfiguracao;
   if fmNovoInd.ShowModal = mrOk then
      begin
        if FCalculo.Memoria.Acha( 'mdNomeIndividuo', TObject( mdMed ))then
           FCalculo.Memoria.NomeArquivo := mdMed.ValorNumerico
        else
           exit; // raise
        if FCalculo.Memoria.Acha( 'mdIdade', TObject( mdMed ) ) then
           ( mdMed as TIdade ).SetMelhorValor
        else
           exit; // raise
        FCalculo.Memoria.Modified := 1;
        mdEscopoOk.ValorNumerico := '1';
        PreparaCorpoHumano;
        Result := True;
      end
    else
       Result := False;
    fmNovoInd.Free;
end;

procedure TEscopo.PreparaCorpoHumano;
var
   mdMed1,
   mdMed2 : TMedida;
begin
   with FCorpoHumano do
   begin
      // Inicializa Corpo humano
//***      DataSourceName := 'BDOrganizador';
      // Verifica o sexo e Idade e seta a figura correspondente
      if FCalculo.Memoria.Acha( 'mdSexo', TObject( mdMed1 ) ) then
      begin
        if FCalculo.Memoria.Acha( 'mdIdadeAnos', TObject( mdMed2 ) ) then
        begin
           if mdMed2.AsFloat >= 9 then
           begin
             if mdMed1.ValorNumerico = 'Masculino' then
                NomeObjetoVisual := 'MADULTO'
             else
                NomeObjetoVisual := 'FADULTO';
           end
           else if mdMed2.AsFloat > 3 then
             NomeObjetoVisual := 'CRIANCA'
           else
             NomeObjetoVisual := 'BEBE';
        end
        else
           ShowMessage( 'Erro: a medida mdIdadeAnos não existe!' );
      end
      else
         ShowMessage( 'Erro: a medida mdSexo não existe!' );
      Active := True;
   end;
end;

procedure TEscopo.SetCalculo(const Value: TCalculo);
begin
  FCalculo := Value;
end;

procedure TEscopo.SetConfiguracao(const Value: TMemoria);
begin
  FConfiguracao := Value;
end;

procedure TEscopo.SetCorpoHumano(const Value: TCorpoHumano);
begin
  FCorpoHumano := Value;
end;

procedure TEscopo.SetIndicadores(const Value: TDescriptorManager);
begin
  FIndicadores := Value;
end;

end.
 