// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TMmListBox                                         }
{                                                                    }
{   ListBox para TMemoria                                            }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file c:\projeto\compdelphi\calculo\mmlstbox.cd }
{   on 10 Feb 1998 at 11:03                                          }
{                                                                    }
{   Copyright © 1998 by CIS/EPM                                      }
{                                                                    }
{ ****************************************************************** }

unit MmLstBox;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls, 
     Forms, Graphics, Stdctrls, NutCnst, HintListBox;

type

  TMmListBox = class(THintListBox)
    private
      { Private fields of TMmListBox }
        { Storage for property NomeLista }
        FNomeLista : String;
        FListaDeItens : TStringList;
        FFirstIndex : Integer;
        FLastIndex : Integer;

      { Private methods of TMmListBox }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        //Write method for property ListaDeItens
        procedure SetListaDeItens (Value : TStringList);

    protected
      { Protected fields of TMmListBox }

      { Protected methods of TMmListBox }
        procedure Click; override;
        procedure KeyPress(var Key : Char); override;
        procedure Loaded; override;

        function GetGUID(Index: Integer): string;
        procedure PutGUID(Index: Integer; const S: string);
        function GetDescricao(Index: Integer): string;
        procedure PutDescricao(Index: Integer; const S: string);

        procedure DrawItem( Index: Integer; Rect: TRect; State: TOwnerDrawState);override;
        procedure MouseUp( Button: TMouseButton; Shift: TShiftState; X, Y: Integer);override;
    public

      { Public methods of TMmListBox }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;

        procedure Refresh;
        procedure AtualizaMemoria;
        { Adiciona String e GUID e retorna o indice}
        function AddDescricaoGUID( Descricao, GUID : String; Estado : TGUIDItemState = gsNone ) : Integer;
        property GUID[Index: Integer]: string read GetGUID write PutGUID;
        property Descricao[Index: Integer]: string read GetDescricao write PutDescricao;

        { Lista de Itens }
        property ListaDeItens : TStringList
             read FListaDeItens write SetListaDeItens;

    published
      { Published properties of TMmListBox }
        property OnClick;
        property OnDblClick;
        property OnDragDrop;
        property OnMouseDown;
        property OnMouseMove;
        property OnMouseUp;
        property OnKeyUp;
        property OnKeyDown;
        property OnKeyPress;
        property OnEnter;
        property OnExit;
        { Nome da Lista na Memoria }
        property NomeLista : String read FNomeLista write FNomeLista;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TMmListBox with Nutricao as its
       default page on the Delphi component palette }
     RegisterComponents('Miscelanea', [TMmListBox]);
end;

{ Method to set variable and property values and create objects }
procedure TMmListBox.AutoInitialize;
begin
  // self.OnDrawItem := xDrawItem;
Style:= lbOwnerDrawVariable;
// servem para o controle de seleção
FFirstIndex := 0;
FLastIndex := 0;
end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TMmListBox.AutoDestroy;
begin
end; { of AutoDestroy }

{ Adiciona Descricao e GUID }
function TMmListBox.AddDescricaoGUID( Descricao, GUID : String; Estado : TGUIDItemState = gsNone ) : Integer;
var
   AuxGUID : TGUIDItem;
begin
   AuxGUID := TGUIDItem.Create( Owner );
   AuxGUID.Guid := GUID;
   AuxGUID.State := Estado;
   Result := Self.items.AddObject( Descricao, AuxGUID);
end;

function TMmListBox.GetGUID(Index: Integer): string;
begin
   if ( self.items.Objects[Index] is TGUIDItem ) then
      Result := TGUIDItem( self.items.Objects[Index] ).GUID
   else
      Result := '';
end;

procedure TMmListBox.PutGUID(Index: Integer; const S: string);
begin
   if ( self.items.Objects[Index] is TGUIDItem ) then
      TGUIDItem( self.Items.Objects[Index] ).GUID := S;
end;

function TMmListBox.GetDescricao(Index: Integer): string;
begin
   Result := self.Items.Strings[Index];
end;

procedure TMmListBox.PutDescricao(Index: Integer; const S: string);
begin
   self.Items.Strings[Index] := S;
end;

{ Override OnClick handler from TListBox }
procedure TMmListBox.Click;
begin
     { Code to execute before activating click
       behavior of component's parent class }

     { Activate click behavior of parent }
     inherited Click;

     { Code to execute after click behavior
       of parent }

end;

{ Override OnKeyPress handler from TListBox }
procedure TMmListBox.KeyPress(var Key : Char);
const
     TabKey = Char(VK_TAB);
     EnterKey = Char(VK_RETURN);
begin
     { Key contains the character produced by the keypress.
       It can be tested or assigned a new value before the
       call to the inherited KeyPress method.  Setting Key
       to #0 before call to the inherited KeyPress method
       terminates any further processing of the character. }

     { Activate KeyPress behavior of parent }
     inherited KeyPress(Key);

     { Code to execute after KeyPress behavior of parent }

end;

constructor TMmListBox.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TMmListBox.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TMmListBox.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;

procedure TMmListBox.Refresh;
var
   I : Integer;
begin
   if not assigned (FListaDeItens) then exit;

   Items.Clear;
   for I := 0 To FListaDeItens.Count - 1 do
       Items.Add( FListaDeItens.Strings[I] );

end;

procedure TMmListBox.SetListaDeItens (Value : TStringList);
     { Internal declarations for method }
begin
  if Value <> nil then
   begin
      FListaDeItens :=Value;
      Refresh;
   end
  else
    FListaDeItens :=Value;
end;

procedure TMmListBox.AtualizaMemoria;
var
   I : Integer;
begin

   if (not assigned (FListaDeItens)) then exit;

   FListaDeItens.Clear;
   for I := 0 To Items.Count - 1 do
       FListaDeItens.Add( Items[I] );

end;

procedure TMmListBox.MouseUp(Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
var
I : Integer;
begin
  inherited;
  // FFirstIndex e FLastIndex servem pra saber que item é o primeiro selecionado e o último
  // para indicar o sentido de seleção que tem que ser inverso ao for que deseleciona
  // para que funcione bem
  FFirstIndex := FLastIndex;
  FLastIndex := ItemIndex;
  if FFirstIndex >= FLastIndex then
  begin
    for I:=0 to Items.Count-1 do
      if ( Assigned( Items.Objects[I] ) and ( Items.Objects[I] is TGUIDItem ) and
           Selected[I] and (TGUIDItem( Items.Objects[I] ).State = gsDisabled) ) or
         ( Assigned( Items.Objects[I] ) and ( Items.Objects[I] is TComponent ) and
           Selected[I] and (TComponent( Items.Objects[I] ).Tag < 0) ) then
         Selected[I]:= False;
  end
  else
  begin
     for I:= Items.Count-1 downto 0  do
      if ( Assigned( Items.Objects[I] ) and ( Items.Objects[I] is TGUIDItem ) and
           Selected[I] and (TGUIDItem( Items.Objects[I] ).State = gsDisabled) ) or
         ( Assigned( Items.Objects[I] ) and ( Items.Objects[I] is TComponent ) and
           Selected[I] and (TComponent( Items.Objects[I] ).Tag < 0) ) then
          Selected[I]:= False;
  end;
end;

procedure TMmListBox.DrawItem(Index: Integer; Rect: TRect; State: TOwnerDrawState);
var
  Flags: Longint;
begin
  if Assigned(OnDrawItem) then OnDrawItem(Self, Index, Rect, State) else
  begin
    Canvas.FillRect(Rect);
    if Index < Items.Count then
    begin
      Flags := DrawTextBiDiModeFlags(DT_SINGLELINE or DT_VCENTER);
      if not UseRightToLeftAlignment then
        Inc(Rect.Left, 2)
      else
        Dec(Rect.Right, 2);

      if ( Assigned( Items.Objects[Index] ) and ( Items.Objects[Index] is TGUIDItem ) and
           ( TGUIDItem( items.Objects[Index] ).State = gsDisabled ) ) or
          ( Assigned( Items.Objects[Index] ) and ( Items.Objects[Index] is TComponent ) and
           ( TComponent( items.Objects[Index] ).Tag < 0 ) ) then
         Canvas.Font.Color := clGray;

      DrawText(Canvas.Handle, PChar(Items[Index]), Length(Items[Index]), Rect,
        Flags);
    end;
  end;
end;


end.
