// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




unit RDA;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  DBTables, Db, memoria, measurement, ActiveX, NutCnst, CCSDBListaLinks,
  DelayedOpIndicator;

type

  EMeassurementNotFound = class(Exception);
  EDataSetIsEmpty = class(Exception);

type
  TdmRDA = class(TDataModule)
    quRDAFaixas: TQuery;
    quRDA: TQuery;
    quRDAGN: TQuery;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

type
  TRDA = class(TCCSDBListaLinks)
  private
    FCaixaRDA: String;
//    FDataBase: String;
    FMemoria: TMemoria;
    FDMRDA: TdmRDA;
    FDelayedOpIndicator: TDelayedOpIndicator;
   { Private methods of TMemoria }
   { Method to set variable and property values and create objects }
    procedure AutoInitialize;
   { Method to free any objects created by AutoInitialize }
    procedure AutoDestroy;
    procedure SetCaixaRDA(const Value: String);
//    procedure SetDataBaseName(const Value: String);
    procedure SetMemoria(const Value: TMemoria);
    procedure SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
    { Private declarations }
  protected
    { Protected declarations }
    procedure OpenTables; override;
  public
    { Public declarations }
    // Resets prop of component type if referenced component deleted
    procedure Notification(AComponent : TComponent; Operation : TOperation); override;
    property DMRDA : TdmRDA read FDMRDA;
    constructor Create (AOwner:TComponent);override;
    destructor Destroy;override;
    procedure Loaded;override;
    function CriaRDA : Boolean;
    function LimparCaixaRDA : Boolean;
  published
    { Published declarations }
//    property DataBase : String read FDataBase write SetDataBaseName;
    property Memoria : TMemoria read FMemoria write SetMemoria;
    property CaixaRDA : String read FCaixaRDA write SetCaixaRDA;
    property DelayedOpIndicator : TDelayedOpIndicator read FDelayedOpIndicator write SetDelayedOpIndicator;
  end;

procedure Register;


implementation

{$R *.DFM}

procedure Register;
begin
  RegisterComponents('Nutricao', [TRDA]);
end;

//========================================================================

{ TRDA }

procedure TRDA.AutoDestroy;
begin
// libera datamodule
if Assigned(FdmRDA) then
   FdmRDA.Free;
end;

procedure TRDA.AutoInitialize;
begin
   // Cria datamodule
   Application.CreateForm (TdmRDA,FdmRDA);
   FdmRDA.FreeNotification (self);
end;

constructor TRDA.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

function TRDA.LimparCaixaRDA : Boolean;
var
   cxRecNut : TCaixa;
   I : Integer;
begin
   Result := False;
   // Pega caixa de nutrientes RDA
   if not FMemoria.Acha( FCaixaRDA, TObject( cxRecNut ) ) then
      raise EMeassurementNotFound.CreateFmt( 'Caixa de Nutrientes: %s não encontrada.', [FCaixaRDA] )
   else
      Result := True;
   // limpa o conteudo dos nutrientes (TMedida)
   for I := 0 to cxRecNut.ComponentCount - 1 do
   begin
       TMedida( cxRecNut.Components[I] ).ValorNumerico := '';
       TMedida( cxRecNut.Components[I] ).Empty := True;
       TMedida( cxRecNut.Components[I] ).Valid := False;
       TMedida( cxRecNut.Components[I] ).Tag := 0;
   end;
end;

function TRDA.CriaRDA: Boolean;
var
   mdSexo,
   mdIdadeMeses,
   mdIdadeAnos,
   mdTempoGestante,
   mdTempoNutriz,
   mdNut : TMedida;
   cxRDA,
   cxRCRDA: TCaixa;
   mdFaixaRDA : TMedida;
   Aux : String;
begin
   Result := False;

   // Não achou os componentes necessarios para criar RDA
   if not Assigned( FMemoria ) or (not Assigned( DataBase )) or ( FCaixaRDA = '' ) then
      raise EMeassurementNotFound.CreateFmt( 'Memória: %s não encontrados ou DataBase e/ou Caixa não definidos.', [FCaixaRDA] );

   with FMemoria do
   begin

      // Define o perfil (escopo) que vai gerar a RDA
      if not Acha( FCaixaRDA, TObject( cxRDA ) ) then
         raise EMeassurementNotFound.CreateFmt( 'Caixa: %s não encontrada.', [FCaixaRDA] );
      if not Acha( 'mdSexo', TObject( mdSexo ) ) then
         raise EMeassurementNotFound.CreateFmt( 'Medida: %s não encontrada.', [mdSexo] );
      if not Acha( 'mdIdadeAnos', TObject( mdIdadeAnos ) ) then
         raise EMeassurementNotFound.CreateFmt( 'Medida: %s não encontrada.', [mdIdadeAnos] );
      if not Acha( 'mdIdadeMeses', TObject( mdIdadeMeses ) ) then
         raise EMeassurementNotFound.CreateFmt( 'Medida: %s não encontrada.', [mdIdadeMeses] );
      if not Acha( 'mdTempoGestante', TObject( mdTempoGestante ) ) then
         raise EMeassurementNotFound.CreateFmt( 'Medida: %s não encontrada.', [mdTempoGestante] );
      if not Acha( 'mdTempoNutriz', TObject( mdTempoNutriz ) ) then
         raise EMeassurementNotFound.CreateFmt( 'Medida: %s não encontrada.', [mdTempoNutriz] );

      with FdmRDA do
      begin
         // Verifica qual a faixa que o perfil cai
         // Individuo, com idade em anos ou meses
         quRDAFaixas.Close;
         quRDAFaixas.ParamByName( 'TIPOF' ).AsString := 'I'; // I - indivíduo
         if ( mdIdadeAnos.AsFloat = 0 ) then
         begin
            // Converter para anos pois maior igual a 12 meses a tabela trabalha em anos
            if StrToFloat( mdIdadeMeses.ValorNumerico ) >= 12 then
            begin
               quRDAFaixas.ParamByName( 'MINF' ).AsFloat := StrToInt( mdIdadeMeses.ValorNumerico ) div 12;
               quRDAFaixas.ParamByName( 'MAXF' ).AsFloat := StrToInt( mdIdadeMeses.ValorNumerico ) div 12;
               quRDAFaixas.ParamByName( 'UNIDADE' ).AsString := LowerCase( 'Anos' );
            end
            else
            begin
               quRDAFaixas.ParamByName( 'MINF' ).AsFloat := StrToFloat( mdIdadeMeses.ValorNumerico );
               quRDAFaixas.ParamByName( 'MAXF' ).AsFloat := StrToFloat( mdIdadeMeses.ValorNumerico );
               quRDAFaixas.ParamByName( 'UNIDADE' ).AsString := LowerCase( mdIdadeMeses.Unidade );
            end;
         end
         else
         begin
            quRDAFaixas.ParamByName( 'MINF' ).AsFloat := StrToFloat( mdIdadeAnos.ValorNumerico );
            quRDAFaixas.ParamByName( 'MAXF' ).AsFloat := StrToFloat( mdIdadeAnos.ValorNumerico );
            quRDAFaixas.ParamByName( 'UNIDADE' ).AsString := LowerCase( mdIdadeAnos.Unidade );
         end;
         // Inicia processo demorado
         if Assigned( FDelayedOpIndicator ) then
            FDelayedOpIndicator.Start;
         Try
            quRDAFaixas.Open;
         finally
           // Finaliza Processo demorado
           if Assigned( FDelayedOpIndicator ) then
              FDelayedOpIndicator.Finish;
         end;

         // Se não achar, tenta com idade em meses
         if quRDAFaixas.IsEmpty then
         begin
            quRDAFaixas.Close;
            quRDAFaixas.ParamByName( 'UNIDADE' ).AsString := LowerCase(mdIdadeMeses.Unidade);
            // Inicia processo demorado
            if Assigned( FDelayedOpIndicator ) then
               FDelayedOpIndicator.Start;
            Try
               quRDAFaixas.Open;
            finally
              // Finaliza Processo demorado
              if Assigned( FDelayedOpIndicator ) then
                 FDelayedOpIndicator.Finish;
            end;
            if quRDAFaixas.IsEmpty then
               raise EDataSetIsEmpty.CreateFmt( 'Tabela: %s está vazia.', [quRDAFaixas.Name]);
         end;

         // Prepara tabela da RDA para pegar coluna de faixa
         quRDA.Close;
         quRDA.ParamByName( 'SEXO' ).AsString := mdSexo.ValorNumerico;
         // Inicia processo demorado
         if Assigned( FDelayedOpIndicator ) then
            FDelayedOpIndicator.Start;
         Try
            quRDA.Open;
         finally
           // Finaliza Processo demorado
           if Assigned( FDelayedOpIndicator ) then
              FDelayedOpIndicator.Finish;
         end;
         if quRDA.IsEmpty then
            raise EDataSetIsEmpty.CreateFmt( 'Tabela: %s está vazia.', [quRDA.Name]);

         // Prepara tabela de RDA para Gestante Nutriz
         // Inicia processo demorado
         if Assigned( FDelayedOpIndicator ) then
            FDelayedOpIndicator.Start;
         Try
            quRDAGN.Open;
         finally
           // Finaliza Processo demorado
           if Assigned( FDelayedOpIndicator ) then
              FDelayedOpIndicator.Finish;
         end;
         if quRDAGN.IsEmpty then
            raise EDataSetIsEmpty.CreateFmt( 'Tabela: %s está vazia.', [quRDAGN.Name]);

         // Limpa caixa para receber os valores
         if not LimparCaixaRDA then
            exit;

         // Carrega os nutrientes do perfil definido acima
         quRDA.First;
         while not quRDA.Eof do
         begin
            if cxRDA.Acha( GuidToName(quRDA.FieldbyName( 'IDNUT' ).AsString, cxRDA.Name ), TObject( mdNut ) ) then
               begin
                  mdNut.ValorNumerico := quRDA.FieldbyName( quRDAFaixas.FieldByName( 'NOMEFAIXA' ).AsString ).AsString;
                  mdNut.Empty := False;
                  mdNut.Valid := True;
                  mdNut.Tag := quRDA.FieldbyName( 'ORDEM' ).AsInteger;
               end;
            quRDA.Next;
         end;

         // Monta título da faixa da RDA
         if not FMemoria.Acha( 'mdFaixaRDA', TObject( mdFaixaRDA ) ) then
            begin
            if not Acha( 'cxprRCRDA', TObject( cxRCRDA ) ) then
               raise EMeassurementNotFound.CreateFmt( 'Caixa: %s não encontrada.', [FCaixaRDA] );
               mdFaixaRDA := TMedidaOrdinal.Create(cxRCRDA);
               mdFaixaRDA.Name := 'mdFaixaRDA';
               mdFaixaRDA.Descricao := 'Faixa da RDA';
               mdFaixaRDA.Valid := True;
            end;
         with quRDAFaixas do
         begin
          if FieldByName( 'MINF' ).AsInteger <= 0 then
            mdFaixaRDA.ValorNumerico := ' para sexo ' + mdSexo.ValorNumerico +
                                        '; Idade menor que ' + IntToStr( FieldByName( 'MAXF' ).AsInteger ) +
                                        ' ' + FieldByName( 'UNIDADE' ).AsString
          else if FieldByName( 'MAXF' ).AsInteger >= 999 then
            mdFaixaRDA.ValorNumerico := ' para sexo ' + mdSexo.ValorNumerico +
                                        '; Idade maior igual a ' + IntToStr( FieldByName( 'MINF' ).AsInteger  ) +
                                        ' ' + FieldByName( 'UNIDADE' ).AsString
          else
            mdFaixaRDA.ValorNumerico := ' para sexo ' + mdSexo.ValorNumerico +
                                        '; Idade entre ' + IntToStr( FieldByName( 'MINF' ).AsInteger  ) +
                                        ' e ' + IntToStr( FieldByName( 'MAXF' ).AsInteger - 1 ) +
                                        ' ' + FieldByName( 'UNIDADE' ).AsString;
         end;

         // Se for mulher, verifica se é gestante ou nutriz e aplica as correções necessárias
         if mdSexo.ValorNumerico = 'Feminino' then
         begin
            // Fecha para uma nova verificação
            quRDAFaixas.Close;
            // Se Nutriz, define faixa de correção
            if mdTempoNutriz.AsFloat > 0 then
            begin
               quRDAFaixas.ParamByName( 'TIPOF' ).AsString := 'N';
               quRDAFaixas.ParamByName( 'MINF' ).AsFloat := mdTempoNutriz.AsFloat;
               quRDAFaixas.ParamByName( 'MAXF' ).AsFloat := mdTempoNutriz.AsFloat;
               quRDAFaixas.ParamByName( 'UNIDADE' ).AsString := LowerCase(mdTempoNutriz.Unidade);
            end
            // Se Gestante, define faixa de correção
            else if mdTempoGestante.AsFloat > 0 then
            begin
               quRDAFaixas.ParamByName( 'TIPOF' ).AsString := 'G';
               quRDAFaixas.ParamByName( 'MINF' ).AsFloat := mdTempoGestante.AsFloat;
               quRDAFaixas.ParamByName( 'MAXF' ).AsFloat := mdTempoGestante.AsFloat;
               quRDAFaixas.ParamByName( 'UNIDADE' ).AsString := LowerCase(mdTempoGestante.Unidade);
            end;
            // Se não tem valores para fazer as correções
            // Obs.: se o individuo for Gestante e Nutriz ao mesmo tempo
            // será considerado só como nutriz, pois o acrescimo de nutrientes
            // é maior nesta categoria (verificar isto com o autor).
            quRDAFaixas.Open;
            if quRDAFaixas.IsEmpty and (( mdTempoGestante.AsFloat + mdTempoNutriz.AsFloat ) > 0 ) then
               raise EDataSetIsEmpty.CreateFmt( 'Tabela: %s está vazia, pois tempo de Gestante/Nutriz não consta da tabela.', [quRDAFaixas.Name]);
            if (( mdTempoGestante.AsFloat + mdTempoNutriz.AsFloat ) > 0 ) then
            begin
               // Faz as correções necessárias
               quRDAGN.First;
               while not quRDAGN.Eof do
               begin
                  if cxRDA.Acha( GuidToName(quRDAGN.FieldbyName( 'IDNUT' ).AsString, cxRDA.Name ), TObject( mdNut ) ) then
                     begin
                        // Adição de um determinado nutriente
                        if quRDAGN.FieldByName( 'OP' ).AsString = '+' then
                           begin
                              mdNut.AsFloat := mdNut.AsFloat + quRDAGN.FieldbyName( quRDAFaixas.FieldByName( 'NOMEFAIXA' ).AsString ).AsFloat;
                              mdNut.Empty := False;
                              mdNut.Valid := True;
                           end
                        // Atribuição de um determinado nutriente
                        else if quRDAGN.FieldByName( 'OP' ).AsString = '=' then
                           begin
                              mdNut.ValorNumerico := quRDAGN.FieldbyName( quRDAFaixas.FieldByName( 'NOMEFAIXA' ).AsString ).AsString;
                              mdNut.Empty := False;
                              mdNut.Valid := True;
                           end
                        // Atribuição de um determinado nutriente
                        else if quRDAGN.FieldByName( 'OP' ).AsString = '&' then
                           begin
                              mdNut.ValorNumerico := '';
                              mdNut.Empty := True;
                              mdNut.Valid := False;
                           end;
                     end;
                  quRDAGN.Next;
               end;
               // Soma ao título informações sobre gestante/nutriz
               with quRDAFaixas do
               begin
                  if FieldByName( 'TIPOFAIXA' ).AsString = 'G' then
                     Aux := 'Gestação'
                  else if FieldByName( 'TIPOFAIXA' ).AsString = 'N' then
                     Aux := 'Nutriz'
                  else
                     Aux := '';
                  if Aux <> '' then
                  begin
                   if FieldByName( 'MINF' ).AsInteger <= 0 then
                     mdFaixaRDA.ValorNumerico := mdFaixaRDA.ValorNumerico +
                                                 ' e ' + aux +
                                                 ' menor que ' + IntToStr( FieldByName( 'MAXF' ).AsInteger ) +
                                                 ' ' + FieldByName( 'UNIDADE' ).AsString
                   else if FieldByName( 'MAXF' ).AsInteger >= 999 then
                     mdFaixaRDA.ValorNumerico := mdFaixaRDA.ValorNumerico +
                                                 ' e ' + aux +
                                                 ' maior igual a ' + IntToStr( FieldByName( 'MINF' ).AsInteger  ) +
                                                 ' ' + FieldByName( 'UNIDADE' ).AsString
                   else
                     mdFaixaRDA.ValorNumerico := mdFaixaRDA.ValorNumerico +
                                                 ' e ' + aux +
                                                 ' entre ' + IntToStr( FieldByName( 'MINF' ).AsInteger  ) +
                                                 ' e ' + IntToStr( FieldByName( 'MAXF' ).AsInteger - 1 ) +
                                                 ' ' + FieldByName( 'UNIDADE' ).AsString;
                  end;
               end;
            end;
         end;
         quRDAGN.Close;
         quRDAFaixas.Close;
         quRDA.Close;
      end;
   end;
   Result := True;

end;

destructor TRDA.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TRDA.Loaded;
begin
     inherited Loaded;
     DM:= FdmRDA;

     { Perform any component setup that depends on the property
       values having been set }

end;

procedure TRDA.Notification(AComponent: TComponent; Operation: TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of
       this component been deleted?  If so, update
       the property. }
     if AComponent = FMemoria then
        FMemoria := nil
     else if AComponent = FdmRDA then
        FdmRDA := nil
     else if AComponent = FDelayedOpIndicator then
        FDelayedOpIndicator := nil;
end;

procedure TRDA.SetCaixaRDA(const Value: String);
begin
  FCaixaRDA := Value;
end;

{procedure TRDA.SetDataBaseName(const Value: String);
begin
  FDataBase := Value;
end;}

procedure TRDA.SetMemoria(const Value: TMemoria);
begin
  FMemoria := Value;
  if Value <> nil then
     Value.FreeNotification(Self);
end;

procedure TRDA.SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
begin
  FDelayedOpIndicator := Value;
  if Value <> nil then
     Value.FreeNotification(Self);
end;

procedure TRDA.OpenTables;
begin
// Eu não quero que abra as queries na definicao, pois atrapalha os parametros 
end;

end.
