#define fmCalcNutr	1
#define fmConfigCalculos	2
#define fmNutrientesAcomp	3
#define fmNovoIndividuo	4
#define TfmAntrop01	5
#define TfmAntrop02	6
#define TfmRecCal01	7
#define TfmRecCal04	8
#define TfmRecCal03	9
#define TfmRecCal06	10
#define TfmInqNumDias	11
#define SelRefCal2	12
#define NutAcomp2	13
#define TfmInquer01	14
#define TfmInqObservacoes	15
#define TfmPlanoAlimentarNome	16
#define TfmSelRecCal	17
#define TfmRecNut	18
#define SelRefCalc	19
#define TfmDieta01	20
#define TfmDieObservacoes	21
#define TfmPrepPesoFinal	22
#define TfmPrepar01	23
#define TfmVerificaPesoFinal	24
#define TfmPrepReceita	25
#define fmAliWiz	26
#define NutAcomp3	27
#define fmDeficiente	28
#define fmCompPerna	29
#define TfmNutrientes	30
#define TfmMedidas	31
#define fmRefeicao	32
