{ Turbo Pascal Unit:  nutwin.pas                  }
{                                                 }
{ This is an interface unit containing integer    }
{ mappings of Topic IDs (names of Help            }
{ Topics) which are located in nutwin.RTF     }
{                                                 }
{ This file is re-written by RoboHELP           }
{ whenever nutwin.RTF is saved.   	          }
{                                                 }
{ However, the numeric values stored in           }
{ nutwin.hh are the 'master values' and if you    }
{ modify the value in nutwin.hh and then          }
{ save the nutwin.RTF again, this file will   }
{ reflect the changed values.                     }
{                                                 }


Unit nutwin;
   Interface
   Const

   Acessando_o_help = 3;
   Acesso_ao_sistema_pela_sala = 17;
   Acesso_ao_Sistema_pelo_menu = 19;
   Acesso_ao_Sistema_pelos_Ícones_rápidos = 20;
   Alterando_a_sala = 18;
   Anamnese_Nutricional_e_modelos_pré_definidos = 24;
   Ativando_e_desativando_as_dicas = 16;
   Bibliografia = 63;
   Cadastrando_sua_senha = 15;
   CEP = 33;
   Cidades = 40;
   Como_exportar_dados_do_sistema = 21;
   Conhecendo_seu_funcionamento = 2;
   Cor_da_Pele = 39;
   Dados_do_Alimento = 26;
   Dados_Pessoais = 22;
   DDD = 42;
   Dúvidas_comuns_entre_os_usuários = 9;
   Endereço_e_telefones = 23;
   Entre_em_contato_conosco = 7;
   Equipamento_necessário = 12;
   Equivalentes_Energéticos = 29;
   Equivalentes_Protéicos = 30;
   Estados = 41;
   Exames_Bioquímicos = 37;
   Exames_e_modelos_pré_definidos = 25;
   Ficha_de_Alimentos = 51;
   Ficha_de_Indivíduos = 47;
   Grupo_Alimentar = 43;
   Grupo_Protéico = 44;
   Grupos_Energético = 46;
   Instalar_o_sistema = 10;
   Introdução = 13;
   Listagem_de_Alimentos_por_Grupo_Alimentar = 53;
   Listagem_de_Alimentos_por_Ordem_Alfabética = 52;
   Listagem_de_alimentos_por_Origem = 54;
   Listagem_Geral_de_Indivíduos = 48;
   Listagem_Geral_de_Indivíduos_por_Pasta = 49;
   Medidas_Caseiras = 28;
   Meios_para_registrar_seu_software = 6;
   Modelos_de_Anamnese = 35;
   Nacionalidades = 38;
   Nutrientes = 27;
   O_que_há_de_novo = 1;
   Obtendo_ajuda_durante_seu_trabalho = 4;
   Obtendo_informações_sobre_o_seu_computador_e_seu_software = 5;
   Origem = 45;
   Pastas = 36;
   Preço = 31;
   Relatórios_de_Acompanhamento = 58;
   Remover_o_sistema = 11;
   Saiba_antes_de_usar_o_Organizador = 14;
   Senha = 34;
   Sobre = 61;
   Tabelas_Alimentares = 56;
   Tabelas_de_Indivíduos = 57;
   Tirando_dúvidas = 8;
   Totais_de_Cadastros_de_Alimentos = 55;
   Totais_de_Cadastros_de_Indivíduos = 50;
   Utilizando_as_Pastas = 60;
	
   Implementation
   end.

