#define fm_Login	1
#define fm_Dica	2
#define TfmPessoa	3
#define TfmLocPess	4
#define TfmTipoAnam	5
#define TfmAlim	6
#define TfmLocAlim	7
#define TfmListNut	8
#define TfmTelaPrincipal	9
#define TfmPPastas	10
#define TfmPSelDados	11
#define TfmSelecionaInqueritos	12
#define tbsPessoal	13
#define tsEndereco	14
#define tbsConsulta	15
#define teExames	16
#define teAntropometria	17
#define teInquerito	18
#define tePlanoAlimentar	19
#define teDadosAli	20
#define teAliNutrientes	21
#define teAliMedidas	22
#define teAliSubsProt	23
#define teAliPreco	24
#define teAliPreparacao	25
#define TfmTabPess	26
#define tsNacionalidade	27
#define tsInstruc	28
#define tsCorPele	29
#define tsCidade	30
#define tsEstado	31
#define tsTipAnam	32
#define tsPastas	33
#define tsExames	34
#define tsProfissao	35
#define TfmTabAli	36
#define tsTANut	37
#define tsTAOrig	38
#define tsTARefeicao	39
#define tsCadRefeicao	40
#define tsListaRef	41
#define tsRefeicao	42
#define tsVisualizacao	43
#define tsTAMedCas	44
#define tsTAGAlim	45
#define tsTAGCal	46
#define tsTASubsCal	47
#define tsTAgProt	48
#define tsTASProt	49
#define TfmDupAlim	50
#define TfmRelatorios	51
#define TfmNutRelInd	52
#define TfmOpcoesPess	53
#define taNut1	54
#define taNut2	55
#define teMenu	56
#define tsSenha	57
#define Tfm_MenuNut	58
#define TfmSobre	59
