// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TCustomListaAlimento                            }
{                                                                    }
{   Lista de Alimentos para Pesquisa                                 }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{                                                                    }
{   on 19 Oct 1999 at 9:09                                           }
{                                                                    }
{   Copyright © 1999 by DIS-EPM/UNIFESP                              }
{                                                                    }
{ ****************************************************************** }

unit CLstAli;

interface

uses SysUtils, Classes, DB, Forms, Dialogs, DMLstAli,
     CCSDBListaLinks, CAlimento, Nutcnst, DelayedOpIndicator;

type

   TOrdemAlimento = ( oaNome, oaNutrientes, oaPreco, oaFrequenciaUso );

   TCustomListaAlimento = class(TCCSDBListaLinks)
   private
      FDMListaAlimento : TDMListaAlimento;
      FFiltrarPorGrupoAlimentar: Boolean;
      FFiltrarPorOrigem: Boolean;
      FFiltrarDoInicio: Boolean;
      FTipoDeOrdem: TTipoOrdem;
      FOrdenarAlimentoPor: TOrdemAlimento;
      FFiltrarNomeAlimento: String;
      FDataBaseName: String;
      FLocalizaNomeAlimento: String;
      FListaDeAlimentos: TDataSource;
      FIDGrupoAlimentar: TDataSource;
      FIDOrigem: TDataSource;
      FIDNutriente: TDataSource;
      FIDUserName: TDataSource;
      FAlimentoCorrente: TAlimento;
      FDelayedOpIndicator: TDelayedOpIndicator;
      function SQLSelectBasico : String;
      function SQLNome : String;
      function SQLNutrientes : String;
//      function SQLPreco : String;
      function SQLFreqUso : String;
      function StrFilter : String;
      { Executa SQL }
      procedure ExecSQL;
      { Filtra lista conforme os atributos de filtro }
      procedure Filtrar;
      procedure DataChangeAli(Sender: TObject; Field: TField);
      procedure SetFiltrarDoInicio(const Value: Boolean);
      procedure SetFiltrarNomeAlimento(const Value: String);
      procedure SetDataBaseName(const Value: String);
      procedure SetFiltrarPorGrupoAlimentar(const Value: Boolean);
      procedure SetFiltrarPorOrigem(const Value: Boolean);
      procedure SetListaDeAlimentos(const Value: TDataSource);
      procedure SetLocalizaNomeAlimento(const Value: String);
      procedure SetOrdenarAlimentoPor(const Value: TOrdemAlimento);
      procedure SetTipoDeOrdem(const Value: TTipoOrdem);
      procedure SetIDGrupoAlimentar(const Value: TDataSource);
      procedure SetIDNutriente(const Value: TDataSource);
      procedure SetIDOrigem(const Value: TDataSource);
      procedure SetIDUserName(const Value: TDataSource);
      procedure SetAlimentoCorrente(const Value: TAlimento);
      procedure SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
   protected
      procedure Loaded; override;
   public
      procedure Notification(AComponent : TComponent; Operation : TOperation); override;
      property DMListaAlimento : TDMListaAlimento read FDMListaAlimento;
      constructor Create(AOwner: TComponent); override;
      destructor Destroy; override;
      procedure Refresh; override;
      { Localiza Alimento }
      function Localizar( Nome : String; Options: TLocateOptions ) : Boolean;
      procedure DefineDefaults;
      function PegaSubEP( IDAli : String ) : String; //*
   published
      { Indicador de Operação demorada }
      property DelayedOpIndicator : TDelayedOpIndicator read FDelayedOpIndicator write SetDelayedOpIndicator;
      { NomeAlimento a ser pesquisada }
      property FiltrarNomeAlimento : String read FFiltrarNomeAlimento write SetFiltrarNomeAlimento;
      { Indica se a pesquisa da NomeAlimento eh do inicio ou nao }
      property FiltrarDoInicio : Boolean read FFiltrarDoInicio write SetFiltrarDoInicio;
      { Filtra pelo Grupo Alimentar }
      property FiltrarPorGrupoAlimentar : Boolean read FFiltrarPorGrupoAlimentar write SetFiltrarPorGrupoAlimentar;
      { Filtra pela Origem do Alimento }
      property FiltrarPorOrigem : Boolean read FFiltrarPorOrigem write SetFiltrarPorOrigem;
      { Campos a serem ordenados }
      property OrdenarAlimentoPor : TOrdemAlimento read FOrdenarAlimentoPor write SetOrdenarAlimentoPor;
      { Sentido da ordenacao }
      property TipoDeOrdem : TTipoOrdem read FTipoDeOrdem write SetTipoDeOrdem;
      { Lista de Alimentos }
      property ListaDeAlimentos : TDataSource read FListaDeAlimentos write SetListaDeAlimentos;
      { Texto a Localizar }
      property LocalizaNomeAlimento : String read FLocalizaNomeAlimento write SetLocalizaNomeAlimento;
      property IDUserName : TDataSource read FIDUserName write SetIDUserName;
      property IDNutriente : TDataSource read FIDNutriente write SetIDNutriente;
      property IDGrupoAlimentar : TDataSource read FIDGrupoAlimentar write SetIDGrupoAlimentar;
      property IDOrigem : TDataSource read FIDOrigem write SetIDOrigem;
      property DataBaseName : String read FDataBaseName write SetDataBaseName;
      property AlimentoCorrente : TAlimento read FAlimentoCorrente write SetAlimentoCorrente;
   end;

procedure Register;

implementation

procedure Register;
begin
   RegisterComponents('Nutricao', [TCustomListaAlimento]);
end;

procedure TCustomListaAlimento.Notification(AComponent : TComponent; Operation : TOperation);
begin
   inherited Notification(AComponent, Operation);
   if Operation <> opRemove then
      Exit;
   if AComponent = FListaDeAlimentos then
      FListaDeAlimentos := nil
   else if AComponent = FIDGrupoAlimentar then
      FIDGrupoAlimentar := nil
   else if AComponent = FIDOrigem then
      FIDOrigem := nil
   else if AComponent = FIDNutriente then
      FIDNutriente := nil
   else if AComponent = FIDUserName then
      FIDUserName := nil
   else if AComponent = FAlimentoCorrente then
      FAlimentoCorrente := nil
   else if AComponent = FDMListaAlimento then
      FDMListaAlimento := nil
   else if AComponent = FDelayedOpIndicator then
      FDelayedOpIndicator := nil;
end;

constructor TCustomListaAlimento.Create(AOwner: TComponent);
begin
   inherited Create(AOwner);
   Application.CreateForm(TDMListaAlimento,FDMListaAlimento);
   FDMListaAlimento.FreeNotification (self);
   FDMListaAlimento.dsQAli.OnDataChange := DataChangeAli;
end;

destructor TCustomListaAlimento.Destroy;
begin
   if Assigned(FDMListaAlimento) then
      FDMListaAlimento.Free;
   inherited Destroy;
end;

procedure TCustomListaAlimento.Loaded;
begin
    inherited Loaded;
    DM:= FDMListaAlimento;
    with FDMListaAlimento do
    begin
       dsGruAli.DataSet.Active := FFiltrarPorGrupoAlimentar;
       dsOrigem.DataSet.Active := FFiltrarPorOrigem;
       dsNut.Dataset.Active := ( FOrdenarAlimentoPor = oaNutrientes );
       dsUsuario.Dataset.Active := ( FOrdenarAlimentoPor = oaFrequenciaUso );
    end;
    ExecSQL;
    Filtrar;
end;

procedure TCustomListaAlimento.Refresh;
begin
   ExecSQL;
   Filtrar;
   inherited;
end;

{ Executa SQL }
procedure TCustomListaAlimento.ExecSQL;
begin
   with FDMListaAlimento do
   begin
      dsQAli.DataSet := quAli;
      quAli.Close;
      quAli.SQL.Clear;
      if FOrdenarAlimentoPor = oaNome then        // Nome
         begin
            quAli.SQL.Add( SQLNome );
         end
      else if FOrdenarAlimentoPor = oaNutrientes then   // Nutrientes
         begin
            quAli.SQL.Add( SQLNutrientes );
         end
      else if FOrdenarAlimentoPor = oaPreco then   // Preço
         begin
//           quAli.SQL.Add( SQLPreco );
         end
      else if FOrdenarAlimentoPor = oaFrequenciaUso then   // Frequência de Uso
         begin
            quAli.SQL.Add( SQLFreqUso );
         end;
      // indica operação demorada;
      if Assigned( FDelayedOpIndicator ) then
         FDelayedOpIndicator.Start;
      try
         quAli.Open;
      finally
         // finaliza indicação de operação demorada
         if Assigned( FDelayedOpIndicator ) then
            FDelayedOpIndicator.Finish;
      end;
   end;
end;

{ Filtra lista conforme os atributos de filtro }
procedure TCustomListaAlimento.Filtrar;
begin
   with FDMListaAlimento do
   begin
      dsQAli.DataSet := quAli;
      dsQAli.DataSet.Filtered := False;
      dsQAli.DataSet.Filter := StrFilter;
      // indica operação demorada;
      if Assigned( FDelayedOpIndicator ) then
         FDelayedOpIndicator.Start;
      try
         dsQAli.DataSet.Filtered := True;
      finally
         // finaliza indicação de operação demorada
         if Assigned( FDelayedOpIndicator ) then
            FDelayedOpIndicator.Finish;
      end;
   end;
end;

function TCustomListaAlimento.Localizar( Nome : String; Options: TLocateOptions ) : Boolean;
begin
   Result := FDMListaAlimento.quAli.Locate( 'NOME', Nome, Options );
end;

Function TCustomListaAlimento.StrFilter : String;
var
   I : Integer;
   sTemp : array [1..2] of String;
begin
   Result := '';
   if FFiltrarPorGrupoAlimentar then
      sTemp[1] := 'IDGRUALI = ' + '''' + FDMListaAlimento.dsGruAli.DataSet.FieldByName( 'IDGRUALI' ).AsString + ''''
   else
      sTemp[1] := '';
   if FFiltrarPorOrigem then
      sTemp[2] := 'IDORIG = ' + '''' + FDMListaAlimento.dsOrigem.DataSet.FieldByName( 'IDORIG' ).AsString + ''''
   else
      sTemp[2] := '';
   Result := '';
   for I := 1  to 2 do
   begin
      if ( Result <> '' ) and ( sTemp[I] <> '' ) then
         Result := Result + ' and ' + sTemp[I]
      else
         Result := Result + sTemp[I];
   end;
end;

function TCustomListaAlimento.SQLSelectBasico : String;
begin
   Result :=
      'SELECT ' +
      ' ALIMENTO.IDALI ,' +
      ' ALIMENTO.NOME ,' +
      ' ALIMENTO.NOMESIMP ,' +
      ' ALIMENTO.IDORIG ,' +
      ' ALIMENTO.IDGRUALI';
end;

function TCustomListaAlimento.SQLNome : String;
begin
   Result := SQLSelectBasico +
      ' FROM ' +
      ' ALIMENTO';
   if FFiltrarNomeAlimento <> '' then
   begin
       if FFiltrarDoInicio then
          Result := Result + ' WHERE ( UPPER(NOME) LIKE UPPER(''' + FFiltrarNomeAlimento + '%'' ))'
       else
          Result := Result + ' WHERE ( UPPER(NOME) LIKE UPPER(''%' + FFiltrarNomeAlimento + '%'' ))'
   end;
   Result := Result + ' ORDER BY ALIMENTO.NOME';
   if FTipoDeOrdem = toDecrescente then
      Result := Result + ' DESC'
   else
      Result := Result + ' ASC';
end;

function TCustomListaAlimento.SQLNutrientes : String;
begin
   Result := SQLSelectBasico +
      ',ALINUT.IDNUT ,' +
      ' ALINUT.VALOR' +
      ' FROM ' +
      ' ALIMENTO ,' +
      ' ALINUT' +
      ' WHERE ' +
      ' ( ALINUT.IDNUT = ''' + FDMListaAlimento.dsNut.DataSet.FieldByName( 'IDNUT' ).AsString + ''' )'  +
      ' AND' +
      ' ( ALINUT.IDALI = ALIMENTO.IDALI )';
   if FFiltrarNomeAlimento <> '' then
   begin
      if FFiltrarDoInicio then
         Result := Result + ' AND ( UPPER(NOME) LIKE ''' + FFiltrarNomeAlimento + '%'' )'
      else
         Result := Result + ' AND ( UPPER(NOME) LIKE ''%' + FFiltrarNomeAlimento + '%'' )'
   end;
   Result := Result + ' ORDER BY ALINUT.VALOR';
   if FTipoDeOrdem = toDecrescente then
      Result := Result + ' DESC'
   else
      Result := Result + ' ASC';
end;
{
function TCustomListaAlimento.SQLPreco : String;
begin
   Result := SQLSelectBasico +
      ' FROM ' +
      ' ALIMENTO ,' +
      ' ALIPRECO' +
      ' WHERE ' +
      ' ( ALIMENTO.IDALI = ALIPRECO.IDALI )';
   if FFiltrarNomeAlimento <> '' then
   begin
      if FFiltrarDoInicio then
         Result := Result + ' AND ( UPPER(NOME) LIKE ''' + FFiltrarNomeAlimento + '%''' + ')'
      else
         Result := Result + ' AND ( UPPER(NOME) LIKE ''%' + FFiltrarNomeAlimento + '%''' + ')'
   end;
   Result := Result + ' ORDER BY ALIPRECO.PRECO';
   if FTipoDeOrdem = toDecrescente then
      Result := Result + ' DESC'
   else
      Result := Result + ' ASC';
   Result := '';
end;
}
function TCustomListaAlimento.SQLFreqUso : String;
begin
   Result := SQLSelectBasico +
      ',ALIFREQ.UserName ,' +
      ' ALIFREQ.FREQUSO' +
      ' FROM ' +
      ' ALIMENTO ,' +
      ' ALIFREQ' +
      ' WHERE ' +
      ' ( ALIFREQ.UserName = ''' + FDMListaAlimento.dsUsuario.DataSet.FieldByName( 'UserName' ).AsString + ''' )'  +
      ' AND' +
      ' ( ALIMENTO.IDALI = ALIFREQ.IDALI )';
   if FFiltrarNomeAlimento <> '' then
   begin
      if FFiltrarDoInicio then
         Result := Result + ' AND ( UPPER(NOME) LIKE ''' + FFiltrarNomeAlimento + '%'' )'
      else
         Result := Result + ' AND ( UPPER(NOME) LIKE ''%' + FFiltrarNomeAlimento + '%'' )'
   end;
   Result := Result + ' ORDER BY ALIFREQ.FREQUSO';
   if FTipoDeOrdem = toDecrescente then
      Result := Result + ' DESC'
   else
      Result := Result + ' ASC';
end;

procedure TCustomListaAlimento.SetFiltrarDoInicio(const Value: Boolean);
begin
   FFiltrarDoInicio := Value;
   if not (csLoading in ComponentState) then
      ExecSQL;
end;

procedure TCustomListaAlimento.SetFiltrarNomeAlimento(const Value: String);
begin
   FFiltrarNomeAlimento := Value;
   if not (csLoading in ComponentState)  then
      ExecSQL;
end;

procedure TCustomListaAlimento.SetDataBaseName(const Value: String);
begin
   FDataBaseName := Value;
end;

procedure TCustomListaAlimento.SetFiltrarPorGrupoAlimentar(
  const Value: Boolean);
begin
   FFiltrarPorGrupoAlimentar := Value;
   if Assigned( FIDGrupoAlimentar ) and (  not (csLoading in ComponentState)  ) then
   begin
      FDMListaAlimento.dsGruAli.DataSet.Active := FFiltrarPorGrupoAlimentar;
      Filtrar;
   end;
end;

procedure TCustomListaAlimento.SetFiltrarPorOrigem(const Value: Boolean);
begin
   FFiltrarPorOrigem := Value;
   if Assigned( FIDOrigem ) and (  not (csLoading in ComponentState)  ) then
   begin
      FDMListaAlimento.dsOrigem.DataSet.Active := FFiltrarPorOrigem;
      Filtrar;
   end;
end;

procedure TCustomListaAlimento.SetLocalizaNomeAlimento(const Value: String);
begin
   FLocalizaNomeAlimento := Value;
   if not (csLoading in ComponentState)  then
      Localizar( FLocalizaNomeAlimento, [loCaseInsensitive,loPartialKey] );
end;

procedure TCustomListaAlimento.SetOrdenarAlimentoPor(const Value: TOrdemAlimento);
begin
   FOrdenarAlimentoPor := Value;
   if not Assigned( FIDNutriente ) and not Assigned( FIDUserName ) and ( csLoading in ComponentState ) then
      exit;
    // Provisorio
    if FOrdenarAlimentoPor = oaPreco then
       begin
          ShowMessage( 'Ordenar por preço não está disponível!' );
          exit;
       end;
    FDMListaAlimento.dsNut.Dataset.Active := ( FOrdenarAlimentoPor = oaNutrientes );
    FDMListaAlimento.dsUsuario.Dataset.Active := ( FOrdenarAlimentoPor = oaFrequenciaUso );
    if ( FOrdenarAlimentoPor = oaNutrientes ) then
       FDMListaAlimento.dsNut.DataSet.Active := True
    else
       FDMListaAlimento.dsNut.DataSet.Active := False;
    if ( FOrdenarAlimentoPor = oaFrequenciaUso ) then
       FDMListaAlimento.dsUsuario.DataSet.Active := True
    else
       FDMListaAlimento.dsUsuario.DataSet.Active := False;
    ExecSQL;
end;

procedure TCustomListaAlimento.SetTipoDeOrdem(const Value: TTipoOrdem);
begin
   FTipoDeOrdem := Value;
   if not (csLoading in ComponentState)  then
      ExecSQL;
end;

procedure TCustomListaAlimento.SetIDGrupoAlimentar(const Value: TDataSource);
begin
   FIDGrupoAlimentar := Value;
   if Assigned (Value) then
   begin
      Value.DataSet := FDMListaAlimento.dsGruAli.DataSet;
      Value.FreeNotification(self);
   end;
end;

procedure TCustomListaAlimento.SetIDNutriente(const Value: TDataSource);
begin
   FIDNutriente := Value;
   if Assigned (Value) then
   begin
      Value.DataSet := FDMListaAlimento.dsNut.DataSet;
      Value.FreeNotification(self);
   end;
end;

procedure TCustomListaAlimento.SetIDOrigem(const Value: TDataSource);
begin
   FIDOrigem := Value;
   if Assigned (Value) then
   begin
      Value.DataSet := FDMListaAlimento.dsOrigem.DataSet;
      Value.FreeNotification(self);
   end;
end;

procedure TCustomListaAlimento.SetIDUserName(const Value: TDataSource);
begin
   FIDUserName := Value;
   if Assigned (Value) then
   begin
      Value.DataSet := FDMListaAlimento.dsUsuario.DataSet;
      Value.FreeNotification(self);
   end;
end;

procedure TCustomListaAlimento.SetListaDeAlimentos(const Value: TDataSource);
begin
   FListaDeAlimentos := Value;
   if Assigned (Value) then
   begin
      Value.DataSet := FDMListaAlimento.dsQAli.DataSet;
      Value.FreeNotification(self);
   end;
end;

procedure TCustomListaAlimento.DataChangeAli(Sender: TObject; Field: TField);
begin
   if Assigned( FAlimentoCorrente ) and (Field = nil) then
   begin
      FAlimentoCorrente.Peso := 100; // 100 gramas
      FAlimentoCorrente.IDAlimento := FDMListaAlimento.dsQAli.DataSet.FieldByName( 'IDALI' ).AsString;
   end;
end;

procedure TCustomListaAlimento.SetAlimentoCorrente(const Value: TAlimento);
begin
   FAlimentoCorrente := Value;
   if Assigned( Value ) then
      Value.FreeNotification(self);
end;

procedure TCustomListaAlimento.DefineDefaults;
begin
   FFiltrarPorGrupoAlimentar := False;
   FFiltrarPorOrigem := False;
   FFiltrarDoInicio := True;
   FTipoDeOrdem := toCrescente;
   FOrdenarAlimentoPor := oaNome;
   FFiltrarNomeAlimento := '';
   FLocalizaNomeAlimento := '';
end;

procedure TCustomListaAlimento.SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
begin
   if Assigned( Value ) then
      Value.FreeNotification(self);
   FDelayedOpIndicator := Value;
end;

//*
function TCustomListaAlimento.PegaSubEP(IDAli: String): String;
begin
    Result := '  ';
    if (IDAli = '') and FDMListaAlimento.quAli.Active then
        IDAli := FDMListaAlimento.quAli.FieldByName( 'IDALI' ).AsString;
    if FDMListaAlimento.taAliGCal.Locate( 'IDALI', IDAli, [] ) then
       Result := 'E'
    else
       Result := ' ';
    if FDMListaAlimento.taAliGProt.Locate( 'IDALI', IDAli, [] ) then
       Result := Result + 'P'
    else
       Result := Result + ' ';
end;

end.


