// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TEquivalenteEnergia                                }
{                                                                    }
{   Equivalente de Energia                                           }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file                                       }
{   on 28 Oct 1999 at 15:30                                          }
{                                                                    }
{   Copyright © 1999 by CIS/EPM                                      }
{                                                                    }
{ ****************************************************************** }

unit EquEnergia;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  db, dbtables, CAlimento, NutCnst, CCSListaLinks, DelayedOpIndicator;

type
  TEquivalenteEnergia = class(TCCSListaLinks) 
  private
    FListaDeGruposEquivalentes: TDataSource;
    FListaDeAlimentosEquivalentes: TDataSource;
    FFiltrarDoInicio: Boolean;
    FPeso: Double;
    FFiltrarNomeAlimento: String;
    FLocalizaNomeAlimento: String;
    FAlimento: TAlimento;
    FOrdenarEquivalentePor: TOrdenarEquivalente;
    FTipoDeOrdem: TTipoOrdem;
    FAtivar: Boolean;
    FIDAlimento: String;
    FDelayedOpIndicator: TDelayedOpIndicator;
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
    procedure SetListaDeAlimentosEquivalentes(const Value: TDataSource);
    procedure SetListaDeGruposEquivalentes(const Value: TDataSource);
    procedure SetAlimento(const Value: TAlimento);
    procedure SetFiltrarDoInicio(const Value: Boolean);
    procedure SetFiltrarNomeAlimento(const Value: String);
    procedure SetLocalizaNomeAlimento(const Value: String);
    procedure SetOrdenarEquivalentePor(const Value: TOrdenarEquivalente);
    procedure SetPeso(const Value: Double);
    procedure SetTipoDeOrdem(const Value: TTipoOrdem);
    procedure SetAtivar(const Value: Boolean);
    procedure SetIDAlimento(const Value: String);
    procedure SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
    { Private declarations }
  protected
    { Protected declarations }
      procedure Loaded; override; 
      procedure Notification(AComponent : TComponent; Operation : TOperation); override;

      function SQLSelectBasico : String;
      function SQLOrdemNome : String;
      function SQLOrdemMedida : String;
      procedure ExecSQL;
  public
    { Public declarations }
        property IDAlimento : String read FIDAlimento write SetIDAlimento;
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        procedure Refresh;override;
        { Localiza Medida }
        function Localizar( Nome : String; Options: TLocateOptions ) : Boolean;
   published
      { Published properties  }
        { Indicador de Operação Demorada }
        property DelayedOpIndicator : TDelayedOpIndicator read FDelayedOpIndicator write SetDelayedOpIndicator;
        { Palavra a ser pesquisada }
        property FiltrarNomeAlimento : String read FFiltrarNomeAlimento write SetFiltrarNomeAlimento;
        { Indica se a pesquisa da palavra eh do inicio ou nao }
        property FiltrarDoInicio : Boolean read FFiltrarDoInicio write SetFiltrarDoInicio;
        { Campos a serem ordenados }
        property OrdenarEquivalentePor : TOrdenarEquivalente read FOrdenarEquivalentePor write SetOrdenarEquivalentePor;
        { Sentido da ordenacao }
        property TipoDeOrdem : TTipoOrdem read FTipoDeOrdem write SetTipoDeOrdem;
        property ListaDeGruposEquivalentes : TDataSource read FListaDeGruposEquivalentes write SetListaDeGruposEquivalentes;
        { Lista de Alimentos }
        property ListaDeAlimentosEquivalentes : TDataSource read FListaDeAlimentosEquivalentes write SetListaDeAlimentosEquivalentes;
        { Texto a Localizar }
        property LocalizaNomeAlimento : String read FLocalizaNomeAlimento write SetLocalizaNomeAlimento;
        property Peso : Double read FPeso write SetPeso;
        property Alimento : TAlimento read FAlimento write SetAlimento;
        property Ativar : Boolean read FAtivar write SetAtivar;



  end;

procedure Register;

implementation

procedure Register;
begin
  RegisterComponents('Nutricao', [TEquivalenteEnergia]);
end;

{ TEquivalenteEnergia }

procedure TEquivalenteEnergia.AutoDestroy;
begin

end;

procedure TEquivalenteEnergia.AutoInitialize;
begin

end;

constructor TEquivalenteEnergia.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TEquivalenteEnergia.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TEquivalenteEnergia.ExecSQL;
begin
   if (not Assigned( FAlimento )) or (not FAtivar) then
      exit;
   if (not Assigned (FAlimento.DMUmAlimento)) or
      (not Assigned (FAlimento.DMUmAlimento.dsAliEquEnergia)) or
      (not Assigned (FAlimento.DMUmAlimento.dsAliEquEnergia.Dataset)) then
      exit;

{   if Assigned(FAlimento) then
   begin
      if FAlimento.DMUmAlimento.taAlimento.Locate( 'IDALI', FAlimento.IDAlimento,[] ) then
         FPeso := FAlimento.Peso
      else
         FPeso := 0;
   end; }

   with TQuery( FAlimento.DMUmAlimento.dsAliEquEnergia.Dataset ) do
   begin
      Close;
{      SQL.Clear;
      if OrdenarEquivalentePor = oeAlimento then
         SQL.Add( SQLOrdemNome )
      else if OrdenarEquivalentePor = oeMedida then
         SQL.Add( SQLOrdemMedida );
}      // indica operação demorada;
      if Assigned( FDelayedOpIndicator ) then
         FDelayedOpIndicator.Start;
      try
         Open;
      finally
         // finaliza indicação de operação demorada
         if Assigned( FDelayedOpIndicator ) then
            FDelayedOpIndicator.Finish;
      end;
   end;
end;

procedure TEquivalenteEnergia.Loaded;
begin
   inherited Loaded;

   if not FAtivar then
      exit;
   { Perform any component setup that depends on the property
     values having been set }
   with FAlimento.DMUmAlimento.dsGruEquEnergia.DataSet do
   begin
      Open;
   end;
   ExecSQL;
end;

function TEquivalenteEnergia.Localizar(Nome: String;
  Options: TLocateOptions): Boolean;
begin
   Result := FAlimento.DMUmAlimento.quAliEquEnergia.Locate( 'NOME', Nome, Options );
end;

procedure TEquivalenteEnergia.Notification(AComponent: TComponent;
  Operation: TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of
       this component been deleted?  If so, update
       the property. }
     if AComponent = FListaDeGruposEquivalentes then
        FListaDeGruposEquivalentes := nil
     else if AComponent = FListaDeAlimentosEquivalentes then
        FListaDeAlimentosEquivalentes := nil
     else if AComponent = FAlimento then
        FAlimento := nil
     else if AComponent = FDelayedOpIndicator then
        FDelayedOpIndicator := nil;
end;

procedure TEquivalenteEnergia.Refresh;
begin
   ExecSQL;
   inherited;
end;

procedure TEquivalenteEnergia.SetAlimento(const Value: TAlimento);
begin
  FAlimento := Value;
  if Assigned( Value ) then
     Value.FreeNotification(self);
  ExecSQL;
end;

procedure TEquivalenteEnergia.SetAtivar(const Value: Boolean);
begin
  if not Assigned( FAlimento ) then
     begin
        FAtivar := False;
        exit;
     end   
  else if FAtivar = Value then
  else if Value then
     begin
        FAtivar := Value;
        FAlimento.DMUmAlimento.dsGruEquEnergia.DataSet.Open;
        ExecSQL;
     end
  else
     begin
        FAtivar := Value;
        TQuery( FAlimento.DMUmAlimento.dsAliEquEnergia.Dataset ).Close;
        FAlimento.DMUmAlimento.dsGruEquEnergia.DataSet.Close;
     end;
end;

procedure TEquivalenteEnergia.SetDelayedOpIndicator(
  const Value: TDelayedOpIndicator);
begin
  FDelayedOpIndicator := Value;
  if Assigned( Value ) then
     Value.FreeNotification(self);
end;

procedure TEquivalenteEnergia.SetFiltrarDoInicio(const Value: Boolean);
begin
  FFiltrarDoInicio := Value;
  ExecSQL;
end;

procedure TEquivalenteEnergia.SetFiltrarNomeAlimento(const Value: String);
begin
  FFiltrarNomeAlimento := Value;
  ExecSQL;
end;

procedure TEquivalenteEnergia.SetIDAlimento(const Value: String);
begin
  FIDAlimento := Value;
end;

procedure TEquivalenteEnergia.SetListaDeAlimentosEquivalentes(
  const Value: TDataSource);
begin
  FListaDeAlimentosEquivalentes := Value;
  if Assigned (Value) then
  begin
     Value.FreeNotification(self);
     if Assigned( Alimento ) then
        Value.DataSet := Alimento.DMUmAlimento.dsAliEquEnergia.DataSet;
  end;      
end;

procedure TEquivalenteEnergia.SetListaDeGruposEquivalentes(
  const Value: TDataSource);
begin
  FListaDeGruposEquivalentes := Value;
  if Assigned (Value) then
  begin
     Value.FreeNotification(self);
     if Assigned( Alimento ) then
        Value.DataSet := FAlimento.DMUmAlimento.dsGruEquEnergia.DataSet;
  end;      
end;

procedure TEquivalenteEnergia.SetLocalizaNomeAlimento(const Value: String);
begin
  FLocalizaNomeAlimento := Value;
  Localizar( FLocalizaNomeAlimento, [loCaseInsensitive,loPartialKey] );
end;

procedure TEquivalenteEnergia.SetOrdenarEquivalentePor(
  const Value: TOrdenarEquivalente);
begin
  FOrdenarEquivalentePor := Value;
  ExecSQL;
end;

procedure TEquivalenteEnergia.SetPeso(const Value: Double);
begin
  FPeso := Value;
  ExecSQL;
end;

procedure TEquivalenteEnergia.SetTipoDeOrdem(const Value: TTipoOrdem);
begin
  FTipoDeOrdem := Value;
  ExecSQL;
end;

function TEquivalenteEnergia.SQLOrdemMedida: String;
begin
 Result := SQLSelectBasico +
   ' FROM ' +
   'MEDIDAS, ' +
   'ALIGCAL, ' +
   'ALIMENTO ' +

   ' WHERE (ALIGCAL.IDMEDCAS = MEDIDAS.IDMEDCAS) AND ' +
   ' (ALIGCAL.IDGRUCAL = :IDGRUCAL ) AND ' +
   ' (ALIGCAL.IDALI = ALIMENTO.IDALI ) ';

 if FFiltrarNomeAlimento <> '' then
 begin
    if FFiltrarDoInicio then
       Result := Result + ' AND ( UPPER(NOME) LIKE UPPER(''' + FFiltrarNomeAlimento + '%'' ))'
    else
       Result := Result + ' AND ( UPPER(NOME) LIKE UPPER(''%' + FFiltrarNomeAlimento + '%'' ))'
 end;

 Result := Result + ' ORDER BY ALIMENTO.NOME';

 if FTipoDeOrdem = toDecrescente then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';

end;

function TEquivalenteEnergia.SQLOrdemNome: String;
begin

 Result := SQLSelectBasico +
   ' FROM ' +
   'MEDIDAS, ' +
   'ALIGCAL, ' +
   'ALIMENTO ' +

   ' WHERE (ALIGCAL.IDMEDCAS = MEDIDAS.IDMEDCAS) AND ' +
   ' (ALIGCAL.IDGRUCAL = :IDGRUCAL ) AND ' +
   ' (ALIGCAL.IDALI = ALIMENTO.IDALI ) ';

 if FFiltrarNomealimento <> '' then
 begin
    if FFiltrarDoInicio then
       Result := Result + ' AND ( UPPER(NOME) LIKE UPPER(''' + FFiltrarNomeAlimento + '%'' ))'
    else
       Result := Result + ' AND ( UPPER(NOME) LIKE UPPER(''%' + FFiltrarNomeAlimento + '%'' ))'
 end;

 Result := Result + ' ORDER BY ALIMENTO.NOME';

 if FTipoDeOrdem = toDecrescente then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';


end;

function TEquivalenteEnergia.SQLSelectBasico: String;
begin
{   Result := 'SELECT Aligcal.QTDE, Aligcal.MEDGR, Medidas.MEDIDA, Aligcal.IDGRUCAL, ' +
                    'AliGCal.IDALI, Alimento.NOME ' +
             'FROM Medidas, Aligcal, Alimento ' +
             'WHERE  (Aligcal.IDMEDCAS = Medidas.IDMEDCAS) AND ' +
                    '(AligCal.IDGRUCAL = :IDGRUCAL ) AND ' +
                    '(AligCal.IDALI = Alimento.IDALI )'
}
  Result :=
   'SELECT ' +
   'ALIGCAL.QTDE, ' +
   'ALIGCAL.MEDGR, ' +
   'MEDIDAS.MEDIDA, ' +
   'ALIGCAL.IDGRUCAL, ' +
   'ALIGCAL.IDALI, ' +
   'ALIMENTO.NOME ';

end;

end.

