// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TListaAlimento                                     }
{                                                                    }
{   Lista de Alimentos para Pesquisa                                 }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file c:\projeto\compdelphi\alinut\lstali.cd }
{   on 27 Jan 1998 at 9:09                                           }
{                                                                    }
{   Copyright © 1998 by CIS/EPM                                      }
{                                                                    }
{ ****************************************************************** }

unit LstAli;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls,
     DMAli,CCSListaLinks,CCSDBListaLinks,
     Forms, Graphics, dbctrls, stdctrls, extctrls, dbgrids, db, Dialogs;

type

  TListaAlimento = class(TCCSDBListaLinks)
    private
      { Private fields of TListaAlimento }
        FUserName : String;
        FIDNutriente : String;
        FPalavra : String;
        FDoInicio : Boolean;
        FIDGrupoAlimentar : String;
        FIDOrigem : String;
        FOrdenarPor : Integer;
        FOrdem : Integer;
        FDMAlimento : TDMAlimento;
        FTextoLocalizar : String;

        { Pointers para os eventos dos componentes presentes nas propriedades}
        FOnGrupoAlimentarAFiltrarClick : TNotifyEvent;
        FOnNutrienteAOrdenarPorValorClick : TNotifyEvent;
        FOnUsuarioClick : TNotifyEvent;
        FOnOrdenarAlimentoPorClick : TNotifyEvent;
        FOnTipoDeOrdemClick : TNotifyEvent;
        FOnOrigemAFiltrarClick : TNotifyEvent;
        FOnAchaPalavraKeyPress : TKeyPressEvent;
        FOnAchaPalavraExit : TNotifyEvent;
        FOnAchaDoInicioClick : TNotifyEvent;
        FOnFiltrarPorGrupoAlimentarClick : TNotifyEvent;
        FOnFiltrarPorOrigemClick : TNotifyEvent;
        FOnLocalizaTextoChange : TNotifyEvent;
        FEventosOk : Boolean;

        { Storage for property Usuario }
        FUsuario : TDBLookupComboBox;
        { Storage for property FiltrarPorGrupoAlimentar }
        FFiltrarPorGrupoAlimentar : TCheckBox;
        { Storage for property GrupoAlimentarAFiltrar }
        FGrupoAlimentarAFiltrar : TDBLookupComboBox;
        { Storage for property FiltrarPorOrigem }
        FFiltrarPorOrigem : TCheckBox;
        { Storage for property OrigemOrigemAFiltrar }
        FOrigemAFiltrar : TDBLookupComboBox;
        { Storage for property AchaPalavra }
        FAchaPalavra : TEdit;
        { Storage for property AchaDoInicio }
        FAchaDoInicio : TCheckBox;
        { Storage for property NutrienteAOrdenarPorValor }
        FNutrienteAOrdenarPorValor : TDBLookupComboBox;
        { Storage for property OrdenarAlimentoPor }
        FOrdenarAlimentoPor : TRadioGroup;
        { Storage for property TipoOrdem }
        FTipoDeOrdem : TRadioGroup;
        { Storage for property ListaDeAlimentos }
        FListaDeAlimentos : TDBGrid;
        { Storage for property Ativar }
        FAtivar : Boolean;
        { Storage for property LocalizaTexto }
        FLocalizaTexto : TEdit;
        { Storage for property DataBaseName }
        FDataBaseName : String;

      { Private methods of TListaAlimento }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;

        { para montagem das querys }
        function SQLSelectBasico : String;
        function SQLNome : String;
        function SQLNutrientes : String;
//        function SQLPreco : String;
        function SQLFreqUso : String;
        function StrFilter : String;
        { Executa SQL }
        procedure ExecSQL;
        { Filtra lista conforme os atributos de filtro }
        procedure Filtrar;
        { Ativar os dados }
        procedure SetAtivar( Value : Boolean );
        { Seta variaveis de eventos }
        procedure SetEventos;

        { procedures a serem executadas antes dos eventos dos componentes das propriedades}
        procedure OnGrupoAlimentarAFiltrarClick(Sender: TObject);
        procedure OnNutrienteAOrdenarPorValorClick(Sender: TObject);
        procedure OnUsuarioClick(Sender: TObject);
        procedure OnOrdenarAlimentoPorClick(Sender: TObject);
        procedure OnTipoDeOrdemClick(Sender: TObject);
        procedure OnOrigemAFiltrarClick(Sender: TObject);
        procedure OnAchaPalavraKeyPress(Sender: TObject; var Key: Char);
        procedure OnAchaPalavraExit(Sender: TObject);
        procedure OnAchaDoInicioClick(Sender: TObject);
        procedure OnFiltrarPorGrupoAlimentarClick(Sender: TObject);
        procedure OnFiltrarPorOrigemClick(Sender: TObject);
        procedure OnLocalizaTextoChange(Sender: TObject);

    protected
      { Protected fields of TListaAlimento }

      { Protected methods of TListaAlimento }
        procedure Loaded; override;

    public
      { Public fields and properties of TListaAlimento }
        procedure Notification(AComponent : TComponent; Operation : TOperation); override;
        { Nome do Usuário para as suas preferencias }
        property DMAlimento : TDMAlimento read FDMALimento;

      { Public methods of TListaAlimento }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function Execute : Boolean;
        { Localiza Alimento }
        function Localizar( Nome : String; Options: TLocateOptions ) : Boolean;

    published
      { Published properties of TListaAlimento }
        { Nome do Usuário para as suas preferencias }
        property Usuario : TDBLookupComboBox read FUsuario write FUsuario;
        { Palavra a ser pesquisada }
        property AchaPalavra : TEdit read FAchaPalavra write FAchaPalavra;
        { Indica se a pesquisa da palavra eh do inicio ou nao }
        property AchaDoInicio : TCheckBox read FAchaDoInicio write FAchaDoInicio;
        { Filtra pelo Grupo Alimentar }
        property FiltrarPorGrupoAlimentar : TCheckBox
                 read FFiltrarPorGrupoAlimentar write FFiltrarPorGrupoAlimentar;
        property GrupoAlimentarAFiltrar : TDBLookupComboBox
                 read FGrupoAlimentarAFiltrar write FGrupoAlimentarAFiltrar;
        { Filtra pela Origem do Alimento }
        property FiltrarPorOrigem : TCheckBox
                 read FFiltrarPorOrigem write FFiltrarPorOrigem;
        property OrigemAFiltrar : TDBLookupComboBox
                 read FOrigemAFiltrar write FOrigemAFiltrar;
        { nutriente cujo valor ordenara o alimento }
        property NutrienteAOrdenarPorValor : TDBLookupComboBox
                 read FNutrienteAOrdenarPorValor write FNutrienteAOrdenarPorValor;
        { Campos a serem ordenados }
        property OrdenarAlimentoPor : TRadioGroup
                 read FOrdenarAlimentoPor write FOrdenarAlimentoPor;
        { Sentido da ordenacao }
        property TipoDeOrdem : TRadioGroup read FTipoDeOrdem write FTipoDeOrdem;
        { Lista de Alimentos }
        property ListaDeAlimentos : TDBGrid read FListaDeAlimentos write FListaDeAlimentos;
        { Texto a Localizar }
        property LocalizaTexto : TEdit read FLocalizaTexto write FLocalizaTexto;
        { Ativar dados }
//        property Ativar : Boolean read FAtivar write SetAtivar;
        { DataBaseName }
        property DataBaseName : String read FDataBaseName write FDataBaseName;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TListaAlimento with Nutricao as its
       default page on the Delphi component palette }
     RegisterComponents('Nutricao', [TListaAlimento]);
end;

{ Resets prop of component type if referenced component deleted }
procedure TListaAlimento.Notification(AComponent : TComponent; Operation : TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of
       this component been deleted?  If so, update
       the property. }
     if AComponent = FUsuario then
        FUsuario := nil
     else if AComponent = FFiltrarPorGrupoAlimentar then
        FFiltrarPorGrupoAlimentar := nil
     else if AComponent = FGrupoAlimentarAFiltrar then
        FGrupoAlimentarAFiltrar := nil
     else if AComponent = FFiltrarPorOrigem then
        FFiltrarPorOrigem := nil
     else if AComponent = FOrigemAFiltrar then
        FOrigemAFiltrar := nil
     else if AComponent = FAchaPalavra then
        FAchaPalavra := nil
     else if AComponent = FAchaDoInicio then
        FAchaDoInicio := nil
     else if AComponent = FNutrienteAOrdenarPorValor then
        FNutrienteAOrdenarPorValor := nil
     else if AComponent = FOrdenarAlimentoPor then
        FOrdenarAlimentoPor := nil
     else if AComponent = FTipoDeOrdem then
        FTipoDeOrdem := nil
     else if AComponent = FListaDeAlimentos then
        FListaDeAlimentos := nil
     else if AComponent = FLocalizaTexto then
        FLocalizaTexto := nil;

end; { of Notification }

{ Method to set variable and property values and create objects }
procedure TListaAlimento.AutoInitialize;
begin
   FEventosOk := False;
//   FDMAlimento := TDMAlimento.Create(self);
   Application.CreateForm(TDMAlimento,FDMAlimento);
   //Acerta o DM

end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TListaAlimento.AutoDestroy;
begin
if Assigned(FDMAlimento) then
   FDMAlimento.Free;
end; { of AutoDestroy }

constructor TListaAlimento.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TListaAlimento.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TListaAlimento.Loaded;
begin
     inherited Loaded;
     DM:= FDMAlimento;

     { Perform any component setup that depends on the property
       values having been set }

end;

function TListaAlimento.Execute : Boolean;
begin
   SetAtivar( True );
   { Return True if the operation was successful, False otherwise }
   Result := True
end;

{ Ativar dados }
procedure TListaAlimento.SetAtivar( Value : Boolean );
begin
   if (csLoading in ComponentState) then
      FAtivar := Value
   else if FAtivar = Value then
   else if not Value then
      begin
         FIDNutriente := '';
         FUserName := '';
         FPalavra := '';
         FDoInicio := False;
         FIDGrupoAlimentar := '';
         FIDOrigem := '';
         FOrdenarPor := 0;
         FOrdem := 0;
         FTextoLocalizar := '';
         if not ( FDMAlimento is TDMAlimento ) then
         if ( FDMAlimento = nil ) then
         with FDMAlimento do
         begin
            dsGruAli.DataSet.Active := False;
            dsOrigem.DataSet.Active := False;
            dsNut.Dataset.Active := False;
            dsUsuario.Dataset.Active := False;

            FListaDeAlimentos.DataSource := nil;
            FGrupoAlimentarAFiltrar.ListSource := nil;
            FNutrienteAOrdenarPorValor.ListSource := nil;
            FUsuario.ListSource := nil;
            OrigemAFiltrar.ListSource := nil;
         end;
         FAtivar := Value;
      end
   else if FUsuario = nil then
      ShowMessage( 'Usuario não definido' )
   else if FFiltrarPorGrupoAlimentar = nil then
      ShowMessage( 'FiltrarPorGrupoAlimentar não definido' )
   else if FGrupoAlimentarAFiltrar = nil then
      ShowMessage( 'GrupoAlimentarAFiltrar não definido' )
   else if FFiltrarPorOrigem = nil then
      ShowMessage( 'FiltrarPorOrigem não definido' )
   else if FOrigemAFiltrar = nil then
      ShowMessage( 'OrigemAFiltrar não definido' )
   else if FAchaPalavra = nil then
      ShowMessage( 'AchaPalavra não definido' )
   else if FAchaDoInicio = nil then
      ShowMessage( 'AchaDoInicio não definido' )
   else if FNutrienteAOrdenarPorValor = nil then
      ShowMessage( 'NutrienteAOrdenarPorValor não definido' )
   else if FOrdenarAlimentoPor = nil then
      ShowMessage( 'OrdenarAlimentoPor não definido' )
   else if FTipoDeOrdem = nil then
      ShowMessage( 'TipoDeOrdem não definido' )
   else if FListaDeAlimentos = nil then
      ShowMessage( 'ListaDeAlimentos não definido' )
   else if FLocalizaTexto = nil then
      ShowMessage( 'LocalizaTexto não definido' )
   else
      begin
         SetEventos;
         FIDNutriente := '';
         FUserName := '';
         FPalavra := FAchaPalavra.Text;
         FDoInicio := FAchaDoInicio.Checked;
         FIDGrupoAlimentar := '';
         FIDOrigem := '';
         FOrdenarPor := FOrdenarAlimentoPor.ItemIndex;
         FOrdem := FTipoDeOrdem.ItemIndex;
         FTextoLocalizar := FLocalizaTexto.Text;
         with FDMAlimento do
         begin
            dsGruAli.DataSet.Active := FFiltrarPorGrupoAlimentar.Checked;
            dsOrigem.DataSet.Active := FFiltrarPorOrigem.Checked;
            dsNut.Dataset.Active := ( FOrdenarAlimentoPor.ItemIndex = 1 );
            dsUsuario.Dataset.Active := ( FOrdenarAlimentoPor.ItemIndex = 3 );

            FListaDeAlimentos.DataSource := dsQAli;
            FGrupoAlimentarAFiltrar.KeyField := 'IDGRUALI';
            FGrupoAlimentarAFiltrar.ListField := 'NOMEGRU';
            FGrupoAlimentarAFiltrar.ListSource := dsGruAli;
            FNutrienteAOrdenarPorValor.KeyField := 'IDNUT';
            FNutrienteAOrdenarPorValor.ListField := 'NOMENUT';
            FNutrienteAOrdenarPorValor.ListSource := dsNut;
            FUsuario.KeyField := 'USERNAME';
            FUsuario.ListField := 'USERNAME';
            FUsuario.ListSource := dsUsuario;
            OrigemAFiltrar.KeyField := 'IDORIG';
            OrigemAFiltrar.ListField := 'DESCRICAO';
            OrigemAFiltrar.ListSource := dsOrigem;
         end;
         ExecSQL;
         Filtrar;
         FAtivar := Value;
      end;
end;

{ Seta variaveis de eventos }
procedure TlistaAlimento.SetEventos;
begin
   { Perform the component operation }
   if not FEventosOk then
   begin
      FOnGrupoAlimentarAFiltrarClick := FGrupoAlimentarAFiltrar.OnCloseUp;
      FOnNutrienteAOrdenarPorValorClick := FNutrienteAOrdenarPorValor.OnCloseUp;
      FOnUsuarioClick := FUsuario.OnCloseUp;
      FOnOrdenarAlimentoPorClick := FOrdenarAlimentoPor.OnClick;
      FOnTipoDeOrdemClick := FTipoDeOrdem.OnClick;
      FOnOrigemAFiltrarClick := FOrigemAFiltrar.OnClick;
      FOnAchaPalavraKeyPress := FAchaPalavra.OnKeyPress;
      FOnAchaPalavraExit := FAchaPalavra.OnExit;
      FOnAchaDoInicioClick := FAchaDoInicio.OnClick;
      FOnFiltrarPorGrupoAlimentarClick := FFiltrarPorGrupoAlimentar.OnClick;
      FOnFiltrarPorOrigemClick := FFiltrarPorOrigem.OnClick;
      FOnLocalizaTextoChange := FLocalizaTexto.OnChange;

      FGrupoAlimentarAFiltrar.OnCloseUp := OnGrupoAlimentarAFiltrarClick;
      FNutrienteAOrdenarPorValor.OnCloseUp := OnNutrienteAOrdenarPorValorClick;
      FUsuario.OnCloseUp := OnUsuarioClick;
      FOrdenarAlimentoPor.OnClick := OnOrdenarAlimentoPorClick;
      FTipoDeOrdem.OnClick := OnTipoDeOrdemClick;
      FOrigemAFiltrar.OnClick := OnOrigemAFiltrarClick;
      FAchaPalavra.OnKeyPress := OnAchaPalavraKeyPress;
      FAchaPalavra.OnExit := OnAchaPalavraExit;
      FAchaDoInicio.OnClick := OnAchaDoInicioClick;
      FFiltrarPorGrupoAlimentar.OnClick := OnFiltrarPorGrupoAlimentarClick;
      FFiltrarPorOrigem.OnClick := OnFiltrarPorOrigemClick;
      FLocalizaTexto.OnChange := OnLocalizaTextoChange;
      FEventosOk := True;
   end;
end;

{ Executa SQL }
procedure TListaAlimento.ExecSQL;
begin

with FDMAlimento do
begin
   dsQAli.DataSet := quAli;
   quAli.Close;
   quAli.SQL.Clear;
   FListaDeAlimentos.Columns[0].Width := 165;
   FListaDeAlimentos.Columns[1].Width := 70;
   if FOrdenarPor = 0 then        // Nome
      begin
         quAli.SQL.Add( SQLNome );
         FListaDeAlimentos.Columns[0].Width := 235;
         FListaDeAlimentos.Columns[1].Width := 0;
      end
   else if FOrdenarPor = 1 then   // Nutrientes
      begin
         quAli.SQL.Add( SQLNutrientes );
         FListaDeAlimentos.Columns[1].Title.Caption := taNut.FieldByName( 'NOMENUT' ).AsString + ' (' +
                                                       taNut.FieldByName( 'UNIDADE' ).AsString + ')';
         FListaDeAlimentos.Columns[1].FieldName := 'VALOR';
      end
   else if FOrdenarPor = 2 then   // Preço
      begin
{         quAli.SQL.Add( SQLPreco );
         FListaDeAlimentos.Columns[1].Title.Caption := 'Preço R$';
         FListaDeAlimentos.Columns[1].FieldName := 'PRECO';   }
      end
   else if FOrdenarPor = 3 then   // Frequência de Uso
      begin
         quAli.SQL.Add( SQLFreqUso );
         FListaDeAlimentos.Columns[1].Title.Caption := 'Freq. de Uso';
         FListaDeAlimentos.Columns[1].FieldName := 'FREQUSO';
      end;
   quAli.Open;
end;


end;

{ Filtra lista conforme os atributos de filtro }
procedure TListaAlimento.Filtrar;
begin
with FDMAlimento do
begin
   dsQAli.DataSet := quAli;
   dsQAli.DataSet.Filtered := False;
   dsQAli.DataSet.Filter := StrFilter;
   dsQAli.DataSet.Filtered := True;
end;
end;

//==============================================================================

Function TListaAlimento.StrFilter : String;
var
   I : Integer;
   sTemp : array [1..2] of String;
begin
   if FIDGrupoAlimentar <> '' then
      sTemp[1] := 'IDGRUALI = ' + '''' + FIDGrupoAlimentar + ''''
   else
      sTemp[1] := '';

   if FIDOrigem <> '' then
      sTemp[2] := 'IDORIG = ' + '''' + FIDOrigem + ''''
   else
      sTemp[2] := '';

   Result := '';
   for I := 1  to 2 do
   begin
      if ( Result <> '' ) and ( sTemp[I] <> '' ) then
         Result := Result + ' and ' + sTemp[I]
      else
         Result := Result + sTemp[I];
   end;

end;

function TListaAlimento.SQLSelectBasico : String;
begin

{ Result :=
   'SELECT ' +
   ' ALIMENTO.IDALI ,' +
   ' ALIMENTO.NOME ,' +
   ' ALIMENTO.NOMESIMP ,' +
   ' ALIMENTO.IDORIG ,' +
   ' ALIMENTO.IDGRUALI ,' +

   ' ALIPRECO.PRECO ,' +
   ' ALIPRECO.DATA'; }

 Result :=
   'SELECT ' +
   ' ALIMENTO.IDALI ,' +
   ' ALIMENTO.NOME ,' +
   ' ALIMENTO.NOMESIMP ,' +
   ' ALIMENTO.IDORIG ,' +
   ' ALIMENTO.IDGRUALI';

end;

function TListaAlimento.SQLNome : String;
begin

{ Result := SQLSelectBasico +
   ' FROM ' +
   ' ALIMENTO,' +
   ' ALIPRECO' +

   ' WHERE ' +
   ' ( ALIMENTO.IDALI = ALIPRECO.IDALI )';  }

 Result := SQLSelectBasico +
   ' FROM ' +
   ' ALIMENTO';

 if FPalavra <> '' then
 begin
    if FDoInicio then
       Result := Result + ' WHERE ( NOME LIKE ''' + FPalavra + '%'' )'
    else
       Result := Result + ' WHERE ( NOME LIKE ''%' + FPalavra + '%'' )'
 end;

 Result := Result + ' ORDER BY ALIMENTO.NOME';

 if FOrdem = 1 then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';

end;

function TListaAlimento.SQLNutrientes : String;
begin

{ Result := SQLSelectBasico +
   ',ALINUT.IDNUT ,' +
   ' ALINUT.VALOR' +

   ' FROM ' +
   ' ALIMENTO ,' +
   ' ALINUT ,' +
   ' ALIPRECO' +

   ' WHERE ' +
   ' ( ALINUT.IDNUT = ' + ''' + FIDNutriente + ''' )'  +
   ' AND' +
   ' ( ALINUT.IDALI = ALIMENTO.IDALI )' +
   ' AND' +
   ' ( ALINUT.IDALI = ALIPRECO.IDALI )';  }

 Result := SQLSelectBasico +
   ',ALINUT.IDNUT ,' +
   ' ALINUT.VALOR' +

   ' FROM ' +
   ' ALIMENTO ,' +
   ' ALINUT' +

   ' WHERE ' +
   ' ( ALINUT.IDNUT = ''' + FIDNutriente + ''' )'  +
   ' AND' +
   ' ( ALINUT.IDALI = ALIMENTO.IDALI )';

 if FPalavra <> '' then
 begin
    if FDoInicio then
       Result := Result + ' AND ( NOME LIKE ''' + FPalavra + '%'' )'
    else
       Result := Result + ' AND ( NOME LIKE ''%' + FPalavra + '%'' )'
 end;

 Result := Result + ' ORDER BY ALINUT.VALOR';

 if FOrdem = 1 then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';

end;
{
function TListaAlimento.SQLPreco : String;
begin

 Result := SQLSelectBasico +
   ' FROM ' +
   ' ALIMENTO ,' +
   ' ALIPRECO' +

   ' WHERE ' +
   ' ( ALIMENTO.IDALI = ALIPRECO.IDALI )';

 if FPalavra <> '' then
 begin
    if FDoInicio then
       Result := Result + ' AND ( NOME LIKE ''' + FPalavra + '%''' + ')'
    else
       Result := Result + ' AND ( NOME LIKE ''%' + FPalavra + '%''' + ')'
 end;

 Result := Result + ' ORDER BY ALIPRECO.PRECO';

 if FOrdem = 1 then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';

 Result := '';

end;
}
function TListaAlimento.SQLFreqUso : String;
begin

{ Result := SQLSelectBasico +
   ',ALIFREQ.USERNAME ,' +
   ' ALIFREQ.FREQUSO' +

   ' FROM ' +
   ' ALIMENTO ,' +
   ' ALIFREQ ,' +
   ' ALIPRECO' +

   ' WHERE ' +
   ' ( ALIFREQ.USERNAME = ' + ''' + FUserName + ''' )'  +
   ' AND' +
   ' ( ALIMENTO.IDALI = ALIPRECO.IDALI )' +
   ' AND' +
   ' ( ALIMENTO.IDALI = ALIFREQ.IDALI )';    }

 Result := SQLSelectBasico +
   ',ALIFREQ.USERNAME ,' +
   ' ALIFREQ.FREQUSO' +

   ' FROM ' +
   ' ALIMENTO ,' +
   ' ALIFREQ' +

   ' WHERE ' +
   ' ( ALIFREQ.USERNAME = ''' + FUserName + ''' )'  +
   ' AND' +
   ' ( ALIMENTO.IDALI = ALIFREQ.IDALI )';

 if FPalavra <> '' then
 begin
    if FDoInicio then
       Result := Result + ' AND ( NOME LIKE ''' + FPalavra + '%'' )'
    else
       Result := Result + ' AND ( NOME LIKE ''%' + FPalavra + '%'' )'
 end;

 Result := Result + ' ORDER BY ALIFREQ.FREQUSO';

 if FOrdem = 1 then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';

end;

function TListaAlimento.Localizar( Nome : String; Options: TLocateOptions ) : Boolean;
begin
   Result := FDMAlimento.quAli.Locate( 'NOME', Nome, Options );
end;

//------------------------------------------------------------------------------

procedure TListaAlimento.OnGrupoAlimentarAFiltrarClick(Sender: TObject);
begin
   FIDGrupoAlimentar := FDMAlimento.taGruAli.FieldByName( 'IDGRUALI' ).AsString;
   Filtrar;
   if Assigned(FOnGrupoAlimentarAFiltrarClick) then
      FOnGrupoAlimentarAFiltrarClick(Sender);
end;

procedure TListaAlimento.OnNutrienteAOrdenarPorValorClick(Sender: TObject);
begin
   FIDNutriente := FDMAlimento.taNut.FieldByName( 'IDNUT' ).AsString;
   ExecSQL;
   if Assigned(FOnNutrienteAOrdenarPorValorClick) then
      FOnNutrienteAOrdenarPorValorClick(Sender);
end;

procedure TListaAlimento.OnUsuarioClick(Sender: TObject);
begin
   FUserName := FDMAlimento.taUsuario.FieldByName( 'USERNAME' ).AsString;
   ExecSQL;
   if Assigned(FOnUsuarioClick) then
      FOnUsuarioClick(Sender);
end;

procedure TListaAlimento.OnOrdenarAlimentoPorClick(Sender: TObject);
begin
   // Provisorio
   if FOrdenarAlimentoPor.ItemIndex = 2 then
      begin
         ShowMessage( 'Ordenar por preço não está disponível!' );
         FOrdenarAlimentoPor.ItemIndex := FOrdenarPor;
      end;

   FOrdenarPor := FOrdenarAlimentoPor.ItemIndex;
   FDMAlimento.dsNut.Dataset.Active := ( FOrdenarAlimentoPor.ItemIndex = 1 );
   FDMAlimento.dsUsuario.Dataset.Active := ( FOrdenarAlimentoPor.ItemIndex = 3 );
   if ( FOrdenarAlimentoPor.ItemIndex = 1 ) then
      FIDNutriente := FDMAlimento.taNut.FieldByName( 'IDNUT' ).AsString
   else
      FIDNutriente:= '';
   if ( FOrdenarAlimentoPor.ItemIndex = 3 ) then
      FUserName := FDMAlimento.taUsuario.FieldByName( 'USERNAME' ).AsString
   else
      FUserName := '';
   ExecSQL;
   if Assigned(FOnOrdenarAlimentoPorClick) then
      FOnOrdenarAlimentoPorClick(Sender);
end;

procedure TListaAlimento.OnTipoDeOrdemClick(Sender: TObject);
begin
   FOrdem := FTipoDeOrdem.ItemIndex;
   ExecSQL;
   if Assigned(FOnTipoDeOrdemClick) then
      FOnTipoDeOrdemClick(Sender);
end;

procedure TListaAlimento.OnOrigemAFiltrarClick(Sender: TObject);
begin
   FIDOrigem := FDMAlimento.taOrigem.FieldByName( 'IDORIG' ).AsString;
   Filtrar;
   if Assigned(FOnOrigemAFiltrarClick) then
      FOnOrigemAFiltrarClick(Sender);
end;

procedure TListaAlimento.OnAchaPalavraKeyPress(Sender: TObject; var Key: Char);
begin
   if Key = #13 then
      begin
         FPalavra := FAchaPalavra.Text;
         ExecSQL;
      end;
   if Assigned(FOnAchaPalavraKeyPress) then
      FOnAchaPalavraKeyPress(Sender, Key);
end;

procedure TListaAlimento.OnAchaPalavraExit(Sender: TObject);
begin
   FPalavra := FAchaPalavra.Text;
   ExecSQL;
   if Assigned(FOnAchaPalavraExit) then
      FOnAchaPalavraExit(Sender);
end;

procedure TListaAlimento.OnAchaDoInicioClick(Sender: TObject);
begin
   FDoInicio := FAchaDoInicio.Checked;
   ExecSQL;
   if Assigned(FOnAchaDoInicioClick) then
      FOnAchaDoInicioClick(Sender);
end;

procedure TListaAlimento.OnFiltrarPorGrupoAlimentarClick(Sender: TObject);
begin
   FDMAlimento.dsGruAli.DataSet.Active := FFiltrarPorGrupoAlimentar.Checked;
   if FFiltrarPorGrupoAlimentar.Checked then
      FIDGrupoAlimentar := FDMAlimento.taGruAli.FieldByName( 'IDGRUALI' ).AsString
   else
      FIDGrupoAlimentar:= '';
   Filtrar;
   if Assigned(FOnFiltrarPorGrupoAlimentarClick) then
      FOnFiltrarPorGrupoAlimentarClick(Sender);
end;

procedure TListaAlimento.OnFiltrarPorOrigemClick(Sender: TObject);
begin
   FDMAlimento.dsOrigem.DataSet.Active := FFiltrarPorOrigem.Checked;
   if FFiltrarPorOrigem.Checked then
      FIDOrigem := FDMAlimento.taOrigem.FieldByName( 'IDORIG' ).AsString
   else
      FIDOrigem:= '';
   Filtrar;
   if Assigned(FOnFiltrarPorOrigemClick) then
      FOnFiltrarPorOrigemClick(Sender);
end;

procedure TListaAlimento.OnLocalizaTextoChange(Sender: TObject);
begin
   FTextoLocalizar := FLocalizaTexto.Text;
   Localizar( FTextoLocalizar, [loCaseInsensitive,loPartialKey] );
   if Assigned(FOnLocalizaTextoChange) then
      FOnLocalizaTextoChange(Sender);
end;


end.


