// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TListaMedida                                       }
{                                                                    }
{   Lista de Medidas de um Alimento                                  }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file                                       }
{   on 27 Jan 1998 at 9:09                                           }
{                                                                    }
{   Copyright © 1998 by CIS/EPM                                      }
{                                                                    }
{ ****************************************************************** }

unit LstMed;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls, DMAli, LstAli,
     Forms, Graphics, dbctrls, stdctrls, extctrls, dbgrids, db, Dialogs;

type
  TListaMedida = class(TComponent)
    private
      { Private fields of TListaMedida }
        FUserName : String;

        FPalavra : String;
        FDoInicio : Boolean;
        FOrdenarPor : Integer;
        FOrdem : Integer;
        FTextoLocalizar : String;
//        FQtde : String;
        FPeso : String;

        { Pointers para os eventos dos componentes presentes nas propriedades}
        FEventosOk : Boolean;
        FOnOrdenarMedidaPorClick : TNotifyEvent;
        FOnTipoDeOrdemClick : TNotifyEvent;
        FOnAchaPalavraKeyPress : TKeyPressEvent;
        FOnAchaPalavraExit : TNotifyEvent;
        FOnAchaDoInicioClick : TNotifyEvent;
        FOnLocalizaTextoChange : TNotifyEvent;
        FOnQuantidadeChange : TNotifyEvent;

        { Storage for property AchaPalavra }
        FAchaPalavra : TEdit;
        { Storage for property AchaDoInicio }
        FAchaDoInicio : TCheckBox;
        { Storage for property OrdenarMedidaPor }
        FOrdenarMedidaPor : TRadioGroup;
        { Storage for property TipoOrdem }
        FTipoDeOrdem : TRadioGroup;
        { Lista de Alimentos }
        FListaAlimento : TListaAlimento;
        { Lista de Medidas }
        FListaMedida : TDBGrid;
        { Ativar  dados }
        FAtivar : Boolean;
        { Storage for property LocalizaTexto }
        FLocalizaTexto : TEdit;
        { Storage for property Quantidade }
        FQuantidade : TEdit;
        { Storage for property PesoTotal }
        FPesoTotal : TDBEdit;

      { Private methods of TListaMedida }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;

        { para montagem das querys }
        function SQLSelectBasico : String;
        function SQLOrdemNome : String;
        function SQLOrdemUsuario : String;
        { Executa SQL }
        procedure ExecSQL;
        { Seta variaveis de eventos }
        procedure SetEventos;
        { Sela Ativar }
        procedure SetAtivar( Value : Boolean );

        { procedures a serem executadas antes dos eventos dos componentes das propriedades}
        procedure OnOrdenarMedidaPorClick(Sender: TObject);
        procedure OnTipoDeOrdemClick(Sender: TObject);
        procedure OnAchaPalavraKeyPress(Sender: TObject; var Key: Char);
        procedure OnAchaPalavraExit(Sender: TObject);
        procedure OnAchaDoInicioClick(Sender: TObject);
        procedure OnLocalizaTextoChange(Sender: TObject);
        procedure OnQuantidadeChange(Sender: TObject );

    protected
      { Protected fields of TListaMedida }
      procedure Loaded; override;

      procedure Notification(AComponent : TComponent; Operation : TOperation); override;

    public
      { Public fields and properties of TListaMedida }
        property Ativar : Boolean read FAtivar write SetAtivar;

      { Public methods of TListaMedida }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function Execute : Boolean;
        { Localiza Medida }
        function Localizar( Nome : String; Options: TLocateOptions ) : Boolean;
        procedure CalculaPesoTotal;

    published
      { Published properties of TListaMedida }
        { Lista de Alimentos que fornece o alimento corrente }
        property ListaAlimento : TListaAlimento read FListaAlimento write FListaAlimento;
        { Palavra a ser pesquisada }
        property AchaPalavra : TEdit read FAchaPalavra write FAchaPalavra;
        { Indica se a pesquisa da palavra eh do inicio ou nao }
        property AchaDoInicio : TCheckBox read FAchaDoInicio write FAchaDoInicio;
        { Campos a serem ordenados }
        property OrdenarMedidaPor : TRadioGroup
                 read FOrdenarMedidaPor write FOrdenarMedidaPor;
        { Sentido da ordenacao }
        property TipoDeOrdem : TRadioGroup read FTipoDeOrdem write FTipoDeOrdem;
        { Lista de Alimentos }
        property ListaDeMedidas : TDBGrid read FListaMedida write FListaMedida;
        { Texto a Localizar }
        property LocalizaTexto : TEdit read FLocalizaTexto write FLocalizaTexto;
        property Quantidade : TEdit read FQuantidade write FQuantidade;
        property PesoTotal : TDBEdit read FPesoTotal write FPesoTotal;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TListaMedida with Nutricao as its
       default page on the Delphi component palette }
     RegisterComponents('Nutricao', [TListaMedida]);
end;

{ Resets prop of component type if referenced component deleted }
procedure TListaMedida.Notification(AComponent : TComponent; Operation : TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of
       this component been deleted?  If so, update
       the property. }
     if AComponent = FAchaPalavra then
        FAchaPalavra := nil
     else if AComponent = FAchaDoInicio then
        FAchaDoInicio := nil
     else if AComponent = FOrdenarMedidaPor then
        FOrdenarMedidaPor := nil
     else if AComponent = FTipoDeOrdem then
        FTipoDeOrdem := nil
     else if AComponent = FListaAlimento then
        FListaAlimento := nil
     else if AComponent = FListaMedida then
        FListaMedida := nil
     else if AComponent = FLocalizaTexto then
        FLocalizaTexto := nil
     else if AComponent = FQuantidade then
        FQuantidade := nil
     else if AComponent = FPesoTotal then
        FPesoTotal := nil;

end; { of Notification }

{ Method to set variable and property values and create objects }
procedure TListaMedida.AutoInitialize;
begin
   FEventosOk := False;
end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TListaMedida.AutoDestroy;
begin
end; { of AutoDestroy }

constructor TListaMedida.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TListaMedida.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TListaMedida.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;

function TListaMedida.Execute : Boolean;
begin
   SetAtivar( True );
   { Return True if the operation was successful, False otherwise }
   Result := True
end;

{ Ativar dados }
procedure TListaMedida.SetAtivar( Value : Boolean );
begin

   // Ativar e Desativar conforme lista de Alimentos
   if (csLoading in ComponentState) then
      FAtivar := Value
   else if Value = FAtivar then
   else if FListaAlimento = nil then
      ShowMessage( 'Lista de Alimentos não definida' )
   else if not Value then
      begin
         ListaAlimento.DMAlimento.dsQMed.DataSet.Close;
         FAtivar := Value;
      end
   else if FAchaPalavra = nil then
      ShowMessage( 'AchaPalavra não definido' )
   else if FAchaDoInicio = nil then
      ShowMessage( 'AchaDoInicio não definido' )
   else if FOrdenarMedidaPor = nil then
      ShowMessage( 'OrdenarMedidaPor não definido' )
   else if FTipoDeOrdem = nil then
      ShowMessage( 'TipoDeOrdem não definido' )
   else if FQuantidade = nil then
      ShowMessage( 'Quantidade não definido' )
   else if FPesoTotal = nil then
      ShowMessage( 'PesoTotal não definido' )
   else
      begin
         SetEventos;

         FUserName := FListaAlimento.Usuario.Text;
         FPalavra := FAchaPalavra.Text;
         FDoInicio := FAchaDoInicio.Checked;
         FOrdenarPor := FOrdenarMedidaPor.ItemIndex;
         FOrdem := FTipoDeOrdem.ItemIndex;
         FTextoLocalizar := FLocalizaTexto.Text;
         FListaAlimento.DMAlimento.QtdeMedida := FQuantidade;
         FPesoTotal.DataSource := FListaAlimento.DMAlimento.dsQMed;
         FPesoTotal.DataField := 'PESOTOTAL';
         FPeso := FPesoTotal.Text;

//         ListaAlimento.DMAlimento.dsQNut.DataSet := ListaAlimento.DMAlimento.quNut;
         FListaMedida.DataSource := FListaAlimento.DMAlimento.dsQMed;

         ExecSQL;
         FAtivar := Value;
      end;
end;

{ Seta variaveis de eventos }
procedure TListaMedida.SetEventos;
begin
   { Perform the component operation }
   if not FEventosOk then
     begin
        FOnOrdenarMedidaPorClick := FOrdenarMedidaPor.OnClick;
        FOrdenarMedidaPor.OnClick := OnOrdenarMedidaPorClick;
        FOnTipoDeOrdemClick := FTipoDeOrdem.OnClick;
        FTipoDeOrdem.OnClick := OnTipoDeOrdemClick;
        FOnAchaPalavraKeyPress := FAchaPalavra.OnKeyPress;
        FAchaPalavra.OnKeyPress := OnAchaPalavraKeyPress;
        FOnAchaPalavraExit := FAchaPalavra.OnExit;
        FAchaPalavra.OnExit := OnAchaPalavraExit;
        FOnAchaDoInicioClick := FAchaDoInicio.OnClick;
        FAchaDoInicio.OnClick := OnAchaDoInicioClick;
        FOnLocalizaTextoChange := FLocalizaTexto.OnChange;
        FLocalizaTexto.OnChange := OnLocalizaTextoChange;
        FOnQuantidadeChange := FQuantidade.OnChange;
        FQuantidade.OnChange := OnQuantidadeChange;
        FEventosOk := True;
     end;
end;

{ Executa SQL }
procedure TListaMedida.ExecSQL;
begin

with FListaALimento.DMAlimento do
begin
//   dsQMed.DataSet := quMed;
   quMed.Close;
   quMed.SQL.Clear;
   if FOrdenarPor = 0 then
      quMed.SQL.Add( SQLOrdemNome )
   else if FOrdenarPor = 1 then
      quMed.SQL.Add( SQLOrdemUsuario );
   quMed.Open;
end;


end;

//==============================================================================

function TListaMedida.SQLSelectBasico : String;
begin

 Result :=
   'SELECT ' +
   ' MEDIDACASEIRA.IDMEDCAS ,' +
   ' MEDIDAS.MEDIDA ,' +
   ' MEDIDACASEIRA.VALOR ';

   end;

function TListaMedida.SQLOrdemNome : String;
begin

 Result := SQLSelectBasico +
   ' FROM ' +
   ' MEDIDAS , ' +
   ' MEDIDACASEIRA ' +

   ' WHERE ' +
   ' ( MEDIDACASEIRA.IDALI = :IDALI )' +
   ' AND ' +
   ' ( MEDIDACASEIRA.IDMEDCAS = MEDIDAS.IDMEDCAS ) ';

 if FPalavra <> '' then
 begin
    if FDoInicio then
       Result := Result + ' AND ( MEDIDA LIKE ''' + FPalavra + '%'' )'
    else
       Result := Result + ' AND ( MEDIDA LIKE ''%' + FPalavra + '%'' )'
 end;

 Result := Result + ' ORDER BY Medidas.MEDIDA';

 if FOrdem = 1 then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';

end;

function TListaMedida.SQLOrdemUsuario : String;
begin

 Result := SQLSelectBasico +
   ' FROM ' +
   ' MEDIDAS , ' +
   ' MEDIDACASEIRA ' +

   ' WHERE ' +
   ' ( MEDIDACASEIRA.IDALI = :IDALI )' +
   ' AND ' +
   ' ( MEDIDACASEIRA.IDMEDCAS = Medidas.IDMEDCAS ) ';

 if FPalavra <> '' then
 begin
    if FDoInicio then
       Result := Result + ' AND ( MEDIDA LIKE ''' + FPalavra + '%'' )'
    else
       Result := Result + ' AND ( MEDIDA LIKE ''%' + FPalavra + '%'' )'
 end;

end;

function TListaMedida.Localizar( Nome : String; Options: TLocateOptions ) : Boolean;
begin
   Result := FListaAlimento.DMAlimento.quMed.Locate( 'MEDIDA', Nome, Options );
end;

procedure TListaMedida.CalculaPesoTotal;
begin
//   FPeso := FloatToStr( StrToFloat( FQtde ) * ListaAlimento.DMAlimento.quMed.FieldByName( 'VALOR' ).AsFloat );
//   FPesoTotal.Caption := FPeso;
end;

//------------------------------------------------------------------------------

procedure TListaMedida.OnOrdenarMedidaPorClick(Sender: TObject);
begin
   FOrdenarPor := FOrdenarMedidaPor.ItemIndex;
   ExecSQL;
   if Assigned(FOnOrdenarMedidaPorClick) then
      FOnOrdenarMedidaPorClick(Sender);
end;

procedure TListaMedida.OnTipoDeOrdemClick(Sender: TObject);
begin
   FOrdem := FTipoDeOrdem.ItemIndex;
   ExecSQL;
   if Assigned(FOnTipoDeOrdemClick) then
      FOnTipoDeOrdemClick(Sender);
end;

procedure TListaMedida.OnAchaPalavraKeyPress(Sender: TObject; var Key: Char);
begin
   if Key = #13 then
      begin
         FPalavra := FAchaPalavra.Text;
         ExecSQL;
      end;
   if Assigned(FOnAchaPalavraKeyPress) then
      FOnAchaPalavraKeyPress(Sender, Key);
end;

procedure TListaMedida.OnAchaPalavraExit(Sender: TObject);
begin
   FPalavra := FAchaPalavra.Text;
   ExecSQL;
   if Assigned(FOnAchaPalavraExit) then
      FOnAchaPalavraExit(Sender);
end;

procedure TListaMedida.OnAchaDoInicioClick(Sender: TObject);
begin
   FDoInicio := FAchaDoInicio.Checked;
   ExecSQL;
   if Assigned(FOnAchaDoInicioClick) then
      FOnAchaDoInicioClick(Sender);
end;

procedure TListaMedida.OnLocalizaTextoChange(Sender: TObject);
begin
   FTextoLocalizar := FLocalizaTexto.Text;
   Localizar( FTextoLocalizar, [loPartialKey] );
   if Assigned(FOnLocalizaTextoChange) then
      FOnLocalizaTextoChange(Sender);
end;

procedure TListaMedida.OnQuantidadeChange(Sender: TObject);
begin
     FListaAlimento.DMAlimento.quMed.Refresh;
end;

end.


