// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TMedidasCaseiras                                   }
{                                                                    }
{   Medidas Caseiras de um Alimento                                  }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file                                       }
{   on 22 Oct 1999 at 15:00                                          }
{                                                                    }
{   Copyright © 1999 by CIS/EPM                                      }
{                                                                    }
{ ****************************************************************** }

unit MedidasCaseiras;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls,
     Forms, db, Dialogs, NutCnst, CAlimento, Measurement, CCSListaLinks, DelayedOpIndicator;

type

  TOrdenarMedidaCaseira = ( omNome, omPreferenciaUser );
  TOrigemQtdeMedida = ( qmNenhuma, qmUsuario, qmPesoAlimento, qmNutriente );

  TMedidasCaseiras = class(TCCSListaLinks)
    private
       FFiltrarDoInicio: Boolean;
       FFiltrarNomeMedida: String;
       FLocalizaNomeMedida: String;
       FIDUserName: TDataSource;
       FListaDeMedidas: TDataSource;
       FOrdenarMedidaPor: TOrdenarMedidaCaseira;
       FTipoDeOrdem: TTipoOrdem;
       FAlimento: TAlimento;
       FAtivar: Boolean;
       FOrigemQtdeMedidaPor: TOrigemQtdeMedida;
       FValorQtdeMedida: TMedida;
    FDelayedOpIndicator: TDelayedOpIndicator;
      { Private fields of TMedidasCaseiras }

      { Private methods of TMedidasCaseiras }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        { para montagem das querys }
        function SQLSelectBasico : String;
        function SQLOrdemNome : String;
        function SQLOrdemUsuario : String;
        { Executa SQL }
        procedure ExecSQL;
        procedure SetFiltrarDoInicio(const Value: Boolean);
        procedure SetFiltrarNomeMedida(const Value: String);
        procedure SetIDUserName(const Value: TDataSource);
        procedure SetListaDeMedidas(const Value: TDataSource);
        procedure SetLocalizaNomeMedida(const Value: String);
        procedure SetOrdenarMedidaPor(const Value: TOrdenarMedidaCaseira);
        procedure SetTipoDeOrdem(const Value: TTipoOrdem);
        procedure SetAlimento(const Value: TAlimento);
        procedure SetAtivar(const Value: Boolean);
        procedure SetOrigemQtdeMedidaPor(const Value: TOrigemQtdeMedida);
        procedure SetValorQtdeMedida(const Value: TMedida);
    procedure SetDelayedOpIndicator(const Value: TDelayedOpIndicator);

    protected
      { Protected fields of TMedidasCaseiras }
      procedure Loaded; override;
      procedure Notification(AComponent : TComponent; Operation : TOperation); override;

    public
      { Public methods of TMedidasCaseiras }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        procedure Refresh; override;
        { Localiza Medida }
        function Localizar( Nome : String; Options: TLocateOptions ) : Boolean;
        function TemMedidaCaseira : Boolean;

    published
      { Published properties of TMedidasCaseiras }
        { Indicador de Operação Demorada }
        property DelayedOpIndicator : TDelayedOpIndicator read FDelayedOpIndicator write SetDelayedOpIndicator;
        { Palavra a ser pesquisada }
        property FiltrarNomeMedida : String read FFiltrarNomeMedida write SetFiltrarNomeMedida;
        { Indica se a pesquisa da palavra eh do inicio ou nao }
        property FiltrarDoInicio : Boolean read FFiltrarDoInicio write SetFiltrarDoInicio;
        { Campos a serem ordenados }
        property OrdenarMedidaPor : TOrdenarMedidaCaseira read FOrdenarMedidaPor write SetOrdenarMedidaPor;
        { Sentido da ordenacao }
        property TipoDeOrdem : TTipoOrdem read FTipoDeOrdem write SetTipoDeOrdem;
        { Lista de Alimentos }
        property ListaDeMedidas : TDataSource read FListaDeMedidas write SetListaDeMedidas;
        property IDUserName : TDataSource read FIDUserName write SetIDUserName;
        { Texto a Localizar }
        property LocalizaNomeMedida : String read FLocalizaNomeMedida write SetLocalizaNomeMedida;
        property Alimento : TAlimento read FAlimento write SetAlimento;
        property Ativar : Boolean read FAtivar write SetAtivar;
        property OrigemQtdeMedidaPor : TOrigemQtdeMedida read FOrigemQtdeMedidaPor write SetOrigemQtdeMedidaPor;
        property ValorQtdeMedida : TMedida read FValorQtdeMedida write SetValorQtdeMedida;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TMedidasCaseiras with Nutricao as its
       default page on the Delphi component palette }
     RegisterComponents('Nutricao', [TMedidasCaseiras]);
end;

{ Resets prop of component type if referenced component deleted }
procedure TMedidasCaseiras.Notification(AComponent : TComponent; Operation : TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of
       this component been deleted?  If so, update
       the property. }
     if AComponent = FListaDeMedidas then
        FListaDeMedidas := nil
     else if AComponent = FIDUserName then
        FIDUserName := nil
     else if AComponent = FDelayedOpIndicator then
        FDelayedOpIndicator := nil;

end; { of Notification }

{ Method to set variable and property values and create objects }
procedure TMedidasCaseiras.AutoInitialize;
begin
end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TMedidasCaseiras.AutoDestroy;
begin
end; { of AutoDestroy }

constructor TMedidasCaseiras.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TMedidasCaseiras.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TMedidasCaseiras.Loaded;
begin
   inherited Loaded;

   { Perform any component setup that depends on the property
     values having been set }
   with FAlimento.DMUmAlimento do
   begin
   end;
   ExecSQL;
end;

procedure TMedidasCaseiras.Refresh;
begin
   ExecSQL;
   inherited;
end;

{ Executa SQL }
procedure TMedidasCaseiras.ExecSQL;
begin
   if not Assigned( FAlimento ) or not FAtivar then
      exit;
   with FALimento.DMUmAlimento do
   begin
      dsQMed.DataSet := quMed;
      quMed.Close;
      quMed.SQL.Clear;
      if FOrdenarMedidaPor = omNome then
         quMed.SQL.Add( SQLOrdemNome )
      else if FOrdenarMedidaPor = omPreferenciaUser then
         quMed.SQL.Add( SQLOrdemUsuario );
      // indica operação demorada;
      if Assigned( FDelayedOpIndicator ) then
         FDelayedOpIndicator.Start;
      try
         quMed.Open;
      finally
         // finaliza indicação de operação demorada
         if Assigned( FDelayedOpIndicator ) then
            FDelayedOpIndicator.Finish;
      end;
   end;
end;

//==============================================================================

function TMedidasCaseiras.SQLSelectBasico : String;
begin

 Result :=
   'SELECT ' +
   ' MEDIDACASEIRA.IDMEDCAS, ' +
   ' MEDIDAS.MEDIDA, ' +
   ' MEDIDACASEIRA.VALOR, ' +
   ' MEDIDACASEIRA.ORDPADRAO ';

  if not Assigned( FValorQtdeMedida ) then
     exit;   
   with FValorQtdeMedida do
   begin
      if FOrigemQtdeMedidaPor = qmUsuario then
         begin
            Result := Result + ', ' + ValorNumerico + 'QTDEMEDIDA, ' +
                                      ValorNumerico + ' * MEDIDACASEIRA.VALOR PESOTOTAL';
         end
      else if FOrigemQtdeMedidaPor = qmPesoAlimento then
         begin
            Result := Result +  ', ' + ValorNumerico + ' / MEDIDACASEIRA.VALOR QTDEMEDIDA, ' +
                                       ValorNumerico + ' PESOTOTAL';
         end
      else if FOrigemQtdeMedidaPor = qmNutriente then
         begin
            Result := Result +  ', ' + ValorNumerico + 'QTDEMEDIDA, ' +
                                       ValorNumerico + ' * MEDIDACASEIRA.VALOR PESOTOTAL';
         end;
   end;

end;

function TMedidasCaseiras.SQLOrdemNome : String;
begin

 Result := SQLSelectBasico +
   ' FROM ' +
   ' MEDIDAS , ' +
   ' MEDIDACASEIRA ' +

   ' WHERE ' +
   ' ( MEDIDACASEIRA.IDALI = :IDALI )' + // ''' + FAlimento.IDAlimento + ''')' +
   ' AND ' +
   ' ( MEDIDACASEIRA.IDMEDCAS = MEDIDAS.IDMEDCAS ) ';

 if FFiltrarNomeMedida <> '' then
 begin
    if FFiltrarDoInicio then
       Result := Result + ' AND ( UPPER(MEDIDA) LIKE UPPER(''' + FFiltrarNomeMedida + '%'' ))'
    else
       Result := Result + ' AND ( UPPER(MEDIDA) LIKE UPPER(''%' + FFiltrarNomeMedida + '%'' ))'
 end;

 Result := Result + ' ORDER BY MEDIDAS.MEDIDA';

 if FTipoDeOrdem = toDecrescente then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';

end;

function TMedidasCaseiras.SQLOrdemUsuario : String;
begin

 Result := SQLSelectBasico +
   ' FROM ' +
   ' MEDIDAS , ' +
   ' MEDIDACASEIRA ' +

   ' WHERE ' +
   ' ( MEDIDACASEIRA.IDALI = :IDALI )' + // ''' + FAlimento.IDAlimento + ''')' +
   ' AND ' +
   ' ( MEDIDACASEIRA.IDMEDCAS = MEDIDAS.IDMEDCAS ) ';

 if FFiltrarNomeMedida <> '' then
 begin
    if FFiltrarDoInicio then
       Result := Result + ' AND ( UPPER(MEDIDA) LIKE UPPER(''' + FFiltrarNomeMedida + '%'' ))'
    else
       Result := Result + ' AND ( UPPER(MEDIDA) LIKE UPPER(''%' + FFiltrarNomeMedida + '%'' ))'
 end;

 Result := Result + ' ORDER BY MEDIDACASEIRA.ORDPADRAO';

 if FTipoDeOrdem = toDecrescente then
    Result := Result + ' DESC'
 else
    Result := Result + ' ASC';

end;

function TMedidasCaseiras.Localizar( Nome : String; Options: TLocateOptions ) : Boolean;
begin
   Result := FAlimento.DMUmAlimento.quMed.Locate( 'MEDIDA', Nome, Options );
end;

//------------------------------------------------------------------------------

procedure TMedidasCaseiras.SetFiltrarDoInicio(const Value: Boolean);
begin
  FFiltrarDoInicio := Value;
  ExecSQL;
end;

procedure TMedidasCaseiras.SetFiltrarNomeMedida(const Value: String);
begin
  FFiltrarNomeMedida := Value;
  ExecSQL;
end;

procedure TMedidasCaseiras.SetIDUserName(const Value: TDataSource);
begin
  FIDUserName := Value;
  if Assigned (Value) then
  begin
     Value.FreeNotification(self);
     if Assigned( FAlimento ) then
        Value.DataSet := nil; // FAlimento.DMUmAlimento.dsUsuario.DataSet;
  end;
end;

procedure TMedidasCaseiras.SetListaDeMedidas(const Value: TDataSource);
begin
  FListaDeMedidas := Value;
  if Assigned (Value) then
  begin
     Value.FreeNotification(self);
     if Assigned( FAlimento ) then
        Value.DataSet := FAlimento.DMUmAlimento.dsQMed.DataSet;
  end;
end;

procedure TMedidasCaseiras.SetLocalizaNomeMedida(const Value: String);
begin
  FLocalizaNomeMedida := Value;
  Localizar( FLocalizaNomeMedida, [loCaseInsensitive,loPartialKey] );
end;

procedure TMedidasCaseiras.SetOrdenarMedidaPor(
  const Value: TOrdenarMedidaCaseira);
begin
  FOrdenarMedidaPor := Value;
  ExecSQL;
end;

procedure TMedidasCaseiras.SetTipoDeOrdem(const Value: TTipoOrdem);
begin
  FTipoDeOrdem := Value;
  ExecSQL;
end;

procedure TMedidasCaseiras.SetAlimento(const Value: TAlimento);
begin
  FAlimento := Value;
  if Assigned( Value ) then
     Value.FreeNotification(self);
  ExecSQL;
end;

// .............................................................................

function TMedidasCaseiras.TemMedidaCaseira: Boolean;
begin
   Result := not FAlimento.DMUmAlimento.quMed.IsEmpty;
end;

procedure TMedidasCaseiras.SetAtivar(const Value: Boolean);
begin
  if not Assigned( FAlimento ) then
     begin
        FAtivar := False;
        exit;
     end
  else if FAtivar = Value then
  else if Value then
     begin
        FAtivar := Value;
        ExecSQL;
     end
  else
     begin
        FAtivar := Value;
        FALimento.DMUmAlimento.dsQMed.DataSet.Close;
     end;
end;

procedure TMedidasCaseiras.SetOrigemQtdeMedidaPor(
  const Value: TOrigemQtdeMedida);
begin
  if not Assigned( FValorQtdeMedida ) then
//     FOrigemQtdeMedidaPor := qmNenhuma
  else
     with FValorQtdeMedida do
     begin
        if Value = qmNenhuma then
           begin
              Descricao := '';
              ValorNumerico := '0';
              Unidade := '';
           end
        else if Value = qmUsuario then
           begin
              Descricao := 'Quantidade';
              ValorNumerico := '1';
              Unidade := '';
           end
        else if Value = qmPesoAlimento then
           begin
              Descricao := 'Peso';
              ValorNumerico := '100';
              Unidade := 'g';
           end
        else if Value = qmNutriente then
           begin
              Descricao := 'Nutriente';
              ValorNumerico := '0';
              Unidade := 'Und';
           end;
        ExecSQL;
     end;
     FOrigemQtdeMedidaPor := Value;
     ExecSQL;
end;

procedure TMedidasCaseiras.SetValorQtdeMedida(const Value: TMedida);
begin
  FValorQtdeMedida := Value;
  if Assigned( Value ) then
     Value.FreeNotification(self);
end;

procedure TMedidasCaseiras.SetDelayedOpIndicator(
  const Value: TDelayedOpIndicator);
begin
  FDelayedOpIndicator := Value;
  if Assigned( Value ) then
     Value.FreeNotification(self);
end;

end.


