// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TCNSIni                                            }
{                                                                    }
{   Trata a configuração do sistema .ini                             }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from untitled component definition                     }
{   on 12 Nov 1998 at 13:12                                          }
{                                                                    }
{   Copyright © 1998 by ...                                          }
{                                                                    }
{ ****************************************************************** }

unit CNSIni;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls, 
     Forms, Graphics, inifiles, CNSDBSUS, CCSListaLinks;

type
  TCNSIni = class(TCustomDB)
    private
      { Private fields of TCNSIni }
        Fdt_instalacao : String;
        FTimeOut : Integer;
        FBase : String;
        FMaquina : String;
        FUltPacoteMunicipio: Integer;
        FSenha : String;
        FMunicipio : String;
        FUltPacoteGeral : Integer;
        FActive : boolean;
        FDirTransmissao : string;
        FDirRecepcao : string;
        FDirInstalacao : string;
        FDirRecHost : string;
        FDirTransHost : string;
        FNomeZip : string;
        FSenhaFTP : string;
        FUsuarioFTP : string;
        FRemoteHost : string;
        FRemotePort : integer;

      { Private methods of TCNSIni }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        procedure SetActive(Value : boolean);

    protected
      { Protected fields of TCNSIni }

      { Protected methods of TCNSIni }
        procedure Loaded; override;

    public
      { Public fields and properties of TCNSIni }

      { Public methods of TCNSIni }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function Execute : Boolean;
        { carrega as properties com os valores do arquivo }
        function Carrega : Shortint;
        { Atualiza o arquivo com os novos valores }
        procedure Limpa;
        procedure Atualiza;
        procedure refresh;

    published
      { Published properties of TCNSIni }
        { data da instalação do sistema }
        property Dt_Instalacao : String read FDt_Instalacao write FDt_Instalacao;
        { base que esta sendo usada PARADOX, ORACLE ou MSSQL}
        property Base : String read FBase write FBase;
        { numero do ultimo pacote geral enviado }
        property UltPacoteMunicipio: Integer
             read FUltPacoteMunicipio write FUltPacoteMunicipio;
        { codigo do IBGE do municipio
        não esta resolvido o caso em que um consorcio usa o programa }
        property Municipio : String read FMunicipio write FMunicipio;
        { minutos antes de cancelar sessão aberta }
        property Timeout : Integer read FTimeout write FTimeout;
        { Nome da maquina para a rede Windows }
        property Maquina : String read FMaquina write FMaquina;
        { senha para acesso a base de dados }
        property Senha : String read FSenha write FSenha;
        { numero do ultimo pacotao gerado }
        property UltPacoteGeral : Integer read FUltPacoteGeral write FUltPacoteGeral;
        property Active : boolean read FActive write SetActive;
        property DirRecepcao : string read FDirRecepcao write FdirRecepcao;
        property DirTransmissao : string read FDirTransmissao write FDirTransmissao;
        property DirInstalacao : string read FDirInstalacao write FDirInstalacao;
        property DirRecHost : string read FDirRecHost write FdirRecHost;
        property DirTransHost : string read FDirTransHost write FDirTransHost;
        Property NomeZip : string read FNomeZip write FNomeZip;
        property SenhaFTP : string read FSenhaFTP write FSenhaFTP;
        property UsuarioFTP : string read FUsuarioFTP write FUsuarioFTP;
        property RemoteHost : string read FRemoteHost write FRemoteHost;
        property RemotePort : integer read FRemotePort write FRemotePort;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TCNSIni with Cartao as its
       default page on the Delphi component palette }
     RegisterComponents('Cartao', [TCNSIni]);
end;

{ Method to set variable and property values and create objects }
procedure TCNSIni.AutoInitialize;
begin
end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TCNSIni.AutoDestroy;
begin
     { No objects from AutoInitialize to free }
end; { of AutoDestroy }

constructor TCNSIni.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TCNSIni.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TCNSIni.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;

function TCNSIni.Execute : Boolean;
begin
     { Perform the component operation }

     { Return True if the operation was successful, False otherwise }
     Result := True
end;

{ carrega as properties com os valores do arquivo }
function TCNSIni.Carrega : shortint;
     { Internal declarations for method }
     { type }
     { . . . }
Var inicartao : TIniFile;
begin
{se um valor nao existir ou estiver invalido retorna -1 }
inicartao := TIniFile.Create('CARTAO.INI');
{ o default é -1 se o valor nao existir, 30 colocado pelo programa }
FTimeout := inicartao.ReadInteger('Ambiente','timeout',-1);
FMaquina := inicartao.ReadString('Ambiente','Maquina','');
FSenha := inicartao.ReadString('Ambiente','Senha','');
FMunicipio := inicartao.ReadString('Municipio','Municipio','');
FDirRecHost := inicartao.ReadString('Diretorios','DirRecHost','');
FDirTransHost := inicartao.ReadString('Diretorios','DirTransHost','');
FDirRecepcao := inicartao.ReadString('Diretorios','DirRecepcao','');
FDirTransmissao := inicartao.ReadString('Diretorios','DirTransmissao','');
FDirInstalacao := inicartao.ReadString('Diretorios','DirInstalacao','c:\');
FNomeZip := inicartao.ReadString('FTP','NomeZip','');
FSenhaFTP := inicartao.ReadString('FTP','SenhaFTP','');
FUsuarioFTP := inicartao.ReadString('FTP','UsuarioFTP','');
FRemoteHost := inicartao.ReadString('FTP','RemoteHost','ftp.datasus.gov.br');
FRemotePort := inicartao.ReadInteger('FTP','RemotePort', 21);
FUltPacoteMunicipio := inicartao.ReadInteger('Pacotes','UltPacoteMunicipio',-1);
FUltPacoteGeral := inicartao.ReadInteger('Pacotes','UltPacoteGeral',-1);
Fdt_instalacao := inicartao.ReadString('Ambiente','dt_instalacao','');
FBase := inicartao.ReadString('Ambiente','Base','');
NotifyLinks(self, lRefreshViewer);
inicartao.free;
end;

procedure TCNSIni.refresh;
begin
   NotifyLinks(self, lRefreshViewer);
end;


procedure TCNSIni.Limpa;
begin
   FTimeout := 0;
   FMaquina := '';
   FUltPacoteMunicipio := 0;
   FSenha := '';
   FMunicipio := '';
   FDirRecHost := '';
   FDirTransHost := '';
   FDirRecepcao := '';
   FDirTransmissao:= '';
   FDirInstalacao := '';
   FNomeZip := '';
   FSenhaFTP := '';
   FUsuarioFTP := '';
   FRemoteHost := '';
   FRemotePort := 0;
   FUltPacoteGeral := 0;
   Fdt_instalacao := '';
   FBase := '';
   NotifyLinks(self, lRefreshViewer);
end;

{ Atualiza o arquivo com os novos valores }
Procedure TCNSIni.Atualiza;
     { Internal declarations for method }
     { type }
     { . . . }
Var IniCartao : TIniFile;
Begin
{obs. se o valor não existir é criado }
   IniCartao := TIniFile.Create('CARTAO.INI');

   With IniCartao Do
      Begin
      WriteInteger('Ambiente','TimeOut',FTimeout);
      WriteString('Ambiente','Maquina',FMaquina);
      WriteString('Ambiente','Senha',FSenha);
      WriteString('Ambiente','Dt_Instalacao',Fdt_instalacao);
      WriteString('Ambiente','Base',FBase);
      WriteInteger('Pacotes','UltPacoteMunicipio',FUltPacoteMunicipio);
      WriteInteger('Pacotes','UltPacoteGeral',FUltPacoteGeral);
      WriteString('Municipio','Municipio',FMunicipio);
      WriteString('FTP','NomeZip',FNomeZip);
      WriteString('FTP','SenhaFTP',FSenhaFTP);
      WriteString('FTP','UsuarioFTP',FUsuarioFTP);
      WriteString('FTP','RemoteHost',FRemoteHost);
      WriteInteger('FTP','RemotePort',FRemotePort);
      WriteString('Diretorios','DirInstalacao',FDirInstalacao);
      WriteString('Diretorios','DirRecepcao',FDirRecepcao);
      WriteString('Diretorios','DirTransmissao',FDirTransmissao);
      WriteString('Diretorios','DirRecHost',FDirRecHost);
      WriteString('Diretorios','DirTransHost',FDirTransHost);
      Free;
      End;
End;

Procedure TCNSIni.SetActive(Value : boolean);
var
  i : integer;
begin
   FActive := Value;
   if Value then
      i := carrega
   else
      Limpa;
end;

end.
