// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TLote                                              }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from untitled component definition                     }
{   on 7 Aug 1998 at 17:09                                           }
{                                                                    }
{   Copyright © 1998 by ...                                          }
{                                                                    }
{ ****************************************************************** }

unit CNSLote;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls,
     Forms, Graphics, CNSDBSUS, dbtables, dialogs, db;

type
  TCNSLote = class(TCNSDBSUS)
    private
      { Private fields of TLote }
        { Storage for property Lote }
        FLote : Integer;
        { Storage for property DataAbertura }
        FDataAbertura : TDateTime;
        { Storage for property Status }
        FStatus : String;
        { Storage for property DataEnvioDatasus }
        FDataEnvioDatasus : TDateTime;
        FDataGeracao : TDateTime;
        FDataRecebimentoPIS : TDateTime;
        FDataEmissao : TDateTime;
        FTotalLinhas: Integer;
        FTotalDocs: Integer;
        FTotDocs: Integer;
        FPisDigitador: string;
        FPisReDigitador: string;
        FCanUpdate : boolean;
        FErroDigitacao : boolean;
        FTirar : string;
//        FDataBase : TDataBase;

      { Private methods of TLoteinhas }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        { Read method for property DataAbertura }
        function GetDataAbertura : TDateTime;
        { Write method for property DataAbertura }
        procedure SetDataAbertura(Value : TDateTime);
        procedure SetStatusLote(Value : string);

    protected
      { Protected fields of TLote }

      { Protected methods of TLote }
        procedure Loaded; override;

    public
      { Public fields and properties of TLote }

      { Public methods of TLote }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function Execute : Boolean;
        procedure AbrirLote;
        procedure DigitarFichas;
        procedure CarregarLote(NumLote : integer);
        function MarcarErro : Boolean;
        function TodoLoteEmitido : Boolean;
        procedure Atualizar;
        procedure FecharLote;
        function ObterTotalLinhas: integer;
        function ObterTotalDocs: integer;
        property AtivarFields;
        property Lote : Integer read FLote write FLote;
        property DataAbertura : TDateTime read GetDataAbertura write SetDataAbertura;
        property Status : String read FStatus;
        property DataEnvioDatasus : TDateTime read FDataEnvioDatasus;
        property DataGeracao : TDateTime read FDataGeracao;
        property DataRecebimentoPIS : TDateTime read FDataRecebimentoPIS;
        property DataEmissao : TDateTime read FDataEmissao;
        property TotalLinhas : Integer read FTotalLinhas;
        property PisDigitador : string read FPisDigitador write FPisDigitador;
        property PisReDigitador : string read FPisReDigitador write FPisReDigitador;
        property TotalDocs : Integer read FTotalDocs write FTotalDocs;
        property ErroDigitacao : boolean read FErroDigitacao write FErroDigitacao;
        property CanUpdate : boolean read FCanUpdate;
    published
      { Published properties of TLote }
//        property DataBase : TDataBase read FDataBase write FDataBase;

  end;

procedure Register;

implementation
uses lotedialog01;

procedure Register;
begin
     { Register TLote with Cartao as its
       default page on the Delphi component palette }
     RegisterComponents('Cartao', [TCNSLote]);
end;

{ Method to set variable and property values and create objects }
procedure TCNSLote.AutoInitialize;
begin
end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TCNSLote.AutoDestroy;
begin
end; { of AutoDestroy }

{ Read method for property DataAbertura }
function TCNSLote.GetDataAbertura : TDateTime;
begin
     Result := FDataAbertura
end;

{ Write method for property DataAbertura }
procedure TCNSLote.SetDataAbertura(Value : TDateTime);
begin
     FDataAbertura := Value;
end;

constructor TCNSLote.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TCNSLote.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TCNSLote.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;

function TCNSLote.Execute : Boolean;
begin
     { Perform the component operation }

     { Return True if the operation was successful, False otherwise }
     Result := True
end;

procedure TCNSLote.AbrirLote;
var
   xFrm : TFrmCapaLote;
   xValidar : boolean;
begin
   xFrm := TFrmCapaLote.Create(self);
   xFrm.ShowModal;
   CarregarLote(StrToInt(xFrm.NumLote.Text));
   FLote := StrToInt(xFrm.NumLote.text);

end;

procedure TCNSLote.DigitarFichas;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin

end;

procedure TCNSLote.CarregarLote(NumLote : integer);
begin
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         sql.add('select * from Lote where Num_Lote = :xNumLote');
         ParamByName('xNumLote').AsFloat := NumLote;
         Open;
         if not eof then
         begin
             FLote := FieldByName('Num_Lote').AsInteger;
             FDataAbertura := FieldByName('Dt_Abertura').AsDateTime;
             FStatus := FieldByName('st_Lote').AsString;
             FDataEnvioDatasus := FieldByName('DT_Envio_DATASUS').AsDateTime;
             FDataGeracao := FieldByName('DT_Geracao').AsDateTime;
             FDataRecebimentoPIS := FieldByName('DT_RecebCom').AsDateTime;
             FDataEmissao := FieldByName('DT_Emissao').AsDateTime;
             FTotalLinhas := FieldByName('Tot_Linhas').AsInteger;
             FTotalDocs := FieldByName('Tot_Docs').AsInteger;
             FPisDigitador := FieldByName('PIS_Criador').AsString;
//             FPisReDigitador := FieldByName('PIS_ReDigitador').AsString;
             FCanUpdate := True;
         end else
         begin
             FLote := 0;
             FDataAbertura := (now);
             FDataEnvioDatasus := (now);//StrToDate('01/01/1998');
             FDataGeracao := (now);//StrToDate('01/01/1998');
             FDataRecebimentoPIS := (now);//StrToDate('01/01/1998');
             FDataEmissao := (now);//StrToDate('01/01/1998');
             FTotalLinhas := 10;
             FTotalDocs := 10;
             FPisDigitador := '10297874508';
             FPisReDigitador := '          ';
             FCanUpdate := False;
         end;;
         if (not FCanUpdate) or (FStatus = 'PENDENT') then
            FStatus := 'ABERTO ';
      end;
   end;

end;

function TCNSLote.MarcarErro;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin

end;

function TCNSLote.TodoLoteEmitido;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin

end;

procedure TCNSLote.Atualizar;
var
   xTirarDepois : integer;
begin
      with DataSource.Dataset as TQuery do
      begin
         if ((not CanUpdate) or ((CanUpdate) and (FTotalDocs >= ObterTotalDocs))) then
         begin
            close;
            sql.clear;
            if (FStatus = 'FECHADO') OR (FStatus = 'EMITIDO') then
            begin
               ShowMessage('LOTE NAO PODE SER ALTERADO QUANDO JA FOI ' +  FStatus);
            end else
            begin
               if not FCanUpdate then
               begin
                  sql.add('INSERT INTO Lote (Num_Lote,   Dt_Abertura,   st_Lote,   Dt_Envio_DATASUS,   Dt_Geracao,   DT_RecebCom,      Dt_Emissao,   Tot_Linhas,   Tot_Docs,   PIS_Criador)');
                  sql.add('VALUES           (:xNum_Lote, :xDt_Abertura, :xst_Lote, :xDt_Envio_DATASUS, :xDt_Geracao, :xDT_RecebComPIS, :xDt_Emissao, :xTot_Linhas, :xTot_Docs, :xPIS_Criador)');
                  FCanUpdate := True;
               end else
               begin
                  sql.add(' UPDATE  Lote   SET Dt_Abertura = :xDt_Abertura, st_Lote = :xst_Lote,');
                  sql.add(' Dt_Envio_DATASUS = :xDt_Envio_DATASUS, Dt_Geracao = :xDt_Geracao, DT_RecebCom = :xDT_RecebComPIS,  Dt_Emissao = :xDt_Emissao, Tot_Linhas = :xTot_Linhas, Tot_Docs = :xTot_Docs, PIS_Criador = :xPIS_Criador');
                  sql.add(' where Num_Lote = :xNum_Lote');
                  FCanUpdate := True;
               end;
               ParamByName('xNum_Lote').AsFloat := FLote;
               ParamByName('xDt_Abertura').AsDate := FDataAbertura;
               ParamByName('xst_Lote').AsString := FStatus;
               ParamByName('xDT_Envio_DATASUS').AsDate := FDataEnvioDatasus;
               ParamByName('xDT_Geracao').AsDate := FDataGeracao;
               ParamByName('xDT_RecebComPIS').AsDate := FDataRecebimentoPIS;
               ParamByName('xDT_Emissao').AsDate := FDataEmissao;
               ParamByName('xTot_Linhas').AsInteger := FTotalLinhas;
               ParamByName('xTot_Docs').AsInteger := FTotalDocs;
               ParamByName('xPis_Criador').AsString := FPisDigitador;
//               ParamByName('xPIS_ReDigitador').AsString := FPisReDigitador;
               try
                  CNSDataBase.StartTransaction;
                  ExecSql;
                  CNSDataBase.Commit;
               except
                  on h2 : EDBEngineError do
                     begin
                     ShowMessage('E0021 - Erro ao Atualizar Lote - ' + IntToStr(lote));
                     CNSDataBase.RollBack;
                     end;
                  on h1 : EDatabaseError do
                     begin
                     ShowMessage('E0021 - Erro ao Atualizar Lote - ' + IntToStr(lote));
                     CNSDatabase.RollBack;
                     end;
               end;
            end;
         end;
      end;
end;

procedure TCNSLote.FecharLote;
{
          Fecha lote indicando quando estiver com erro na digitacao ou redigitacao
}
begin
   if (ErroDigitacao) then
      FStatus := 'FECERRO'
   else
      if FTotalDocs = ObterTotalDocs then
         FStatus := 'FECHADO';
   FCanUpdate := True;
   FTotalLinhas := ObterTotalLinhas;
   Atualizar;
end;

function TCNSLote.ObterTotalLinhas : integer;
begin
   Result := 0;
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         sql.add('select count(Num_Lote) TotalFichas  from Usuario where Num_Lote = :xNum_lote');
         ParamByName('xNum_lote').AsInteger := FLote;
         Open;
         Result :=  FieldByName('TotalFichas').AsInteger;
         close;
      end;
   end;
end;


function TCNSLote.ObterTotalDocs : integer;
begin
   Result := 0;
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         //**********Alterar na base a acertar aqui para num_ficha
         sql.add('select count(Distinct(Num_Lote)) TotalDocs  from Usuario where Num_Lote = :xNum_lote');
         ParamByName('xNum_lote').AsString := IntToStr(FLote);
         Open;
         Result :=  FieldByName('TotalDocs').AsInteger;
         close;
      end;
   end;
end;

procedure TCNSLote.SetStatusLote(Value : String);
begin
   FStatus := Value;
end;

end.


