// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TLote                                              }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from untitled component definition                     }
{   on 7 Aug 1998 at 17:09                                           }
{                                                                    }
{   Copyright © 1998 by ...                                          }
{                                                                    }
{ ****************************************************************** }

unit CNSLote;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls,
     Forms, Graphics, CNSDBSUS, dbtables, dialogs, db,checklst,
     CNSConnect,CNSlib, ccslistalinks;

type
  TCNSLote = class(TCNSDBSUS)
    private
      { Private fields of TLote }
        { Storage for property Lote }

        FLote : Integer;
        FErroLote : ELote;
        FDInicial : TDateTime;
        FDFinal : TDateTime;
        { Storage for property DataAbertura }
        FDataAbertura : TDateTime;
        { Storage for property Status }
        FStatus : String;
        { Storage for property DataEnvioDatasus }
        FDataEnvioDatasus : TDateTime;
        FDataGeracao : TDateTime;
        FDataRecebimentoPIS : TDateTime;
        FDataEmissao : TDateTime;
        FTotalLinhas: Integer;
        FTotalDocs: Integer;
        FTotDocs: Integer;
        FPisDigitador: string;
        FPisReDigitador: string;
        FUserLogado : TCNSUserName;
        FCanUpdate : boolean;
        FErroDigitacao : boolean;
        FTirar : string;
        FCHKListaLotes : TCheckListBox;


        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        { Read method for property DataAbertura }
        function GetDataAbertura : TDateTime;
        { Write method for property DataAbertura }

//        procedure SelecionarLotesPeriodo (DInicial, DFinal : string; FStatus :string);


        procedure SetDataAbertura(Value : TDateTime);
//        procedure SetCHKListaLotes(Value : TCheckListBox);
        procedure MontarCHKListaLotes;

    protected
      { Protected fields of TLote }

      { Protected methods of TLote }
        procedure Loaded; override;
        procedure Notification(AComponent: TComponent; Operation: TOperation); override;

    public
      { Public fields and properties of TLote }

        procedure SetStatusLote(Value : string);

      { Public methods of TLote }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function  Execute : Boolean;
        procedure AbrirLote(Value : String);
        procedure DigitarFichas;
        procedure SetUserLogado(Value : TCNSUserName);
        procedure CarregarLote(NumLote : integer);
        procedure Carregar(P1, P2, P3, P4 : string); override;
        function  MarcarErro : Boolean;
        function  TodoLoteEmitido : Boolean;
        procedure Atualizar; override;
        procedure ST_Atualizar(xStLote: string; xlista: tstrings);
        procedure FecharLote;
        function  ObterTotalLinhas: integer;
        function  ObterTotalDocs: integer;
        procedure SelecionarLotes;
        procedure SelecionarUsuariosLote(xLote : integer);
        function  ListaLotesStatus(xStatus : string) : TStrings;
        function  ListaLotesPeriodo(xDataInicial, xDataFinal : TDate; xStatus : string): TStrings;
        function  ListaLotesGeral : TStrings;
//        property CHKListaLotes : TCheckListBox read FCHKListaLotes write SetCHKListaLotes;
        property AtivarFields;

    published
        property CHKListaLotes : TCheckListBox read FCHKListaLotes write FCHKListaLotes;
        property UserLogado : TCnsUserName read FUserLogado     write SetUserLogado;
        property Lote : Integer read FLote write FLote;
        property DataAbertura : TDateTime read GetDataAbertura write SetDataAbertura;
        property Status : String read FStatus;
        property DataEnvioDatasus : TDateTime read FDataEnvioDatasus;
        property DataGeracao : TDateTime read FDataGeracao;
        property DataRecebimentoPIS : TDateTime read FDataRecebimentoPIS;
        property DataEmissao : TDateTime   read FDataEmissao;
        property TotalLinhas : Integer     read FTotalLinhas;
        property PisDigitador : string     read FPisDigitador   write FPisDigitador;
        property PisReDigitador : string   read FPisReDigitador write FPisReDigitador;
        property TotalDocs : Integer       read FTotalDocs      write FTotalDocs;
        property ErroDigitacao : boolean   read FErroDigitacao  write FErroDigitacao;
        property CanUpdate : boolean       read FCanUpdate;
  end;

procedure Register;

implementation
uses lotedialog01;

procedure Register;
begin
     RegisterComponents('Cartao', [TCNSLote]);
end;

procedure TCNSLote.AutoInitialize;
begin
end;

procedure TCNSLote.AutoDestroy;
begin
   if assigned(FCHKListaLotes) then
      FCHKListaLotes.Items.Clear;
end;

function TCNSLote.GetDataAbertura : TDateTime;
begin
     Result := FDataAbertura
end;

procedure TCNSLote.SetDataAbertura(Value : TDateTime);
begin
     FDataAbertura := Value;
end;


procedure TCNSLote.SetStatusLote(Value : String);
begin
   FStatus := Value;
end;


procedure TCNSLote.SetUserLogado(Value : TCNSUserName);
begin
   FUserLogado := Value;
   // o assigned testa se o objeto existe e se a propriedade esta setada para um objeto valido
   if assigned(Value) then
   begin
      Value.FreeNotification(Self);
   end;
end;

constructor TCNSLote.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);
     AutoInitialize;
     ObjectView.Clear;
     ObjectView.Add('Select * from lote');
end;

procedure TCNSLote.Notification(AComponent: TComponent;
  Operation: TOperation);
begin
  inherited Notification(AComponent, Operation);
  if Operation = opRemove then
  begin
    if (FCHKListaLotes <> nil) and (AComponent = CHKListaLotes) then
       CHKListaLotes := nil;
    if (FUserLogado <> nil) and (AComponent = UserLogado) then
       UserLogado := nil;
  end;
end;

destructor TCNSLote.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;
     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }
     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TCNSLote.Loaded;
begin
     inherited Loaded;
end;

function TCNSLote.Execute : Boolean;
begin
     { Perform the component operation }
     { Return True if the operation was successful, False otherwise }
     Result := True
end;




// ROTINAS DE MANUTENÇÃO DOS LOTES  --------------------------------------------
procedure TCNSLote.AbrirLote(Value : String);

begin
   FLote := StrtoInt(Value);
   CarregarLote(FLote);
end;

procedure TCNSLote.CarregarLote(NumLote : integer);
begin
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         sql.add('select * from Lote where Num_Lote = :xNumLote');
         ParamByName('xNumLote').AsFloat := NumLote;
         Open;
         if not eof then
         begin
             FLote := FieldByName('Num_Lote').AsInteger;
             FDataAbertura := FieldByName('Dt_Abertura').AsDateTime;
             FStatus := FieldByName('st_Lote').AsString;
             FDataEnvioDatasus := FieldByName('DT_Envio_DATASUS').AsDateTime;
             FDataGeracao := FieldByName('DT_Geracao').AsDateTime;
             FDataRecebimentoPIS := FieldByName('DT_RecebCom').AsDateTime;
             FDataEmissao := FieldByName('DT_Emissao').AsDateTime;
             FTotalLinhas := FieldByName('Tot_Linhas').AsInteger;
             FTotalDocs := FieldByName('Tot_Docs').AsInteger;
             FPisDigitador := FieldByName('PIS_Criador').AsString;
//             FPisReDigitador := FieldByName('PIS_ReDigitador').AsString;
             FCanUpdate := True;
            if (FStatus <> 'ABERTO') AND (FStatus <> 'FECERRO') then
               // if (FStatus = 'FECHADO') OR (FStatus = 'EMITIDO') then
               ShowMessage('LOTE NAO PODE SER ALTERADO QUANDO JA FOI ' +  FStatus);
         end else
             begin
                FLote := 0;
                FDataAbertura := (now);
                FTotalLinhas := 0;
                FTotalDocs := 0;
                FStatus := 'ABERTO ';
                if assigned(FUserLogado) then
                   FPisDigitador := FUserLogado.PIS
                else
                   begin
                    FErroLote := ELote.Create('Associe na propriedade do lote o username');
                    raise FErroLote;
                    FErroLote.free;
                   end;
                FPisReDigitador := '          ';
                FCanUpdate := False;
             end;
         if (not FCanUpdate) or (FStatus = 'FECERRO') then
            // esta reabrindo um lote fechado com erro para ser corrigido
            FStatus := 'ABERTO ';
      end;
   end;
end;

procedure TCNSLote.Carregar(P1, P2, P3, P4 : string);
begin
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         sql.add('select * from Lote where Num_Lote = :xNumLote');
         ParamByName('xNumLote').AsFloat := StrToFloat(P1);
         Open;
         if not eof then
         begin
             FLote := FieldByName('Num_Lote').AsInteger;
             FDataAbertura := FieldByName('Dt_Abertura').AsDateTime;
             FStatus := FieldByName('st_Lote').AsString;
             FDataEnvioDatasus := FieldByName('DT_Envio_DATASUS').AsDateTime;
             FDataGeracao := FieldByName('DT_Geracao').AsDateTime;
             FDataRecebimentoPIS := FieldByName('DT_RecebCom').AsDateTime;
             FDataEmissao := FieldByName('DT_Emissao').AsDateTime;
             FTotalLinhas := FieldByName('Tot_Linhas').AsInteger;
             FTotalDocs := FieldByName('Tot_Docs').AsInteger;
             FPisDigitador := FieldByName('PIS_Criador').AsString;
//             FPisReDigitador := FieldByName('PIS_ReDigitador').AsString;
             FCanUpdate := True;
         end else
             begin
                FLote := 0;
                FDataAbertura := (now);
                FTotalLinhas := 0;
                FTotalDocs := 0;
                FStatus := 'ABERTO ';
                if assigned(FUserLogado) then
                   FPisDigitador := FUserLogado.PIS
                else
                   begin
                    FErroLote := ELote.Create('Associe na propriedade do lote o username');
                    raise FErroLote;
                    FErroLote.free;
                   end;
                FPisReDigitador := '          ';
                FCanUpdate := False;
             end;
         NotifyLinks(self, lRefreshViewer);
      end;
   end;
end;


procedure TCNSLote.Atualizar;
begin
      with DataSource.Dataset as TQuery do
      begin
         if ((not CanUpdate) or ((CanUpdate) and (FTotalDocs >= ObterTotalDocs))) then
         begin
            close;
            sql.clear;
           { if (FStatus <> 'ABERTO') OR (FStatus <> 'FECERRO') then
            begin
               ShowMessage('LOTE NAO PODE SER ALTERADO QUANDO JA FOI ' +  FStatus);
            end else}
            begin
               if not FCanUpdate then
                 begin
                  sql.add('INSERT INTO Lote (Num_Lote,   Dt_Abertura,   st_Lote,   Dt_Envio_DATASUS,   Dt_Geracao,   DT_RecebCom,      Dt_Emissao,   Tot_Linhas,   Tot_Docs,   PIS_Criador)');
                  sql.add('VALUES           (:xNum_Lote, :xDt_Abertura, :xst_Lote, :xDt_Envio_DATASUS, :xDt_Geracao, :xDT_RecebComPIS, :xDt_Emissao, :xTot_Linhas, :xTot_Docs, :xPIS_Criador)');
                  FCanUpdate := True;
                 end
               else
                 begin
                  sql.add(' UPDATE  Lote   SET Dt_Abertura = :xDt_Abertura, st_Lote = :xst_Lote,');
                  sql.add(' Dt_Envio_DATASUS = :xDt_Envio_DATASUS, Dt_Geracao = :xDt_Geracao, DT_RecebCom = :xDT_RecebComPIS,  Dt_Emissao = :xDt_Emissao, Tot_Linhas = :xTot_Linhas, Tot_Docs = :xTot_Docs, PIS_Criador = :xPIS_Criador');
                  sql.add(' where Num_Lote = :xNum_Lote');
                  FCanUpdate := True;
                end;
               NotifyLinks(self, lRefreshControl);
               ParamByName('xNum_Lote').AsFloat := FLote;
               ParamByName('xDt_Abertura').AsDate := FDataAbertura;
               ParamByName('xst_Lote').AsString := FStatus;
               ParamByName('xDT_Envio_DATASUS').AsDate := FDataEnvioDatasus;
               ParamByName('xDT_Geracao').AsDate := FDataGeracao;
               ParamByName('xDT_RecebComPIS').AsDate := FDataRecebimentoPIS;
               ParamByName('xDT_Emissao').AsDate := FDataEmissao;
               ParamByName('xTot_Linhas').AsInteger := FTotalLinhas;
               ParamByName('xTot_Docs').AsInteger := FTotalDocs;
               ParamByName('xPis_Criador').AsString := FPisDigitador;
//             ParamByName('xPIS_ReDigitador').AsString := FPisReDigitador;
               try
                  CNSDataBase.StartTransaction;
                  ExecSql;
                  CNSDataBase.Commit;
               except
                  on h2 : EDBEngineError do
                     begin
                     ShowMessage('E0021 - Erro ao Atualizar Lote - ' + IntToStr(lote));
                     CNSDataBase.RollBack;
                     end;
                  on h1 : EDatabaseError do
                     begin
                     ShowMessage('E0021 - Erro ao Atualizar Lote - ' + IntToStr(lote));
                     CNSDatabase.RollBack;
                     end;
               end;
            end;
         end;
      end;
end;

procedure TCNSLote.FecharLote;
// Fecha lote indicando quando estiver com erro na digitacao ou redigitacao
begin
   if (ErroDigitacao) then
      FStatus := 'FECERRO'
   else
      if FTotalDocs = ObterTotalDocs then
         FStatus := 'FECHADO'
      else
         FStatus := 'FECERRO';

   FTotalLinhas := ObterTotalLinhas;

   with DataSource.Dataset as TQuery do
      begin
        close;
        sql.clear;
        sql.add(' UPDATE  Lote   SET  st_Lote = :xst_Lote');
        sql.add(' where Num_Lote = :xNum_Lote');
        ParamByName('xNum_Lote').AsFloat := FLote;
        ParamByName('xst_Lote').AsString := FStatus;
        try
           CNSDataBase.StartTransaction;
           ExecSql;
           CNSDataBase.Commit;
        except
           on h2 : EDBEngineError do
              begin
              ShowMessage('E0021 - Erro ao Fechar Lote - ' + IntToStr(lote));
              CNSDataBase.RollBack;
              end;
           on h1 : EDatabaseError do
              begin
              ShowMessage('E0021 - Erro ao Fechar Lote - ' + IntToStr(lote));
              CNSDatabase.RollBack;
              end;
        end;
     end;
//
//    Zerar propriedade NUMERO DO LOTE do componente99
//
   FLote := 0;

   //Atualizar;
end;

procedure TCNSLote.ST_Atualizar(xStLote: string; xlista: tstrings);
var
//  queryant : TStrings;
  i : integer;
begin
   with DataSource.Dataset as TQuery do
   begin
      sql.clear;
      sql.add(' UPDATE Lote SET st_Lote = '+ ''''+xStLote+'''' );
      sql.add(' where num_lote in ( ' + xlista[0]);
      if xlista.count > 1 then
            for i:=1 to xlista.count-1 do
                      sql.add( ',' + xlista[i]);
      sql.add(  ' )' );

      try
        CNSDataBase.StartTransaction;
        ExecSql;
        CNSDataBase.Commit;
      except
           on h2 : EDBEngineError do
                   begin
                        ShowMessage('E0021 - Erro ao Atualizar Lote - ' + IntToStr(lote));
                        CNSDataBase.RollBack;
                      end;
           on h1 : EDatabaseError do
                   begin
                      ShowMessage('E0021 - Erro ao Atualizar Lote - ' + IntToStr(lote));
                      CNSDatabase.RollBack;
                   end;
           //end;
      end;
   end;
end;
//   F I M   --  ROTINAS DE MANUTENÇÃO DOS LOTES

procedure TCNSLote.DigitarFichas;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
end;

function TCNSLote.MarcarErro : boolean;
begin
end;

function TCNSLote.TodoLoteEmitido : boolean;
begin
end;



// ROTINAS DE TOTALIZAÇÃO DE REGISTROS E FICHAS POR LOTE  ----------------------
function TCNSLote.ObterTotalLinhas : integer;
begin
   Result := 0;
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         sql.add('select count(Num_Lote) TotalLinhas  from Usuario where Num_Lote = :xNum_lote');
         ParamByName('xNum_lote').AsInteger := FLote;
         Open;
         Result :=  FieldByName('TotalLinhas').AsInteger;
         close;
      end;
   end;
end;

function TCNSLote.ObterTotalDocs : integer;
begin
   Result := 0;
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         //**********Alterar na base a acertar aqui para num_ficha
         sql.add('select count(Distinct(Num_ficha)) TotalDocs  from Usuario where Num_Lote = :xNum_lote');
         ParamByName('xNum_lote').AsInteger := FLote;
         Open;
         Result :=  FieldByName('TotalDocs').AsInteger;
         close;
      end;
   end;
end;
//   F I M    ROTINAS DE TOTALIZAÇÃO DE REGISTROS E FICHAS POR LOTE





// ROTINAS PARA SELECIONAR LOTES -----------------------------------------------

procedure TCNSLote.SelecionarLotes;
//  Metodo para retornar uma tabela com os lotes selecionados
begin
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         sql.add('select Num_Lote, St_Lote ,Tot_Linhas From Lote where St_lote = ''FECHADO'' or ST_Lote = ''ENVIADO''');
         Open;
      end;
   //   MontarCHKListaLotes;
   end;
end;


procedure TCNSLote.MontarCHKListaLotes;

begin

end;
//  F I M   ROTINAS PARA SELECIONAR LOTES




// ROTINAS PARA SELECIONAR USUÁRIOS DE UM LOTE ---------------------------------
procedure TCNSLote.SelecionarUsuariosLote(xLote: integer);
//    Montar tabela com os usuarios do lote x
begin
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;

         //  NÃO PRECISAMOS MAIS DE DESCRIÇÃO DE USUÁRIO !?!?!?!?!?!?!? - PELO MENOS PARA MONTAR PACOTE NÃO.
         // BUSCAR ENDERECO DA TABELA CARTAO
         //sql.add('select Usuario.* ,Municipio.Descricao From Usuario, Municipio where Num_Lote = ' +  IntToStr(xLote));
         sql.add('select Usuario.* , Cartao.Nome_Logradouro, Cartao.Num_Logradouro, Cartao.Compl_Logradouro, Cartao.Bairro,Cartao.CEP, Cartao.Cod_IBGE');
         sql.add('From Usuario, Cartao where Num_Lote = ' +  IntToStr(xLote));
         sql.add('  and Usuario.Num_controle = Cartao.Num_controle');
         Open;
         // BUSCAR ENDERECO DA TABELA CARTAO

      end;
   end;
end;
//  F I M   ROTINAS PARA SELECIONAR USUÁRIOS DE UM LOTE -

// ROTINAS PARA LISTAR LOTES   -------------------------------------------------
function TCNSLote.ListaLotesGeral : TStrings;
var
   i : integer;
begin
    Result := TStringList.Create;
    for i := 0 to CHKListaLotes.items.count - 1 do
        if CHKListaLotes.checked[i] then
           Result.Add(string(copy(CHKListaLotes.items[i],1 ,5)));
end;

function TCNSLote.ListaLotesPeriodo(xDataInicial, xDataFinal : TDate; xStatus : string): TStrings;
begin
   Result := TStringList.Create;
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;

         if xStatus = 'FechadoEnviado' then
         begin
            sql.add('select Num_Lote From Lote where (St_lote = ''FECHADO'' or ST_Lote = ''ENVIADO'') ');
            sql.add('and DT_Fechamento >= :DataInicial and DT_Fechamento <= :DataFinal');
         end else
         begin
            sql.add('select Num_Lote From Lote where St_lote = :Status  ');
            sql.add('and DT_Fechamento >= :DataInicial and DT_Fechamento <= :DataFinal');
            ParamByName('Status').AsString := xStatus;
         end;
         ParamByName('DataInicial').AsDate := xDataInicial;
         ParamByName('DataFinal').AsDate := xDataFinal;
         // tratar status
         Open;
         Result.Clear;
         while not eof do
         begin
            Result.add(fieldbyname('Num_lote').asstring);
            next;
         end;
      end;
   end;
end;

function TCNSLote.ListaLotesStatus(xStatus : string) : TStrings;
begin
   Result := TStringList.Create;
   if assigned(DataSource) and assigned(DataSource.Dataset) then
   begin
      with DataSource.Dataset as TQuery do
      begin
         close;
         sql.clear;
         sql.add('select Num_Lote From Lote where St_lote = :Status');
         ParamByName('Status').AsString := xStatus;
         Open;
         Result.Clear;
         while not eof do
         begin
             Result.add(fieldbyname('Num_lote').asstring);
             next;
         end;
      end;
   end;
end;
// F I M   ROTINAS PARA LISTAR LOTES   -----------------------------------------

end.


