// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   VCL component TCCSFuncionario                                    }
{                                                                    }
{   Comp do cartão                                                   }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file d:\cartao\uccsrog.cd                  }
{   on 5 Aug 1998 at 11:29                                           }
{                                                                    }
{   Copyright © 1998 by CCS-SIS - Consórcio de Componentes de Software. }
{                                                                    }
{ ****************************************************************** }

unit UCCSRog;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls,
     Forms, Graphics, Db, dbctrls, dbtables;

type
  TCCSFuncionario = class(TComponent)
    private
      { Private fields of TCCSFuncionario }
        { Storage for property PISRic }
        FPISRic : double;
        { Storage for property Nome }
        FNome : String;
        { Storage for property Habilitado }
        FHabilitado : String;
        { Storage for property DataSource }
        FDataSource : TDataSource;

      { Private methods of TCCSFuncionario }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        { Write method for property Nome }
        procedure SetNome(Value : String);

    protected
      { Protected fields of TCCSFuncionario }
        Temp : String;

      { Protected methods of TCCSFuncionario }
        { Resets prop of component type if referenced component deleted }
        procedure Notification(AComponent : TComponent; Operation : TOperation); override;
        procedure Loaded; override;

    public
      { Public fields and properties of TCCSFuncionario }

      { Public methods of TCCSFuncionario }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function Execute : Boolean;
        procedure CarregaFuncionario;
        procedure Habilitar;
        procedure Desabilitar;

    published
      { Published properties of TCCSFuncionario }
        property PISRic : double read FPISRic write FPISRic;
        property Nome : String read FNome write SetNome;
        property Habilitado : String read FHabilitado write FHabilitado;
        property DataSource : TDataSource read FDataSource write FDataSource;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TCCSFuncionario with Cartao as its
       default page on the Delphi component palette }
     RegisterComponents('Cartao', [TCCSFuncionario]);
end;

{ Method to set variable and property values and create objects }
procedure TCCSFuncionario.AutoInitialize;
begin
     FPISRic := 0;
     FNome := '';
     FDataSource := nil;
end; { of AutoInitialize }

{ Resets prop of component type if referenced component deleted }
procedure TCCSFuncionario.Notification(AComponent : TComponent; Operation : TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of 
       this component been deleted?  If so, update 
       the property. }
     if AComponent = FDataSource then
        FDataSource := nil;
end;

{ Method to free any objects created by AutoInitialize }
procedure TCCSFuncionario.AutoDestroy;
begin
     { No objects from AutoInitialize to free }
end; { of AutoDestroy }

{ Write method for property Nome }
procedure TCCSFuncionario.SetNome(Value : String);
begin
     FNome := Value;
end;

constructor TCCSFuncionario.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

destructor TCCSFuncionario.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TCCSFuncionario.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;

function TCCSFuncionario.Execute : Boolean;
begin
     { Perform the component operation }

     { Return True if the operation was successful, False otherwise }
     Result := True
end;

procedure TCCSFuncionario.CarregaFuncionario;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
   with DataSource.Dataset as TQuery do
   begin
      close;
      sql.clear;
      sql.add('select * from funcionario where pisric = :pis');
      ParamByName('pis').AsFloat := pisric;
      Open;
      nome := Fieldbyname('nomefunc').asString;
      habilitado := Fieldbyname('habilitado').asString;
  end;
end;

procedure TCCSFuncionario.Habilitar;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin

end;

procedure TCCSFuncionario.Desabilitar;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin

end;


end.
