; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MySQL Server"
#define MyAppVerName "MySQL Server 5.1. "
#define MyAppPublisher "Sun Microsystens"
#define MyAppURL "http://mysql.com/"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)

AppId={{9C00511A-8DC4-4E41-8EB4-EF911E6FE089}
AppName={#MyAppName}
AppVerName={#MyAppVerName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\MySQL\MySQL Server 5.1
DefaultGroupName={#MyAppName}
OutputBaseFilename=setup-MySQLServer
Compression=lzma
SolidCompression=yes

[Languages]
Name: english; MessagesFile: compiler:Default.isl
Name: brazilianportuguese; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

[Files]
Source: mysql-essential-5.1.47-win32.msi; DestDir: {tmp}; Flags: deleteafterinstall

; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Run]

Filename: msiexec.exe; Parameters: "/qb /i ""{tmp}\mysql-essential-5.1.47-win32.msi"""; WorkingDir: {tmp}; StatusMsg: Instalando MySQL Server 5.1; Flags: waituntilterminated
Filename: {pf}\MySQL\MySQL Server 5.1\bin\MySQLInstanceConfig; Parameters: " -i -q "; WorkingDir: {tmp}; StatusMsg: Iniciando Serviço MySQL; Flags: waituntilterminated
Filename: {pf}\MySQL\MySQL Server 5.1\bin\MySQLInstanceConfig; Parameters: " -i  RootPassword=masterkey ServiceName=MySQL  ""-p{pf}\MySQL\MySQL Server 5.1"" AddBinToPath=yes ServerType=SERVER DatabaseType=MIXED ConnectionUsage=DSS Port=3306 StrictMode=yes Charset=latin1 ""-l{pf}\MySQL\MySQL Server 5.1\instanceConfig.log"""; WorkingDir: {tmp}; StatusMsg: Configurando instancia do MySQL; Flags: waituntilterminated
