;; NutWin - Programa de Apoio a Nutrição(R)
;; Copyright (C) 2002-2010 Departamento de Informática em Saúde
;; Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
;;
;; This file is part of NutWin.
;;
;; NutWin is free software:  you  can  redistribute  it  and/or
;; modify it under the terms of the GNU General Public  License
;; as published by the Free Software Foundation, either version
;; 3 of the License, or (at your option) any later version.
;;
;; Nutwin is distributed in the hope that it  will  be  useful,
;; but WITHOUT ANY WARRANTY; without even the implied  warranty
;; of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
;; the GNU General Public License for more details.
;;
;; You should have received a copy of the  GNU  General  Public
;; License along with Foobar.
;; If not, see <http://www.gnu.org/licenses/>.

; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CBDD2F0B-FECC-4A68-B707-6A0A35E641CA}
AppName=Programa de Apoio à Nutrição
AppVerName=Programa de Apoio à Nutrição 1.6.0.7
AppPublisher=Departamento de Informática em Saúde - UNIFESP
AppPublisherURL=http://sourceforge.net/projects/nutwin/
AppSupportURL=http://sourceforge.net/projects/nutwin/
AppUpdatesURL=http://sourceforge.net/projects/nutwin/
DefaultDirName={pf}\DIS-EPM\NutWin-1.6.0.7
DefaultGroupName=Programa de Apoio à Nutrição 1.6.0.7
AllowNoIcons=true
LicenseFile=C:\nutwin\installer\ScriptFiles\SourceFiles\installFiles\COPYING.txt
InfoAfterFile=C:\nutwin\installer\ScriptFiles\SourceFiles\MirrorDest\Leia-me.txt
OutputBaseFilename=NutWin-1.6.0.7-beta-6
Compression=lzma/ultra64
SolidCompression=true
ShowTasksTreeLines=true

;;     MySQL     = 155 MiB
;;   + MyODBC    =   9 MiB
;;   + ScriptSQL =  17 MiB
;;	 + MySQLData = 391 MiB
;;   + BDE          13 MiB
;;   ------------------
;;   total    =    585 MiB => 613416960 Bytes
;; ainda falta BDE, Dados ...
ExtraDiskSpaceRequired=2147483647
UserInfoPage=false
VersionInfoVersion=1.6.0.7
ShowLanguageDialog=auto
AppVersion=1.6.0.7
VersionInfoCopyright=Departamento de Informática em Saúde - UNIFESP
VersionInfoProductName=NutWin
VersionInfoProductVersion=1.6.0.7
AppCopyright=Departamento de Informática em Saúde - UNIFESP
;;DefaultUserInfoSerial={userinfoserial}
UsePreviousUserInfo=false
InfoBeforeFile=C:\nutwin\installer\ScriptFiles\SourceFiles\installFiles\APRESENTAÇÃO.txt
WindowVisible=false
WindowResizable=false
WizardImageFile=C:\nutwin\installer\ScriptFiles\SourceFiles\installFiles\Imagens\WizardImageFile.bmp
WizardSmallImageFile=C:\nutwin\installer\ScriptFiles\SourceFiles\installFiles\Imagens\WizardSmallImageFile.bmp

[Languages]
Name: brazilianportuguese; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

[Types]
Name: full; Description: Completa - Instala todos os recursos
Name: client; Description: Cliente - Instala Organizador e Calculadora
Name: server; Description: Servidor - Instala Sevidor e Base de Dados
Name: custom; Description: Personalizada - permite escolher os componentes; Flags: iscustom

[Components]
;; instalação para uso isolado
Name: Client; Description: Organizador e Calculadora; Types: full client custom; Flags: fixed
;Name: Client\BDE; Description: Borland Database Engine; types: full client
;name: Client\ODBC; Description: MyODBC Connector; types: full client
;Name: Client\Help; Description: Arquivos de Ajuda; Types: full client
;; Instalação para uso na rede local
Name: Server; Description: MySQL Server; Types: full server
;; Database, datafiles, application data,
Name: Server\Database; Description: Base de Dados Padrão; Types: full server




[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Components: Client; Flags: unchecked
Name: quicklaunchicon; Description: {cm:CreateQuickLaunchIcon}; GroupDescription: {cm:AdditionalIcons}; Components: Client; Flags: unchecked


[Files]

Source: SourceFiles\components\libmySQL.dll; DestDir: {sys}; Components: Client

;;;; BDE Files
Source: C:\nutwin\installer\ScriptFiles\BDEInstall\BdeCore\windir\system32\bdeadmin.cpl; Components: Client; DestDir: {sys}
Source: C:\nutwin\installer\ScriptFiles\BDEInstall\BdeCore\CommonProgramFiles\Borland Shared\BDE\*; DestDir: {cf}\Borland Shared\BDE\; Components: Client; Flags: ignoreversion recursesubdirs createallsubdirs

;;;; MySQL Connector ODBC Files
Source: C:\nutwin\installer\ScriptFiles\MyODBCConnector\mysql-connector-odbc-noinstall-5.1.6-win32\lib\myodbc5S.dll; DestDir: {sys}; Components: Client
Source: C:\nutwin\installer\ScriptFiles\MyODBCConnector\mysql-connector-odbc-noinstall-5.1.6-win32\lib\myodbc5S.lib; DestDir: {sys}; Components: Client
Source: C:\nutwin\installer\ScriptFiles\MyODBCConnector\mysql-connector-odbc-noinstall-5.1.6-win32\lib\myodbc5.dll; DestDir: {sys}; Components: Client
Source: C:\nutwin\installer\ScriptFiles\MyODBCConnector\mysql-connector-odbc-noinstall-5.1.6-win32\lib\myodbc5.lib; DestDir: {sys}; Components: Client
Source: C:\nutwin\installer\ScriptFiles\MyODBCConnector\mysql-connector-odbc-noinstall-5.1.6-win32\bin\myodbc-installer.exe; DestDir: {sys}; Components: Client
Source: C:\nutwin\installer\ScriptFiles\MyODBCConnector\mysql-connector-odbc-noinstall-5.1.6-win32\doc\myodbc3.hlp; DestDir: {sys}; Components: Client


;;;; NutFiles
Source: SourceFiles\MirrorDest\*; DestDir: {app}; Flags: ignoreversion recursesubdirs createallsubdirs; Components: Client
Source: SourceFiles\components\SQLScript\dumpNutWin.sql; DestDir: {tmp}; Flags: deleteafterinstall; Components: Client
Source: SourceFiles\components\MySQL\*; DestDir: {tmp}; Flags: deleteafterinstall; Components: Client
Source: C:\nutwin\src\NutWin\Calc\Calcnut.exe; DestDir: {app}\Calc; Flags: ignoreversion recursesubdirs createallsubdirs; Components: Client
Source: C:\nutwin\src\NutWin\NutPrg\PNutwin.exe; DestDir: {app}\OrgNut; Flags: ignoreversion recursesubdirs createallsubdirs; Components: Client


[Icons]

Name: {commondesktop}\Organizador; Filename: {app}\OrgNut\PNutwin.exe; Components: Client; Tasks: desktopicon
Name: {userappdata}\Microsoft\Internet Explorer\Quick Launch\Organizador; Filename: {app}\OrgNut\PNutwin.exe; Components: Client; Tasks: quicklaunchicon
Name: {group}\Ajuda da Calculadora; Filename: {app}\Help\Calculo.chm; Components: Client
Name: {group}\Ajuda do Organizador; Filename: {app}\Help\Organiza.chm; Components: Client
Name: {group}\Calculadora; Filename: {app}\Calc\CalcNut.exe; Components: Client
Name: {group}\Atualizações; Filename: {app}\NutWin.txt; Components: Client
Name: {group}\Guia-Nut; Filename: {app}\Help\Guia-Nut.html; Components: Client
Name: {group}\Organizador; Filename: {app}\OrgNut\PNutwin.exe; Components: Client
Name: {group}\{cm:ProgramOnTheWeb,Programa de Apoio à Nutrição}; Filename: http://sourceforge.net/projects/nutwin/; Components: Client
Name: {group}\{cm:UninstallProgram,Programa de Apoio à Nutrição}; Filename: {uninstallexe}; Components: Client

[Run]
Filename: "notepad "; Description: Exibir arquivo Leia-me; Flags: nowait postinstall skipifsilent runasoriginaluser; Parameters: {app}\Leia-me.txt; Components: Client
Filename: {app}\OrgNut\PNutwin.exe; Description: {cm:LaunchProgram,Programa de Apoio à Nutrição}; Flags: nowait postinstall skipifsilent runasoriginaluser; Components: Client

;;;; MySQL Connector ODBC Runs
Filename: myodbc-installer; Parameters: "-d -a -n ""MySQL ODBC 5.1 Driver"" -t ""DRIVER=myodbc5.dll;SETUP=myodbc5S.dll"""; WorkingDir: {tmp}; StatusMsg: Instalando MySQL Connector/ODBC 5.1; Flags: waituntilterminated shellexec runhidden runascurrentuser; Components: Client


;; MySQL Server Install
Filename: msiexec.exe; Parameters: "/qb /i ""{tmp}\mysql-essential-5.1.47-win32.msi"""; WorkingDir: {tmp}; StatusMsg: Instalando MySQL Server 5.1; Flags: waituntilterminated runascurrentuser; Components: Server
;; msiexec.exe "/qb /i mysql-5.1.33-win32.msi"

;; MySQL Server Config
;;Filename: {pf}\MySQL\MySQL Server 5.1\bin\MySQLInstanceConfig; Parameters: -q -i -nMySQL AddBinToPath=yes ServerType=SERVER DatabaseType=MIXED ConnectionUsage=DSS Port=3306 StrictMode=yes Charset=latin1 RootPassword=masterkey; WorkingDir: {tmp}; StatusMsg: Configurando instancia do MySQL
;; -s para o serviço
;; -i inicia o servico/reconfigura (Instala)
;; -r remove o servico
;;	Filename: net; Parameters: start MySQL; WorkingDir: {tmp}; StatusMsg: Verificando instancia do MySQL; Flags: waituntilterminated
;;	Filename: net; Parameters: start MySQL; WorkingDir: {tmp}; StatusMsg: Verificando instancia do MySQL; Flags: waituntilterminated
;;"%programfiles%\MySQL\MySQL Server 5.1\bin\MySQLInstanceConfig" -r
Filename: {pf}\MySQL\MySQL Server 5.1\bin\MySQLInstanceConfig; Parameters: " -i -q "; WorkingDir: {tmp}; StatusMsg: Iniciando Serviço MySQL; Flags: waituntilterminated runascurrentuser; Components: Server
;;Filename: {pf}\MySQL\MySQL Server 5.1\bin\MySQLInstanceConfig; Parameters: "  -r "; WorkingDir: {tmp}; StatusMsg: Verificando instancia do MySQL; Flags: waituntilterminated

Filename: {pf}\MySQL\MySQL Server 5.1\bin\MySQLInstanceConfig; Parameters: " -i  RootPassword=masterkey ServiceName=MySQL  ""-p{pf}\MySQL\MySQL Server 5.1"" AddBinToPath=yes ServerType=SERVER DatabaseType=MIXED ConnectionUsage=DSS Port=3306 StrictMode=yes Charset=latin1 ""-l{pf}\MySQL\MySQL Server 5.1\instanceConfig.log"""; WorkingDir: {tmp}; StatusMsg: Configurando instancia do MySQL; Flags: waituntilterminated runascurrentuser; Components: Server
;;"%programfiles%\MySQL\MySQL Server 5.1\bin\MySQLInstanceConfig" -i -q RootPassword=masterkey ServiceName=MySQL  "-p%programfiles%\MySQL\MySQL Server 5.1" AddBinToPath=yes ServerType=SERVER DatabaseType=MIXED ConnectionUsage=DSS Port=3306 StrictMode=yes Charset=latin1 "-l%programfiles%\MySQL\MySQL Server 5.1\instanceConfig.log"


;;;; Database records Install
;;
Filename: {pf}\MySQL\MySQL Server 5.1\bin\mysql; Parameters: "-u root -pmasterkey --execute=""source {tmp}\dumpNutWin.sql"""; WorkingDir: {tmp}; StatusMsg: Gerando Base de dados e Registros; Flags: waituntilterminated runhidden runascurrentuser; Components: Server\Database
;; "%programfiles%\Mysql\MySQL Server 5.1\bin\mysql" -u root -pmasterkey --execute="source {tmp}\dumpNutWin.sql"


[Registry]
;;;; NutWin
;;By registering your application under the App Paths key, users can start your application from Explorer's Run dialog by entering just the EXE's filename and no path.
Root: HKLM; Subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\PNutwin.exe; ValueType: string; ValueName: ; ValueData: {app}\OrgNut\PNutwin.exe; Flags: uninsdeletekey; Components: Client
Root: HKLM; Subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\Calcnut.exe; ValueType: string; ValueName: ; ValueData: {app}\Calc\Calcnut.exe; Flags: uninsdeletekey; Components: Client
;;;; NutWin Registry default path
Root: HKLM; Subkey: SOFTWARE\DIS-EPM; Flags: createvalueifdoesntexist uninsdeletekeyifempty; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; Flags: createvalueifdoesntexist uninsdeletekey; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7\0; Flags: createvalueifdoesntexist; Components: Client
;;;; User Info
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: Name; ValueData: {userinfoname}; ValueType: string; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: Company; ValueData: {userinfoorg}; ValueType: string; Components: Client
;;;; Entrys
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: VERSAO CALCNUT; ValueData: BETA 1.6.0.7; ValueType: string; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: DefaultDataPath; ValueData: {app}\DefaultData; ValueType: string; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: Tipo; ValueData: Cliente/Servidor; ValueType: string; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: PERSONA FILE NAME; ValueData: {app}; ValueType: string; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: LOGO FILE NAME; ValueData: {app}; ValueType: string; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: Path; ValueData: {app}; ValueType: string; Components: Client
Root: HKLM; Subkey: SOFTWARE\DIS-EPM\NutWin-1.6.0.7; ValueName: ProgramDataPath; ValueData: {reg:HKLM\SOFTWARE\MySQL AB\MySQL Server 5.1,DataLocation}data; ValueType: string; Components: Client


;;;;; MyODBC
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\ODBC Data Sources; ValueType: string; ValueName: My_NutWin-1.6.0.7; ValueData: MySQL ODBC 5.1 Driver; Flags: createvalueifdoesntexist uninsdeletevalue; Components: Client
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6.0.7; Flags: uninsdeletekey createvalueifdoesntexist; Components: Client
Root: HKLM; SubKey: Software\ODBC\ODBC.INI\My_NutWin-1.6.0.7; ValueType: string; ValueName: Driver; ValueData: {sys}\myodbc5.dll; Flags: createvalueifdoesntexist uninsdeletevalue; Components: Client
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6.0.7; ValueType: string; ValueName: DATABASE; ValueData: MyNutWin; Flags: createvalueifdoesntexist uninsdeletevalue; Components: Client
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6.0.7; ValueType: string; ValueName: DESCRIPTION; ValueData: NutWin ODBC Data Source; Flags: createvalueifdoesntexist uninsdeletevalue; Components: Client
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6.0.7; ValueType: string; ValueName: PWD; ValueData: masterkey; Flags: createvalueifdoesntexist uninsdeletevalue; Components: Client
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6.0.7; ValueType: string; ValueName: SERVER; ValueData: localhost; Flags: createvalueifdoesntexist uninsdeletevalue; Components: Client
Root: HKLM; Subkey: SOFTWARE\ODBC\ODBC.INI\My_NutWin-1.6.0.7; ValueType: string; ValueName: UID; ValueData: root; Flags: createvalueifdoesntexist uninsdeletevalue; Components: Client

;;;; BDE Registry
Root: HKLM; SubKey: SOFTWARE\Borland\BLW32; ValueType: string; ValueName: BLAPIPATH; ValueData: {cf}\Borland Shared\BDE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine; ValueType: string; ValueName: DLLPATH; ValueData: {cf}\Borland Shared\BDE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine; ValueType: string; ValueName: UseCount; ValueData: 1; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine; ValueType: string; ValueName: CONFIGFILE01; ValueData: {cf}\Borland Shared\BDE\IDAPI32.CFG; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine; ValueType: string; ValueName: SaveConfig; ValueData: WIN32; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine; ValueType: string; ValueName: RESOURCE; ValueData: 0009; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\INIT; ValueType: string; ValueName: VERSION; ValueData: 5.0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\INIT; ValueType: string; ValueName: TYPE; ValueData: FILE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\INIT; ValueType: string; ValueName: LANGDRIVER; ValueData: DBWINUS0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\TABLE CREATE; ValueType: string; ValueName: LEVEL; ValueData: 7; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\TABLE CREATE; ValueType: string; ValueName: MDX BLOCK SIZE; ValueData: 1024; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\DBASE\TABLE CREATE; ValueType: string; ValueName: MEMO FILE BLOCK SIZE; ValueData: 1024; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\FOXPRO\INIT; ValueType: string; ValueName: VERSION; ValueData: 5.0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\FOXPRO\INIT; ValueType: string; ValueName: TYPE; ValueData: FILE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\FOXPRO\INIT; ValueType: string; ValueName: LANGDRIVER; ValueData: DBWINUS0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\FOXPRO\TABLE CREATE; ValueType: string; ValueName: LEVEL; ValueData: 25; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; ValueName: LANGDRIVER; ValueData: ; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; ValueName: DATABASE NAME; ValueData: ; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; ValueName: USER NAME; ValueData: ; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; ValueName: OPEN MODE; ValueData: READ/WRITE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\DB OPEN; ValueType: string; ValueName: SYSTEM DATABASE; ValueData: ; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; ValueName: VERSION; ValueData: 1.0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; ValueName: TYPE; ValueData: SERVER; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; ValueName: DLL32; ValueData: IDDAO32.DLL; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; ValueName: DRIVER FLAGS; ValueData: ; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\MSACCESS\INIT; ValueType: string; ValueName: TRACE MODE; ValueData: 0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\INIT; ValueType: string; ValueName: VERSION; ValueData: 5.0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\INIT; ValueType: string; ValueName: TYPE; ValueData: FILE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\INIT; ValueType: string; ValueName: LANGDRIVER; ValueData: DBWINUS0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\TABLE CREATE; ValueType: string; ValueName: LEVEL; ValueData: 4; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\TABLE CREATE; ValueType: string; ValueName: BLOCK SIZE; ValueData: 2048; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\TABLE CREATE; ValueType: string; ValueName: FILL FACTOR; ValueData: 95; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\DRIVERS\PARADOX\TABLE CREATE; ValueType: string; ValueName: STRICTINTEGRTY; ValueData: TRUE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; ValueName: SEPARATOR; ValueData: /; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; ValueName: MODE; ValueData: 0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; ValueName: FOURDIGITYEAR; ValueData: FALSE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; ValueName: YEARBIASED; ValueData: TRUE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; ValueName: LEADINGZEROM; ValueData: FALSE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\DATE; ValueType: string; ValueName: LEADINGZEROD; ValueData: FALSE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\NUMBER; ValueType: string; ValueName: DECIMALSEPARATOR; ValueData: .; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\NUMBER; ValueType: string; ValueName: THOUSANDSEPARATOR; ValueData: ,; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\NUMBER; ValueType: string; ValueName: DECIMALDIGITS; ValueData: 2; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\NUMBER; ValueType: string; ValueName: LEADINGZERON; ValueData: TRUE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; ValueName: TWELVEHOUR; ValueData: TRUE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; ValueName: AMSTRING; ValueData: AM; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; ValueName: PMSTRING; ValueData: PM; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; ValueName: SECONDS; ValueData: TRUE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\FORMATS\TIME; ValueType: string; ValueName: MILSECONDS; ValueData: FALSE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: VERSION; ValueData: 5.0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: LOCAL SHARE; ValueData: FALSE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: MINBUFSIZE; ValueData: 128; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: MAXBUFSIZE; ValueData: 2048; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: LANGDRIVER; ValueData: DBWINUS0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: MAXFILEHANDLES; ValueData: 48; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: SYSFLAGS; ValueData: 0; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: LOW MEMORY USAGE LIMIT; ValueData: 32; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: AUTO ODBC; ValueData: FALSE; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: DEFAULT DRIVER; ValueData: PARADOX; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: SHAREDMEMSIZE; ValueData: 2048; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: SHAREDMEMLOCATION; ValueData: ; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: MEMSIZE; ValueData: 16; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: DATA REPOSITORY; ValueData: ; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: SQLQRYMODE; ValueData: ; Components: Client
Root: HKLM; SubKey: SOFTWARE\Borland\Database Engine\Settings\SYSTEM\INIT; ValueType: string; ValueName: MTS POOLING; ValueData: FALSE; Components: Client

[UninstallRun]
Filename: "myodbc-installer "; Parameters: "-d -r -n ""MySQL ODBC 5.1 Driver"""; WorkingDir: {app} Flags: waituntilterminated shellexec runhidden
;;;;;
