; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{68EF2352-3243-463D-88F6-B628747A695E}
AppName=Programa de Apoio à Nutrição
AppVerName=Programa de Apoio à Nutrição 1.6
AppPublisher=Departamento de Informática em Saúde - UNIFESP
AppPublisherURL=http://www.unifesp.br/dis/produtos/nutwin/
AppSupportURL=http://www.unifesp.br/dis/produtos/nutwin/
AppUpdatesURL=http://www.unifesp.br/dis/produtos/nutwin/
DefaultDirName={pf}\DIS-EPM\NutWin
DefaultGroupName=Programa de Apoio à Nutrição
AllowNoIcons=yes
LicenseFile=G:\nutwin\src\InnoNutWin\SourceFiles\installFiles\License.txt
InfoAfterFile=G:\nutwin\src\InnoNutWin\SourceFiles\MirrorDest\Leia-me.txt
OutputDir=G:\nutwin\src\InnoNutWin\output
OutputBaseFilename=config
SetupIconFile=G:\nutwin\src\InnoNutWin\SourceFiles\NutWin.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "G:\nutwin\src\InnoNutWin\SourceFiles\MirrorDest\OrgNut\PNutwin.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "G:\nutwin\src\InnoNutWin\SourceFiles\MirrorDest\Leia-me.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "G:\nutwin\src\InnoNutWin\SourceFiles\MirrorDest\NutWin.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "G:\nutwin\src\InnoNutWin\SourceFiles\MirrorDest\Calc\*"; DestDir: "{app}\Calc"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\nutwin\src\InnoNutWin\SourceFiles\MirrorDest\Help\*"; DestDir: "{app}\Help"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "G:\nutwin\src\InnoNutWin\SourceFiles\MirrorDest\OrgNut\*"; DestDir: "{app}\OrgNut"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Programa de Apoio à Nutrição"; Filename: "{app}\PNutwin.exe"
Name: "{group}\{cm:ProgramOnTheWeb,Programa de Apoio à Nutrição}"; Filename: "http://www.unifesp.br/dis/produtos/nutwin/"
Name: "{group}\{cm:UninstallProgram,Programa de Apoio à Nutrição}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Programa de Apoio à Nutrição"; Filename: "{app}\PNutwin.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Programa de Apoio à Nutrição"; Filename: "{app}\PNutwin.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\PNutwin.exe"; Description: "{cm:LaunchProgram,Programa de Apoio à Nutrição}"; Flags: nowait postinstall skipifsilent

