;; NutWin - Programa de Apoio a Nutrição(R)
;; Copyright (C) 2002-2010 Departamento de Informática em Saúde
;; Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
;;
;; This file is part of NutWin.
;;
;; NutWin is free software:  you  can  redistribute  it  and/or
;; modify it under the terms of the GNU General Public  License
;; as published by the Free Software Foundation, either version
;; 3 of the License, or (at your option) any later version.
;;
;; Nutwin is distributed in the hope that it  will  be  useful,
;; but WITHOUT ANY WARRANTY; without even the implied  warranty
;; of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
;; the GNU General Public License for more details.
;;
;; You should have received a copy of the  GNU  General  Public
;; License along with Foobar.
;; If not, see <http://www.gnu.org/licenses/>.

; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Borland Database Engine"
#define MyAppVerName "Borland Database Engine 5.0"
#define MyAppPublisher "Borland"
#define MyAppURL "http://www.inprise.com/bde"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FA77CD25-0991-4995-9B42-05F071E25B7E}
AppName={#MyAppName}
AppVerName={#MyAppVerName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
ExtraDiskSpaceRequired=13631488
[Languages]
Name: english; MessagesFile: compiler:Default.isl
Name: brazilianportuguese; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

[Files]
Source: BdeInst.dll; DestDir: {tmp}; Flags: deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: regsvr32.exe; Parameters: /s /i {tmp}\BdeInst.dll; WorkingDir: {tmp}; StatusMsg: Instalando Borland Database Engine e SQL Links
