#define Abrindo_outra_memoria.htm	1
#define Abrindo_um_cálculo_já_existente.htm	2
#define formulasAdequao_de_Peso_para_Estatura_e_.htm	3
#define formulasAdequao_de_Peso_para_Idade_PI.htm	4
#define Alimentos.htm	5
#define Anamnese_Nutricional.htm	6
#define Antropometria\formulasAntropometria.htm	7
#define formulasAtividades_Fsicas.htm	8
#define formulasBalano_Nitrogenado_BN.htm	9
#define Botões_da_Calculadora.htm	10
#define formulasCalculadora_Iniciando_um_novo_cá.htm	11
#define formulasCircunferncia_Muscular_do_Brao_C.htm	12
#define formulasClearance_de_Creatinina_CC.htm	13
#define formulasComo_dar_os_primeiros_passos_com.htm	14
#define Como_fazer_um_Inquérito_Alimentar__.htm	15
#define Como_fazer_um_Plano_Alimentar__.htm	16
#define formulasCompleio_Fsica.htm	17
#define formulasComposio_Corporal_por_Pregas_Cut.htm	18
#define Configurando_sua_Calculadora.htm	19
#define vConfigurações_da_Lista_de_Alimentos.htm	20
#define Conhecendo_calculadora.htm	21
#define formulasCálculo_do_Percentil_Px.htm	22
#define Definindo_um_escopo_para_todos_os_cálculos.htm	23
#define v	24
#define Diferenças_entre_Inquérito_e_Plano_Alimentar.htm	25
#define Configurações_da_Lista_de_Alimentos.htm	26
#define Antropometria\formulasEntrada_dos_Valores.htm	27
#define formulasEstatura_Calculada_pelo_Comprime.htm	28
#define Fechando_o_cálculo_ativo.htm	29
#define formulasFrmulas_Especiais.htm	30
#define Imprimindo_um_cálculo.htm	31
#define Iniciando_calculo.htm	32
#define Iniciando_um_novo_documento.htm	33
#define formulasInqurito.htm	34
#define Inquérito.htm	35
#define formulasInqurito__Refeies.htm	36
#define formulasInqurito_Consumo.htm	37
#define formulasInqurito_Consumo_Alimentar.htm	38
#define formulasInqurito_Relatrio_de_resultados.htm	39
#define Introducao_calculadora.htm	40
#define formulasMassa_Corporal_Magra_atravs_da_C.htm	41
#define formulasNitrognio_Excretado_Total_NET.htm	42
#define formulasNitrognio_Ingerido_NI.htm	43
#define formulasNitrognio_Urinário_Total_NUT.htm	44
#define formulasNitrognio_Urico_Urinário_de_24h_.htm	45
#define Nutrientes.htm	46
