// NutWin - Programa de Apoio a Nutrição(R)
// Copyright (C) 2002-2010 Departamento de Informática em Saúde
// Universidade Federal de São Paulo - UNIFESP <www.unifesp.br>
//
// This file is part of NutWin.
//
// NutWin is free software:  you  can  redistribute  it  and/or
// modify it under the terms of the GNU General Public  License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// Nutwin is distributed in the hope that it  will  be  useful,
// but WITHOUT ANY WARRANTY; without even the implied  warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License for more details.
//
// You should have received a copy of the  GNU  General  Public
// License along with Foobar.
// If not, see <http://www.gnu.org/licenses/>.




{ ****************************************************************** }
{                                                                    }
{   Delphi component TTabela                                         }
{                                                                    }
{   Faz pesquisa em tabela                                           }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from untitled component definition                     }
{   on 23 July 1997 at 14:36                                         }
{                                                                    }
{   Copyright © 1997 by Nutrição - DIS-EPM/UNIFESP                   }
{                                                                    }
{ ****************************************************************** }

unit ROM;

interface

uses Classes, SysUtils, DB, DBTables, Measurement, Parser10, DelayedOpIndicator;

type

   TModoPesquisa = ( mpFirstRecord, mpLastRecord, mpRanges, mpNewRanges );

   ETabelaVazia = class(Exception);

   TTabela = class(TComponent)
   private
      FDataBaseName : String;
      FNomeTabela : String;
      FCondicao : String;
      FCampoResult : String;
      FResultado : TMedida;
      FA : TMedida;
      FB : TMedida;
      FC : TMedida;
      FD : TMedida;
      FE : TMedida;
      FModoPesquisa : TModoPesquisa;
      FFaixas : TMeasurementRanges;
      FDelayedOpIndicator : TDelayedOpIndicator;
    FAceitaParametrosInvalidos: Boolean;
      function GetA : TMedida;
      procedure SetA(Value : TMedida);
      function GetDataBaseName : String;
      procedure SetDataBaseName(Value : String);
      function GetNomeTabela : String;
      procedure SetNomeTabela(Value : String);
      function GetCondicao : String;
      procedure SetCondicao(Value : String);
      function GetCampoResult : String;
      procedure SetCampoResult(Value : String);
      function GetResultado : TMedida;
      procedure SetResultado(Value : TMedida);
      function GetB : TMedida;
      procedure SetB(Value : TMedida);
      function GetC : TMedida;
      procedure SetC(Value : TMedida);
      function GetD : TMedida;
      procedure SetD(Value : TMedida);
      function GetE : TMedida;
      procedure SetE(Value : TMedida);
      function SetaParam( Qry : TQuery; I : integer; Param : TMedida ) : Boolean;
      procedure SetModoPesquisa(const Value: TModoPesquisa);
      procedure SetFaixas(const Value: TMeasurementRanges);
      procedure FaixasValidas(var ListaFaixas: TStringList; Medida : TMedida);
      function  Caption(Medida : TMedida) : String;
      procedure CarregaFaixas(DataSet: TDataSet; CampoValor, CampoDescricao: String; UnidadeFaixas : String); overload;
      procedure CarregaFaixas( DataSet : TDataSet; CampoCaption : String = 'CAPTION' ); overload;
      function PegaCampo( ListaCampos : String; Pos : Integer ) : String;
      function SemAspas( Str : String ) : String;
      procedure SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
    procedure SetAceitaParametrosInvalidos(const Value: Boolean);
   protected
      procedure Loaded; override;
      procedure Notification(AComponent : TComponent; Operation : TOperation); override;
   public
      procedure LimparParametros;
      constructor Create(AOwner: TComponent); override;
      destructor Destroy; override;
      function Execute : Boolean;
   published
      property DelayedOpIndicator : TDelayedOpIndicator read FDelayedOpIndicator write SetDelayedOpIndicator;
      property DataBaseName : String read GetDataBaseName write SetDataBaseName;
      property NomeTabela : String read GetNomeTabela write SetNomeTabela;
      property Condicao : String read GetCondicao write SetCondicao;
      property CampoResult : string read GetCampoResult write SetCampoResult;
      property Resultado : TMedida read GetResultado write SetResultado;
      property A : TMedida read GetA write SetA;
      property B : TMedida read GetB write SetB;
      property C : TMedida read GetC write SetC;
      property D : TMedida read GetD write SetD;
      property E : TMedida read GetE write SetE;
      property ModoPesquisa : TModoPesquisa read FModoPesquisa write SetModoPesquisa;
      property Faixas : TMeasurementRanges read FFaixas write SetFaixas;
      property AceitaParametrosInvalidos : Boolean read FAceitaParametrosInvalidos write SetAceitaParametrosInvalidos;
   end;

procedure Register;

implementation

procedure Register;
begin
   RegisterComponents('Calculadora', [TTabela]);
end;

function TTabela.GetA : TMedida;
begin
   Result := FA
end;

procedure TTabela.SetA(Value : TMedida);
begin
   FA := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TTabela.GetDataBaseName : String;
begin
   Result := FDataBaseName
end;

procedure TTabela.SetDataBaseName(Value : String);
begin
   FDataBaseName := Value;
end;

function TTabela.GetNomeTabela : String;
begin
   Result := FNomeTabela;
end;

procedure TTabela.SetNomeTabela(Value : String);
begin
   FNomeTabela := Value;
end;

function TTabela.GetCondicao : String;
begin
   Result := FCondicao
end;

procedure TTabela.SetCondicao(Value : String);
begin
   FCondicao := Value;
end;

function TTabela.GetResultado : TMedida;
begin
   Result := FResultado;
end;

procedure TTabela.SetResultado(Value : TMedida);
begin
   FResultado := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TTabela.GetCampoResult : String;
begin
   Result := FCampoResult
end;

procedure TTabela.SetCampoResult(Value : String );
begin
   FCampoResult := Value;
end;

function TTabela.GetB : TMedida;
begin
   Result := FB
end;

procedure TTabela.SetB(Value : TMedida);
begin
   FB := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TTabela.GetC : TMedida;
begin
   Result := FC
end;

procedure TTabela.SetC(Value : TMedida);
begin
   FC := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TTabela.GetD : TMedida;
begin
   Result := FD
end;

procedure TTabela.SetD(Value : TMedida);
begin
   FD := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

function TTabela.GetE : TMedida;
begin
   Result := FE
end;

procedure TTabela.SetE(Value : TMedida);
begin
   FE := Value;
   if Value <> nil then
      Value.FreeNotification(Self);
end;

constructor TTabela.Create(AOwner: TComponent);
begin
   inherited Create(AOwner);
end;

destructor TTabela.Destroy;
begin
   inherited Destroy;
end;

procedure TTabela.Loaded;
begin
   inherited Loaded;
end;

function TTabela.Execute : Boolean;
var
   dsTab : TDataSource;
   qrTab : TQuery;
   sSQL : string;
   I : integer;
   Lista : TStringList;
begin
   Result := True;
   // Criando objetos de acesso a tabela
   dsTab := TDataSource.Create(self);
   qrTab := TQuery.Create(self);
   // configurando a Query
   with qrTab do
   begin
      Close;
      DatabaseName := FDataBaseName;
      DataSource := dsTab;
      SQL.Clear;
      if FModoPesquisa = mpNewRanges then
         begin
            sSQL := 'SELECT * FROM ' + FNomeTabela;
            if FCondicao <> '' then
               sSQL := sSQL + ' WHERE ' + FCondicao;
         end
      else
         begin
            sSQL := 'SELECT ' + FCampoResult + ' FROM ' + FNomeTabela;
            if FCondicao <> '' then
               sSQL := sSQL + ' WHERE ' + FCondicao;
         end;
      SQL.Add( sSQL );
      Result := True;
      Try
         for I := 0 to ParamCount - 1 do
           begin
            if Params[I].Name = 'A' then
            begin
               Result := SetaParam( qrTab, I, FA );
            end
            else if Params[I].Name = 'B' then
            begin
               Result := SetaParam( qrTab, I, FB );
            end
            else if Params[I].Name = 'C' then
            begin
               Result := SetaParam( qrTab, I, FC );
            end
            else if Params[I].Name = 'D' then
            begin
               Result := SetaParam( qrTab, I, FD );
            end
            else if Params[I].Name = 'E' then
            begin
               Result := SetaParam( qrTab, I, FE );
            end
           end;
      except
        on E:exception do
        begin
           Close;
           FResultado.Valid := False;
           Result:=False;
           raise exception.CreateFmt(e.message,[]);
        end;
      end;

      if not Result then
         begin
            Close;
            FResultado.ValorNumerico := '*** indeterminado ***';
            FResultado.Valid := False;
            exit;
         end;

      // indica operação demorada;
      if Assigned( FDelayedOpIndicator ) then
         FDelayedOpIndicator.Start;
      try
         Open;
      finally
         // finaliza indicação de operação demorada
         if Assigned( FDelayedOpIndicator ) then
            FDelayedOpIndicator.Finish;
      end;
      if qrTab.IsEmpty then
         begin
            Close;
            FResultado.ValorNumerico := '*** indeterminado ***';
            FResultado.Valid := False;
            // Quebra galho. Deveria ter uma tabela de erros
            if UpperCase(FNomeTabela) = 'T29' then
               FResultado.InvalidDescr := 'não disponível para essa idade gestacional (a partir da 10a. semana)'
            else
               FResultado.InvalidDescr := 'não adequado para essa faixa etária';
            Result:= False;
            exit;
         end;
      case FModoPesquisa of
           mpFirstRecord : begin
                              qrTab.First;
                              FResultado.ValorNumerico := FieldByName(FCampoResult).AsString;
                              FResultado.Valid := (FResultado.ValorNumerico <> '');
                           end;
           mpLastRecord : begin
                              qrTab.Last;
                              FResultado.ValorNumerico := FieldByName(FCampoResult).AsString;
                              FResultado.Valid := (FResultado.ValorNumerico <> '');
                           end;
           mpRanges :      begin
                              CarregaFaixas(qrTab, PegaCampo( FCampoResult, 1 ), PegaCampo( FCampoResult, 2 ), FA.Unidade);
                              Lista := TStringList.Create;
                              FaixasValidas(Lista, FA);
                              FResultado.ValorNumerico := SemAspas( Lista.CommaText );
                              FResultado.Valid := (FResultado.ValorNumerico <> '');
                              Lista.Free;
                           end;
           mpNewRanges :   begin
                              CarregaFaixas( qrTab, FCampoResult );
                              FResultado.ValorNumerico := Caption(FA);
                              FResultado.Valid := (FResultado.ValorNumerico <> '');
                           end;
      end;
      Close;
   end;
end;

function TTabela.SetaParam( Qry : TQuery; I : integer; Param : TMedida ) : Boolean;
begin
   Result := False;
   if ( Param.Empty ) then
      raise EMeasurementError.CreateFmt( '%s é uma medida vazia', [Param.Name])
   //So o Param tem o conhecimento do tipo de variavel (Float ou String)
   else if Param is TMedidaOrdinal then
        Qry.Params[I].AsString := Param.ValorNumerico
   else //TMedida e' o default (numerico)
        Qry.Params[I].AsFloat := Param.AsFloat;
   if Param.Valid or FAceitaParametrosInvalidos then
      Result := True;
end;

procedure TTabela.LimparParametros;
begin
   A := nil;
   B := nil;
   C := nil;
   D := nil;
   E := nil;
end;

procedure TTabela.SetModoPesquisa(const Value: TModoPesquisa);
begin
   FModoPesquisa := Value;
end;

procedure TTabela.SetFaixas(const Value: TMeasurementRanges);
begin
   FFaixas := Value;
   if Assigned( Value ) then
      Value.FreeNotification(self);
end;

procedure TTabela.Notification(AComponent: TComponent;
  Operation: TOperation);
begin
   inherited Notification(AComponent, Operation);
   if Operation <> opRemove then
      Exit;
   if AComponent = FFaixas then
      FFaixas := nil
   else if AComponent = FDelayedOpIndicator then
      FDelayedOpIndicator := nil
   else if AComponent = FResultado then
      FResultado := nil
   else if AComponent = FA then
      FA := nil
   else if AComponent = FB then
      FB := nil
   else if AComponent = FC then
      FC := nil
   else if AComponent = FD then
      FD := nil
   else if AComponent = FE then
      FE := nil;
end;

procedure TTabela.CarregaFaixas(DataSet: TDataSet; CampoValor,
  CampoDescricao: String; UnidadeFaixas : String);
begin
   with DataSet do begin
      FFaixas.Ranges.Clear;
      if IsEmpty then
         Exit;
      First;
      with FFaixas.Ranges.Add do begin
         with BeginPoint do begin
            Opened := True;
            Excluded := False;
            with Point do begin
               Descricao := '';
               Unidade := '';
            end;
         end;
         with EndPoint do begin
            Opened := False;
            Excluded := True;
            with Point do begin
               Descricao := FieldByName( CampoDescricao ).AsString;
               AsFloat := FieldByName( CampoValor ).AsFloat;
               Unidade := UnidadeFaixas;
            end;
         end;
         Caption := 'menor que ' + EndPoint.Point.Descricao ;
      end;
      while not EOF do begin
      with FFaixas.Ranges.Add do begin
         with BeginPoint do begin
            Opened := False;
            Excluded := False;
            with Point do begin
               Descricao := FieldByName( CampoDescricao ).AsString;;
               AsFloat := FieldByName( CampoValor ).AsFloat;
               Unidade := UnidadeFaixas;
            end;
         end;
         with EndPoint do begin
            Opened := False;
            Excluded := False;
            with Point do begin
               Descricao := FieldByName( CampoDescricao ).AsString;;
               AsFloat := FieldByName( CampoValor ).AsFloat;
               Unidade := UnidadeFaixas;
            end;
         end;
         Caption := BeginPoint.Point.Descricao;
      end;
         with FFaixas.Ranges.Add do begin
            with BeginPoint do begin
               Opened := False;
               Excluded := True;
               with Point do begin
                  Descricao := FieldByName( CampoDescricao ).AsString;;
                  AsFloat := FieldByName( CampoValor ).AsFloat;
                  Unidade := UnidadeFaixas;
               end;
            end;
            next;
            with EndPoint do begin
               Opened := False;
               Excluded := True;
               with Point do begin
                  Descricao := FieldByName( CampoDescricao ).AsString;;
                  AsFloat := FieldByName( CampoValor ).AsFloat;
                  Unidade := UnidadeFaixas;
               end;
            end;
            Caption := BeginPoint.Point.Descricao + ' e ' + EndPoint.Point.Descricao;
         end;
      end;
      with FFaixas.Ranges.Add do begin
         with BeginPoint do begin
            Opened := False;
            Excluded := True;
            with Point do begin
               Descricao := FieldByName( CampoDescricao ).AsString;;
               AsFloat := FieldByName( CampoValor ).AsFloat;
               Unidade := UnidadeFaixas;
            end;
         end;
         with EndPoint do begin
            Opened := True;
            Excluded := False;
            with Point do begin
               Descricao := '';
               Unidade := '';
            end;
         end;
         Caption := 'maior que ' + BeginPoint.Point.Descricao;
      end;
   end;
end;

procedure TTabela.FaixasValidas(var ListaFaixas: TStringList; Medida : TMedida);
var
   I : Integer;
begin
   ListaFaixas.Clear;
   for I := 0 to FFaixas.Ranges.Count - 1 do
   begin
      if FFaixas.Ranges.Items[I].Has( Medida ) then
      begin
         if FFaixas.Ranges.Items[I].BeginPoint.Point.ValorNumerico =
            FFaixas.Ranges.Items[I].EndPoint.Point.ValorNumerico then
            ListaFaixas.Add( FFaixas.Ranges.Items[I].Caption + ' ( ' +
                              FFaixas.Ranges.Items[I].BeginPoint.Point.ValorNumerico + ' ' +
                              FFaixas.Ranges.Items[I].EndPoint.Point.Unidade + ' )' )
      else
         ListaFaixas.Add( FFaixas.Ranges.Items[I].Caption + ' ( ' +
                          FFaixas.Ranges.Items[I].BeginPoint.Point.ValorNumerico + ' ... ' +
                          FFaixas.Ranges.Items[I].EndPoint.Point.ValorNumerico + ' ' +
                          FFaixas.Ranges.Items[I].EndPoint.Point.Unidade + ' )' );
      end;
   end;
end;

function TTabela.PegaCampo(ListaCampos: String; Pos: Integer): String;
var
   S : TStringList;
begin
   S := TStringList.Create;
   S.CommaText := ListaCampos;
   if S.Count >= Pos then
      Result := S.Strings[Pos-1]
   else
      Result := '';
   S.Free;
end;

function TTabela.SemAspas(Str: String): String;
begin
   { Convert " to ' ' }
   while Pos('"', Str) > 0 do
      Str[Pos('"', Str)] := ' ';
   Result := Trim( Str );
end;

procedure TTabela.SetDelayedOpIndicator(const Value: TDelayedOpIndicator);
begin
   FDelayedOpIndicator := Value;
   if Assigned( Value ) then
      Value.FreeNotification(self);
end;

procedure TTabela.CarregaFaixas( DataSet : TDataSet; CampoCaption : String = 'CAPTION' );
begin
   with DataSet do begin
    FFaixas.Ranges.Clear;
    if IsEmpty then
       Exit;
    First;
    while not EOF do begin
      with FFaixas.Ranges.Add do begin
         AutoName := True;
         with BeginPoint do begin
            Opened := ( FieldByName( 'BEGINOPENED' ).AsString = 'T' );
            Excluded := ( FieldByName( 'BEGINEXCLUDED' ).AsString = 'T' );
            if FindField( 'BEGINCAPTION' ) <> nil then
               Caption := FieldByName( 'BEGINCAPTION' ).AsString
            else
               Caption := FieldByName( CampoCaption ).AsString;
            with Point do begin
               Descricao := 'MeasurementBegin' + FieldByName( 'INTERVAL' ).AsString;
               ValorNumerico := FieldByName( 'BEGINPOINT' ).AsString;
               Unidade := '';
            end;
         end;
         with EndPoint do begin
            Opened := ( FieldByName( 'ENDOPENED' ).AsString = 'T' );
            Excluded := ( FieldByName( 'ENDEXCLUDED' ).AsString = 'T' );
            if FindField( 'ENDCAPTION' ) <> nil then
               Caption := FieldByName( 'ENDCAPTION' ).AsString
            else
               Caption := FieldByName( CampoCaption ).AsString;
            with Point do begin
               Descricao := 'MeasurementEnd' + FieldByName( 'INTERVAL' ).AsString;
               ValorNumerico := FieldByName( 'ENDPOINT' ).AsString;
               Unidade := '';
            end;
         end;
         Caption := FieldByName( CampoCaption ).AsString;
      end;
      Next;
    end;
   end;
end;

function TTabela.Caption(Medida: TMedida): String;
var
   I : Integer;
   Point : TMeasureLimit;
   Percent : Double;
begin
   Result := '';
   for I := 0 to FFaixas.Ranges.Count - 1 do
   begin
      if FFaixas.Ranges.Items[I].Has( Medida, Point, Percent ) then
      begin
         if Result <> '' then
            Result := Result + '; ';
         if ( Point = nil ) or ( Percent = 0 )then  // Não existe um ponto próximo
            Result := Result + FFaixas.Ranges.Items[I].Caption
         else
            Result := Result + Point.Caption;
      end;
   end;
end;

procedure TTabela.SetAceitaParametrosInvalidos(const Value: Boolean);
begin
  FAceitaParametrosInvalidos := Value;
end;

end.
